### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by manuelmeurer** [bundler/bundler#1570]
Getting the following error during deploy with Capistrano:

```
Unfortunately, a fatal error has occurred. Please report this error to the Bundler issue tracker at https://github.com/carlhuda/bundler/issues so that we can fix it. Thanks!

/usr/local/lib/ruby/1.9.1/rubygems/specification.rb:519:in `normalize_yaml_input'
:
invalid byte sequence in US-ASCII
(
ArgumentError
)
from /usr/local/lib/ruby/1.9.1/rubygems/specification.rb:479:in `from_yaml'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_input.rb:183:in `load_gemspec'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_input.rb:51:in `block in initialize'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_reader.rb:64:in `block in each'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `loop'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `each'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_input.rb:32:in `initialize'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_input.rb:17:in `new'
from /usr/local/lib/ruby/1.9.1/rubygems/package/tar_input.rb:17:in `open'
from /usr/local/lib/ruby/1.9.1/rubygems/package.rb:58:in `open'
from /usr/local/lib/ruby/1.9.1/rubygems/format.rb:63:in `from_io'
from /usr/local/lib/ruby/1.9.1/rubygems/format.rb:51:in `block in from_file_by_path'
from /usr/local/lib/ruby/1.9.1/open-uri.rb:35:in `open'
from /usr/local/lib/ruby/1.9.1/open-uri.rb:35:in `open'
from /usr/local/lib/ruby/1.9.1/rubygems/format.rb:50:in `from_file_by_path'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/rubygems_integration.rb:100:in `spec_from_gem'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/source.rb:209:in `block in cached_specs'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/source.rb:205:in `each'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/source.rb:205:in `cached_specs'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/source.rb:165:in `fetch_specs'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/source.rb:70:in `specs'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/lazy_specification.rb:48:in `__materialize__'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/spec_set.rb:86:in `block in materialize'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/spec_set.rb:83:in `map!'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/spec_set.rb:83:in `materialize'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/definition.rb:90:in `specs'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/definition.rb:78:in `resolve_with_cache!'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/installer.rb:47:in `run'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/installer.rb:12:in `install'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/cli.rb:219:in `install'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/vendor/thor/task.rb:22:in `run'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/vendor/thor.rb:263:in `dispatch'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/lib/bundler/vendor/thor/base.rb:386:in `start'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc/bin/bundle:13:in `<top (required)>'
from /usr/local/bin/bundle:19:in `load'
from /usr/local/bin/bundle:19:in `<main>'
```

Gemfile and Gemfile.lock here: https://gist.github.com/1415877

Bundler version: 1.1.rc
Ruby version: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
Rails version: 3.1.3

**Comment by fahidnasir** [comment]
Fixed: I added the env in ~/.bash_profile and relaunched the VSCode.
```
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

```
