### ISSUE TITLE
rake release does not show any prompt for the login/password under Windows

### ISSUE THREAD

**Issue by tkrotoff** [bundler/bundler#1918]
Inside a Git bash provided by [msysgit](http://code.google.com/p/msysgit/).
- Create a new gem using bundler
- Run `rake release` in order to publish the gem <--- this fails with the following error (with --trace option):

```
$ rake release --trace
** Invoke release (first_time)
** Execute release
jquery-qtip2-rails 0.0.1 built to pkg/jquery-qtip2-rails-0.0.1.gem
Tagged v0.0.1
Untagged v0.0.1 due to error
rake aborted!
Couldn't git push. `git push  2>&1' failed with the following output:

Password for 'github.com':
fatal: Could not read password: No such file or directory

c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/gem_helper.rb:93:in `perform_git_push'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/gem_helper.rb:85:in `git_push'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/gem_helper.rb:65:in `block in release_gem'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/gem_helper.rb:113:in `tag_version'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/gem_helper.rb:64:in `release_gem'
c:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.rc.7/lib/bundler/gem_helper.rb:38:in `block in install'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:205:in `call'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:200:in `each'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
c:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
c:/Ruby193/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:94:in `each'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
c:/Ruby193/lib/ruby/1.9.1/rake/application.rb:63:in `run'
c:/Ruby193/bin/rake:32:in `<main>'
Tasks: TOP => release
```

`rake release` never asks for the git password and fails after pressing enter key (also tried to enter the password before pressing enter).
It does not prompt for entering the password and fails to read from stdin. 

Rails version 3.2.1
rake version 0.9.2.2
bundle version 1.1.rc.7
Ruby version 1.9.3p0
Git version 1.7.8.msysgit.0
Windows 7 x64 french familial edition

My Ruby installation is from: http://rubyinstaller.org/downloads/
Downloaded in january 2012.

My Git installation is from: http://code.google.com/p/msysgit/
Downloaded in january 2012.

My Ruby interpreter is inside my PATH and thus accessible from within the msysgit bash.

This is first issue I encounter since january with my Ruby and Git installation under Windows.

I guess this can be reproduced using http://railsinstaller.org/ I can confirm that if you need to.

Thanks in advance.

**Comment by daddie888** [comment]
> affecting a small number of people
Nice, after 3 yearns still not fixed, shame on you
