### ISSUE TITLE
SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by jamesottaway** [bundler/bundler#2531]
Having trouble running `bundle install` for [tentd-omnibus](https://github.com/tent/tentd-omnibus).

Output is:

```
~/Projects/tentd-omnibus (master ✔) ᐅ bundle install
Fetching gem metadata from https://rubygems.org/.Unfortunately, a fatal error has occurred. Please report this error to the Bundler issue tracker at https://github.com/carlhuda/bundler/issues so that we can fix it. Please include the full output of the command, your Gemfile and Gemfile.lock. Thanks!
/Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A (OpenSSL::SSL::SSLError)
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/net/http.rb:799:in `connect'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/net/http.rb:750:in `start'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/net/http/persistent.rb:224:in `connection_for'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/net/http/persistent.rb:358:in `request'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/fetcher.rb:135:in `fetch'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/fetcher.rb:163:in `fetch_dependency_remote_specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/fetcher.rb:122:in `fetch_remote_specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/fetcher.rb:70:in `specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:234:in `block in remote_specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:232:in `each'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:232:in `remote_specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:165:in `fetch_specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:70:in `specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:205:in `block (2 levels) in index'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:202:in `each'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:202:in `block in index'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/index.rb:9:in `build'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:198:in `index'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:192:in `resolve'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:127:in `specs'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:122:in `resolve_remotely!'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/installer.rb:48:in `run'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/installer.rb:12:in `install'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/cli.rb:220:in `install'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor.rb:263:in `dispatch'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor/base.rb:386:in `start'
    from /Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/bin/bundle:13:in `<top (required)>'
    from /Users/james/.rbenv/versions/1.9.3-p125/bin/bundle:19:in `load'
    from /Users/james/.rbenv/versions/1.9.3-p125/bin/bundle:19:in `<main>'
```

`Gemfile` looks like:

```
source "https://rubygems.org"

gemspec

gem "tentd", :git => "git://github.com/tent/tentd.git", :branch => "master"
gem "tent-status", :git => "git://github.com/tent/tent-status.git", :branch => "master"
gem "tent-admin", :git => "git://github.com/tent/tent-admin.git", :branch => "master"

gem 'rake'

gem 'sequel_pg', :require => 'sequel'
gem 'sequel', :require => false

gem 'tent-schemas', :git => 'git://github.com/tent/tent-schemas.git', :branch => 'master'
gem 'json-pointer', :git => 'git://github.com/tent/json-pointer-ruby.git', :branch => 'master'
gem 'tent-canonical-json', :git => 'git://github.com/tent/tent-canonical-json-ruby.git', :branch => 'master'
gem 'api-validator', :git => 'git://github.com/tent/api-validator.git', :branch => 'master'
gem 'hawk-auth', :git => 'git://github.com/tent/hawk-ruby.git', :branch => 'master'

gem 'rack-putty', :git => 'git://github.com/tent/rack-putty.git', :branch => 'master'
gem 'tent-client', :git => 'git://github.com/tent/tent-client-ruby.git', :branch => 'master'
gem 'hawk-auth', :git => 'git://github.com/tent/hawk-ruby.git', :branch => 'master'
gem 'omniauth-tent', :git => 'git://github.com/tent/omniauth-tent.git', :branch => 'master'
gem 'marbles-js', :git => 'git://github.com/jvatic/marbles-js.git', :branch => 'master'
gem 'marbles-tent-client-js', :git => 'git://github.com/tent/marbles-tent-client-js.git', :branch => 'master'
gem 'lodash-assets', :git => 'git://github.com/jvatic/lodash-assets.git', :branch => 'master'
gem 'icing', :git => 'git://github.com/tent/icing.git', :branch => 'master'
gem 'sequel-json', :git => 'git://github.com/tent/sequel-json.git', :branch => 'master'
gem 'sprockets', :git => 'git://github.com/jvaill/sprockets.git', :branch => 'master'

gem 'marbles-js', :git => 'git://github.com/jvatic/marbles-js.git', :branch => 'master'

group :assets do
  gem 'uglifier'
  gem 'sprockets-rainpress'
end
```

And the `Gemfile.lock`:

```
GIT
  remote: git://github.com/jvaill/sprockets.git
  revision: 6327a13e77609991509c8cf3d3c1e571f6a4b23d
  branch: master
  specs:
    sprockets (2.9.2)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)

GIT
  remote: git://github.com/jvatic/lodash-assets.git
  revision: 34bfb392e2407053d6cf28f76c884c6e77df34e8
  branch: master
  specs:
    lodash-assets (0.0.1)
      execjs (>= 1.2.9)
      sprockets (>= 2.0.3)
      tilt (>= 1.3.3)
      yajl-ruby

GIT
  remote: git://github.com/jvatic/marbles-js.git
  revision: 3a51fb546e778f4dcb602da126e8de8f57c9cd73
  branch: master
  specs:
    marbles-js (0.0.3)

GIT
  remote: git://github.com/tent/api-validator.git
  revision: a9a94d50bab6ab4666284ef4cff050b4a691c46b
  branch: master
  specs:
    api-validator (0.0.1)
      json-pointer

GIT
  remote: git://github.com/tent/hawk-ruby.git
  revision: 427d2ee50dbfe9f728f717298e42b90ebeccd69e
  branch: master
  specs:
    hawk-auth (0.2.0)

GIT
  remote: git://github.com/tent/icing.git
  revision: fde984d037393cecc78a8f867699d03511625995
  branch: master
  specs:
    icing (0.0.1)
      compass (~> 0.12.2)
      sass
      sprockets (~> 2.0)
      sprockets-helpers (~> 0.2)
      sprockets-sass (~> 0.5)

GIT
  remote: git://github.com/tent/json-pointer-ruby.git
  revision: ade5fea30acd9c85c3886db62e83d68e3b5919bb
  branch: master
  specs:
    json-pointer (0.0.2)

GIT
  remote: git://github.com/tent/marbles-tent-client-js.git
  revision: 6014ed324b64fcc68bda99453b1e742a08e4a653
  branch: master
  specs:
    marbles-tent-client-js (0.0.1)

GIT
  remote: git://github.com/tent/omniauth-tent.git
  revision: 03a26e96db40554d783c6d12a79054f81991afd8
  branch: master
  specs:
    omniauth-tent (0.2.0)
      omniauth (~> 1.1.1)
      tent-client

GIT
  remote: git://github.com/tent/rack-putty.git
  revision: f5769196226018fc87a9f8dcf1eeddc05c45bd6f
  branch: master
  specs:
    rack-putty (0.0.1)
      rack-mount (~> 0.8.3)

GIT
  remote: git://github.com/tent/sequel-json.git
  revision: 5412015d8053fc1ec85f220d1974c83436d8f379
  branch: master
  specs:
    sequel-json (0.0.1)
      sequel
      yajl-ruby

GIT
  remote: git://github.com/tent/tent-admin.git
  revision: 0245f3d3eceee76f5e2bdfe954068e6e5c2d6f2c
  branch: master
  specs:
    tent-admin (0.0.1)
      coffee-script
      icing
      lodash-assets
      marbles-js
      marbles-tent-client-js
      mimetype-fu
      omniauth-tent
      pg
      rack-putty
      sass
      sequel (= 3.46)
      sequel-json
      sprockets (~> 2.0)

GIT
  remote: git://github.com/tent/tent-canonical-json-ruby.git
  revision: a5b503362f9fa0c7da27b05d844c028b5b94dbd3
  branch: master
  specs:
    tent-canonical-json (0.0.2)
      json-pointer
      yajl-ruby

GIT
  remote: git://github.com/tent/tent-client-ruby.git
  revision: 367a56f44cd4f0ed64a056b7d2cfc40b5848b028
  branch: master
  specs:
    tent-client (0.2.0)
      faraday (= 0.8.4)
      faraday_middleware (= 0.8.8)
      faraday_middleware-multi_json
      hawk-auth
      nokogiri
      yajl-ruby

GIT
  remote: git://github.com/tent/tent-schemas.git
  revision: 48deddffd39739603bf01ec88ff195a8503ae4cd
  branch: master
  specs:
    tent-schemas (0.2.0)
      json-schema (= 2.0.0)

GIT
  remote: git://github.com/tent/tent-status.git
  revision: 23089a85e97d1c52b919e7f7fef25e8a5a541855
  branch: master
  specs:
    tent-status (0.2.0)
      coffee-script
      icing
      lodash-assets
      marbles-js
      marbles-tent-client-js
      mimetype-fu
      omniauth-tent
      pg
      rack-putty
      sequel (= 3.46)
      sequel-json
      sprockets (~> 2.0)
      sprockets-sass (~> 0.5)
      tent-client

GIT
  remote: git://github.com/tent/tentd.git
  revision: 6dc4d59cdf86a5a18f7a396e390ade6759cd2776
  branch: master
  specs:
    tentd (0.2.0)
      api-validator
      fog
      hawk-auth
      pg
      rack-putty
      sequel (= 3.46.0)
      sequel-json
      sequel-pg_array
      sequel_pg
      sidekiq
      tent-canonical-json
      tent-client
      tent-schemas
      unicorn
      yajl-ruby

PATH
  remote: .
  specs:
    tentd-omnibus (0.0.1)
      bcrypt-ruby
      mimetype-fu
      rack-putty
      sidekiq
      tent-status
      tentd (~> 0.2)
      unicorn

GEM
  remote: https://rubygems.org/
  specs:
    bcrypt-ruby (3.1.0)
    builder (3.2.2)
    celluloid (0.14.1)
      timers (>= 1.0.0)
    chunky_png (1.2.8)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.3)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    connection_pool (1.1.0)
    excon (0.6.6)
    execjs (1.4.0)
      multi_json (~> 1.0)
    faraday (0.8.4)
      multipart-post (~> 1.1)
    faraday_middleware (0.8.8)
      faraday (>= 0.7.4, < 0.9)
    faraday_middleware-multi_json (0.0.5)
      faraday_middleware
      multi_json
    fog (0.9.0)
      builder
      excon (~> 0.6.1)
      formatador (>= 0.1.3)
      json
      mime-types
      net-scp (>= 1.0.4)
      net-ssh (>= 2.1.4)
      nokogiri (>= 1.4.4)
      ruby-hmac
    formatador (0.2.4)
    fssm (0.2.10)
    hashie (2.0.5)
    hike (1.2.3)
    json (1.8.0)
    json-schema (2.0.0)
    kgio (2.8.0)
    mime-types (1.23)
    mimetype-fu (0.1.2)
    mini_portile (0.5.1)
    multi_json (1.7.7)
    multipart-post (1.2.0)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.6.8)
    nokogiri (1.6.0)
      mini_portile (~> 0.5.0)
    omniauth (1.1.4)
      hashie (>= 1.2, < 3)
      rack
    pg (0.15.1)
    rack (1.5.2)
    rack-mount (0.8.3)
      rack (>= 1.0.0)
    raindrops (0.11.0)
    rainpress (1.0)
    rake (10.1.0)
    redis (3.0.4)
    redis-namespace (1.3.0)
      redis (~> 3.0.0)
    ruby-hmac (0.4.0)
    sass (3.2.9)
    sequel (3.46.0)
    sequel-pg_array (0.0.1)
    sequel_pg (1.6.7)
      pg (>= 0.8.0)
      sequel (>= 3.39.0)
    sidekiq (2.12.4)
      celluloid (>= 0.14.1)
      connection_pool (>= 1.0.0)
      json
      redis (>= 3.0)
      redis-namespace
    sprockets-helpers (0.9.1)
      sprockets (~> 2.0)
    sprockets-rainpress (0.0.1)
      rainpress
      sprockets
    sprockets-sass (0.9.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    tilt (1.4.1)
    timers (1.1.0)
    uglifier (2.1.1)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    unicorn (4.6.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    yajl-ruby (1.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  api-validator!
  hawk-auth!
  icing!
  json-pointer!
  lodash-assets!
  marbles-js!
  marbles-tent-client-js!
  omniauth-tent!
  rack-putty!
  rake
  sequel
  sequel-json!
  sequel_pg
  sprockets!
  sprockets-rainpress
  tent-admin!
  tent-canonical-json!
  tent-client!
  tent-schemas!
  tent-status!
  tentd!
  tentd-omnibus!
  uglifier
```

**Comment by SanjayYadav90** [comment]
Hi,

I am also  getting same issue as

SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A

how to fix it out?
