### ISSUE TITLE
Getting an Array where we expect a Gem::Dependency

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler#2615]
One of our scheduled builds failed with this error:

```
Using /home/jenkins/.rvm/gems/ruby-1.9.3-p392
Fetching gem metadata from http://rubygems.org/.
Fetching source index from http://rubygems.org/
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `block (3 levels) in unmet_dependency_names': undefined method `name' for ["ruby-ajp", ">= 0.2.0"]:Array (NoMethodError)
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `map'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `block (2 levels) in unmet_dependency_names'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:94:in `map'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:94:in `block in unmet_dependency_names'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:93:in `map'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/index.rb:93:in `unmet_dependency_names'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:240:in `remote_specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:163:in `fetch_specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:67:in `specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/lazy_specification.rb:52:in `__materialize__'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/spec_set.rb:88:in `block in materialize'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in `resolve_remotely!'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/installer.rb:83:in `run'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/installer.rb:14:in `install'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/cli.rb:247:in `install'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/vendor/thor/task.rb:27:in `run'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/vendor/thor.rb:344:in `dispatch'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/vendor/thor/base.rb:434:in `start'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/bin/bundle:20:in `block in <top (required)>'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/bin/bundle:20:in `<top (required)>'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/bin/bundle:19:in `load'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/bin/bundle:19:in `<main>'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
running loadtest
/home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.0.4 in any of the sources (Bundler::GemNotFound)
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in `specs_for'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/definition.rb:148:in `requested_specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/runtime.rb:13:in `setup'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler.rb:120:in `setup'
	from /home/jenkins/.rvm/gems/ruby-1.9.3-p392/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
	from /home/jenkins/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jenkins/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
```

The same code built successfully before and after this failure, so I thinkit must have been a transient error related to the API server.

I found this related (closed, fixed) issue: bundler/bundler-api#8 but this happened on the client side. I guess there must be a weird entry in the full RubyGems index?

**Comment by segiddins** [comment]
Is this still happening? The last comment is well over a year old.

**Comment by TimMoore** [comment]
#2706 is fixed, so I think that effectively solves this. The ajp gemspec for that version is still broken, but I think the conditions that would cause it to be unexpectedly fetched should be fixed.
