### ISSUE TITLE
Bundler fails to install rails

### ISSUE THREAD

**Issue by ErwinM** [bundler/bundler#2618]
Reinstalled my laptop. Clean install with ruby 1.9.3 under RVM. Cloned my repo and trying to `bundle install` (worked fine before reinstall).

```
MacBook-Air-van-Erwin:insight erwinmatthijssen$ bundle install --verbose
Fetching from: http://rubygems.org/api/v1/dependencies
HTTP Success
Fetching gem metadata from http://rubygems.org/
Query List: ["rails"]
Query Gemcutter Dependency Endpoint API: rails
Fetching from: http://rubygems.org/api/v1/dependencies?gems=rails
HTTP Success
Query List: ["bundler", "railties", "actionmailer", "activeresource", "activerecord", "actionpack", "activesupport", "sprockets-rails", "rake", "actionwebservice"]
Query Gemcutter Dependency Endpoint API: bundler,railties,actionmailer,activeresource,activerecord,actionpack,activesupport,sprockets-rails,rake,actionwebservice
Fetching from: http://rubygems.org/api/v1/dependencies?gems=bundler,railties,actionmailer,activeresource,activerecord,actionpack,activesupport,sprockets-rails,rake,actionwebservice
Error during API request. Bundler::HTTPError: Network error while fetching http://rubygems.org/api/v1/dependencies?gems=bundler,railties,actionmailer,activeresource,activerecord,actionpack,activesupport,sprockets-rails,rake,actionwebservice
/Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:211:in `rescue in fetch'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:199:in `fetch'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:242:in `fetch_dependency_remote_specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:151:in `fetch_remote_specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:154:in `fetch_remote_specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:106:in `specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:235:in `block in remote_specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:235:in `each'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:235:in `remote_specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:163:in `fetch_specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:67:in `specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:192:in `block (2 levels) in index'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:189:in `each'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:189:in `block in index'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/index.rb:9:in `build'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:185:in `index'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:179:in `resolve'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in `resolve_remotely!'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/installer.rb:83:in `run'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/installer.rb:14:in `install'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/cli.rb:247:in `install'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/task.rb:27:in `run'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/vendor/thor.rb:344:in `dispatch'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/base.rb:434:in `start'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/bin/bundle:20:in `block in <top (required)>'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/gems/bundler-1.3.5/bin/bundle:20:in `<top (required)>'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/bin/bundle:23:in `load'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@global/bin/bundle:23:in `<main>'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@insight/bin/ruby_noexec_wrapper:14:in `eval'  /Users/erwinmatthijssen/.rvm/gems/ruby-1.9.3-p448@insight/bin/ruby_noexec_wrapper:14:in `<main>'
```

After this error it goes on to fetch (?) every gem on RubyGems:

```
Fetching source index from http://rubygems.org/
Fetching from: http://rubygems.org/quick/Marshal.4.8/_-1.0.gemspec.rz
HTTP Redirection
Fetching from: http://production.cf.rubygems.org/quick/Marshal.4.8/_-1.0.gemspec.rz
HTTP Success
Fetching from: http://rubygems.org/quick/Marshal.4.8/_-1.1.gemspec.rz
HTTP Redirection
Fetching from: http://production.cf.rubygems.org/quick/Marshal.4.8/_-1.1.gemspec.rz
HTTP Success
Fetching from: http://rubygems.org/quick/Marshal.4.8/_-1.2.gemspec.rz
HTTP Redirection
Fetching from: http://production.cf.rubygems.org/quick/Marshal.4.8/_-1.2.gemspec.rz
HTTP Success
ETC
```

After some troubleshooting, I reduced my Gemfile to:

``` ruby
source 'http://rubygems.org'
ruby "1.9.3"

gem 'rails', '~>3.2.0'
```

The behavior stays the same. In fact, above parses are from running this gemfile.

What is going on?

**Comment by Wokoro** [comment]
Please am currently having similar issue how can I fit it?
