### ISSUE TITLE
Could not find rake-10.1.1 in any of the sources

### ISSUE THREAD

**Issue by orangeudav** [bundler/bundler#2908]
Hi all, i have strange warning from bundler 1.5.3 and ruby-1.9.3-p545. 
```
/Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/spec_set.rb:92:in `materialize': Could not find rake-10.1.1 in any of the sources (Bundler::GemNotFound)
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/definition.rb:133:in `specs'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/definition.rb:178:in `specs_for'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/definition.rb:167:in `requested_specs'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/runtime.rb:13:in `setup'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler.rb:119:in `setup'
	from /Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/gems/bundler-1.5.3/lib/bundler/setup.rb:17
```
I tried already:
- change rvm to rbenv :)
- gem update --system
- reinstall and test on different ruby versions (1.9.3, 2.0.0, 2.1.1)
- check $PATH and remove any other (brew) ruby

This error happens after 'bundle install'

Additional infos
```
OS X 10.9.2

bundle exec which rake 
/Users/orangeudav/.rvm/gems/ruby-1.9.3-p545@adword/bin/rake

bundle exec rake -V
rake, version 10.1.1

gem list | grep rake
rake (10.1.1)

bundler (1.5.3)
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-darwin13.1.0]
```

**Comment by LynnCo** [comment]
Closing because

> Thanks a lot for the pointer, although I figured out a different solution to my particular problem. I'm thinking that this issue may be closed, as it's basically to do with whatever gems the original people are using... Perhaps we could wait for people to confirm.

Will create a new issue with about https://github.com/bundler/bundler/issues/2908#issuecomment-43013740
