### ISSUE TITLE
bundle install failing with `install_in_parallel': undefined method `[]'

### ISSUE THREAD

**Issue by akshaykarle** [bundler/bundler#3063]
Hey,

I'm trying to do a bundle install and its failing with the following error:

```
/opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/installer.rb:303:in `install_in_parallel': undefined method `[]' for nil:NilClass (NoMethodError)
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/installer.rb:89:in `run'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/installer.rb:15:in `install'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/cli/install.rb:78:in `run'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/cli.rb:146:in `install'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/command.rb:27:in `run'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/base.rb:440:in `start'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/cli.rb:9:in `start'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/bin/bundle:20:in `block in <top (required)>'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
    from /opt/local/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/bin/bundle:20:in `<top (required)>'
    from /opt/local/ruby/2.1.1/bin/bundle:23:in `load'
    from /opt/local/ruby/2.1.1/bin/bundle:23:in `<main>'
```

My bundle config is:

```

---
BUNDLE_PATH: /var/go/.bundled-gems
BUNDLE_JOBS: '4'
```

Link to the Gemfile: https://gist.github.com/akshaykarle/421d441869c873fcb2ee

I'm using bundler-1.6.2 and ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
However, this **failure happens only when I set** `RUBY_GC_MALLOC_LIMIT=1000000000`. So is it happening when GC is kicking in? I added this variable for optimizing my ruby runs.
Any clues?

**Comment by imton** [comment]
got it randomly

````
Installing hirb 0.7.3
Installing honeybadger 2.0.10
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/usr/local/bundle/gems/bundler-1.7.12/lib/bundler/installer.rb:305:in `install_in_parallel': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/installer.rb:88:in `run'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/installer.rb:18:in `install'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/cli/install.rb:79:in `run'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/cli.rb:145:in `install'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/vendor/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/vendor/thor/base.rb:440:in `start'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/cli.rb:9:in `start'
	from /usr/local/bundle/gems/bundler-1.7.12/bin/bundle:20:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-1.7.12/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-1.7.12/bin/bundle:18:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:23:in `load'
	from /usr/local/bundle/bin/bundle:23:in `<main>'
INFO[0303] The command [/bin/sh -c bundle install] returned a non-zero code: 1
````
