### ISSUE TITLE
Problems loading gems with 'github' option in Gemfile, with Rails 4.1

### ISSUE THREAD

**Issue by antonrd** [bundler/bundler#3070]
Hello,

I updated from Rails 4.0 to Rails 4.1 and started seeing an error coming from bundler related to loading a gem, which is listed in the Gemfile with the 'github' options like this:

```
gem 'activeadmin', github: 'gregbell/active_admin'
```

The error occurs when starting up the rails server. The app seems to be working fine but the errors are worrying. Here is the backtrace from the error:

```
/Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/source/git.rb:187:in `rescue in load_spec_files': git://github.com/gregbell/active_admin.git (at f65e7cd) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/source/git.rb:184:in `load_spec_files'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/source/path.rb:92:in `local_specs'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/source/git.rb:154:in `specs'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/lazy_specification.rb:53:in `__materialize__'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:88:in `block in materialize'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `map!'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/spec_set.rb:85:in `materialize'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:133:in `specs'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:178:in `specs_for'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/definition.rb:167:in `requested_specs'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/environment.rb:18:in `requested_specs'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/runtime.rb:13:in `setup'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler.rb:120:in `setup'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.3/lib/bundler/setup.rb:17:in `<top (required)>'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
16:34:56 web.1              | 	from /Users/testuser/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

This happens with ruby 2.0.0, too. The current error occurred with ruby 2.1.2. I think it's not specific to the activeadmin gem, because I tried to specify the 'github' option for other gems and they were failing, too.

From my research so far bundler tries to look for gems in the wrong place - a subdir of the root dir for the project. When installing gems to an explicit directory like this:

```
bundle install --path <some_path>
```

things seems to be working fine. But I don't like this approach.

Any help on this will be appreciated.

**Comment by calfzhou** [comment]
Facing the same issue today, it always says `git://github.com/brainspec/enumerize.git (at 3682d36) is not yet checked out. Run bundle install first.` Using ruby 2.1.5, rails 4.1.8, bundler 1.8.2.

in my Gemfile, there is 
```ruby
gem 'enumerize', github: 'brainspec/enumerize', ref: '3682d36'
```

When running `bundle install`, it prints
```
...
Using enumerize 0.9.0 from git://github.com/brainspec/enumerize.git (at 3682d36)
...
```

When run `bundle show enum`, the result is
```
/Users/zhouji/.rvm/gems/ruby-2.1.5@hire/bundler/gems/enumerize-3682d36caf5c
```

**Comment by calfzhou** [comment]
The error only occurs for `rails c`.

`rails s` can successfully load the github gem.

**Comment by calfzhou** [comment]
My problem solved by upgrade `spring` to 1.3.2

**Comment by TimMoore** [comment]
Thanks for the pointer @calfzhou. There's more detail at https://github.com/rails/spring/issues/383

**Comment by allaire** [comment]
I had to `spring binstub --all` to make it works with 1.3.2, but now everything is fixed!
