### ISSUE TITLE
bundle install fails due to SSL error, bundler 1.7.7, Ruby 2.0, Windows

### ISSUE THREAD

**Issue by agross** [bundler/bundler#3282]
```
$ bundle init
$ echo gem "rake", "~> 0.9.6" >> Gemfile
$ bundle install --verbose
DL is deprecated, please use Fiddle
HTTP GET https://bundler.rubygems.org/api/v1/dependencies
HTTP 200 OK
Fetching gem metadata from https://rubygems.org/
Query List: ["rake"]
Query Gemcutter Dependency Endpoint API: rake
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=rake
HTTP 200 OK
Query List: []
Resolving dependencies...

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/gems/rake-0.9.6.gem)
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:420:in `rescue in connection_for'
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:393:in `connection_for'
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:495:in `request'
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:236:in `fetch_http'
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:271:in `fetch_path'
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:304:in `cache_update_path'
C:/Ruby/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:170:in `download'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/rubygems_integration.rb:537:in `download_gem'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/fetcher.rb:61:in `download_gem_from_uri'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/source/rubygems.rb:333:in `fetch_gem'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/source/rubygems.rb:92:in `install'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/installer.rb:104:in `block in install_gem_from_spec'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/rubygems_integration.rb:162:in `with_build_args'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/installer.rb:103:in `install_gem_from_spec'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/installer.rb:264:in `block in install_sequentially'
C:/Ruby/lib/ruby/2.0.0/forwardable.rb:171:in `each'
C:/Ruby/lib/ruby/2.0.0/forwardable.rb:171:in `each'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/installer.rb:263:in `install_sequentially'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/installer.rb:90:in `run'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/installer.rb:18:in `install'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/cli/install.rb:79:in `run'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/cli.rb:145:in `install'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/vendor/thor/command.rb:27:in `run'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/vendor/thor.rb:363:in `dispatch'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/vendor/thor/base.rb:440:in `start'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/cli.rb:9:in `start'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/bin/bundle:20:in `block in <top (required)>'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
C:/Ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.7/bin/bundle:18:in `<top (required)>'
C:/Ruby/bin/bundle:23:in `load'
C:/Ruby/bin/bundle:23:in `<main>'
An error occurred while installing rake (0.9.6), and Bundler cannot continue.
Make sure that `gem install rake -v '0.9.6'` succeeds before bundling.
```

I've seen the SSL-related commits 012a388d9d4289f60df1d85da0c5a64944b3b7dd dc55c6471f3e425ba7a9e52ec285526fca5a812a etc, and the PEM files are in my Ruby installation, but it seems that bundler doesn't use them.

**Comment by BLCK-NLSH** [comment]
What a life saver, thank you very much
