### ISSUE TITLE
Creating gem error : TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by selcham** [bundler/bundler#3374]
Hi,

I'm trying to create a new gem project using ```bundle gem foo__bar``` but I'm facing the error below :
```
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    TypeError: no implicit conversion of nil into String
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/cli/gem.rb:23:in `+'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/cli/gem.rb:23:in `block in run'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/cli/gem.rb:23:in `map'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/cli/gem.rb:23:in `run'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/cli.rb:351:in `gem'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/vendor/thor/command.rb:27:in `run'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/vendor/thor/base.rb:440:in `start'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/cli.rb:10:in `start'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/bin/bundle:20:in `block in <top (required)>'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /Users/selcham/.gem/ruby/2.1.0/gems/bundler-1.8.0.pre/bin/bundle:18:in `<top (required)>'
    /Users/selcham/.rbenv/versions/2.1.4/bin/bundle:23:in `load'
    /Users/selcham/.rbenv/versions/2.1.4/bin/bundle:23:in `<main>'

Environment

    Bundler   1.8.0.pre
    Rubygems  2.2.2
    Ruby      2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
    Git       2.2.1
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

```

I've got the same error using version 1.7.12.

Any ideas ?

Thanks

**Comment by selcham** [comment]
Hum, my bad, it doesn't like my double underscore in gem's name !

**Comment by indirect** [comment]
Thanks for reporting this! We definitely shouldn't throw an exception when the gem name has two underscores.

**Comment by selcham** [comment]
I've submitted PR #3376 to address this issue.
