### ISSUE TITLE
Problem with normalize_uri in 1.8.1

### ISSUE THREAD

**Issue by pierre-pretorius** [bundler/bundler#3398]
When running the following command with bundler 1.8.1, Ruby 2.2 and Ubuntu 12.04 (it's the command Capistrano uses):

```
bundle install --binstubs /opt/redmine/shared/bin --path /opt/redmine/shared/bundle --without development test --deployment
```

it fails with error:
```
ArgumentError: Gem sources must be absolute. You provided 'build.httparty/'.
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/settings.rb:191:in `normalize_uri'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/settings.rb:133:in `key_for'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/settings.rb:14:in `[]'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/installer.rb:99:in `install_gem_from_spec'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/installer.rb:263:in `block in install_sequentially'
/usr/local/lib/ruby/2.2.0/forwardable.rb:183:in `each'
/usr/local/lib/ruby/2.2.0/forwardable.rb:183:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/installer.rb:262:in `install_sequentially'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/installer.rb:90:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/installer.rb:18:in `install'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/cli/install.rb:80:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/cli.rb:157:in `install'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/vendor/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/vendor/thor.rb:363:in `dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/vendor/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/cli.rb:10:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/bin/bundle:20:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.1/bin/bundle:18:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
An error occurred while installing httparty (0.13.3), and Bundler cannot continue.
Make sure that `gem install httparty -v '0.13.3'` succeeds before bundling.
```

**Installing httparty 0.13.3 with the gem command works fine.**
**Bundler 1.3.5 (my previous version) installed the bundle successfully.  I reverted back to fix this problem.**

Please let me know if this is a problem with httparty instead so that I can log a issue there.  I couldn't see anything wrong with the gem.  I can provide the full bundler verbose log if required.

**Comment by TimMoore** [comment]
I think this is a bug that was just introduced in 1.8.1. Any version 1.8.0 and earlier should be OK.

Thanks for the report!

**Comment by pda** [comment]
It seems to break for any gem that has the string `http` in its name, e.g. `httparty`, `http_signatures`.

**Comment by TimMoore** [comment]
Fix proposed at #3399.

**Comment by mkonecny** [comment]
Same problem here with `http_parser` lib.

**Comment by codekitchen** [comment]
:+1: just ran into this head-scratcher with `http-cookie`

**Comment by i** [comment]
Can confirm. Just happened with httpclient

**Comment by indirect** [comment]
ack, sorry everyone :grimacing: totally my bad. obviously a terrible idea in retrospect.

**Comment by afilhodaniel** [comment]
I had same problem with httpclient. I fix it return bundler to version 1.8.0.

**Comment by brookr** [comment]
I hit this issue with `http_parser` and `httparty`. So glad I found this thread, thanks everyone!

I'm working around it by reverting to bundler 1.8.0 for now: 
`gem uninstall bundler --version 1.8.1 && gem install bundler --version 1.8.0`

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/3399 was merged, so this can be closed.
