### ISSUE TITLE
[windows] bundler installs multiple platforms when platform ruby is present

### ISSUE THREAD

**Issue by ABaumgaertner** [bundler/bundler#3456]
ruby 2.2.2p86 (2015-03-03 revision 49825) [x64-mingw32]

IMO bundler should not install additional platforms if platform ruby is present. 
ruby require is not aware of platforms and platform ruby has precedence over other platforms (e.g. x64-mingw32).

e.g. building mysql2 with devkit and up2date libmysql
`gem install mysql2 -N --platform=ruby -- "--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64"`
now running bundle install (e.g. with redmine) will install additionally mysql2-0.3.18-x64-mingw32.gem

**Comment by indirect** [comment]
Please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) and provide a complete description of your environment, what you are doing, what happens, what you expect to happen instead, and why you expect that. Thanks!

**Comment by ABaumgaertner** [comment]
on a fresh ruby installation
compile gem mysql2 with devkit (only possible for platform ruby)
require test succeeds
run bundle install
installs additional mysql2 gem for platform x64-mingw32
require test failes

workaround: manually uninstall platform x64-mingw32

```
C:\apps\redmine_dev\test>ruby -v
ruby 2.2.2p86 (2015-03-03 revision 49825) [x64-mingw32]

C:\apps\redmine_dev\test>more mysql.rb
require 'mysql2'
C:\apps\redmine_dev\test>gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
io-console (0.4.3)
json (1.8.1)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)

C:\apps\redmine_dev\test>gem install bundler
Fetching: bundler-1.8.3.gem (100%)
Successfully installed bundler-1.8.3
1 gem installed

C:\apps\redmine_dev\test>gem install mysql2 -N --platform=ruby -- "--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64"
Fetching: mysql2-0.3.18.gem (100%)
Building native extensions with: '--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64'
This could take a while...
Successfully installed mysql2-0.3.18
1 gem installed

C:\apps\redmine_dev\test>ruby mysql.rb

C:\apps\redmine_dev\test>more Gemfile
source 'https://rubygems.org'

gem "mysql2", "~> 0.3.11"

C:\apps\redmine_dev\test>bundle install
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing mysql2 0.3.18
Using bundler 1.8.3
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from mysql2:

======================================================================================================

 \ You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.5.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:
  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.5-winx64.zip

 \ This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/README.

======================================================================================================


C:\apps\redmine_dev\test>gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
bundler (1.8.3)
io-console (0.4.3)
json (1.8.1)
mysql2 (0.3.18 ruby x64-mingw32)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)

C:\apps\redmine_dev\test>bundle env
Environment

    Bundler   1.8.3
    Rubygems  2.4.5
    Ruby      2.2.2p86 (2015-03-03 revision 49825) [x64-mingw32]
    Git       2.3.1

Gemfile

    source 'https://rubygems.org'

    gem "mysql2", "~> 0.3.11"

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        mysql2 (0.3.18-x64-mingw32)

    PLATFORMS
      x64-mingw32

    DEPENDENCIES
      mysql2 (~> 0.3.11)

C:\apps\redmine_dev\test>ruby mysql.rb
C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mysql2/2.2/mysql2 (LoadError)
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2/mysql2.rb:2:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:31:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from mysql.rb:1:in `<main>'

C:\apps\redmine_dev\test>
C:\apps\redmine_dev\test>gem uninstall mysql2

Select gem to uninstall:
 1. mysql2-0.3.18
 2. mysql2-0.3.18-x64-mingw32
 3. All versions
> 2
Successfully uninstalled mysql2-0.3.18-x64-mingw32

C:\apps\redmine_dev\test>ruby mysql.rb

C:\apps\redmine_dev\test>
```

**Comment by indirect** [comment]
What does "compile gem mysql2 with devkit" mean? What are the steps I need to follow to reproduce this problem? If possible, please provide a ruby script I can run that will demonstrate the problem. Please keep in mind that I don't use Windows on a daily basis, so your reproduction instructions will need to include how to install Ruby in the first place.

**Comment by TimMoore** [comment]
@ABaumgaertner is the problem that there's no way to force Bundler to compile a gem's extension from source when there is a platform-specific binary version available? That's how I interpret what you're saying. I think that's correct that Bundler currently has no way to do that, and it does sound like a reasonable thing to want to do.

**Comment by LynnCo** [comment]
the relevant feedback from this issue:

> there's no way to force Bundler to compile a gem's extension from source when there is a platform-specific binary version available

**Comment by dsisnero** [comment]
This keeps on biting me with the sqlite3  gem , the mysql gem.  Any movement on this?  Can someone knowledgeable with bundlers code base outline the tasks needed to make this happen so that I or someone else can attempt to fix this?

**Comment by segiddins** [comment]
Master now has a configuration option for this, but I can't remember what it is

**Comment by segiddins** [comment]
`bundle config force_ruby_platform` should address this issue, so I think it's safe to close.
