### ISSUE TITLE
Mingw Ruby 2.2 "Bundler.require(*Rails.groups)" does not work

### ISSUE THREAD

**Issue by marutosi** [bundler/bundler#3484]
http://www.redmine.org/issues/19419

On Redmine 3.0.1 (Rails 4.2.0):
```
$ bundle --version
Bundler version 1.9.0.rc

$ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]

$ rake -T
rake aborted!
LoadError: cannot load such file -- nokogiri/nokogiri
c:/workdir/hg-workdir/REDMINE/all/config/application.rb:5:in `<top (required)>'
c:/workdir/hg-workdir/REDMINE/all/Rakefile:5:in `<top (required)>'
LoadError: cannot load such file -- nokogiri/2.2/nokogiri
c:/workdir/hg-workdir/REDMINE/all/config/application.rb:5:in `<top (required)>'
c:/workdir/hg-workdir/REDMINE/all/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

"Bundler.require(*Rails.groups)" does not work.
http://www.redmine.org/projects/redmine/repository/entry/tags/3.0.1/config/application.rb#L5

ruby 2.0.0p598 (2014-11-13) [x64-mingw32] and Bundler version 1.7.6 have no problem.

**Comment by marutosi** [comment]
It seems Ruby problem.
https://bugs.ruby-lang.org/issues/10878

**Comment by marutosi** [comment]
It seems nokogiri problem.
https://github.com/sparklemotion/nokogiri/issues/1256
