### ISSUE TITLE
bundle error during metasploit install

### ISSUE THREAD

**Issue by chadbernick** [bundler/bundler#3538]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
followed metasploit install http://hackerforhire.com.au/installing-metasploit-framework-on-os-x-yosemite/

Error details
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

/usr/local/opt/ruby21/bin/ruby extconf.rb
/Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `initialize': Permission denied @ rb_sysopen - /usr/local/Cellar/ruby21/2.1.5/bin/rdoc (Errno::EACCES)
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `open'
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `block in try_to_fix_binstubs'
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `map'
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `try_to_fix_binstubs'
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:46:in `block in execute_no_wrapper'
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `each'
	from /Users/chadbernick/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `execute_no_wrapper'
	from extconf.rb:19:in `<main>'
bundler 1.9.2
bundler 1.7.6
cucumber 1.2.1
diff-lcs 1.2.5
erubis 2.7.0
executable-hooks 1.3.2
rack 1.4.5
rake 10.4.2
rake 10.1.0
rdoc 4.1.0

extconf failed, exit code 1

Gem files will remain installed in /Users/chadbernick/.rvm/gems/ruby-2.1.5@global/gems/executable-hooks-1.3.2 for inspection.
Results logged to /Users/chadbernick/.rvm/gems/ruby-2.1.5@global/extensions/x86_64-darwin-14/2.1.0/executable-hooks-1.3.2/gem_make.out

    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:89:in `run'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/tempfile.rb:324:in `open'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /usr/local/Cellar/ruby21/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/fetcher.rb:1:in `<top (required)>'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/cli/install.rb:72:in `run'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/bin/bundle:23:in `load'
    /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework/bin/bundle:23:in `<main>'
```
Environment

    Bundler   1.9.2
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    GEM_HOME  /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework
    GEM_PATH  /Users/chadbernick/.rvm/gems/ruby-2.1.5@metasploit-framework:/Users/chadbernick/.rvm/gems/ruby-2.1.5@global
    RVM       1.26.11 (latest)
    Git       2.3.4
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by supertopher** [comment]
__Does not appear to be an issue with bundler__

it looks like you have a ruby install from both brew and rvm.  Just use one.  start by ```brew uninstall ruby``` ing and then trying again.  that guide assumed you aren't using RVM.  for the record, using RVM is fine... this guide just assumes you aren't 

it would be useful if you could tell us the output of the following two commands

```which -a ruby``` and ```which -a bundler```

**Comment by chadbernick** [comment]
Sorry for disappearing on this.
I had to move our Corp HQ and got buried under 600 unread emails.
Here’s the output of the commands.

brew uninstall ruby ing
osdoom:~ chadbernick$ brew uninstall ruby ing
Error: No such keg: /usr/local/Cellar/ruby


osdoom:~ chadbernick$ which -a ruby and which -a bundler
/Users/chadbernick/.rvm/rubies/ruby-2.1.5/bin/ruby
/usr/local/bin/ruby
/usr/local/bin/ruby
/usr/bin/ruby
/usr/bin/which
/Users/chadbernick/.rvm/gems/ruby-2.1.5@global/bin/bundler
/Users/chadbernick/.rvm/rubies/ruby-2.1.5/bin/bundler


Chad

**Comment by wtfiwtz** [comment]
Try running `brew doctor`

This error is a clue: Permission denied @ rb_sysopen - /usr/local/Cellar/ruby21/2.1.5/bin/rdoc

Normally /usr/local/Cellar should be writable by the current normal user (as running `sudo` for brew is not ideal).

**Comment by chadbernick** [comment]
Thanks, I got it sorted.
