### ISSUE TITLE
Paralellized `bundle install` with BUNDLE_JOBS=16 fails with newer Rubies

### ISSUE THREAD

**Issue by tknerr** [bundler/bundler#3545]
I have a weird issue when installing a bundle in parallel using the `BUNDLE_JOBS` configuration. This is on a Windows7 machine (have not tested on my linux box yet).

Up to now I was using Ruby 2.0.0p451 and everything was fine. 

Once I switched to Ruby 2.1.5p273 (and same for 2.2.1p85) the parallelized installation of the bundled gems fails at a random gem. Once I repeat this will eventually succeed and fail at another gem. After repeating several times I get all gems installed.

I suspect is has something to do with multithreading and the http(s) connections. Observations:

* when I do a single threaded install (i.e. remove `BUNDLE_JOBS` from `~/.bundle/config`) everything works fine - no warnings and it succeeds on the first pass
* during a multithreaded install I get lots of `OpenSSL::SSL::SSLError: SSL_read: cert already in hash table` warnings

This is my `~/.bundle/config`:
```
---
BUNDLE_PATH: ~/.gem/ruby/2.2.0
BUNDLE_JOBS: 16
BUNDLE_RETRY: 3
```

Here's the `Gemfile` I'm trying to install:
https://github.com/tknerr/sample-toplevel-cookbook/blob/master/Gemfile

And this is what I get on `bundle install` with Ruby 2.1.5 / 2.2.1:
```
...
Installing sawyer 0.6.0
Installing net-ssh-gateway 1.2.0
Installing net-scp 1.2.1
Installing stove 3.2.3

OpenSSL::SSL::SSLError: SSL_read: cert already in hash table
Installing rspec-mocks 3.2.1
Installing celluloid-io 0.16.2
Installing pry 0.10.1
Installing highline 1.7.1
Installing rspec-core 3.2.2
Installing tailor 1.4.1
Installing net-ssh-multi 1.2.0

OpenSSL::SSL::SSLError: SSL_read: cert already in hash table
Installing octokit 3.8.0
Installing specinfra 2.28.0
Installing ffi 1.9.8
An error occurred while installing foodcritic (4.0.0), and Bundler cannot
continue.
Make sure that `gem install foodcritic -v '4.0.0'` succeeds before bundling.
```

Here it fails randomly at the foodcritic gem. Once I try again it would fail on another gem. And I can repeat until everything installed...

Running `bundle install --verbose` reveals the stacktrace behind the SSL warnings, e.g.:
```
...
Installing polyglot 0.3.5
4:  polyglot (0.3.5) from X:/home/.gem/ruby/2.2.0/specifications/polyglot-0.3.5.gemspec

OpenSSL::SSL::SSLError: SSL_read: cert already in hash table
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1384:in `request'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/request.rb:154:in `perform_request'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/request.rb:109:in `fetch'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:346:in `request'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:231:in `fetch_http'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:247:in `fetch_http'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:267:in `fetch_path'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:302:in `cache_update_path'
X:/tools/ruby-2.2.1/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:168:in `download'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/rubygems_integration.rb:544:in `download_gem'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/fetcher.rb:63:in `download_gem_from_uri'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:370:in `fetch_gem'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:98:in `install'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/installer.rb:107:in `install_gem_from_spec'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/installer.rb:287:in `block in install_in_parallel'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/worker.rb:55:in `call'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/worker.rb:55:in `apply_func'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/worker.rb:50:in `block in process_queue'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/worker.rb:47:in `loop'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/worker.rb:47:in `process_queue'
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.2/lib/bundler/worker.rb:22:in `block (2 levels) in initialize'
...
```

..however, it does not reveal any details about the failed gem. For example, this is how the 2nd pass (that I started with the --verbose flag) ended:
```
...
Installing win32console 1.3.2
14:  win32console (1.3.2) from X:/home/.gem/ruby/2.2.0/specifications/win32console-1.3.2.gemspec
Installing hitimes 1.2.2
5:  hitimes (1.2.2) from X:/home/.gem/ruby/2.2.0/specifications/hitimes-1.2.2.gemspec
Installing libyajl2 1.2.0
7:  libyajl2 (1.2.0) from X:/home/.gem/ruby/2.2.0/specifications/libyajl2-1.2.0.gemspec
Installing json 1.8.2
12:  json (1.8.2) from X:/home/.gem/ruby/2.2.0/specifications/json-1.8.2.gemspec
An error occurred while installing addressable (2.3.8), and Bundler cannot
continue.
Make sure that `gem install addressable -v '2.3.8'` succeeds before bundling.
```

It's probably not an original bundler issue either. I had tried with differerent bundler versions as well, but it did not have any effect. The Ruby version was the crucial factor (2.0 works, 2.1 + 2.2 fail). 

However, since it happens in the context of bundler I thought it makes sense to report it here.

Any ideas?

**Comment by tknerr** [comment]
Oh, and that's my `bundle env` for the failed run above:
```
X:\tmp\sample-toplevel-cookbook>bundle env
Environment

    Bundler   1.9.2
    Rubygems  2.4.5
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]
    Git       1.9.5.msysgit.0

Bundler settings

    path
      Set for the current user (X:/home/.bundle/config): "~/.gem/ruby/2.2.0"
    jobs
      Set for the current user (X:/home/.bundle/config): "16"
    retry
      Set for the current user (X:/home/.bundle/config): "3"
    disable_shared_gems
      Set for your local app (X:/tmp/sample-toplevel-cookbook/.bundle/config): "1"

Gemfile

    source 'https://rubygems.org'

    gem 'chef', '11.16.4'
    gem 'berkshelf', '3.2.2'
    gem 'stove', '3.2.3'

    group :test do
      gem 'foodcritic', '4.0.0'
      gem 'tailor', '1.4.1'
      gem 'chefspec', '4.1.1'
    end

    group :integration do
      gem 'vagrant-wrapper', '2.0.2'
      gem 'test-kitchen', '1.3.1'
      gem 'kitchen-docker', '1.7.0'
      gem 'kitchen-vagrant', '0.16.0'
      gem 'serverspec', '2.3.1'
    end

Gemfile.lock

    <No X:/tmp/sample-toplevel-cookbook/Gemfile.lock found>
```

**Comment by segiddins** [comment]
That looks like an issue in rubygems to me

**Comment by tknerr** [comment]
I even suspect ruby core now, specifically in the OpenSSL part:

1. after changing the source in `Gemfile` to be `https://rubygems.org` (i.e. not https) I neither get the SSL errors nor the random errors
2. found an older [patch to improve the OpenSSL thread safety](https://bugs.ruby-lang.org/issues/8386). This just indicates there *might* be an issue with the OpenSSL part. Maybe a regression...

**Comment by tknerr** [comment]
Reported the bug in ruby core here:
https://bugs.ruby-lang.org/issues/11033

**Comment by tknerr** [comment]
Workaround: `bundle config mirror.https://rubygems.org http://rubygems.org` 

Not ideal, but better than changing all my Gemfiles...

**Comment by tknerr** [comment]
It must be indeed a ruby core issue. Just downgraded Rubygems to 2.4.4 (the version that ships with Ruby 2.0) but still the same behaviour

**Comment by shansudhakar** [comment]
It worked after updating the Gemfile with http://rubygems.org
