### ISSUE TITLE
NoMethodError: undefined method `spec' for nil:NilClass

### ISSUE THREAD

**Issue by digitalextremist** [bundler/bundler#3558]
That exception occurs when running `bundle install` on the current `ruby-head` ...
Have found this twice so far, and suspect I'll keep finding it if I keep looking:

* abstractive/rspec-log_split#2
* celluloid/timers#47

**Comment by digitalextremist** [comment]
This is in fact a bundler error. Posting patch.

**Comment by segiddins** [comment]
@digitalextremist could you please share the info requested in https://github.com/bundler/bundler/blob/master/ISSUES.md ? As it is, your issue doesn't really have enough in it to debug anything. Thanks!

**Comment by digitalextremist** [comment]
Copied from the referenced issues:

```
NoMethodError: undefined method `spec' for nil:NilClass
/home/de/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:232:in `spec'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/source/path/installer.rb:19:in `generate_bin'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/source/path.rb:194:in `block in generate_bin'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:53:in `chdir'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/monitor.rb:211:in `mon_synchronize'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:52:in `chdir'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/source/path.rb:189:in `generate_bin'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/source/path.rb:73:in `install'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/installer.rb:269:in `block in install_sequentially'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/forwardable.rb:183:in `each'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/forwardable.rb:183:in `each'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/installer.rb:268:in `install_sequentially'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/installer.rb:90:in `run'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/installer.rb:18:in `install'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/cli/install.rb:80:in `run'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
/home/de/.rvm/gems/ruby-head/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
/home/de/.rvm/gems/ruby-head/bin/bundle:23:in `load'
/home/de/.rvm/gems/ruby-head/bin/bundle:23:in `<main>'
/home/de/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/home/de/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

Resolved in #3559

**Comment by indirect** [comment]
Closing this in favor of #3559.

**Comment by benlovell** [comment]
For everyone experiencing travis issues, a smarter and perhaps more beneficial way of resolving this issue is to add the `sudo: false` configuration to your `.travis.yml` to use the container-based infrastructure that is generally better/faster and isn't afflicted with the same issue.
