### ISSUE TITLE
Bundle install running out of memory

### ISSUE THREAD

**Issue by dbackeus** [bundler/bundler#356]
Using Bundler while deploying to a 64 bit ubuntu 10.04 vps with 256MB ram I get this output/error.

$ bundle install --without test development

```
Updating git@github.com:streamio/logparser.git
Updating git://github.com/plataformatec/devise
Updating git://github.com/justinfrench/formtastic.git
Updating git://github.com/dbackeus/monque.git
Updating git://github.com/durran/mongoid.git
Updating git://github.com/rails/rails.git
Fetching source index from http://rubygems.org/
Updating git://github.com/rails/rails.git
/usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:352:in ``': Cannot allocate memory - git fetch --force --quiet "git://github.com/rails/rails.git" refs/heads/*:refs/heads/* (Errno::ENOMEM)
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:352:in `git'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:382:in `cache'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:413:in `chdir'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:413:in `in_cache'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:382:in `cache'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/source.rb:320:in `specs'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/environment.rb:51:in `send'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/environment.rb:51:in `resolve'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/environment.rb:49:in `each'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/environment.rb:49:in `resolve'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/installer.rb:66:in `resolve_remotely'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/environment.rb:28:in `specs'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/installer.rb:21:in `run'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/installer.rb:6:in `install'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/cli.rb:90:in `install'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor/task.rb:33:in `send'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor/task.rb:33:in `run'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor/invocation.rb:109
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor/invocation.rb:116:in `call'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor/invocation.rb:116:in `invoke'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor.rb:137:in `start'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor/base.rb:378:in `start'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/lib/bundler/vendor/thor.rb:124:in `start'
from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.25/bin/bundle:13
from /usr/bin/bundle:19:in `load'
from /usr/bin/bundle:19
```

If I monitor the memory usage while running the command it's clear that bundler is eating up more and more memory as it goes along (seems to syncronize with every "Updating git://..." output) starting out at 24MB and crashing at around 150MB (even though there is still 100MB to go on the system).

This seems like rather a lot of memory usage for a tool like bundler to use.

Let me know if you'd like more information about the VPS I'm running on etc. I noticed "privmpages"  failures in the admin interface for the VPS but I'm not knowledgeable enough to tell wether that can mean there is a problem with the VPS setup rather than bundler itself.

**Comment by jamrizzi** [comment]
I had this issue with `Bundler version 1.13.4`. `bundle lock` seemed to fix it. I have no idea why.
