### ISSUE TITLE
`ruby-head` cannot install certain gems: "NoMethodError: undefined method spec for NilClass"

### ISSUE THREAD

**Issue by digitalextremist** [bundler/bundler#3560]
This is a duplicate of the `rubygems` issue I posted: rubygems/rubygems#1220

This is happening *only* on `ruby-head` ... using `ruby-head`:

```
ruby -v
ruby 2.3.0dev (2015-04-11 trunk 50230) [x86_64-linux]
```

Trying to run `bundle install` will fail for certain gems:
```
$ bundle install
Your Gemfile lists the gem rspec (~> 3.2) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem rspec-log_split (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching git://github.com/abstractive/rspec-log_split.git
Fetching git://github.com/celluloid/timers.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Installing ast 2.0.0
Installing parser 2.2.0.3
Installing astrolabe 1.3.0
Installing benchmark-ips 1.2.0
Installing benchmark_suite 1.0.0
Using bundler 1.9.2
Installing hitimes 1.2.2

NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing timers (4.0.1), and Bundler cannot continue.
Make sure that `gem install timers -v '4.0.1'` succeeds before bundling.
```

Running this with `--verbose` we get:

```
NoMethodError: undefined method `spec' for nil:NilClass
/home/de/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:232:in `spec'
/home/de/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:717:in `build_extensions'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/source/path.rb:192:in `block in generate_bin'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:53:in `chdir'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/monitor.rb:211:in `mon_synchronize'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/shared_helpers.rb:52:in `chdir'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/source/path.rb:189:in `generate_bin'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/source/git.rb:170:in `install'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:269:in `block in install_sequentially'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/forwardable.rb:183:in `each'
/home/de/.rvm/rubies/ruby-head/lib/ruby/2.3.0/forwardable.rb:183:in `each'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:268:in `install_sequentially'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:90:in `run'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/installer.rb:18:in `install'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/cli/install.rb:80:in `run'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
/home/de/.rvm/gems/ruby-head@global/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
/home/de/.rvm/gems/ruby-head@global/bin/bundle:23:in `load'
/home/de/.rvm/gems/ruby-head@global/bin/bundle:23:in `<main>'
/home/de/.rvm/gems/ruby-head@global/bin/ruby_executable_hooks:15:in `eval'
/home/de/.rvm/gems/ruby-head@global/bin/ruby_executable_hooks:15:in `<main>'
An error occurred while installing timers (4.0.1), and Bundler cannot continue.
Make sure that `gem install timers -v '4.0.1'` succeeds before bundling.
```

Strangely, `gem install <gem> -v <version>` does work:

```
$ gem install timers -v '4.0.1'
Fetching: timers-4.0.1.gem (100%)
Successfully installed timers-4.0.1
Parsing documentation for timers-4.0.1
Installing ri documentation for timers-4.0.1
Done installing documentation for timers after 0 seconds
1 gem installed
```

But that doesn't affect the outcome of `bundle install` in the least. Same error again.

Then, if one clones the gem that's failing and tries to run `bundle install` within the scope of that gemspec, the exact same error there. *It cannot build itself.*

---

At the closest inspection I can perform at this moment without submitting a patch that breaks all the tests like last time, not knowing `bundler` or `rubygems` as well as other library's internals:

The issue does ultimately happen here, in the `rubygems/installer.rb` for `2.3.0` ( ruby-head ):

```ruby
def spec
  @package.spec
rescue Gem::Package::Error => e
  raise Gem::InstallError, "invalid gem: #{e.message}"
end
```

Like the exception raised says, `@package` is `nil` at that moment.

Here is an example `gemspec` that fails right now:

```ruby
# -*- encoding: utf-8 -*-
require File.expand_path('../lib/rspec/log_split/version', __FILE__)

Gem::Specification.new do |gem|
  gem.name          = "rspec-log_split"
  gem.version       = RSpec::LogSplit::VERSION
  gem.authors       = ["Tim Carey-Smith","digitalextremist //"]
  gem.email         = ["tim@spork.in","de@freed.network"]
  gem.description   = %q{A new logger for each example}
  gem.summary       = %q{Separate the logs between examples to allow for easier understanding}
  gem.homepage      = "https://github.com/halorgium/rspec-log_split"
  gem.license       = "MIT"

  gem.required_ruby_version     = '>= 1.9.3'

  gem.files         = `git ls-files`.split("\n")
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.require_paths = ["lib"]
  # gem.executables   = [] # tried setting this, but it doesn't matter either way.

  gem.add_development_dependency 'rake'
  gem.add_development_dependency 'bundler'
end
```

And here is the `Gemfile` for that same gem:

```ruby
source "https://rubygems.org"

gem 'bundler'
gem 'rake'

gem 'rspec', '~> 3.2'

gemspec

group :development do
  gem 'pry'
end
```

---

Last time I tried to frame this, it was believed this change broke this:

* rubygems/rubygems@620910a

But putting `attr_writer :spec` back helps nothing, since it's looking for `@package.spec` and not `#spec` ...

#### This however does fix the issue, which leads me to believe ( as I write this, that it's not bundler at all ):

```ruby
def spec
  @spec || @package.spec
rescue Gem::Package::Error => e
  raise Gem::InstallError, "invalid gem: #{e.message}"
end
```

But I am not sure. So this is preventing many, many gems from building properly from `gemspec` I am posting this in both `bundler` and `rubygems` -- whichever it doesn't apply to, I am sorry. But it seems important enough to double post. And I posted a Pull Request with the above change, but I am not confident that it is the right solution. Here is the commit:

* abstractive/rubygems@c49b29c8d3a3caae9587939b8e49949a11f9d449

**Comment by digitalextremist** [comment]
The 'patch' I pushed to `rubygems` doesn't break any tests. I posted this here with `bundler` because of the "installs via `gem install <gem> -v <version>`" piece, unsure of the specification is not being sent over properly, because `@package` definitely is `nil` under `ruby-head`

**Comment by digitalextremist** [comment]
`bundle env` output: https://gist.github.com/digitalextremist/76da54b7381856bc060f

**Comment by indirect** [comment]
Sorry, but I can't reproduce this.

```
$ gem -v
2.4.5

$ ruby -v
ruby 2.3.0dev (2015-04-12 trunk 50271) [x86_64-darwin14]

$ bundle -v
Bundler version 1.9.3

$ bundle install --path .bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rspec-log_split 0.0.2.pre from source at .
Using bundler 1.9.3
Installing method_source 0.8.2
Installing rspec-support 3.2.2
Installing slop 3.6.0
Installing diff-lcs 1.2.5
Installing coderay 1.1.0
Installing rspec-expectations 3.2.1
Installing pry 0.10.1
Installing rspec-mocks 3.2.1
Installing rspec-core 3.2.3
Installing pry-nav 0.2.4
Installing rspec 3.2.0
Bundle complete! 4 Gemfile dependencies, 13 gems now installed.
Bundled gems are installed into ./.bundle.
```

**Comment by digitalextremist** [comment]
I reproduced it with rubygems `2.4.6` and you can see the failure here:

https://travis-ci.org/celluloid/celluloid/jobs/58201750

**Comment by indirect** [comment]
Sorry, still works perfectly for me.

```
$ bundle -v
Bundler version 1.9.3

$ gem -v
2.4.6

$ ruby -v
ruby 2.3.0dev (2015-04-12 trunk 50271) [x86_64-darwin14]

$ bundle install --path .bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Using rspec-log_split 0.0.2.pre from source at .
Using bundler 1.9.3
Installing method_source 0.8.2
Installing slop 3.6.0
Installing rspec-support 3.2.2
Installing diff-lcs 1.2.5
Installing coderay 1.1.0
Installing rspec-expectations 3.2.1
Installing pry 0.10.1
Installing rspec-mocks 3.2.1
Installing rspec-core 3.2.3
Installing pry-nav 0.2.4
Installing rspec 3.2.0
Bundle complete! 4 Gemfile dependencies, 13 gems now installed.
Bundled gems are installed into ./.bundle.
```

**Comment by yuki24** [comment]
@digitalextremist I believe this commit 5749adedea810a94dc5c156f0f36247c572ea368 fixed the issue. Try using 1.9.3. The celluloid build picked up 1.9.2.

**Comment by kbhute-ibm** [comment]
Using 'gem install bundler -v 1.9.3' fixed this issue. Thank you!
