### ISSUE TITLE
lib/ruby/2.2.0/x86_64-linux/digest/sha1.so: undefined symbol: rb_Digest_SHA1_Init

### ISSUE THREAD

**Issue by rye** [bundler/bundler#3615]
I currently have Ruby 2.2.2p95 installed, and all of my other packages work fine, except for `bundler`.  My version of Ruby was compiled with OpenSSL support (I have the latest version available from my Linux distribution's package repositories), but for some reason whenever I try to run `bundle` commands, I get the following error:

```
/home/kristofer/.local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /home/kristofer/.local/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so: undefined symbol: rb_Digest_SHA1_Init - /home/kristofer/.local/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so (LoadError)
	from /home/kristofer/.local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/definition.rb:1:in `<top (required)>'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler.rb:155:in `definition'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/cli/install.rb:78:in `run'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/cli.rb:157:in `install'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/cli.rb:10:in `start'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/bin/bundle:20:in `block in <top (required)>'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /home/kristofer/.local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/bin/bundle:18:in `<top (required)>'
	from /home/kristofer/.local/bin/bundle:23:in `load'
	from /home/kristofer/.local/bin/bundle:23:in `<main>'
```

Okay, so it looks like it can't read some symbols. Does the file have those symbols? Yes, it does, which is odd, because I feel like bundler should pick up on it.

It's trying to find the `rb_Digest_SHA1_Init` function in the `~/.local/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so` file.

So when I run `readelf -a ~/.local/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so`, here's the pertinent stuff:

```
Symbol table '.symtab' contains 76 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 00000000000001c8     0 SECTION LOCAL  DEFAULT    1 
     2: 00000000000001f0     0 SECTION LOCAL  DEFAULT    2 
     3: 0000000000000230     0 SECTION LOCAL  DEFAULT    3 
     4: 0000000000000470     0 SECTION LOCAL  DEFAULT    4 
     5: 0000000000000620     0 SECTION LOCAL  DEFAULT    5 
     6: 0000000000000650     0 SECTION LOCAL  DEFAULT    6 
     7: 0000000000000690     0 SECTION LOCAL  DEFAULT    7 
     8: 0000000000000798     0 SECTION LOCAL  DEFAULT    8 
     9: 0000000000000870     0 SECTION LOCAL  DEFAULT    9 
    10: 0000000000000890     0 SECTION LOCAL  DEFAULT   10 
    11: 0000000000000930     0 SECTION LOCAL  DEFAULT   11 
    12: 0000000000000ad0     0 SECTION LOCAL  DEFAULT   12 
    13: 0000000000000ad9     0 SECTION LOCAL  DEFAULT   13 
    14: 0000000000000b04     0 SECTION LOCAL  DEFAULT   14 
    15: 0000000000000b28     0 SECTION LOCAL  DEFAULT   15 
    16: 0000000000200d20     0 SECTION LOCAL  DEFAULT   16 
    17: 0000000000200d28     0 SECTION LOCAL  DEFAULT   17 
    18: 0000000000200d30     0 SECTION LOCAL  DEFAULT   18 
    19: 0000000000200d40     0 SECTION LOCAL  DEFAULT   19 
    20: 0000000000200d98     0 SECTION LOCAL  DEFAULT   20 
    21: 0000000000200fc8     0 SECTION LOCAL  DEFAULT   21 
    22: 0000000000201000     0 SECTION LOCAL  DEFAULT   22 
    23: 0000000000201060     0 SECTION LOCAL  DEFAULT   23 
    24: 0000000000000000     0 SECTION LOCAL  DEFAULT   24 
    25: 0000000000000000     0 SECTION LOCAL  DEFAULT   25 
    26: 0000000000000000     0 SECTION LOCAL  DEFAULT   26 
    27: 0000000000000000     0 SECTION LOCAL  DEFAULT   27 
    28: 0000000000000000     0 SECTION LOCAL  DEFAULT   28 
    29: 0000000000000000     0 SECTION LOCAL  DEFAULT   29 
    30: 0000000000000000     0 SECTION LOCAL  DEFAULT   30 
    31: 0000000000000000     0 SECTION LOCAL  DEFAULT   31 
    32: 0000000000000000     0 SECTION LOCAL  DEFAULT   32 
    33: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
    34: 0000000000200d30     0 OBJECT  LOCAL  DEFAULT   18 __JCR_LIST__
    35: 0000000000000930     0 FUNC    LOCAL  DEFAULT   11 deregister_tm_clones
    36: 0000000000000970     0 FUNC    LOCAL  DEFAULT   11 register_tm_clones
    37: 00000000000009c0     0 FUNC    LOCAL  DEFAULT   11 __do_global_dtors_aux
    38: 0000000000201060     1 OBJECT  LOCAL  DEFAULT   23 completed.6636
    39: 0000000000200d28     0 OBJECT  LOCAL  DEFAULT   17 __do_global_dtors_aux_fin
    40: 0000000000000a00     0 FUNC    LOCAL  DEFAULT   11 frame_dummy
    41: 0000000000200d20     0 OBJECT  LOCAL  DEFAULT   16 __frame_dummy_init_array_
    42: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS sha1init.c
    43: 0000000000200d60    56 OBJECT  LOCAL  DEFAULT   19 sha1
    44: 0000000000201068     8 OBJECT  LOCAL  DEFAULT   23 rb_intern_id_cache.8334
    45: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS sha1ossl.c
    46: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
    47: 0000000000000ba8     0 OBJECT  LOCAL  DEFAULT   15 __FRAME_END__
    48: 0000000000200d30     0 OBJECT  LOCAL  DEFAULT   18 __JCR_END__
    49: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS 
    50: 0000000000201000     0 OBJECT  LOCAL  DEFAULT   22 _GLOBAL_OFFSET_TABLE_
    51: 0000000000201060     0 OBJECT  LOCAL  DEFAULT   22 __TMC_END__
    52: 0000000000200d40     0 OBJECT  LOCAL  DEFAULT   19 __dso_handle
    53: 0000000000200d98     0 OBJECT  LOCAL  DEFAULT   20 _DYNAMIC
    54: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_ivar_set
    55: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
    56: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _Jv_RegisterClasses
    57: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_define_class_under
    58: 0000000000000ad0     0 FUNC    GLOBAL DEFAULT   12 _fini
    59: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_Digest_SHA1_Finish
    60: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_Digest_SHA1_Init
    61: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTab
    62: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
    63: 0000000000000a30   141 FUNC    GLOBAL DEFAULT   11 Init_sha1
    64: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@@GLIBC_2.2
    65: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_intern2
    66: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_require
    67: 0000000000201060     0 NOTYPE  GLOBAL DEFAULT   23 __bss_start
    68: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_Digest_SHA1_Update
    69: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_data_object_alloc
    70: 0000000000000ac0    14 FUNC    GLOBAL DEFAULT   11 SHA1_Finish
    71: 0000000000201070     0 NOTYPE  GLOBAL DEFAULT   23 _end
    72: 0000000000201060     0 NOTYPE  GLOBAL DEFAULT   22 _edata
    73: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND rb_path2class
    74: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SHA1_Final@@libcrypto.so.
    75: 0000000000000870     0 FUNC    GLOBAL DEFAULT    9 _init
```

So it has `rb_Digest_SHA1_Init`, but it's not reading it.

Help?

**Comment by segiddins** [comment]
This definitely feels like a ruby (or maybe RubyGems) issue, but not a bundler issue.

**Comment by TimMoore** [comment]
Yeah, I don't think there's anything Bundler can do about this. Does `ruby -rdigest/sha1 -e '1'` fail the same way?

Some Googling around suggests that it might be a missing libssl-dev OS package http://stackoverflow.com/questions/3545118/faulty-ruby-compilation-with-rvm-getting-undefined-symbol-rb-digest-md5-init

**Comment by rye** [comment]
No, `ruby -rdigest/sha1 -e '1'` works perfectly fine without complaining.

As I stated, I have the RPM version of libssl-dev installed and very up-to-date.

**Comment by rye** [comment]
`gem install <anything>` works flawlessly.

**Comment by rye** [comment]
I just found a potential problem: it could be an outdated system-wide installation of Ruby that was included as part of some `texlive-*` tomfoolery. I'm erasing it now, will test a clean install of Ruby to see if it works better this time.

**Comment by TimMoore** [comment]
OK cool... I was thinking that the most likely explanation is that Bundler is invoking a different version of Ruby than you expect, but I didn't see any evidence of that in the error.

In any case, Bundler doesn't do anything unusual as far as loading native code goes, so there is almost certainly some environmental issue. Let us know how it goes after you remove the system-wide Ruby.

**Comment by rye** [comment]
Important to note that those symbols *exist* in the appropriate file, but they aren't read, and it could've very well been the outdated system installation, as you say. Recompiling ruby now, will report back very shortly once it's done and installed.

**Comment by rye** [comment]
It seems like Bundler was, indeed, invoking the incorrect version of Ruby, since when I tried invoking `bundle install` it complained about `/usr/bin/ruby` no longer existed, consistent with your explanation.

**Comment by indirect** [comment]
it might be that the ruby is hard-coded. you can check with `head $(which bundle)`.

**Comment by rye** [comment]
Well okay, now `ruby -rdigest/sha1 -e '1'` doesn't work. So it is a Ruby problem.
