### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_file_s_stat - lib/elasticsearch_indexer/**/*

### ISSUE THREAD

**Issue by GustavoCaso** [bundler/bundler#3684]
- What did you do?

  I ran the command `/Users/Gustavo/.gem/ruby/2.1.5/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - lib/elasticsearch_indexer/**/*
      /Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `stat'
      /Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `block in validate_permissions'
      /Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `each'
      /Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `validate_permissions'
      /Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2540:in `validate'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/ui/shell.rb:76:in `silence'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/rubygems_integration.rb:51:in `validate'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler.rb:369:in `block in load_gemspec_uncached'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:53:in `chdir'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:52:in `chdir'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler.rb:362:in `load_gemspec_uncached'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler.rb:352:in `load_gemspec'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/source/path.rb:134:in `block in load_spec_files'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/source/path.rb:133:in `each'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/source/path.rb:133:in `load_spec_files'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/source/git.rb:189:in `load_spec_files'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/source/path.rb:91:in `local_specs'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/source/git.rb:159:in `specs'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/spec_set.rb:88:in `block in materialize'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/spec_set.rb:85:in `map!'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/spec_set.rb:85:in `materialize'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/definition.rb:165:in `missing_specs'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/installer.rb:70:in `block in run'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/ui/shell.rb:76:in `silence'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/installer.rb:67:in `run'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/installer.rb:18:in `install'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/cli/install.rb:107:in `run'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/cli.rb:158:in `install'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/cli.rb:10:in `start'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/bin/bundle:20:in `block in <top (required)>'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/Gustavo/.gem/ruby/2.1.5/gems/bundler-1.10.1/bin/bundle:18:in `<top (required)>'
      /Users/Gustavo/.gem/ruby/2.1.5/bin/bundle:23:in `load'
      /Users/Gustavo/.gem/ruby/2.1.5/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.1
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    GEM_HOME  /Users/Gustavo/.gem/ruby/2.1.5
    GEM_PATH  /Users/Gustavo/.gem/ruby/2.1.5:/Users/Gustavo/.rubies/ruby-2.1.5/lib/ruby/gems/2.1.0
    Git       2.3.2 (Apple Git-55)

**Comment by GustavoCaso** [comment]
Also `bunlde clean --force` give me the same error
