### ISSUE TITLE
Crash on file not found

### ISSUE THREAD

**Issue by brauliobo** [bundler/bundler#3695]
A warning should be given instead, IMO

```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/braulio/.rbenv/versions/2.1.5/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - lib/knife-solo/resources/patch_cookbooks/chef-solo-search/.travis.yml
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `stat'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `block in validate_permissions'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `each'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `validate_permissions'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/specification.rb:2540:in `validate'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `validate'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:369:in `block in load_gemspec_uncached'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `chdir'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:52:in `chdir'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:362:in `load_gemspec_uncached'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:352:in `load_gemspec'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:134:in `block in load_spec_files'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `each'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `load_spec_files'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/git.rb:189:in `load_spec_files'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:91:in `local_specs'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/git.rb:159:in `specs'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/spec_set.rb:88:in `block in materialize'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/spec_set.rb:85:in `map!'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/spec_set.rb:85:in `materialize'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/definition.rb:165:in `missing_specs'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:70:in `block in run'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:67:in `run'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:18:in `install'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/cli/install.rb:107:in `run'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/cli.rb:158:in `install'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/cli.rb:10:in `start'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/bin/bundle:20:in `block in <top (required)>'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/bin/bundle:18:in `<top (required)>'
      /home/braulio/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
      /home/braulio/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.2
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    GEM_HOME  /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0
    GEM_PATH  /home/braulio/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0:/home/braulio/.gem/ruby/2.1.0
    Git       2.1.4
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.
```

**Comment by brauliobo** [comment]
the problem happened because the gem submodules were not fetched. is there an option for bundle to fetch the git submodules?

**Comment by segiddins** [comment]
`:submodules => true`

**Comment by brauliobo** [comment]
duplicate of #933

**Comment by brauliobo** [comment]
thanks @segiddins !
