### ISSUE TITLE
Bundler silences error output from `gem build` (when running `rake install`)

### ISSUE THREAD

**Issue by e2** [bundler/bundler#3701]
Problem: It's an annoyance to run multiple commands to show the cause.

Command: `bundle exec rake install` on new project created with `bundle new foo`

Expected: output with gem error, e.g. 
```
FIXME" or "TODO" is not a description
```

Actual: 
```
Running `gem build -V '/home/me/foo/foo.gemspec' 2>&1' failed. Run this command directly for more detailed output.
```

The `RubyGems::CommandManager` tries to show the error, but the `ui` is set to `Bundler::UI::RGProxy`, with it's `ui` set to `Bundler::UI::Silent`, an the call trace is:

```
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler.rb:99:in `new'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler.rb:99:in `ui='
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler.rb:95:in `ui'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/resolver.rb:230:in `before_resolution'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:99:in `start_resolution'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:59:in `resolve'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:40:in `resolve'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/resolver.rb:199:in `start'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/resolver.rb:182:in `resolve'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/definition.rb:199:in `resolve'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/definition.rb:139:in `specs'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/definition.rb:184:in `specs_for'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/definition.rb:173:in `requested_specs'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/environment.rb:18:in `requested_specs'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/runtime.rb:13:in `setup'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler.rb:126:in `setup'
/home/me/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.2/lib/bundler/setup.rb:18:in `<top (required)>'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/me/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Suggestion: I don't think `UI::Silent` should be used for `Bundler.rubygems.ui` - in this case at least.

**Comment by segiddins** [comment]
Can you please provide us with a reproduction script?

**Comment by e2** [comment]
There's nothing special - it's just running `bundle exec rake` when the fresh gemspec still has TODO entries.

Here's a docker session (ubuntu + non-root user + rvm)

```
➜  ~  docker run -i -t --rm e2dk/rvm_user_install /bin/bash -l
guest@13aa688f0763:~$ bundle config gem.coc true
guest@13aa688f0763:~$ bundle config gem.test false
guest@13aa688f0763:~$ bundle config gem.mit true
guest@13aa688f0763:~$ bundle gem foo
Creating gem 'foo'...
Code of conduct enabled in config
MIT License enabled in config
      create  foo/Gemfile
      create  foo/.gitignore
      create  foo/lib/foo.rb
      create  foo/lib/foo/version.rb
      create  foo/foo.gemspec
      create  foo/Rakefile
      create  foo/README.md
      create  foo/bin/console
      create  foo/bin/setup
      create  foo/CODE_OF_CONDUCT.md
      create  foo/LICENSE.txt
      create  foo/.travis.yml
Initializing git repo in /home/guest/foo
guest@13aa688f0763:~$ cd foo
guest@13aa688f0763:~/foo$ bundle exec rake install
rake aborted!
Running `gem build -V '/home/guest/foo/foo.gemspec' 2>&1' failed. Run this command directly for more detailed output.
/home/guest/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:160:in `sh'
/home/guest/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:75:in `build_gem'
/home/guest/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:39:in `block in install'
Tasks: TOP => install => build
(See full trace by running task with --trace)
guest@13aa688f0763:~/foo$
➜  ~  docker run -i -t --rm e2dk/rvm_user_install /bin/bash -l
guest@13aa688f0763:~$ bundle config gem.coc true
guest@13aa688f0763:~$ bundle config gem.test false
guest@13aa688f0763:~$ bundle config gem.mit true
guest@13aa688f0763:~$ bundle gem foo
Creating gem 'foo'...
Code of conduct enabled in config
MIT License enabled in config
      create  foo/Gemfile
      create  foo/.gitignore
      create  foo/lib/foo.rb
      create  foo/lib/foo/version.rb
      create  foo/foo.gemspec
      create  foo/Rakefile
      create  foo/README.md
      create  foo/bin/console
      create  foo/bin/setup
      create  foo/CODE_OF_CONDUCT.md
      create  foo/LICENSE.txt
      create  foo/.travis.yml
Initializing git repo in /home/guest/foo
guest@13aa688f0763:~$ cd foo
guest@13aa688f0763:~/foo$ bundle exec rake install
rake aborted!
Running `gem build -V '/home/guest/foo/foo.gemspec' 2>&1' failed. Run this command directly for more detailed output.
/home/guest/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:160:in `sh'
/home/guest/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:75:in `build_gem'
/home/guest/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:39:in `block in install'
Tasks: TOP => install => build
(See full trace by running task with --trace)
guest@13aa688f0763:~/foo$ gem --version
2.4.6
```

`gem build` is providing no output, because RubyGems `ui` has been set with Bundler::UI::Silent, which silences all output. And when Bundler gets no output, it gives the fallback message "Run this command directly (...)".

I guess errors shouldn't be silenced, and the default RubyGems user interface classes don't make this too easy.

**Comment by e2** [comment]
Here's is a better example of what's going on:

```
guest@d992a416055f:~/foo$ gem build -V '/home/guest/foo/foo.gemspec'
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    "FIXME" or "TODO" is not an author
guest@d992a416055f:~/foo$ RUBYOPT=-rbundler/setup gem build -V '/home/guest/foo/foo.gemspec'
guest@d992a416055f:~/foo$
```

**Comment by segiddins** [comment]
Great, thanks so much for the reproduction steps @e2 ! probably just need to reset at the end of bundler/setup

**Comment by e2** [comment]
Yes, setting `Bundler.rubygems.ui = nil` at the end of `Bundler#setup` works fine (both for `gem build` and `gem install` errors).

**Comment by segiddins** [comment]
Yeah, I'll make a PR with the necessary changes tonight when I get home, thanks for helping debug!

**Comment by e2** [comment]
Glad to help - thanks for responding so quickly! 

Have a nice evening.

**Comment by segiddins** [comment]
Should be fixed on stable, and there will be a bug fix released shortly.

**Comment by e2** [comment]
Awesome, thanks! :)
