### ISSUE TITLE
No such file or directory @ rb_file_s_stat - .document

### ISSUE THREAD

**Issue by reiz** [bundler/bundler#3702]
I just updated to Ruby 2.2.2 and executed 

```
bundle update
```

on one of my projects and got this 

```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - .document
      /Users/reiz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2716:in `stat'
      /Users/reiz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2716:in `block in validate_permissions'
      /Users/reiz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2715:in `each'
      /Users/reiz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2715:in `validate_permissions'
      /Users/reiz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2582:in `validate'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `validate'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler.rb:369:in `block in load_gemspec_uncached'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `chdir'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /Users/reiz/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:52:in `chdir'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler.rb:362:in `load_gemspec_uncached'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler.rb:352:in `load_gemspec'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/source/path.rb:134:in `block in load_spec_files'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `each'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `load_spec_files'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/source/path.rb:91:in `local_specs'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/source/path.rb:99:in `specs'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/definition.rb:548:in `block in converge_locked_specs'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/definition.rb:537:in `each'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/definition.rb:537:in `converge_locked_specs'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/definition.rb:194:in `resolve'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/definition.rb:139:in `specs'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/definition.rb:128:in `resolve_remotely!'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/installer.rb:79:in `run'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/installer.rb:18:in `install'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/cli/update.rb:51:in `run'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/cli.rb:183:in `update'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/cli.rb:10:in `start'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/bin/bundle:20:in `block in <top (required)>'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/gems/bundler-1.10.2/bin/bundle:18:in `<top (required)>'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/bin/bundle:23:in `load'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/bin/bundle:23:in `<main>'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/bin/ruby_executable_hooks:15:in `eval'
      /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.2
    Rubygems  2.4.7
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    GEM_HOME  /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api
    GEM_PATH  /Users/reiz/.rvm/gems/ruby-2.2.2@veye-api:/Users/reiz/.rvm/gems/ruby-2.2.2@global
    RVM       1.26.11 (latest)
    Git       2.4.2
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.
```

I expected that it updates my Gemfile.lock, like always. But This is totally broken :-( Any ideas?

**Comment by reiz** [comment]
It's fixed now. In a gemspec file I referenced a non existing `.document` file in `s.files`. After I cleaned that up it was running through like always.
