### ISSUE TITLE
`rake install` from gem_tasks fails

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#3705]
```
git clone https://github.com/e2/nenv
cd nenv
gem install bundler
bundle exec rake install
```

gives me

```
nenv 0.2.0 built to pkg/nenv-0.2.0.gem.
rake aborted!
Couldn't install gem, run `gem install /home/davidr/Work/nenv/pkg/nenv-0.2.0.gem' for more detailed output
/home/davidr/.gem/ruby/2.2.2/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:87:in `install_gem'
/home/davidr/.gem/ruby/2.2.2/gems/bundler-1.10.2/lib/bundler/gem_helper.rb:44:in `block in install'
Tasks: TOP => install
(See full trace by running task with --trace)
```

With `1.10.0.pre2` and earlier it seems to work fine.

Running `gem install /home/davidr/Work/nenv/pkg/nenv-0.2.0.gem` does work.

**Comment by segiddins** [comment]
This should be fixed by https://github.com/bundler/bundler/pull/3707, which will be released shortly.

**Comment by deivid-rodriguez** [comment]
Thanks great, thanks!
