### ISSUE TITLE
Connection reset by peer - SSL_connect (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by techgraphics** [bundler/bundler#3717]
- What did you do?
**> bundle exec jekyll serve --drafts**
- What did you expect to happen?
**Start jekyllrb server (using Mac OS X 10.9.5)**
- What happened instead?

**> bundle exec jekyll serve --drafts**

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from ~/git/techgraphics.github.io/Gemfile:7:in `eval_gemfile'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/dsl.rb:32:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/dsl.rb:32:in `eval_gemfile'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/dsl.rb:10:in `evaluate'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:25:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler.rb:155:in `definition'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler.rb:118:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/setup.rb:8:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**> bundle install**

Error details

    Errno::ECONNRESET: Connection reset by peer - SSL_connect
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
    ~/git/techgraphics.github.io/Gemfile:7:in `eval_gemfile'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/dsl.rb:32:in `instance_eval'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/dsl.rb:32:in `eval_gemfile'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/dsl.rb:10:in `evaluate'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:25:in `build'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler.rb:155:in `definition'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/cli/install.rb:78:in `run'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
    /usr/bin/bundle:23:in `load'
    /usr/bin/bundle:23:in `<main>'
```

Environment

    Bundler   1.9.2
    Rubygems  2.4.7
    Ruby      2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    GEM_HOME  /Library/Ruby/Gems/2.0.0
    GEM_PATH  /Library/Ruby/Gems/2.0.0:/Users/gstaylor/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
    Git       2.3.5

**>ping -c5 rubygems.org**

PING rubygems.org (54.186.104.15): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

--- rubygems.org ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by techgraphics** [comment]
Note: they block ping so that’s not a good test.

**Comment by indirect** [comment]
Ugh, we really need to be catching ECONNRESET :(

**Comment by indirect** [comment]
@techgraphics unfortunately, this error has nothing whatsover to do with Bundler. You have put Ruby code into your Gemfile that causes this error:

```ruby
require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)
```

Have a good day!
