### ISSUE TITLE
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!

### ISSUE THREAD

**Issue by vivek2007** [bundler/bundler#3737]
bundle install

```
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb:29:in `initialize': No route to host - connect(2) (Errno::EHOSTUNREACH)
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb:29:in `open'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb:29:in `block in connect'
	from /home/hp/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /home/hp/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb:29:in `connect'
	from /home/hp/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /home/hp/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/net/http.rb:751:in `start'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent.rb:628:in `start'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent.rb:570:in `connection_for'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/net/http/persistent.rb:930:in `request'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:202:in `fetch'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/fetcher.rb:176:in `use_api'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:224:in `block in remote_specs'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:224:in `select'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:224:in `remote_specs'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:163:in `fetch_specs'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:67:in `specs'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/lazy_specification.rb:52:in `__materialize__'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/spec_set.rb:88:in `block in materialize'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in `resolve_remotely!'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/installer.rb:83:in `run'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/installer.rb:14:in `install'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/cli.rb:247:in `install'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/task.rb:27:in `run'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/thor.rb:344:in `dispatch'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/vendor/thor/base.rb:434:in `start'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/bin/bundle:20:in `block in <top (required)>'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/bin/bundle:20:in `<top (required)>'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/bin/bundle:23:in `load'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@global/bin/bundle:23:in `<main>'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@grad_contact/bin/ruby_executable_hooks:15:in `eval'
	from /home/hp/.rvm/gems/ruby-1.9.3-p484@grad_contact/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by TimMoore** [comment]
We should catch this error and print something nicer, but @vivek2007 it looks like the problem is that outbound network connections are blocked. Are you required to use a proxy on your network?

**Comment by vivek2007** [comment]
no not required

**Comment by vivek2007** [comment]
@TimMoore No not required any proxy on my system, because it is localhost ubuntu system

**Comment by segiddins** [comment]
Does the same occur on Bundler 1.10?

**Comment by pducks32** [comment]
Where is this error coming from? I can't seem to find the "Unfortunately..." part anywhere so I can catch it and make it use the normal error report.

**Comment by vivek2007** [comment]
while i am doing bundle install

**Comment by TimMoore** [comment]
@vivek2007 please try again with the latest version of Bundler and let us know if you have the same problem. `gem install bundler` to upgrade.

**Comment by segiddins** [comment]
Closing this due to lack of response.
