### ISSUE TITLE
encounter error while installing nokogiri

### ISSUE THREAD

**Issue by beanscake** [bundler/bundler#3794]
```
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tmpdir.rb:85:in `mkdir'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tmpdir.rb:85:in `block in mktmpdir'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tmpdir.rb:142:in `create'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/tmpdir.rb:85:in `mktmpdir'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:14:in `build'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/beanscake/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/fetcher.rb:1:in `<top (required)>'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/cli/install.rb:98:in `run'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/cli.rb:162:in `install'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/cli.rb:10:in `start'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/bin/bundle:20:in `block in <top (required)>'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.5/bin/bundle:18:in `<top (required)>'
      /Users/beanscake/.rbenv/versions/2.1.6/bin/bundle:23:in `load'
      /Users/beanscake/.rbenv/versions/2.1.6/bin/bundle:23:in `<main>'
```

Environment

    Bundler   1.10.5
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
    GEM_HOME  /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework
    GEM_PATH  /Users/beanscake/.rvm/gems/ruby-2.1.6@metasploit-framework:/Users/beanscake/.rvm/gems/ruby-2.1.6@global
    RVM       1.26.11 (latest)
    Git       1.9.3 (Apple Git-50)
    rubygems-bundler (1.4.4)

Bundler settings

    build.nokogiri
      Set for the current user (/Users/beanscake/.bundle/config): "--use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2"
    build.pg
      Set for the current user (/Users/beanscake/.bundle/config): "--use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2"

**Comment by indirect** [comment]
Thanks for the report! This looks like an error while nokogiri tried to create a temporary directory. Please follow [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md) and report back.
