### ISSUE TITLE
Better error for missing gems

### ISSUE THREAD

**Issue by andremedeiros** [bundler/bundler#3839]
Example:

```
/var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find SyslogLogger-2.0 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/spec_set.rb:85:in `map!'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/spec_set.rb:85:in `materialize'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:185:in `specs_for'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/environment.rb:18:in `requested_specs'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:13:in `setup'
	from /var/lib/gems/2.2.0/gems/bundler-1.10.5/lib/bundler.rb:127:in `setup'
	from test.rb:2:in `<main>'
```

This happened on a call to `Bundler.setup` on a project where I hadn't run `bundle install` yet.

Improve this to indicate that the user might need to run `bundle install` instead of dumping a backtrace.

**Comment by segiddins** [comment]
@andremedeiros I believe we purposefully don't use friendly errors in setup?

**Comment by andremedeiros** [comment]
Maybe we should just raise it, seen as it's not a CLI utilisation. Not 100% sure.

**Comment by segiddins** [comment]
Yeah, I think it's correct the way it is.

**Comment by andremedeiros** [comment]
My bad.
