### ISSUE TITLE
`bundle exec gem list` works, `bundle exec gem list -d` does not.

### ISSUE THREAD

**Issue by richardkmichael** [bundler/bundler#3840]
I have no idea if I ought to expect `b e gem list -d` to work, but as `b e gem list` does, I was surprised..

```shell
$ bundle exec gem list

*** LOCAL GEMS ***

bundler (1.10.5)
hoe (3.13.1)
hoe-bundler (1.2.0)
mini_portile (0.6.2)
minitest (5.7.0)
rake (10.4.2)
rake-compiler (0.9.5)
rdoc (4.2.0)

$ bundle exec gem list -d

*** LOCAL GEMS ***

ERROR:  While executing gem ... (NoMethodError)
    undefined method `fetch_spec' for #<Bundler::StubSpecification:0x007ffc72a0e2b0>

$ bundle --version
Bundler version 1.10.5

$ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin12.0]
```

**Comment by esasse** [comment]
I confirm the problem, same results here.

**Comment by segiddins** [comment]
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `fetch_spec' for #<Bundler::StubSpecification:0x007fd44a13f148>
	/Users/segiddins/Development/OpenSource/bundler/lib/bundler/remote_specification.rb:78:in `method_missing'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:230:in `entry_details'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:273:in `make_entry'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:221:in `block in output_versions'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:201:in `each'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:201:in `output_versions'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:195:in `output_query_results'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:144:in `show_gems'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:109:in `block in execute'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:109:in `each'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/query_command.rb:109:in `execute'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
	/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
	/usr/local/opt/rbenv/versions/2.2.2/bin/gem:21:in `<main>'
```

**Comment by segiddins** [comment]
This was fixed in RubyGems in https://github.com/rubygems/rubygems/commit/3df26b1e8db358a57a414b07087e2611d01a01cb

**Comment by richardkmichael** [comment]
Ok, thanks @segiddins ; it's on `master` (and not `2.4`), so it appears I'll need to wait for `2.5`.
