### ISSUE TITLE
`Permission denied @ rb_sysopen - /usr/bin/rake (Errno::EACCES)`

### ISSUE THREAD

**Issue by paulmenzel** [bundler/bundler#3891]
Dear Bundler folks, using [Debian 8 (Jessie)](https://www.debian.org/releases/stable/) with [Bundler 1.7.4](https://packages.debian.org/jessie/bundler)

        $ bundle --version
        Bundler version 1.7.4

and [rvm](https://rvm.io) 1.26.11, running bundle in a project fails with the error below.

```
$ more .ruby-version
ruby-2.0.0-p645
$ bundle env
Bundler 1.7.4
Ruby 2.1.5 (2014-11-13 patchlevel 273) [i386-linux-gnu]
Rubygems 2.2.2
rvm 1.26.11 (master)
GEM_HOME /home/joey/.rvm/gems/ruby-2.0.0-p645@project
GEM_PATH /home/joey/.rvm/gems/ruby-2.0.0-p645@project:/home/joey/.rvm/gems/ruby-2.0.0-p645@global
rubygems-bundler (1.4.4)

Bundler settings
  build.nokogiri
    Set for the current user (/home/joey/.bundle/config): "--use-system-libraries"


Gemfile
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

gem 'pg'
[…]
$ DEBUG=1 bundle
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /usr/bin/ruby2.1 extconf.rb
/home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `initialize': Permission denied @ rb_sysopen - /usr/bin/rake (Errno::EACCES)
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `open'
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `block in try_to_fix_binstubs'
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `map'
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `try_to_fix_binstubs'
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:46:in `block in execute_no_wrapper'
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `each'
        from /home/joey/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `execute_no_wrapper'
        from extconf.rb:19:in `<main>'
executable-hooks 1.3.2
rake 10.1.0

extconf failed, exit code 1

Gem files will remain installed in /home/joey/.rvm/gems/ruby-2.0.0-p645@global/gems/executable-hooks-1.3.2 for inspection.
Results logged to /home/joey/.rvm/gems/ruby-2.0.0-p645@global/extensions/x86-linux/2.1.0/executable-hooks-1.3.2/gem_make.out
        from /usr/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
        from /usr/lib/ruby/2.1.0/tempfile.rb:324:in `open'
        from /usr/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `synchronize'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
        from /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
        from /usr/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
        from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
        from /usr/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
        from /usr/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
        from /usr/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
        from /usr/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
        from /usr/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:12:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/bundler/vendored_persistent.rb:11:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/bundler/fetcher.rb:1:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:71:in `run'
        from /usr/lib/ruby/vendor_ruby/bundler/cli.rb:145:in `install'
        from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
        from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
        from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
        from /usr/lib/ruby/vendor_ruby/bundler/cli.rb:9:in `start'
        from /usr/bin/bundle:20:in `block in <main>'
        from /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:5:in `with_friendly_errors'
        from /usr/bin/bundle:18:in `<main>'
$ ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [i686-linux]
$ dpkg -S /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb
libruby2.1:i386: /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb
$ ruby2.1 --version # from the Debian package `ruby2.1`
ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]
```

I am wondering, why it’s trying to do something in the system directory `/usr/lib/ruby/2.1.0/rubygems/ext/builder.rb`?

Setting the Ruby version to 2.1.6 in `.ruby-version` gets `bundle` to succeed.

**Comment by EduardoBautista** [comment]
It looks like you are using the Ruby installed at the system level by a debian package.  Changing the ruby version to 2.1.6 means you used a Ruby installed by RVM at the user level so Bundler is able to install gems as requested.  Your bundle command is using system ruby even though your `.ruby-version` file is set to Ruby 2.0.0.  You can verify this by running `head $(which bundle)`.

On another note, you are using an unsupported version of bundler.  Please upgrade to the latest version of Bundler to get the latest bug fixes.  Thanks :).

**Comment by paulmenzel** [comment]
Hmm, I think Ruby 2.0.0-p645 from rvm is set up correctly.

```
$ rvm current
ruby-2.0.0-p645@myproject
$ ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [i686-linux]
$ bundle --version
Bundler version 1.7.4
$ rvm list

rvm rubies

   jruby-1.7.16.1 [ i386 ]
   jruby-1.7.4 [ i386 ]
   ree-1.8.7-2012.02 [ i686 ]
   ruby-1.9.3-p429 [ x86_64 ]
=> ruby-2.0.0-p645 [ i686 ]
   ruby-2.1.6 [ i686 ]
 * ruby-2.2.2 [ i686 ]

# => - current
# =* - current && default
#  * - default

$ which bundle
/usr/bin/bundle
$ head $(which bundle)
#!/usr/bin/ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { exit 1 }

require 'bundler'
# Check if an older version of bundler is installed
$LOAD_PATH.each do |path|
  if path =~ %r'/bundler-0.(\d+)' && $1.to_i < 9
    err = "Looks like you have a version of bundler that's older than 0.9.\n"
```

The problem seems to be, that the packaged Bundler hard codes `/usr/bin/ruby` as the interpreter. `/usr/bin/env ruby` should probably be used instead.

```
$ /usr/bin/env ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [i686-linux]
```

**Comment by indirect** [comment]
The shebang inside the bundle command is set by the ruby used to install it, and is completely outside our control as the authors of Bundler. You'll have to sort out your Ruby and RubyGems installations to get that fixed.

**Comment by segiddins** [comment]
Hmm, I can't seem to remember what the actual issue was here?

**Comment by amit-siddhu** [comment]
Two steps solution:
`rvm gemset use your_gemset_name`
`gem install bundler`

than try `bundle install` :)

Why nobody tells that you should install bundler after creating gemset otherwise system(eg. /usr/bin/bundler) bundler will be used if exist

**Comment by agis-** [comment]
@paulmenzel Is your issue fixed by the suggestions in the comments? If so, this should be closed.

**Comment by agis-** [comment]
Closing this due to lack of feedback. Feel free to share more info and we'll happily reopen!

**Comment by jerome-diver** [comment]
@agis- Please tell us which information you need for be able to help instead of close issue from users asked for help ? Consider that if we allready know everything and which information to provide, maybe also we will not have issue (not sure)... 

OK... i have the same problem, which information should be usefull to give for find an help and maybe find also a solution ? (please)

I do upgrade all from rvm... ruby, passenger with passenger-gninx module, all the gems inside my project but have been stoped by bcrypt error installation:
Errno::EACCES: Permission denied @ dir_s_mkdir - /home/jerome/.rvm/gems/ruby-head@global/extensions/x86_64-linux/2.4.0/bcrypt-3.1.10
and same errors on some other gem modules: debug_inspector-0.0.2, pg-0.18.2, puma-2.12.2, nokogiri-1.6.6.2

Also, all the time ruby/rails change version or passenger or something change, there is problems... maybe it should be nice to have a tutorial about "how to resolve/debug/use new version of rails or new update of things for not waste time".

**Comment by devvrat-thakur** [comment]
Hi i am using Ubuntu14 and ruby with Chef  
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
and getting same issues
 Error executing action `create` on resource 'file[hello.txt]'
 Errno::EACCES
    -------------
    Permission denied @ rb_sysopen - hello.txt
 ERROR: file[hello.txt] (mytest::default line 7) had an error: Errno::EACCES: Permission denied @ rb_sysopen - hello.txt

**Comment by thomas6791** [comment]
Hi, I've a similar problem.
When i try to install middleman.
I get this message:
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/username/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/middleman-4.2.1/.gemtest

**Comment by julianotheiss** [comment]
Try `xcode-select --install`
