### ISSUE TITLE
Bundler trying to install development gems on Jruby with `--deployment` and `--without development test`

### ISSUE THREAD

**Issue by Ch4s3** [bundler/bundler#3901]
When I try to deploy using `--deployment` or `--without development test` Bundler tries to install dev and test gems, and fails because some of those have c extensions that I use in dev with MRI.

For example:
```ruby
group :development do
  gem "better_errors"
  gem "binding_of_caller", "0.7.3.pre1"
  gem "brakeman", require: false
  gem "bullet"
  gem "erb2haml", require: false
  gem "flamegraph"
  ...
  ...
end
```

Then deploying a docker image with the following

```
ADD . /home/app/my_app_name
WORKDIR /home/app//my_app_name
RUN bundle install --deployment

ENV RAILS_ENV production

ENV PORT 3000
EXPOSE 3000
```

I get the following error:
````
remote: INFO -- : Installing fast_stack 0.1.0 with native extensions

remote: INFO -- : 

remote: INFO -- : Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

remote: INFO -- : 

remote: INFO -- :     /opt/jruby/bin/jruby -r ./siteconf20150731-5-kkzg7u.rb extconf.rb

remote: INFO -- : NotImplementedError: C extensions are not supported

remote: INFO -- :     <top> at /opt/jruby/lib/ruby/stdlib/mkmf.rb:1

remote: INFO -- :   require at org/jruby/RubyKernel.java:940

remote: INFO -- :    (root) at /opt/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1

remote: INFO -- :     <top> at extconf.rb:1

remote: INFO -- : 

remote: INFO -- : extconf failed, exit code 1

remote: INFO -- : 

remote: INFO -- : Gem files will remain installed in /home/app/athene/vendor/bundle/jruby/2.2.0/gems/fast_stack-0.1.0 for inspection.

remote: INFO -- : Results logged to /home/app/athene/vendor/bundle/jruby/2.2.0/extensions/universal-java-1.8/2.2.0/fast_stack-0.1.0/gem_make.out

remote: INFO -- : An error occurred while installing fast_stack (0.1.0), and Bundler cannot

remote: INFO -- : continue.

remote: INFO -- : Make sure that `gem install fast_stack -v '0.1.0'` succeeds before bundling.
````

pardon the odd markdown rendering.

**Comment by segiddins** [comment]
Could you also share the output of `bundle env`?

**Comment by rgb-one** [comment]
How about you prepend `jruby -S` to the `bundle install --deployment` command in the docker file:
```
RUN jruby -S bundle install --deployment
```

It is recommended that `jruby -S` be used when executing system level executable commands: 
https://github.com/jruby/jruby/wiki/GettingStarted#running-rake-gem-rails-etc.

**Comment by Ch4s3** [comment]
@segiddins this is what bundler env looks like when I run it on the [server] (https://gist.github.com/Ch4s3/d1a4d249a78cb86985e4) and [locally](https://gist.github.com/Ch4s3/4f129db08168b2ea51e7).

**Comment by Ch4s3** [comment]
I ran `RUN jruby -S bundle install --deployment`

```
remote: INFO -- :  ---> Running in b7f48ce5a8c1

remote: INFO -- : Don't run Bundler as root. Bundler can ask for sudo if it is needed, and

remote: INFO -- : installing your bundle as root will break this application for all non-root

remote: INFO -- : users on this machine.

remote: INFO -- : --- ERROR REPORT TEMPLATE -------------------------------------------------------

remote: INFO -- : - What did you do?

remote: INFO -- : 

remote: INFO -- :   I ran the command `uri:classloader:/bin/bundle install --deployment`

remote: INFO -- : 

remote: INFO -- : - What did you expect to happen?

remote: INFO -- : 

remote: INFO -- :   I expected Bundler to...

remote: INFO -- : 

remote: INFO -- : - What happened instead?

remote: INFO -- : 

remote: INFO -- :   Instead, what actually happened was...

remote: INFO -- : 

remote: INFO -- : 

remote: INFO -- : Error details

remote: INFO -- : 

remote: INFO -- :     Errno::EACCES: Permission denied - uri:classloader://.bundle

remote: INFO -- :       org/jruby/RubyDir.java:450:in `mkdir'

remote: INFO -- :       /opt/jruby/lib/ruby/stdlib/fileutils.rb:252:in `fu_mkdir'

remote: INFO -- :       /opt/jruby/lib/ruby/stdlib/fileutils.rb:226:in `block in mkdir_p'

remote: INFO -- :       org/jruby/RubyArray.java:1643:in `reverse_each'

remote: INFO -- :       /opt/jruby/lib/ruby/stdlib/fileutils.rb:224:in `block in mkdir_p'

remote: INFO -- :       org/jruby/RubyArray.java:1560:in `each'

remote: INFO -- :       /opt/jruby/lib/ruby/stdlib/fileutils.rb:210:in `mkdir_p'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/settings.rb:208:in `set_key'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/cli/install.rb:76:in `run'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/bin/bundle:20:in `block in (root)'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'

remote: INFO -- :       /usr/local/bundle/gems/bundler-1.10.6/bin/bundle:18:in `<top>'

remote: INFO -- :       org/jruby/RubyKernel.java:958:in `load'

remote: INFO -- :       uri:classloader:/bin/bundle:3:in `<top>'

remote: INFO -- : 

remote: INFO -- : Environment

remote: INFO -- : 

remote: INFO -- :     Bundler   1.10.6

remote: INFO -- :     Rubygems  2.4.8

remote: INFO -- :     Ruby      2.2.2p0 (2015-07-21 revision 50293) [java]

remote: INFO -- :     GEM_HOME  /usr/local/bundle

remote: INFO -- :     GEM_PATH  

remote: INFO -- :     Git       1.9.1

remote: INFO -- : 

remote: INFO -- : Bundler settings

remote: INFO -- : 

remote: INFO -- :     path

remote: INFO -- :       Set for the current user (/root/.bundle/config): "/usr/local/bundle"

remote: INFO -- :     bin

remote: INFO -- :       Set for the current user (/root/.bundle/config): "/usr/local/bundle/bin"

remote: INFO -- :     frozen

remote: INFO -- :       Set for your local app (uri:classloader://.bundle/config): "1"

remote: INFO -- :     gemfile

remote: INFO -- :       Set via BUNDLE_GEMFILE: "uri:classloader://Gemfile"

remote: INFO -- : --- TEMPLATE END ----------------------------------------------------------------

remote: INFO -- : 

remote: INFO -- : Unfortunately, an unexpected error occurred, and Bundler cannot continue.

remote: INFO -- : 

remote: INFO -- : First, try this link to see if there are any existing issue reports for this error:

remote: INFO -- : https://github.com/bundler/bundler/search?q=Permission+denied+-+uri%3Aclassloader%3A%2F%2F.bundle&type=Issues

remote: INFO -- : 

remote: INFO -- : If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:

remote: INFO -- : https://github.com/bundler/bundler/issues/new
```

**Comment by Ch4s3** [comment]
So I fixed this by removing lines setting my `$GEMHOME`.

**Comment by rgb-one** [comment]
Cool :)
