### ISSUE TITLE
Whenever I run bundle, I get an invalid argument error

### ISSUE THREAD

**Issue by Summonee** [bundler/bundler#3917]
As the title says, whenever I run bundle, install or update, I get an error:
```
Error details

    Errno::EINVAL: Invalid argument @ rb_sysopen - C:/Users/Jackson/Dropbox/Webs
ites/ValiantGhost/Gemfile.lock
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:445:i
n `read'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:445:i
n `read'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:445:i
n `upgrade_lockfile'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:154:i
n `definition'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/inst
all.rb:104:in `run'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:1
62:in `install'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/t
hor/lib/thor/command.rb:27:in `run'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/t
hor/lib/thor/invocation.rb:126:in `invoke_command'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/t
hor/lib/thor.rb:359:in `dispatch'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/t
hor/lib/thor/base.rb:440:in `start'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:1
0:in `start'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:20:in `bl
ock in <top (required)>'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly
_errors.rb:7:in `with_friendly_errors'
      c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:18:in `<t
op (required)>'
      C:/Ruby22-x64/bin/bundle:23:in `load'
      C:/Ruby22-x64/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]
    GEM_HOME  c:/Ruby22-x64/lib/ruby/gems/2.2.0
    GEM_PATH  c:/Ruby22-x64/lib/ruby/gems/2.2.0;C:/Users/Jackson/.gem/ruby/2.2.0

    Git       1.9.5.msysgit.0
--- TEMPLATE END ---------------------------------------------------------------
-

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=Invalid+argument+%40+rb_sysopen+-+C%
3A%2FUsers%2FJackson%2FDropbox%2FWebsites%2FValiantGhost%2FGemfile.lock&type=Iss
ues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

I was using [Middleman](https://middlemanapp.com/) to design a website, which is the only reason I use bundler. As that too was experiencing errors, I tried deleting ```gemfile.lock``` to see if that would fix it. When I tried running ```bundle install``` again, the above error happened. Its worth noting that no ```gemfile.lock``` was created.

Also, Middleman wise I need bundler to work so I can ``` bundle update``` execjs to 2.5.2

**Comment by artofhuman** [comment]
@Summonee can you show Gemfile?

**Comment by Summonee** [comment]
Sure, he you go:

```Ruby
# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem 'middleman-blog', :git => 'http://github.com/middleman/middleman-blog'
gem 'middleman', "~> 3.3.12"

# For feed.xml.builder
gem "builder", "~> 3.0"

gem "tzinfo-data"

gem 'stylus'

gem 'slim'

gem 'scss'

gem 'haml'

gem 'kramdown'

gem 'execjs'
```

**Comment by Summonee** [comment]
Well, the solution turned out to be a a 'nuke it all' approach. I removed all Ruby installations from my computer, cleaned it with CCleaner, restarted my computer, reinstalled Ruby, Rubygems and all the gems. That somehow fixed it.
