### ISSUE TITLE
Lockfile containing path gem raises when path is deleted

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4004]
As we eventually discovered as part of #3814, if a `:path` gem has been previously locked, but the entire directory containing the gem is deleted, the next run of `bundle install` will raise `undefined method `dependencies' for nil:NilClass`, with a backtrace that looks something like this:

```
NoMethodError: undefined method `dependencies' for nil:NilClass
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:133:in `block in =='
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:94:in `each'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:94:in `block in each'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:93:in `each'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:93:in `each'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:131:in `all?'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:131:in `=='
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:444:in `!='
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:444:in `specs_changed?'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:476:in `block in converge_paths'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:475:in `any?'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:475:in `converge_paths'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:93:in `initialize'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/dsl.rb:166:in `new'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/dsl.rb:166:in `to_definition'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/dsl.rb:11:in `evaluate'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:26:in `build'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/cli/install.rb:104:in `run'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/cli.rb:162:in `install'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/bin/bundle:23:in `load'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/bin/bundle:23:in `<main>'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

Reproduction steps should consist of something like this:

```
$ bundle gem foo
$ echo "gem 'foo', :path => 'foo'" > Gemfile
$ bundle install
$ rm -rf foo
$ bundle install
```

**Comment by asymmetric** [comment]
@indirect I can't reproduce, I get `The path "/home/asymmetric/code/bundler/foo\" does not exist.`

Bundler 1.10.5, ruby 2.3.0dev

**Comment by segiddins** [comment]
I think this happens when the path is an uninitialized submodule, so maybe it's a file instead of being missing?

**Comment by indirect** [comment]
@asymmetric alternatively, maybe it's when the directory is present but empty?

**Comment by agis-** [comment]
I think this may be related to #3981. While the backtrace differs, the scenario sounds very much the same, except it's `:git` instead of `:path`.

**Comment by spidergears** [comment]
Can't reproduce with bundler 1.9.8 using Ruby 2.2.0. Says "The path `/Users/spidergears/stunts/bundler/foo` does not exist."

**Comment by justbaker** [comment]
@indirect Yes, I'm pretty sure this only occurs when directory is present but empty.

**Comment by justbaker** [comment]
@indirect [Here is a test case to reproduce the issue](https://github.com/justbaker/bdlr-test).

**Comment by segiddins** [comment]
Excellent, thanks so much!

**Comment by segiddins** [comment]
Hm, when I run `bundle install` in there with bundler master, I get `The path /vendor/bar does not exist.` (and the same with 1.10.6)
