### ISSUE TITLE
`bundle install` not respecting twiddle-wakka in gemspec

### ISSUE THREAD

**Issue by jbodah** [bundler/bundler#4037]
Bundler Version: 1.10.6

Gemfile:

```rb
source 'https://rubygems.org'

gemspec
```

My gemspec currently has the line:

```rb
  spec.add_runtime_dependency 'minitest', '~> 5.5'
```

```
Bodah@jbodah-local 2.1.3p242 ~/repos/backupify/backupify-test_case (master) $ bundle
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.1
```

Rubygems states that the `~> 5.5` twiddle-wakka is equivalent to `['>= 5.5', '< 5.6']`. When I switch to use the explicit syntax then bundler properly pulls in my dependencies:

```rb
  spec.add_runtime_dependency 'minitest', ['>= 5.5', '< 5.6']
```

```
Bodah@jbodah-local 2.1.3p242 ~/repos/backupify/backupify-test_case (master) $ bundle
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.5.1 (was 5.8.1)
```

**Comment by jbodah** [comment]
Apparently there's some deeper dark magic going on here, might not be a bundler thing:

```
Bodah@jbodah-local 2.1.3p242 ~/repos/backupify/backupify-test_case (master) $ be rake
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have already activated minitest 5.8.1, but your Gemfile requires minitest 5.5.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
        from /Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
        from /Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
        from /Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by segiddins** [comment]
Nope, that's intended behavior. `~> 5.5` is not the same as `~> 5.5.0`

**Comment by jbodah** [comment]
Ah I see, I misread that from the docs. Thanks @segiddins
