### ISSUE TITLE
error report while run bundle install

### ISSUE THREAD

**Issue by semprul57** [bundler/bundler#4057]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/metasploit-framework/vendor/cache/ruby/2.1.0
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:208:in `each'
  /usr/share/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler.rb:308:in `mkdir_p'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/installer.rb:278:in `create_bundle_path'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/installer.rb:54:in `run'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/bin/bundle:23:in `load'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/bin/bundle:23:in `<main>'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/bin/ruby_executable_hooks:15:in `eval'
  /home/semprul57/.rvm/gems/ruby-2.1.6@metasploit-framework/bin/ruby_executable_hooks:15:in `<main>'
```

Environment

```
Bundler   1.10.6
Rubygems  2.4.8
Ruby      2.1.6p336 (2015-04-13 revision 50298) [i686-linux]
GEM_HOME  /opt/metasploit-framework/vendor/cache/ruby/2.1.0
GEM_PATH  
RVM       1.26.11 (manual)
Git       1.9.1
```

Bundler settings

```
build.nokogiri
  Set for the current user (/home/semprul57/.bundle/config): "--use-system-libraries"
path
  Set for your local app (/opt/metasploit-framework/.bundle/config): "vendor/cache"
disable_shared_gems
  Set for your local app (/opt/metasploit-framework/.bundle/config): "1"
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
We now have better errors when the user doesn't have permission to write to a file.
