### ISSUE TITLE
Retrying dependency api due to error: Zlib::BufError buffer error

### ISSUE THREAD

**Issue by sibinx7** [bundler/bundler#4074]
```

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/vagrant/.rvm/gems/ruby-2.1.5/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Zlib::BufError: buffer error
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:357:in `finish'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:357:in `finish'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:262:in `ensure in inflater'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:262:in `inflater'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:274:in `read_body_0'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:201:in `read_body'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:226:in `body'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:163:in `reading_body'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
      /home/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1378:in `request'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent.rb:999:in `request'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:45:in `request'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:15:in `fetch'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:51:in `block in dependency_specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:50:in `each'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:50:in `each_slice'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:50:in `dependency_specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:33:in `block in specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/retry.rb:39:in `call'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/retry.rb:39:in `run'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/retry.rb:29:in `attempt'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:32:in `specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher.rb:102:in `block in specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher.rb:100:in `each'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/fetcher.rb:100:in `specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:356:in `block (2 levels) in remote_specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:354:in `each'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:354:in `block in remote_specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:81:in `specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/spec_set.rb:88:in `block in materialize'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/vagrant/.rvm/gems/ruby-2.1.5/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/vagrant/.rvm/gems/ruby-2.1.5/bin/bundle:23:in `load'
      /home/vagrant/.rvm/gems/ruby-2.1.5/bin/bundle:23:in `<main>'
      /home/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
      /home/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    GEM_HOME  /home/vagrant/.rvm/gems/ruby-2.1.5
    GEM_PATH  /home/vagrant/.rvm/gems/ruby-2.1.5:/home/vagrant/.rvm/gems/ruby-2.1.5@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

```

**Comment by indirect** [comment]
@bundler/core another error to rescue and retry in the fetcher, I guess. 😛

**Comment by sibinx7** [comment]
This happened in my vagrant( guest os ubuntu 14.04, 64 bit), after restart, issue gone...
