### ISSUE TITLE
in `parse_source': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by zhouhaoyang** [bundler/bundler#4099]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
  I'm running gitlab rspec test script:

cd /root/Downloads/gitlab
pwd
ruby -v
which ruby
cp config/database.yml.mysql config/database.yml
cp config/gitlab.yml.example config/gitlab.yml
sed "s/username\:.*$/username\: runner/" -i config/database.yml
sed "s/password\:.*$/password\: 'password'/" -i config/database.yml
sed "s/gitlabhq_test/gitlabhq_test_$((RANDOM/5000))/" -i config/database.yml
touch log/application.log
touch log/test.log
bundle --without postgres production   #here come the bug
#bundle exec rake db:create RAILS_ENV=test

- What did you expect to happen?
when I test gitlab 7.14 , it is OK.
when I test gitlab 8.1 , error comes.

- What happened instead?

Error details

    NoMethodError: undefined method `[]' for nil:NilClass
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/lockfile_parser.rb:95:in `parse_source'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/lockfile_parser.rb:45:in `block in initialize'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/lockfile_parser.rb:39:in `each'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/lockfile_parser.rb:39:in `initialize'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/definition.rb:57:in `new'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/definition.rb:57:in `initialize'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/dsl.rb:161:in `new'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/dsl.rb:161:in `to_definition'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/dsl.rb:11:in `evaluate'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/definition.rb:25:in `build'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler.rb:155:in `definition'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli/install.rb:78:in `run'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli.rb:157:in `install'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/bin/bundle:20:in `block in <top (required)>'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/bin/bundle:18:in `<top (required)>'
    /usr/local/bin/bundle:23:in `load'
    /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.4
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
    GEM_HOME  /usr/local/lib/ruby/gems/2.1.0
    GEM_PATH  /usr/local/lib/ruby/gems/2.1.0:/home/git/.gem/ruby/2.1.0
    Git       1.7.9.5

Bundler settings

    without
      Set for your local app (/root/Downloads/gitlab/.bundle/config): "postgres:production"
――― TEMPLATE END ―――――

**Comment by zhouhaoyang** [comment]
sorry ,  the reason should be my fault.

I edit and change many gitlab file , that's the reason
