### ISSUE TITLE
I can not run the project downloaded from a repository

### ISSUE THREAD

**Issue by jjmonsalveg** [bundler/bundler#4100]
hi guys, I need help, I can not run the console, (rails c):
```
/home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require': cannot load such file -- global (LoadError)
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /home/jj/Escritorio/gcapp/config/application.rb:7:in `<top (required)>'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application.rb:82:in `require'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application.rb:82:in `preload'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application.rb:143:in `serve'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application.rb:131:in `block in run'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application.rb:125:in `loop'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application.rb:125:in `run'
	from /home/jj/.rvm/gems/ruby-2.1.6@global/gems/spring-1.4.1/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/jj/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jj/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

```

I can not run the local server (rails s):

```
bin/rails:6: warning: already initialized constant APP_PATH
/home/jj/Escritorio/gcapp/bin/rails:6: warning: previous definition of APP_PATH was here
Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")

All commands can be run with -h (or --help) for more information. 
```

**Comment by segiddins** [comment]
What's the output if you run `bundle check`, and what's the contents of your gemfile?

**Comment by jjmonsalveg** [comment]
command bundle check:
``` 
The Gemfile's dependencies are satisfied
```
my Gemfile is:
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'

#Use postgresql as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'rack-cors', :require => 'rack/cors'

gem 'active_model_serializers',
    git: 'https://github.com/rails-api/active_model_serializers.git', branch: '0-9-stable'

gem 'activemerchant'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc


gem 'haml'

gem 'bootstrap-sass', '~> 3.2.0'

gem 'font-awesome-rails'

#gema para subida de archivos
gem 'carrierwave'

#Manejo de imagenes
gem 'rmagick', '~> 2.13.4'

#paginaciones
gem 'kaminari'

#autenticacion de usuario
gem 'devise'

#paises
gem 'countries', :require => 'global'

#validaciones
gem 'jquery-validation-rails'

gem 'jquery-fileupload-rails'

gem 'whenever', require: false

gem 'geocoder'

gem 'rpush'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'


# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'seed_dump'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception static_pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'better_errors'

  gem 'binding_of_caller'

  gem 'meta_request'

  gem 'bullet', '4.14.8'

  #revisar en çonfig/environments/development.rb
  #correo en http://127.0.0.1:1080
  gem 'mailcatcher'

  #Para annotates de models
  gem 'annotate'

  #Conversor html a haml
  gem 'html2haml'

  # Generacion de las vistas en formato haml
  gem 'haml-rails'
end

```

**Comment by segiddins** [comment]
Are you sure the countries gem has a required able file named global?

**Comment by jjmonsalveg** [comment]
oh !! right there the error. https://github.com/hexorx/countries (Upgrading to 1.2.0). thanks for your help
