### ISSUE TITLE
Bundle installation failed on kubuntu 14.04 (part of gitlab install)

### ISSUE THREAD

**Issue by hfanous** [bundler/bundler#4118]
-
- What did you do?

  I ran the command `/usr/local/bin/bundle install -j8 --deployment --without development test postgres aws`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /home/git/gitlab/.bundle/config
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `initialize'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `open'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `set_key'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:76:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.5
    Ruby      2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
    Git       1.9.1

Bundler settings

    jobs
      Set for your local app (/home/git/gitlab/.bundle/config): "8"
    frozen
      Set for your local app (/home/git/gitlab/.bundle/config): "1"

**Comment by hfanous** [comment]
This is the same as issue 3858 and changing and adding read/write permissions to  /home/git/gitlab/.bundle/config solved the problem.  Sorry for the noise

Thanks
