### ISSUE TITLE
Bundler 1.11.0 break rspec on Windows (only windows), because #4114

### ISSUE THREAD

**Issue by Eric-Guo** [bundler/bundler#4150]
It's very strange, but I can isolate problem to bundler, #4114 

```
c:\git\Rails\wechat>rake
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/r
spec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spe
c.rb'
No DRb server is running. Running in local process instead ...

Randomized with seed 51044
........................................................................................................................
.................................................

Finished in 0.65787 seconds (files took 10.4 seconds to load)
169 examples, 0 failures

Randomized with seed 51044


c:\git\Rails\wechat>bundle check
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to t
he latest version of Bundler by running `gem install bundler`.
Resolving dependencies...
The Gemfile's dependencies are satisfied

c:\git\Rails\wechat>gem update
Updating installed gems
Updating bundler
Fetching: bundler-1.11.0.gem (100%)
Successfully installed bundler-1.11.0
Gems updated: bundler

c:\git\Rails\wechat>rake
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/r
spec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spe
c.rb'
No DRb server is running. Running in local process instead ...
c:/git/Rails/wechat/spec/lib/wechat/access_token_spec.rb:3:in `<top (required)>': uninitialized constant Wechat (NameErr
or)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_
spec_files'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_file
s'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:70:in `rescue in run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:66:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/r
spec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spe
c.rb' failed

c:\git\Rails\wechat>
```

**Comment by indirect** [comment]
@smellsblue dang, looks like we're excluding Windows even when it's MRI and we should be including it?

**Comment by Eric-Guo** [comment]
I can not work out a more proper fix, but if I revert #4114, at least can fix this problem...

**Comment by agross** [comment]
I'm seeing a similar (?) problem with bundler 1.11.0 on Windows: Runtime dependencies defined in a gemspec won't be added to the `$LOAD_PATH`

```bash
$ bundle --version
Bundler version 1.10.6

D:\Users\agross\Coding\rake-funnel
$ bundle exec rspec
Run options: exclude {:draft=>true}
...

Finished in 1.5 seconds (files took 1.76 seconds to load)
3 examples, 0 failures, 0 pending

D:\Users\agross\Coding\rake-funnel
$ gem install bundler
Fetching: bundler-1.11.0.gem (100%)
Successfully installed bundler-1.11.0
1 gem installed

D:\Users\agross\Coding\rake-funnel
$ bundle exec rspec
D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/extensions/disable_colors.rb:1:in `require': cannot load such file -- smart_colored (LoadError)
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/extensions/disable_colors.rb:1:in `<top (required)>'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/framework.rb:9:in `require'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/framework.rb:9:in `block (2 levels) in <top (required)>'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/framework.rb:8:in `each'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/framework.rb:8:in `block in <top (required)>'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/framework.rb:7:in `each'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel/framework.rb:7:in `<top (required)>'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel.rb:7:in `require'
        from D:/Users/agross/Coding/rake-funnel/lib/rake/funnel.rb:7:in `<top (required)>'
        from D:/Users/agross/Coding/rake-funnel/spec/spec_helper.rb:36:in `require'
        from D:/Users/agross/Coding/rake-funnel/spec/spec_helper.rb:36:in `<top (required)>'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `require'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `block in requires='
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `each'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `requires='
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `each'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:21:in `configure'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:101:in `setup'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
        from C:/Ruby/bin/rspec:23:in `load'
        from C:/Ruby/bin/rspec:23:in `<main>'
```

**Comment by smellsblue** [comment]
I think this is failing because of: https://github.com/bundler/bundler/blob/4b7a940f668d1884d9266946a48ba55a80c4d513/lib/bundler/dsl.rb#L63:
`gem spec.name, :path => path, :glob => glob, :platforms => Bundler::Dependency::REVERSE_PLATFORM_MAP[spec.platform]`

For #4102, `spec.platform` was returning the Java platform (I was setting it that way in my gemspec).

However, for the case of the `wechat` gem, the spec platform isn't changed, and so `spec.platform` returns `"ruby"`, which then means it won't be found when the dependency is being resolved (because it can only be found for the current platform). Changing the line to instead be:
`gem spec.name, :path => path, :glob => glob, :platforms => Bundler::Dependency::REVERSE_PLATFORM_MAP[RUBY_PLATFORM]`
seems to fix this problem, and probably won't affect the fix for #4102. Before I submit a pull request for this, I'm going to see if I can write a test or two to cover this case.

**Comment by smellsblue** [comment]
@Eric-Guo and @agross would you mind trying out my branch?

https://github.com/smellsblue/bundler/tree/restrict-gemspec-platforms-without-breaking-windows

I think this branch will fix both my original problem and these problems I created (sorry for the trouble!). I attempted to run `rake` for `wechat` and `bundle exec rspec` for `rake-funnel`. I got the same failures, and then saw them go away with my changes on a windows machine I got ahold of, but any additional testing you might be able to do would be super helpful!

**Comment by Eric-Guo** [comment]
@smellsblue Confirm it works at branch [restrict-gemspec-platforms-without-breaking-windows](https://github.com/smellsblue/bundler/tree/restrict-gemspec-platforms-without-breaking-windows), I also want to testing it at current master, but found a lot of conflicts, so .... decide relay on your do the rebase. :smile:

**Comment by agross** [comment]
:+1: Thanks!

**Comment by smellsblue** [comment]
@Eric-Guo thanks so much! Yeah, I'll help get it to `1-11-stable` if they plan to release it to 1.11 :-)
