### ISSUE TITLE
bundle install fail

### ISSUE THREAD

**Issue by yingmujianer** [bundler/bundler#4151]
hello,I'm here： https://gist.github.com/mjhea0/b6b58eefc38985380ff9
Install Huginn's dependencies
After using the command, detailed error：
```
D:\Git\Git\bin\huginn>bundle install
Fetching git://github.com/lostisland/faraday_middleware.git
Retrying git clone "git://github.com/lostisland/faraday_middleware.git" "D:/ruby
/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/faraday_middleware-c881d4de2a647f8
7ad56e89f17bf2b22bf19b28b" --bare --no-hardlinks --quiet due to error (2/4): Err
no::ENOENT No such file or directory - git clone "git://github.com/lostisland/fa
raday_middleware.git" "D:/ruby/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/fara
day_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" --bare --no-hardlinks -
-quiet
Retrying git clone "git://github.com/lostisland/faraday_middleware.git" "D:/ruby
/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/faraday_middleware-c881d4de2a647f8
7ad56e89f17bf2b22bf19b28b" --bare --no-hardlinks --quiet due to error (3/4): Err
no::ENOENT No such file or directory - git clone "git://github.com/lostisland/fa
raday_middleware.git" "D:/ruby/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/fara
day_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" --bare --no-hardlinks -
-quiet
Retrying git clone "git://github.com/lostisland/faraday_middleware.git" "D:/ruby
/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/faraday_middleware-c881d4de2a647f8
7ad56e89f17bf2b22bf19b28b" --bare --no-hardlinks --quiet due to error (4/4): Err
no::ENOENT No such file or directory - git clone "git://github.com/lostisland/fa
raday_middleware.git" "D:/ruby/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/fara
day_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" --bare --no-hardlinks -
-quiet
--- ERROR REPORT TEMPLATE ------------------------------------------------------
-
- What did you do?

  I ran the command `D:/ruby/Ruby22/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOENT: No such file or directory - git clone "git://github.com/losti
sland/faraday_middleware.git" "D:/ruby/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/
git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" --bare --no-har
dlinks --quiet
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git/git_proxy.rb:133:in ``'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git/git_proxy.rb:133:in `block in git'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/shared_
helpers.rb:71:in `call'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/shared_
helpers.rb:71:in `with_clean_git_env'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git/git_proxy.rb:133:in `git'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git/git_proxy.rb:127:in `block in git_retry'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/retry.r
b:38:in `call'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/retry.r
b:38:in `run'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/retry.r
b:28:in `attempt'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git/git_proxy.rb:126:in `git_retry'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git/git_proxy.rb:82:in `checkout'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/source/
git.rb:153:in `specs'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:209:in `block (2 levels) in index'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:207:in `each'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:207:in `block in index'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/index.r
b:9:in `build'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:204:in `index'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:198:in `resolve'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:137:in `specs'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definit
ion.rb:126:in `resolve_remotely!'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/install
er.rb:194:in `resolve_if_need'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/install
er.rb:69:in `run'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/install
er.rb:21:in `install'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli/ins
tall.rb:105:in `run'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli.rb:
172:in `install'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/
thor/lib/thor/command.rb:27:in `run'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/
thor/lib/thor/invocation.rb:126:in `invoke_command'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/
thor/lib/thor.rb:359:in `dispatch'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/
thor/lib/thor/base.rb:440:in `start'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli.rb:
10:in `start'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/exe/bundle:19:in `b
lock in <top (required)>'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/friendl
y_errors.rb:7:in `with_friendly_errors'
      D:/ruby/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/exe/bundle:17:in `<
top (required)>'
      D:/ruby/Ruby22/bin/bundle:23:in `load'
      D:/ruby/Ruby22/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.0
    Rubygems  2.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
    GEM_HOME  D:/ruby/Ruby22/lib/ruby/gems/2.2.0
    GEM_PATH  D:/ruby/Ruby22/lib/ruby/gems/2.2.0;C:/Users/Administrator.da-PC.00
1/.gem/ruby/2.2.0
    Git       not installed
--- TEMPLATE END ---------------------------------------------------------------
-

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clon
e+%22git%3A%2F%2Fgithub.com%2Flostisland%2Ffaraday_middleware.git%22+%22D%3A%2Fr
uby%2FRuby22%2Flib%2Fruby%2Fgems%2F2.2.0%2Fcache%2Fbundler%2Fgit%2Ffaraday_middl
eware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b%22+--bare+--no-hardlinks+--quiet&
type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

**Comment by indirect** [comment]
Can you try this with Bundler 1.10? Run `gem uninstall bundler` and then `gem install bundler -v "~> 1.10.0"` and try again.

**Comment by Eric-Guo** [comment]
@yingmujianer suggest install ruby and running all code in `C:` instead of any other drive, because both Mac and Linux have no concept of drive, so many place can cause unexpected problem like above.

**Comment by rgb-one** [comment]
Install git. And the instructions above may be useful as well.

**Comment by jane084263** [comment]
i encontered the same issue. does anyone have idea on how to solve this?
Git error: command `git clone 'git://github.com/makoviy/rocket_tag.git'
"/Users/t_sunl/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/rocket_tag-980eff661fdcc8491a9965c7f96c096ade7cdb3f"
--bare --no-hardlinks --quiet` in directory /Users/t_sunl/gallery has failed.

**Comment by colby-swandale** [comment]
@jane084263 can you please open a new issue with the details of the problem you're having. And we will try and help resolve your problem.
