### ISSUE TITLE
After install Bundler 1.11.0 rails app fail

### ISSUE THREAD

**Issue by Sega100500** [bundler/bundler#4153]
gem update
bundler 1.11.0

in rails app
bundle upate

```
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::ANY
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF8
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:6: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:6: warning: previous definition of BIG_DECIMAL was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::COMPLEX
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:7: warning: previous definition of COMPLEX was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::DATE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:8: warning: previous definition of DATE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:9: warning: previous definition of DATE_TIME was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::EXCEPTION
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:10: warning: previous definition of EXCEPTION was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::OBJECT
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:11: warning: previous definition of OBJECT was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:12: warning: previous definition of PSYCH_OMAP was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_SET was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::RANGE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:14: warning: previous definition of RANGE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RATIONAL
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:15: warning: previous definition of RATIONAL was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::REGEXP
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:16: warning: previous definition of REGEXP was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::STRUCT
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:17: warning: previous definition of STRUCT was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::SYMBOL
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:18: warning: previous definition of SYMBOL was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/class_loader.rb:64: warning: already initialized constant Psych::ClassLoader::CACHE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/class_loader.rb:64: warning: previous definition of CACHE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/scalar_scanner.rb:8: warning: already initialized constant Psych::ScalarScanner::TIME
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/scalar_scanner.rb:8: warning: previous definition of TIME was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/scalar_scanner.rb:11: warning: already initialized constant Psych::ScalarScanner::FLOAT
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/scalar_scanner.rb:11: warning: previous definition of FLOAT was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/stream.rb:12: warning: already initialized constant Psych::Nodes::Stream::ANY
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/stream.rb:12: warning: previous definition of ANY was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/stream.rb:15: warning: already initialized constant Psych::Nodes::Stream::UTF8
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/stream.rb:15: warning: previous definition of UTF8 was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/stream.rb:18: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/stream.rb:18: warning: previous definition of UTF16LE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/stream.rb:21: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/stream.rb:21: warning: previous definition of UTF16BE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/sequence.rb:42: warning: already initialized constant Psych::Nodes::Sequence::ANY
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/sequence.rb:42: warning: previous definition of ANY was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/sequence.rb:45: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/sequence.rb:45: warning: previous definition of BLOCK was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/sequence.rb:48: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/sequence.rb:48: warning: previous definition of FLOW was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/scalar.rb:9: warning: already initialized constant Psych::Nodes::Scalar::ANY
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/scalar.rb:9: warning: previous definition of ANY was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/scalar.rb:12: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/scalar.rb:12: warning: previous definition of PLAIN was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/scalar.rb:15: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/scalar.rb:15: warning: previous definition of SINGLE_QUOTED was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/scalar.rb:18: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/scalar.rb:18: warning: previous definition of DOUBLE_QUOTED was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/scalar.rb:21: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/scalar.rb:21: warning: previous definition of LITERAL was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/scalar.rb:24: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/scalar.rb:24: warning: previous definition of FOLDED was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/mapping.rb:16: warning: already initialized constant Psych::Nodes::Mapping::ANY
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/mapping.rb:16: warning: previous definition of ANY was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/mapping.rb:19: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/mapping.rb:19: warning: previous definition of BLOCK was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/nodes/mapping.rb:22: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/nodes/mapping.rb:22: warning: previous definition of FLOW was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/visitors/visitor.rb:10: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/visitors/visitor.rb:10: warning: previous definition of DISPATCH was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/handler.rb:26: warning: already initialized constant Psych::Handler::OPTIONS
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/handler.rb:26: warning: previous definition of OPTIONS was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/handler.rb:29: warning: already initialized constant Psych::Handler::EVENTS
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/handler.rb:29: warning: previous definition of EVENTS was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:430: warning: already initialized constant Psych::Visitors::YAMLTree::NULL
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/visitors/yaml_tree.rb:439: warning: previous definition of NULL was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:431: warning: already initialized constant Psych::Visitors::YAMLTree::BINARY_RANGE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/visitors/yaml_tree.rb:440: warning: previous definition of BINARY_RANGE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:432: warning: already initialized constant Psych::Visitors::YAMLTree::WS_RANGE
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/psych-2.0.16/lib/psych/visitors/yaml_tree.rb:441: warning: previous definition of WS_RANGE was here
/home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/parser.rb:33:in `<class:Parser>': superclass mismatch for class Mark (TypeError)
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/parser.rb:32:in `<module:Psych>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych/parser.rb:1:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych.rb:7:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/2.2.0/psych.rb:7:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/ordered_hash.rb:2:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/ordered_hash.rb:2:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/ordered_options.rb:1:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/ordered_options.rb:1:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/configuration.rb:2:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/configuration.rb:2:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/railtie.rb:2:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/railtie.rb:2:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/engine.rb:1:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/engine.rb:1:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/plugin.rb:1:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/plugin.rb:1:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/application.rb:3:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/application.rb:3:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails.rb:10:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails.rb:10:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/all.rb:1:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/all.rb:1:in `<top (required)>'
        from /home/ruby/projects/zile.work/config/application.rb:3:in `require'
        from /home/ruby/projects/zile.work/config/application.rb:3:in `<top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:53:in `require'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:53:in `block in <top (required)>'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:50:in `tap'
        from /home/ruby/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:50:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
``

and rails app fail to run

revert to bundler 1.10.6
all work fine

**Comment by thehybridtechnician** [comment]
+1 - Just did fresh 2.2.3 Ruby install/ Rails 4.2.5 and had this occur.  Reverted to bundler 1.10.6 and everthing worked fine.

**Comment by jsmartt** [comment]
+1 Similar problems with my Rails app when deploying with Capistrano & [rvm1-capistrano3](https://github.com/rvm/rvm1-capistrano3). 
Mine complained about the $GEM_HOME and/or $GEM_PATH not being set and referred me to [this](https://github.com/wayneeseguin/rvm/issues/3212) rvm issue.

I'm running rvm 1.26.11 and ruby ruby 2.1.4p265 and here's a short output of my error message:

```
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@<filtered>: rake exit status: 1
rake stdout: Nothing written
rake stderr: Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.1.4'.
/usr/local/rvm/gems/ruby-2.1.4/gems/bundler-1.11.0/lib/bundler/lazy_specification.rb:75:in
`method_missing': LazySpecification has not been materialized yet (calling :required_ruby_version []) (RuntimeError)
```

Reverted to bundler 1.10.6 and everything worked again.

**Comment by Sega100500** [comment]
updated to 1.11.2
all work
Thanks!
