### ISSUE TITLE
1.11.0/1.11.1 rails generate controller fails

### ISSUE THREAD

**Issue by fschwan** [bundler/bundler#4165]
reproduction:
ruby: 2.2.3p173
bundler: 1.11.1

```
mkdir testapp
cd testapp
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'rails'" >> Gemfile
bundle install --path vendor/bundle
bundle exec rails new .
```
Overwrite Gemfile? -> Yes
```
bundle exec rails g controller con view
```
leads to:
```
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/commands.rb:33:in `<module:Spring>'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/commands.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:77:in `preload'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:143:in `serve'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:131:in `block in run'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:125:in `loop'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:125:in `run'
	from /home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Fix:
Downgrade to 1.10.6

**Comment by segiddins** [comment]
What's the output of `bundle env`? This might be due to a bug in RubyGems itself that was fixed in 2.5.1.

**Comment by fschwan** [comment]
Here we go
```
Environment

    Bundler   1.11.1
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    Git       2.6.4

Bundler settings

    path
      Set for your local app (/home/user/testapp/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/home/user/testapp/.bundle/config): "1"

Gemfile

    source 'https://rubygems.org'
    
    
    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.5'
    # Use sqlite3 as the database for Active Record
    gem 'sqlite3'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby
    
    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0', group: :doc
    
    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'
    
    # Use Unicorn as the app server
    # gem 'unicorn'
    
    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development
    
    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'
    end
    
    group :development do
      # Access an IRB console on exception pages or by using <%= console %> in views
      gem 'web-console', '~> 2.0'
    
      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'
    end

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        actionmailer (4.2.5)
          actionpack (= 4.2.5)
          actionview (= 4.2.5)
          activejob (= 4.2.5)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 1.0, >= 1.0.5)
        actionpack (4.2.5)
          actionview (= 4.2.5)
          activesupport (= 4.2.5)
          rack (~> 1.6)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        actionview (4.2.5)
          activesupport (= 4.2.5)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        activejob (4.2.5)
          activesupport (= 4.2.5)
          globalid (>= 0.3.0)
        activemodel (4.2.5)
          activesupport (= 4.2.5)
          builder (~> 3.1)
        activerecord (4.2.5)
          activemodel (= 4.2.5)
          activesupport (= 4.2.5)
          arel (~> 6.0)
        activesupport (4.2.5)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        arel (6.0.3)
        binding_of_caller (0.7.2)
          debug_inspector (>= 0.0.1)
        builder (3.2.2)
        byebug (8.2.1)
        coffee-rails (4.1.0)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.10.0)
        concurrent-ruby (1.0.0)
        debug_inspector (0.0.2)
        erubis (2.7.0)
        execjs (2.6.0)
        globalid (0.3.6)
          activesupport (>= 4.1.0)
        i18n (0.7.0)
        jbuilder (2.3.2)
          activesupport (>= 3.0.0, < 5)
          multi_json (~> 1.2)
        jquery-rails (4.0.5)
          rails-dom-testing (~> 1.0)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        json (1.8.3)
        loofah (2.0.3)
          nokogiri (>= 1.5.9)
        mail (2.6.3)
          mime-types (>= 1.16, < 3)
        mime-types (2.99)
        mini_portile2 (2.0.0)
        minitest (5.8.3)
        multi_json (1.11.2)
        nokogiri (1.6.7)
          mini_portile2 (~> 2.0.0.rc2)
        rack (1.6.4)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (4.2.5)
          actionmailer (= 4.2.5)
          actionpack (= 4.2.5)
          actionview (= 4.2.5)
          activejob (= 4.2.5)
          activemodel (= 4.2.5)
          activerecord (= 4.2.5)
          activesupport (= 4.2.5)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.2.5)
          sprockets-rails
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.7)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.2)
          loofah (~> 2.0)
        railties (4.2.5)
          actionpack (= 4.2.5)
          activesupport (= 4.2.5)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (10.4.2)
        rdoc (4.2.0)
        sass (3.4.20)
        sass-rails (5.0.4)
          railties (>= 4.0.0, < 5.0)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (>= 1.1, < 3)
        sdoc (0.4.1)
          json (~> 1.7, >= 1.7.7)
          rdoc (~> 4.0)
        spring (1.6.0)
        sprockets (3.5.2)
          concurrent-ruby (~> 1.0)
          rack (> 1, < 3)
        sprockets-rails (2.3.3)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (>= 2.8, < 4.0)
        sqlite3 (1.3.11)
        thor (0.19.1)
        thread_safe (0.3.5)
        tilt (2.0.1)
        turbolinks (2.5.3)
          coffee-rails
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (2.7.2)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        web-console (2.2.1)
          activemodel (>= 4.0)
          binding_of_caller (>= 0.7.2)
          railties (>= 4.0)
          sprockets-rails (>= 2.0, < 4.0)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      byebug
      coffee-rails (~> 4.1.0)
      jbuilder (~> 2.0)
      jquery-rails
      rails (= 4.2.5)
      sass-rails (~> 5.0)
      sdoc (~> 0.4.0)
      spring
      sqlite3
      turbolinks
      uglifier (>= 1.3.0)
      web-console (~> 2.0)
    
    BUNDLED WITH
       1.11.1
```

**Comment by fschwan** [comment]
Still the same problem with 1.11.2

**Comment by ojab** [comment]
Same here.
Actually spring loading fails, so all `bundle exec rails` commands will fail by default, disabling spring (via `export DISABLE_SPRING=y` for example) can be used as another one workaround.

**Comment by ojab** [comment]
`git bisect` told me that
```
42b507218fd910feb2a9756bc08dc41181a9d1c4 is the first bad commit
commit 42b507218fd910feb2a9756bc08dc41181a9d1c4
Author: Andre Arko <andre@arko.net>
Date:   Tue Sep 8 13:57:26 2015 -0700

    Clean RUBYLIB as well in `with_clean_env`

    refs #3982

:040000 040000 e0807ae79f042ee797b79720bb915444d94302a3 459454213a55425b985ecba3d61a2744dc747460 M	lib
:040000 040000 f8ec7853faecfc76ee244e667f1f3ed51ffc5e61 cb3e71a89babc4df8250d3b3a5e1f8fca8df1d37 M	spec
bisect run success
```

**Comment by ojab** [comment]
Looks like spring bug for me, issue filled https://github.com/rails/spring/issues/456 and PR is already exists https://github.com/rails/spring/pull/453.

**Comment by fschwan** [comment]
This is still an issue in 1.6.2. Any suggestions to solve this?

**Comment by ratracegrad** [comment]
I too am still getting errors with Spring 1.6.2.

**Comment by indirect** [comment]
This was a bug in Bundler, and the documentation has always said that all environment variables would be cleared. Spring depending on this bug to works is a problem I would like to fix, but I don't want to fix it by re-breaking Bundler.

**Comment by fschwan** [comment]
Ok, so let us close this and concentrate on the spring bug. Thank you for taking the time.
