### ISSUE TITLE
rubygems 2.6.2 breaks nested bundle exec support

### ISSUE THREAD

**Issue by taoza** [bundler/bundler#4381]
The issue can be reproduced with the latest [ruby:2.3.0-slim docker image](https://github.com/docker-library/ruby/blob/c88f3a67da720bfa9fb1717960d90fd5db11c757/2.3/slim/Dockerfile), which has a newly upgrade rubygems 2.6.2.

### Reproduce steps:
```shell
$  docker pull ruby:2.3.0-slim
2.3.0-slim: Pulling from ruby
d8bd0657b25f: Already exists
a582cd499e0f: Already exists
ae7c36464f9a: Already exists
9e853bd088c3: Already exists
29ba3bda4368: Already exists
8ddd74aaef1d: Already exists
2d6db04da3e0: Already exists
cf824e9b9462: Already exists
69f3ed685b86: Already exists
3396732706b8: Already exists
f0f8bb86227b: Already exists
0137e070fc88: Already exists
a1dea42157c8: Already exists
ca04fb901096: Already exists
b86b27ca1964: Already exists
41bb4e536f92: Already exists
Digest: sha256:927b3ffe7c47f830c2f955e28bb02e3aaca6cbecd71e534dc4fda02156eec589
Status: Image is up to date for ruby:2.3.0-slim
$  docker run -it ruby:2.3.0-slim bash
root@9a7a388a97ff:/# touch Gemfile
root@9a7a388a97ff:/# bundle install
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into .usr/local/bundle.
root@9a7a388a97ff:/# bundle exec bundle -v
/usr/local/bin/bundle:22:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/gems/bundler-1.11.2/bin/bundle (LoadError)
        from /usr/local/bin/bundle:22:in `<main>'
```

### Possible cause:
A further look into bundler's binstub:
```shell
root@9a7a388a97ff:/# cat `which bundle`
#!/usr/local/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.activate_bin_path('bundler', 'bundle', version)
```

`Gem.activate_bin_path('bundler', 'bundle', version)` is recently introduced in rubygems 2.6.2: https://github.com/rubygems/rubygems/pull/1527. A corresponding bundler PR to support the new method  has been merged: https://github.com/bundler/bundler/pull/4341. But looks like it doesn't cover the scenario of nested bundle exec, e.g. `bundle exec bundle -v`, which relies on an early return of `ENV["BUNDLE_BIN_PATH"]`: https://github.com/bundler/bundler/pull/4341/files#diff-f271319d553ee0af23e993e254a92c6cR385

### Edit
Ok, looks like the PR (https://github.com/bundler/bundler/pull/4341) to support `Gem.activate_bin_path` is on `1.12.0.rc`, which indeed fixed the nested bundler issue:
```shell
root@b90610f5d2fe:/# bundler -v
Bundler version 1.11.2
root@b90610f5d2fe:/# bundle exec bundle -v
/usr/local/bin/bundle:22:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/gems/bundler-1.11.2/bin/bundle (LoadError)
        from /usr/local/bin/bundle:22:in `<main>'
root@b90610f5d2fe:/# gem install bundler --pre
Fetching: bundler-1.12.0.rc.gem (100%)
Successfully installed bundler-1.12.0.rc
1 gem installed
root@b90610f5d2fe:/# bundle exec bundle -v
Bundler version 1.12.0.rc
```
:tada: :tada: :tada:

**Comment by eric-hu** [comment]
I just want to comment that this doesn't appear to be fixed for me with Ruby 2.1.5 and rvm, though the error message is different:

```
$ bundle -v
Bundler version 1.12.0.rc

$ bundle exec bundle -v
bundler: failed to load command: bundle (/home/ubuntu/.rvm/gems/ruby-2.1.5/bin/bundle)
Gem::Exception: can't find executable bundle
  /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bundler-1.12.0.rc/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path'
  /home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems.rb:278:in `activate_bin_path'
```

**Comment by SamSaffron** [comment]
```
discourse@ubuntu-standalone:/var/www/discourse$ bundler --version
Bundler version 1.12.4
discourse@ubuntu-standalone:/var/www/discourse$ gem --version
2.6.4
discourse@ubuntu-standalone:/var/www/discourse$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
discourse@ubuntu-standalone:/var/www/discourse$ bundle exec bundle exec ls
bundler: failed to load command: bundle (/usr/local/bin/bundle)
Gem::Exception: can't find executable bundle
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
  /usr/local/bin/bundle:22:in `<top (required)>'

```

Appears broken for me on latest

**Comment by rmm5t** [comment]
**Should this issue should be re-opened?**

I'm still seeing the same behavior with bundler 1.12.5 and rubygems 2.6.4. @SamSaffron provides an [easy way to reproduce the problem](https://github.com/bundler/bundler/issues/4381#issuecomment-220893495).
