### ISSUE TITLE
undefined method `add_root_vertex' for Molinillo::DependencyGraph:[]:Molinillo::DependencyGraph

### ISSUE THREAD

**Issue by codebycody** [bundler/bundler#4383]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NoMethodError: undefined method `add_root_vertex' for Molinillo::DependencyGraph:[]:Molinillo::DependencyGraph
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:194:in `block in initialize'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:194:in `initialize'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:181:in `new'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:181:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:166:in `missing_specs'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:70:in `block in run'
      /usr/lib/ruby/vendor_ruby/bundler/ui/shell.rb:76:in `silence'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:67:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:18:in `install'
      /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:107:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:162:in `install'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
      /usr/bin/bundle:20:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/bin/bundle:18:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.6.2
    Ruby      2.2.4p230 (2015-12-16 revision 0) [x86_64-linux-gnu]
    GEM_HOME  /var/lib/gems/2.2.0
    GEM_PATH  /var/lib/gems/2.2.0:/root/.gem/ruby/2.2.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2:/usr/share/rubygems-integration/all
    Git       2.7.0
--- TEMPLATE END ----------------------------------------------------------------

**Comment by codebycody** [comment]
updated the Bundler from 1.10.6 to 1.11.2-1 using
`apt-get install --only-upgrade bundler`
reran the `bundle install` command and was successful
