### ISSUE TITLE
/usr/share/metasploit-framework/lib/metasploit/framework.rb:18:in `require': cannot load such file -- robots (LoadError)

### ISSUE THREAD

**Issue by greenhand2learn** [bundler/bundler#4398]
```
> ./msfconsole 
/usr/share/metasploit-framework/lib/metasploit/framework.rb:18:in `require': cannot load such file -- robots (LoadError)
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:18:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:228:in `const_get'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:228:in `block in constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `each'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `inject'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from ./msfconsole:48:in `<main>'

```

```
> ruby -v
ruby 2.2.4p230 (2015-12-16) [x86_64-linux-gnu]
> bundle -v
Bundler version 1.11.2
> gem -v
2.5.1
```
how could i solve the problem? i have made some changes, maybe made the wrong change, could someone tell me how to solve it ? thank you very much!

**Comment by greenhand2learn** [comment]
solve the problem,with the Permissions, chmod 755 robots.rb, it's work!
