### ISSUE TITLE
Shared gems from OS package are shown but not usable

### ISSUE THREAD

**Issue by antoineco** [bundler/bundler#4422]
Gems installed from OS packages (example: Debian's `rake`) are shown in the bundle list with the correct path. However using them in the context of bundler fails.

We're using the default value of `0` for `disable_shared_gems`.

```
$ dpkg -l rake
[...]
ii  rake           10.5.0-2~fl1 all          ruby make-like utility

$ bundle exec gem list rake
rake (10.5.0)

$ bundle show
  * rake (10.5.0)

$ bundle exec gem which rake
/usr/lib/ruby/vendor_ruby/rake.rb

$ bundle exec rake -V
rake, version 10.5.0
```

So far so good. But:

```
$ bundle show rake
The gem rake has been deleted. It was installed at:
/usr/share/rubygems-integration/all/gems/rake-10.5.0

$ rails c
/var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find rake-10.5.0 in any of the sources (Bundler::GemNotFound)
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
    from /var/lib/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /app/config/boot.rb:3:in `<top (required)>'
    from bin/rails:7:in `require_relative'
    from bin/rails:7:in `<main>'
```

More info about the environment:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /root/.gem/ruby/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

**Comment by segiddins** [comment]
Given `bundle exec rake` works, I'm not entirely sure how this could be a bundler issue?

**Comment by antoineco** [comment]
I came to believe it was because of the error trace showing `Bundler::GemNotFound`, but I may be wrong.

**Comment by segiddins** [comment]
What happens if you `bundle exec rails c`?

**Comment by antoineco** [comment]
It works as expected. I'm not sure to understand what is going on there since all gems are installed in a standard location :confused:

**Comment by segiddins** [comment]
I'm going to close this, as it's been over a year and I'm not convinced this is a bug to begin with, but feel free to open a new issue if you're still having issues!
