### ISSUE TITLE
`bundle open` fails when the gem is a default gem

### ISSUE THREAD

**Issue by glennfu** [bundler/bundler#4436]
- What did you do?
  
  I ran the command `/Users/Glenn/.rvm/gems/ruby-2.3.0/bin/bundle open json`
- What did you expect to happen?
  
  I expected Bundler to open a folder that exists, such as `~/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/json-1.8.3` or `~/.rvm/gems/ruby-2.2.4/gems/json-1.8.3` or wherever it happens to really exist on the system. Maybe it should point to the `~/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json` as the native 2.3.0 location.
- What happened instead?
  
  Instead, what actually happened was this error template spit out:

Error details

```
Errno::ENOENT: No such file or directory @ dir_chdir - /Users/Glenn/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/json-1.8.3
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli/open.rb:16:in `chdir'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli/open.rb:16:in `run'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli.rb:313:in `open'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
  /Users/Glenn/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
```

Environment

```
Bundler   1.11.2
Rubygems  2.5.1
Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
GEM_HOME  /Users/Glenn/.rvm/gems/ruby-2.3.0
GEM_PATH  /Users/Glenn/.rvm/gems/ruby-2.3.0:/Users/Glenn/.rvm/gems/ruby-2.3.0@global
RVM       1.26.11 (latest)
Git       2.6.4
rubygems-bundler (1.4.4)
```

**Comment by bguban** [comment]
Hm. It's strange, but there is no bundle in a ruby 2.3.0 installed over rvm
$ bundle install
The program 'bundle' is currently not installed. You can install it by typing:
sudo apt-get install bundler

**Comment by segiddins** [comment]
```diff
diff --git a/lib/bundler/cli/open.rb b/lib/bundler/cli/open.rb
index 0bbfa63..35ee853 100644
--- a/lib/bundler/cli/open.rb
+++ b/lib/bundler/cli/open.rb
@@ -13,12 +13,16 @@ module Bundler
     def run
       editor = [ENV["BUNDLER_EDITOR"], ENV["VISUAL"], ENV["EDITOR"]].find {|e| !e.nil? && !e.empty? }
       return Bundler.ui.info("To open a bundled gem, set $EDITOR or $BUNDLER_EDITOR") unless editor
-      path = Bundler::CLI::Common.select_spec(name, :regex_match).full_gem_path
-      Dir.chdir(path) do
-        command = Shellwords.split(editor) + [path]
-        Bundler.with_clean_env do
-          system(*command)
-        end || Bundler.ui.info("Could not run '#{command.join(" ")}'")
+      spec = Bundler::CLI::Common.select_spec(name, :regex_match)
+      begin
+        Dir.chdir(spec.full_gem_path) do |path|
+          command = Shellwords.split(editor) + [path]
+          Bundler.with_clean_env do
+            system(*command)
+          end || Bundler.ui.info("Could not run '#{command.join(" ")}'")
+        end
+      rescue Errno::ENOENT
+        raise InvalidOption, "Unable to open #{spec} because the directory it would normally be installed to does not exist."
       end
     end
   end
```

**Comment by allenzhao** [comment]
I can't reproduce it with Bundler v 1.12.5.
@segiddins Above was your implementation that works?

**Comment by segiddins** [comment]
@allenzhao I believe so -- the key was, you have to be `bundle open`ing a default gem
