### ISSUE TITLE
Running `bundle outdated --patch` gets NoMethodError: undefined method '>' for nil:NilClass

### ISSUE THREAD

**Issue by connorshea** [bundler/bundler#4438]
- What did you do?

  I ran the command `/Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle outdated --patch`

- What did you expect to happen?

  I expected Bundler to give me all the gems which were outdated at the patch level.

- What happened instead?

  Part of the way through the output of the command, I got a `NoMethodError`.

Error details

    NoMethodError: undefined method `>' for nil:NilClass
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:139:in `update_present_via_semver_portions'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:60:in `block in run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:45:in `each'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:45:in `run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:257:in `outdated'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:11:in `start'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/exe/bundle:27:in `block in <top (required)>'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/exe/bundle:19:in `<top (required)>'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `load'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `<main>'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment

```
  Bundler   1.12.0.rc
  Rubygems  2.6.2
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  GEM_HOME  /Users/connor/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/connor/.rvm/gems/ruby-2.3.0:/Users/connor/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.8.1
  rubygems-bundler (1.4.4)
      
  Bundler settings
      
  build.eventmachine
    Set for the current user (/Users/connor/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
  build.charlock_holmes
    Set for the current user (/Users/connor/.bundle/config): "--with-icu-dir=/usr/local/opt/icu4c"
  jobs
    Set for your local app (/Users/connor/Programming/gitlab-development-kit/gitlab/.bundle/config): "4"
  without
    Set for your local app (/Users/connor/Programming/gitlab-development-kit/gitlab/.bundle/config): "mysql:production"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/connor/.rvm/gems/ruby-2.3.0/bin:/Users/connor/.rvm/gems/ruby-2.3.0@global/bin:/Users/connor/.rvm/rubies/ruby-2.3.0/bin:/Users/connor/.rvm/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/usr/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/connor/.rvm/gems/ruby-2.3.0:/Users/connor/.rvm/gems/ruby-2.3.0@global"
```

#### Reproduction steps
Assuming Bundler 1.12.0.rc, Git, and Ruby 2.3.0 (note that I tested on 2.1.8 as well and it crashes the same way) are installed:

- `git clone https://gitlab.com/gitlab-org/gitlab-ce.git`
- `cd gitlab-ce`
- `git checkout 091c77e3c54b15fa2378a89d15400795dc9f91ee`
- `bundle install` - you may want to/have to link eventmachine with your OpenSSL version from Homebrew if on OS X.
- `bundle outdated --patch`

If the above doesn't reproduce the error, I can give you the full script for setting up GitLab Development Kit that includes Postgres, Redis, etc. but it's (probably) not necessary to reproduce this. A shallow clone of GitLab CE *should* produce the same error while also downloading faster, but it won't give you the same exact commit for reproduction purposes should the `Gemfile.lock` change at all.

**Comment by connorshea** [comment]
Here's the full terminal output, in case anyone is interested:

```
gitlab connor$ bundle outdated --patch
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies..............

Outdated gems included in the bundle:
  * asciidoctor (newest 1.5.4, installed 1.5.3, requested ~> 1.5.2) in group "default"
  * byebug (newest 8.2.4, installed 8.2.1) in groups "development, test"
  * d3_rails (newest 3.5.16, installed 3.5.11, requested ~> 3.5.0) in group "default"
  * devise (newest 3.5.6, installed 3.5.4, requested ~> 3.5.4) in group "default"
  * dropzonejs-rails (newest 0.7.3, installed 0.7.2, requested ~> 0.7.1) in group "default"
  * hipchat (newest 1.5.3, installed 1.5.2, requested ~> 1.5.0) in group "default"
  * net-ssh (newest 3.0.2, installed 3.0.1, requested ~> 3.0.1) in group "default"
  * omniauth-gitlab (newest 1.0.2, installed 1.0.1, requested ~> 1.0.0) in group "default"
  * paranoia (newest 2.1.5, installed 2.1.4, requested ~> 2.0) in group "default"
  * redcarpet (newest 3.3.4, installed 3.3.3, requested ~> 3.3.3) in group "default"
  * responders (newest 2.1.2, installed 2.1.1, requested ~> 2.0) in group "default"
  * sidekiq-cron (newest 0.4.2, installed 0.4.0, requested ~> 0.4.0) in group "default"
  * sinatra (newest 1.4.7, installed 1.4.6, requested ~> 1.4.4) in group "default"
  * wikicloth (newest 0.8.3, installed 0.8.1, requested = 0.8.1) in group "default"
  * attr_required (newest 1.0.1, installed 1.0.0)
  * bcrypt (newest 3.1.11, installed 3.1.10)
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle outdated --patch`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    NoMethodError: undefined method `>' for nil:NilClass
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:139:in `update_present_via_semver_portions'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:60:in `block in run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:45:in `each'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:45:in `run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:257:in `outdated'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:11:in `start'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/exe/bundle:27:in `block in <top (required)>'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/exe/bundle:19:in `<top (required)>'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `load'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `<main>'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.0.rc
  Rubygems  2.6.2
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  GEM_HOME  /Users/connor/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/connor/.rvm/gems/ruby-2.3.0:/Users/connor/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.8.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  build.eventmachine
    Set for the current user (/Users/connor/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
  build.charlock_holmes
    Set for the current user (/Users/connor/.bundle/config): "--with-icu-dir=/usr/local/opt/icu4c"
  jobs
    Set for your local app (/Users/connor/Programming/gitlab-development-kit/gitlab/.bundle/config): "4"
  without
    Set for your local app (/Users/connor/Programming/gitlab-development-kit/gitlab/.bundle/config): "mysql:production"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/connor/.rvm/gems/ruby-2.3.0/bin:/Users/connor/.rvm/gems/ruby-2.3.0@global/bin:/Users/connor/.rvm/rubies/ruby-2.3.0/bin:/Users/connor/.rvm/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/usr/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/connor/.rvm/gems/ruby-2.3.0:/Users/connor/.rvm/gems/ruby-2.3.0@global"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.
```

**Comment by segiddins** [comment]
The following would be the good start for a patch:

```diff
diff --git a/lib/bundler/cli/outdated.rb b/lib/bundler/cli/outdated.rb
index bd7d1bd..fda52c3 100644
--- a/lib/bundler/cli/outdated.rb
+++ b/lib/bundler/cli/outdated.rb
@@ -127,14 +127,14 @@ module Bundler
       update_present = active_major > current_major if options[:major]
 
       if !update_present && (options[:minor] || options[:patch]) && current_major == active_major
-        current_minor = current_spec.version.segments[1, 1].first
-        active_minor = active_spec.version.segments[1, 1].first
+        current_minor = current_spec.version.segments[1, 1].first || 0
+        active_minor = active_spec.version.segments[1, 1].first || 0
 
         update_present = active_minor > current_minor if options[:minor]
 
         if !update_present && options[:patch] && current_minor == active_minor
-          current_patch = current_spec.version.segments[2, 1].first
-          active_patch = active_spec.version.segments[2, 1].first
+          current_patch = current_spec.version.segments[2, 1].first || 0
+          active_patch = active_spec.version.segments[2, 1].first || 0
 
           update_present = active_patch > current_patch
         end
```
