### ISSUE TITLE
bundler error

### ISSUE THREAD

**Issue by rajan30** [bundler/bundler#4457]

**Comment by rajan30** [comment]
Fetching gem metadata from https://rubygems.org/Retrying fetcher due to error (2/4): Errno::EACCES Permission denied @ rb_sysopen - /home/rajan/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/treetop
Retrying fetcher due to error (3/4): Errno::EACCES Permission denied @ rb_sysopen - /home/rajan/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/treetop
Retrying fetcher due to error (4/4): Errno::EACCES Permission denied @ rb_sysopen - /home/rajan/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/treetop
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /home/rajan/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/treetop
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `initialize'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `open'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `open'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `update'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:63:in `update'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:72:in `update_info'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:42:in `block in dependencies'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/fetcher/compact_index.rb:83:in `call'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/fetcher/compact_index.rb:83:in `block (3 levels) in compact_index_client'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/worker.rb:65:in `call'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/worker.rb:65:in `apply_func'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/worker.rb:60:in `block in process_queue'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/worker.rb:57:in `loop'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/worker.rb:57:in `process_queue'
      /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment
      
  Bundler   1.12.0.rc.3
  Rubygems  2.2.2
  Ruby      2.1.5p273 (2014-11-13 revision 0) [x86_64-linux-gnu]
  GEM_HOME  /home/rajan/.gem
  GEM_PATH  
  Git       2.5.0
      
      Bundler settings
      
  path
    Set for the current user (/home/rajan/.bundle/config): "/home/rajan/.gem"
  disable_shared_gems
    Set for your local app (/home/rajan/app/.bundle/config): true
    Set for the current user (/home/rajan/.bundle/config): "true"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_sysopen+-+%2Fhome%2Frajan%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Finfo%2Ftreetop&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
         run  bundle exec spring binstub --all
/var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/resolver.rb:356:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'rails (= 4.2.6)' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/resolver.rb:331:in `each'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/resolver.rb:331:in `verify_gemfile_dependencies_are_found!'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/resolver.rb:200:in `start'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/resolver.rb:184:in `resolve'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/definition.rb:200:in `resolve'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/definition.rb:140:in `specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/definition.rb:185:in `specs_for'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/definition.rb:174:in `requested_specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/environment.rb:19:in `requested_specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/runtime.rb:14:in `setup'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler.rb:95:in `setup'
	from /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc.3/lib/bundler/setup.rb:19:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
