### ISSUE TITLE
Checksum of /versions does not match the checksum provided by server

### ISSUE THREAD

**Issue by perlun** [bundler/bundler#4472]
When using `bundler-1.12.0.rc.4`, I get this error when doing a `bundle install`:

```
$ bundle install
Fetching gem metadata from https://gem.fury.io/ecraft-gems/.....
Fetching version metadata from https://gem.fury.io/ecraft-gems/...
Fetching dependency metadata from https://gem.fury.io/ecraft-gems/..
Checksum of /versions does not match the checksum provided by server! Something
is wrong.
```

As can be seen, I am using a 3rd party gem source. (Gemfury)

When using the released `bundler 1.11.2`, it works properly:

```
$ bundle install
Warning: the running version of Bundler is older than the version that created t
he lockfile. We suggest you upgrade to the latest version of Bundler by running
`gem install bundler --pre`.
Fetching gem metadata from https://gem.fury.io/ecraft-gems/.....
Fetching version metadata from https://gem.fury.io/ecraft-gems/...
Fetching dependency metadata from https://gem.fury.io/ecraft-gems/..
Fetching gem metadata from https://gem.fury.io/ecraft-gems/.....
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://gem.fury.io/ecraft-gems/...
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://gem.fury.io/ecraft-gems/..
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Installing rake 11.1.1
[...]
```

Any ideas what could be causing this? /cc @rallenecraft

**Comment by indirect** [comment]
@perlun a bug in either the server or client for the new index. Thanks for reporting this!

**Comment by indirect** [comment]
@perlun can you provide some more information, so that we can try to reproduce this issue? The output from `bundle install --verbose` would be very helpful. When I try to install gems from my own GemFury account, everything works fine.

**Comment by indirect** [comment]
It would also be very helpful to see

**Comment by indirect** [comment]
It would also be very helpful to see what, exactly, is being returned for you when you use your GemFury credentials to access the url `https://gem.fury.io/ecraft-gems/versions`. For my account, that is a 404. It seems that it must not be a 404 for your account, and I don't understand how that's happening...

**Comment by mwrock** [comment]
I just started getting this same error on appveyor builds (see https://ci.appveyor.com/project/winrb/winrm/build/master-166). I then tried it on a local windows machine (blowing away my Gemfile.lock first) and got the same error.

Testing with Gem: https://github.com/WinRb/WinRM
version: 1.12.0

Works fine with 1.11.2.

**Comment by mwrock** [comment]
forgot to add `--verbose` output:
```
C:\dev\WinRM [pin_bundler]> bundle install --verbose
HTTP GET https://index.rubygems.org/versions
HTTP 200 OK
HTTP GET https://index.rubygems.org/versions
HTTP 200 OK
Checksum of /versions does not match the checksum provided by server! Something
is wrong.
```

**Comment by mwrock** [comment]
Any chance you are on windows @perlun?

This looks to be a classic case of carriage return injection on windows platforms. I just submitted #4479  to fix that.

**Comment by perlun** [comment]
Yes. This was on Windows.

**Comment by agross** [comment]
I get this on Windows:

```
$ bundle install --verbose
HTTP GET http://gems.on-private.server/versions
HTTP 404 Not Found Bundler::Fetcher::FallbackError: Net::HTTPNotFound
C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/downloader.rb:34:in `fetch'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:76:in `block in compact_index_client'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:23:in `call'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:23:in `update'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:63:in `update'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:54:in `update_and_parse_checksums!'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:63:in `available?'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:15:in `call'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher.rb:154:in `use_api'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:331:in `select'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/index.rb:10:in `build'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:335:in `remote_specs'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:82:in `specs'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/lazy_specification.rb:56:in `__materialize__'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/spec_set.rb:91:in `block in materialize'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/spec_set.rb:88:in `map!'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/spec_set.rb:88:in `materialize'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/definition.rb:140:in `specs'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/definition.rb:129:in `resolve_remotely!'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/installer.rb:195:in `resolve_if_need'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/installer.rb:70:in `run'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/installer.rb:22:in `install'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/cli/install.rb:102:in `run'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/cli.rb:175:in `install'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/cli.rb:11:in `start'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/exe/bundle:27:in `block in <top (required)>'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  C:/Ruby/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/exe/bundle:19:in `<top (required)>'
  C:/Ruby/bin/bundle:23:in `load'
  C:/Ruby/bin/bundle:23:in `<main>'
HTTP GET http://gems.heco.de/api/v1/dependencies
HTTP 200 OK HTTP GET https://index.rubygems.org/versions
HTTP 200 OK
HTTP GET https://index.rubygems.org/versions
HTTP 200 OK
Checksum of /versions does not match the checksum provided by server! Something
is wrong.
```

**Comment by segiddins** [comment]
This should now be fixed in 1.12.1!

**Comment by h8rry** [comment]
I am getting this error after upgrading to Rails 5.0 today. I am using 1.12.5. Any thoughts?

**Comment by pboling** [comment]
Getting this on install of bundler 1.12.5 e.g. https://travis-ci.org/Dynamoid/Dynamoid/jobs/150380064

**Comment by indirect** [comment]
@pboling homu is a bot, and probably can't help you. I believe that we fixed this issue (to instead print a warning and then automatically use the full index), but we haven't released it yet. For the time being, you can work around this problem by running `bundle install --full-index`.

**Comment by ProGM** [comment]
I'm having the same issue in `1.13.2`, fixed with `bundle install --full-index`

**Comment by pilz** [comment]
Yes, I am also currently getting this - wasn't there last friday - and running `bundle install --full-index` fixes it.

**Comment by luizasalantiu** [comment]
Same here

**Comment by anandaverma** [comment]
facing same issue

**Comment by segiddins** [comment]
The issue has been fixed client-side on bundler master, and @dwradcliffe has rolled back the changes on rubygems.org that caused this issue to crop up
