### ISSUE TITLE
Slower performance with 1.12.0 Fetching source index

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#4478]
I just happened upon 1.12.0 after release tonight, so maybe this is too soon to report this as a problem, but here's what I'm seeing consistently: about a 10 second increase in index time with 1.12.

```
[chrismo@momac bundler]$ cat Gemfile
source 'https://rubygems.org'

gem 'rack'
[chrismo@momac bundler]$ bundle --version
/Users/chrismo/.rbenv/versions/2.2.4/bin/ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
Bundler version 1.11.2
[chrismo@momac bundler]$ time bundle install --path zz
/Users/chrismo/.rbenv/versions/2.2.4/bin/ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/..
Installing rack 1.6.4
Using bundler 1.11.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./zz.

real	0m4.837s
user	0m1.077s
sys	0m0.265s
[chrismo@momac bundler]$ gem install bundler -v 1.12.0
/Users/chrismo/.rbenv/versions/2.2.4/bin/ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
Fetching: bundler-1.12.0.gem (100%)
Successfully installed bundler-1.12.0
Parsing documentation for bundler-1.12.0
Installing ri documentation for bundler-1.12.0
Done installing documentation for bundler after 5 seconds
1 gem installed
[chrismo@momac bundler]$ rm -r zz
[chrismo@momac bundler]$ time bundle install --path zz
/Users/chrismo/.rbenv/versions/2.2.4/bin/ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
Fetching source index from https://rubygems.org/
Installing rack 1.6.4
Using bundler 1.12.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./zz.

real	0m14.847s
user	0m7.124s
sys	0m1.269s
```

**Comment by segiddins** [comment]
What's the output of `bundle install --verbose` for you on 1.12?

**Comment by chrismo** [comment]
```
[chrismo@momac bundler]$ bundle install --verbose
/Users/chrismo/.rbenv/versions/2.2.4/bin/ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
Using rack 1.6.4
0:  rack (1.6.4) from /private/tmp/bundler/zz/ruby/2.2.0/specifications/rack-1.6.4.gemspec
Using bundler 1.12.0
0:  bundler (1.12.0) from /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./zz.```

**Comment by segiddins** [comment]
I don't see how that could possibly be any slower, its not even making any network requests!

**Comment by chrismo** [comment]
oh in that case, i didn't blow away the local `zz` dir I installed to. I did that and just re-ran with debug output:
```
[chrismo@momac bundler]$ rm -r zz
[chrismo@momac bundler]$ DEBUG=1 bundle 2>&1 | tee output.txt
/Users/chrismo/.rbenv/versions/2.2.4/bin/ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
HTTP GET https://index.rubygems.org/versions
Bundler::Fetcher::CertificateFailureError: Could not verify the SSL certificate for https://index.rubygems.org/versions.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
/Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/downloader.rb:53:in `rescue in request'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/downloader.rb:41:in `request'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/downloader.rb:16:in `fetch'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:76:in `block in compact_index_client'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:23:in `call'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:23:in `update'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:63:in `update'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:54:in `update_and_parse_checksums!'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:63:in `available?'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/fetcher.rb:154:in `use_api'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:331:in `select'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/index.rb:10:in `build'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:335:in `remote_specs'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source/rubygems.rb:82:in `specs'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/lazy_specification.rb:56:in `__materialize__'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/spec_set.rb:91:in `block in materialize'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/spec_set.rb:88:in `map!'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/spec_set.rb:88:in `materialize'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/definition.rb:140:in `specs'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/definition.rb:129:in `resolve_remotely!'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/installer.rb:195:in `resolve_if_need'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/installer.rb:70:in `run'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/installer.rb:22:in `install'
  /Users/chrismo/.rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/cli/install.rb:102:in `run'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/cli.rb:175:in `install'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/cli.rb:11:in `start'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/exe/bundle:27:in `block in <top (required)>'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/exe/bundle:19:in `<top (required)>'
  /Users/chrismo/.rbenv/versions/2.2.4/bin/bundle:23:in `load'
  /Users/chrismo/.rbenv/versions/2.2.4/bin/bundle:23:in `<main>'
HTTP GET https://index.rubygems.org/api/v1/dependencies
Fetching source index from https://rubygems.org/
Need to query more than 500 gems. Downloading full index instead...
HTTP GET https://rubygems.org/quick/Marshal.4.8/rack-1.6.4.gemspec.rz
HTTP 302 Moved Temporarily
HTTP GET https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/rack-1.6.4.gemspec.rz
HTTP 200 OK
Installing rack 1.6.4
0:  rack (1.6.4) from /private/tmp/bundler/zz/ruby/2.2.0/specifications/rack-1.6.4.gemspec
Using bundler 1.12.0
0:  bundler (1.12.0) from /Users/chrismo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.0/lib/bundler/source
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./zz.
```

**Comment by chrismo** [comment]
full index download ...

**Comment by segiddins** [comment]
Ah!

```
Bundler::Fetcher::CertificateFailureError: Could not verify the SSL certificate for https://index.rubygems.org/versions.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```
Would be the issue, most likely. @indirect want to check why the index.rg.org cert isn't being picked up?

**Comment by chrismo** [comment]
Just to double-check, debug output with 1.11.2 appears to be fine. I can paste if you need - but I'm guessing you don't and it's long.

**Comment by segiddins** [comment]
Nope, its the difference between connecting to `bundler.rubygems.org` and `index.rubygems.org`. We thought we updated the bundled CA certs in 1.12 for that change, but something must've slipped through.

**Comment by chrismo** [comment]
Would that cause this situation: >100k specs in the index just before it says it needs to go download the whole index?

<img width="768" alt="screen shot 2016-04-29 at 12 12 37 am" src="https://cloud.githubusercontent.com/assets/8092/14908643/4fa9c23c-0d9f-11e6-9244-07fc9c2e6c98.png">

**Comment by segiddins** [comment]
That should be the same between 1.12 and 1.11

**Comment by chrismo** [comment]
cool

**Comment by RochesterinNYC** [comment]
@segiddins PR rubygems/rubygems#1583 and associated PR #4448 might alleviate this? Since they generate/pick the certs programmatically and not via a manual process.

**Comment by segiddins** [comment]
@RochesterinNYC nope, that PR wouldn't change anything related to this

**Comment by retrospective5** [comment]
Right now `bundle install` is ways faster with 1.11.2.

There has been a `uri.host` change affecting 1.12.x in 0904c9a (and maybe elsewhere) aiming for performance gains per 32ab479; Possibly still a work in progress.

**Comment by PikachuEXE** [comment]
I got the same issue just starting from today
with `Bundler::Fetcher::CertificateFailureError`
Worked around with downgrading bundler to 1.11.x

**Comment by chrismo** [comment]
Anyone with this issue, I was able to resolve locally by ensuring i have a recent openssl installed and re-installing Ruby. What does `ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'` output for those with problems? Mine used to be 1.0.2a (I think, I actually forgot to copy it before upgrading), it's now `OpenSSL 1.0.2h  3 May 2016`

**Comment by caioproiete** [comment]
@chrismo: I had the same issue yesterday and the workaround was to downgrade bundler to v1.11.2

**Comment by chrismo** [comment]
@caioproiete I 'fixed' it in 1.12 by updating my openssl version. Can you share what version of openssl your ruby is linked to? `ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'`

**Comment by caioproiete** [comment]
@chrismo Interesting. So apparently Ruby is not using the latest openssl I have on the machine.

![image](https://cloud.githubusercontent.com/assets/177608/15591758/4bdbebf8-2375-11e6-87c7-7556321a651b.png)

**Comment by chrismo** [comment]
Yeah, it has to be re-built is my understanding. So, presuming `rbenv` - `rbenv uninstall 2.3.0 && rbenv install 2.3.0` is what I did.

**Comment by PikachuEXE** [comment]
I have rebuilt ruby but problem still exists
```
$ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2h  3 May 2016
```
```
$ bundle update --verbose
HTTP GET https://index.rubygems.org/versions
Bundler::Fetcher::CertificateFailureError: Could not verify the SSL certificate for https://index.rubygems.org/versions.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

**Comment by caioproiete** [comment]
Thanks @chrismo. Reinstalling Ruby fixed the issue.

I reinstalled Ruby:
```
rvm get stable
rvm reinstall ruby-2.3.0 --with-openssl-dir=`brew --prefix openssl`
```

and now it is using the latest OpenSSL installed:
```
$ ruby -r openssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2h  3 May 2016
```

I then updated Bundler to v1.12.5, and it is as fast as v1.11.2.

```
$ bundler --version
Bundler version 1.12.5

$ bundle update --verbose
HTTP GET https://index.rubygems.org/versions
HTTP 206 Partial Content
Fetching gem metadata from https://rubygems.org/
```

**Comment by PikachuEXE** [comment]
Just try `1.12.5` again now it works without issue
I haven't re-install ruby or upgrade openssl since my last comment submitted

**Comment by LynnCo** [comment]
@chrismo this issue is resolved yea?

**Comment by chrismo** [comment]
Yeah, I'd say so.
