### ISSUE TITLE
uninitialized constant Sass::Script after upgrading to 1.12.0

### ISSUE THREAD

**Issue by siebertm** [bundler/bundler#4482]
With our rails application, I noticed an error after I upgraded to 1.12.0 (accidentally I must say):

```
bundle exec rails c
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:91:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'sass-rails'.
Gem Load Error is: uninitialized constant Sass::Script
Did you mean?  ScriptError
Backtrace for gem load error is:
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/helpers.rb:12:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails.rb:8:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails.rb:8:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass-rails.rb:1:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass-rails.rb:1:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:88:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:88:in `block (2 levels) in require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `each'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `block in require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `each'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler.rb:102:in `require'
/home/siebert/code/platform/config/application.rb:6:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `preload'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:87:in `block (2 levels) in require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `each'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:83:in `block in require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `each'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler/runtime.rb:72:in `require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.0/lib/bundler.rb:102:in `require'
        from /home/siebert/code/platform/config/application.rb:6:in `<top (required)>'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:82:in `preload'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:143:in `serve'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/siebert/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

My bundle env is at https://gist.github.com/siebertm/7a13e63b2b16527fa282eabe3b95a7ad

The same Gemfile(.lock) works on 1.11.2 without any problems. Also, downgrading to 1.12.2 makes everything work again. Reproduced on 2 machines, so my feeling is that it's got to to with 1.12.0

Any ideas what I might do to help figure out whats going on?

**Comment by RochesterinNYC** [comment]
Hi @siebertm, thanks for the issue. I'm not yet convinced this is a Bundler problem as it looks like there is a legitimate error coming from `sass-rails` (the output under `Backtrace for gem load error is:`). The new output format for this `GemRequireError` is due to this PR: #4187. However, the additional functionality from that PR only results in existing `GemRequireError`s outputting more helpful information. 

Could you please create minimal reproduction steps (or point us to the affected Rails app if it is public) so we can reproduce and diagnose? Thanks!

**Comment by siebertm** [comment]
Thanks for your quick reply @RochesterinNYC !

So I reproduced a minimal test case. See the Gemfile and Gemfile.lock at the updated gist https://gist.github.com/siebertm/7a13e63b2b16527fa282eabe3b95a7ad#file-gemfile

As you can see, we're using an old `haml` version (`~> 3.0`) and a non-restricted `sass-rails`. What happens in 1.12.0 is that `sass-rails` is loaded, requires `sass`, expects `Sass::Script` and fails because it's not there. `haml` used to implement both HAML and SASS before version 4, where it was extracted into the `sass` gem. 

`sass-rails` requires `sass` ~> 3.4 (https://github.com/rails/sass-rails/blob/master/sass-rails.gemspec#L17)

`haml` 3.1.8 hosts a `sass.rb` file. 

So my guess was that something must have changed in the load order, a.k.a `$LOAD_PATH` and I was right:

In 1.11.2, the `sass` gem path is put before `haml` (https://gist.github.com/siebertm/7a13e63b2b16527fa282eabe3b95a7ad#file-bundler-1-11-load_path)

in 1.12.0, the `haml` gem path comes first (https://gist.github.com/siebertm/7a13e63b2b16527fa282eabe3b95a7ad#file-bundler-1-12-loadpath)

To conclude: _yes_ we should upgrade `haml`, but I'm not sure if this is not a bug. Should bundler change the `$LOAD_PATH` order between versions? I'd consider this at least as unexpected behaviour.

**Comment by segiddins** [comment]
Looks like the load path is being reversed, which is definitely a bug

**Comment by segiddins** [comment]
Likely cause is https://github.com/bundler/bundler/pull/4268

**Comment by awwaiid** [comment]
I also ran into this -- downgrading to 1.11.2 "fixed" it.

**Comment by segiddins** [comment]
Fixed in 1.12.1

**Comment by siebertm** [comment]
Yep, I can confirm that!

Thanks for your help!

**Comment by stonko1994** [comment]
Happened again to me when updating to 1.15.0.
Downgrad to 1.14.6 fixed it.

**Comment by segiddins** [comment]
Please open a new issue with steps to reproduce @stonko1994
