### ISSUE TITLE
Bundle install

### ISSUE THREAD

**Issue by m-sakthivel** [bundler/bundler#4525]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
ArgumentError: wrong number of arguments (5 for 4)
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/definition.rb:200:in `resolve'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/definition.rb:200:in `resolve'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/definition.rb:166:in `missing_specs'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/installer.rb:188:in `resolve_if_need'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/ui/shell.rb:81:in `silence'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/installer.rb:185:in `resolve_if_need'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/installer.rb:70:in `run'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/installer.rb:22:in `install'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/cli/install.rb:102:in `run'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/cli.rb:175:in `install'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `__send__'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/cli.rb:11:in `start'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/exe/bundle:27
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/gems/bundler-1.12.1/exe/bundle:19
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/bin/bundle:23:in `load'
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/bin/bundle:23
  /home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/bin/ruby_executable_hooks:15
```

Environment

  Bundler   1.12.1
  Rubygems  2.0.17
  Ruby      1.8.7 (2013-06-27 patchlevel 374) [i686-linux]
  GEM_HOME  /home/sakthivel/xx/xxxx/vendor/local/ruby/1.8
  GEM_PATH  
  RVM       1.27.0 (latest)
  Git       1.9.1

```
  Bundler settings
```

  disable_shared_gems
    Set for your local app (/home/sakthivel/xx/xxxx/.bundle/config): true
  path
    Set for your local app (/home/sakthivel/xx/xxxx/.bundle/config): "vendor/local"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp/bin:/home/sakthivel/.rvm/gems/ruby-1.8.7-p374@global/bin:/home/sakthivel/.rvm/rubies/ruby-1.8.7-p374/bin:/home/sakthivel/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/sakthivel/.rvm/gems/ruby-1.8.7-p374@csp:/home/sakthivel/.rvm/gems/ruby-1.8.7-p374@global"

**Comment by segiddins** [comment]
This should be fixed by 1.12.5
