### ISSUE TITLE
Bundler fails unexpectedly on bundle install with git gem

### ISSUE THREAD

**Issue by ohboyotero** [bundler/bundler#4533]
```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `bundle install`  (`/Users/username/.rvm/gems/ruby-2.3.0@gemset/bin/bundle install`)

- What did you expect to happen?

  I expected Bundler to install any missing gems. Specifically, bundler needed to check out a gem from git:

`git@github.com:circleci/minitest-ci.git (at master) is not yet checked out. Run `bundle install` first.

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::EEXIST: File exists @ dir_s_mkdir - /Users/username/.rvm/gems/ruby-2.3.0@gemset/bundler
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir'
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `each'
      /Users/username/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/source/git/git_proxy.rb:83:in `copy_to'
      /Users/username/.rvm/gems/ruby-2.3.0@gemsetl/gems/bundler-1.10.6/lib/bundler/source/git.rb:154:in `specs'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `each'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `block in index'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/definition.rb:206:in `index'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
      /Users/username/.rvm/gems/ruby-2.3.0@gemsetl/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/bin/bundle:23:in `load'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/bin/bundle:23:in `<main>'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/bin/ruby_executable_hooks:15:in `eval'
      /Users/username/.rvm/gems/ruby-2.3.0@gemset/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.5.1
    Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    GEM_HOME  /Users/username/.rvm/gems/ruby-2.3.0@gemset
    GEM_PATH  /Users/username/.rvm/gems/ruby-2.3.0@gemset:/Users/username/.rvm/gems/ruby-2.3.0@global
    RVM       1.26.11 (latest)
    Git       2.3.6
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------
```

**Comment by ohboyotero** [comment]
Deleting my rvm gemset entirely and rebuilding it seemed to work, but this still shouldn't have happened in the first place, right?

**Comment by RochesterinNYC** [comment]
You're using an old Bundler version so this might have already been fixed or addressed. Can you reproduce this with the latest Bundler? (`v1.12.3`)

**Comment by LynnCo** [comment]
pgin @ohboyotero

> You're using an old Bundler version so this might have already been fixed or addressed. Can you reproduce this with the latest Bundler? (`v1.12.3`)

**Comment by ohboyotero** [comment]
Sorry I somehow missed the immediate reply back in May. I haven't been able to repro since wiping my rvm gemset. Not sure how to get into whatever funky state I was previously in. Sorry!
