### ISSUE TITLE
bundle install not working

### ISSUE THREAD

**Issue by amandeepmittal** [bundler/bundler#4637]
```
-- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::EACCES: Permission denied - /Users/amandeepmittal/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160602-14328-1llxw4h
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `mkdir'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `block in mktmpdir'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:142:in `create'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `mktmpdir'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.6.4
  Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
  GEM_HOME  /Library/Ruby/Gems/2.0.0
  GEM_PATH  /Library/Ruby/Gems/2.0.0:/Users/amandeepmittal/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  Git       2.7.4 (Apple Git-66)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin"
--- TEMPLATE END ----------------------------------------------------------------

```

**Comment by LynnCo** [comment]
Check out have the other issues with [permission errors](https://github.com/bundler/bundler/search?q=Permission+denied&type=Issues&utf8=%E2%9C%93) were resolved, like https://github.com/bundler/bundler/issues/4458, https://github.com/bundler/bundler/issues/4431, https://github.com/bundler/bundler/issues/4429

**Comment by amandeepmittal** [comment]
Thank you for referring me to the solution.
