### ISSUE TITLE
Bundler cannot continue

### ISSUE THREAD

**Issue by Harishkris** [bundler/bundler#4693]
I was trying to do `bundle install --local` and ended up in this

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
TypeError: wrong argument type nil (expected String)
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:468:in `initialize'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:468:in `wrap'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:468:in `block in read_checksums'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:116:in `seek'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:467:in `read_checksums'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:520:in `block (2 levels) in verify'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:29:in `new'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:519:in `block in verify'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:37:in `open'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:37:in `open'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:518:in `verify'
  /usr/share/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/package.rb:499:in `spec'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:223:in `spec_from_gem'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:218:in `block in prune_gem_cache'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:217:in `delete_if'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:217:in `prune_gem_cache'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:145:in `prune_cache'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:137:in `cache'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:106:in `run'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
  /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Environment

```
Bundler   1.11.2
Rubygems  2.5.1
Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
GEM_HOME  /home/ubuntu/.rvm/gems/ruby-2.3.0
GEM_PATH  /home/ubuntu/.rvm/gems/ruby-2.3.0:/home/ubuntu/.rvm/gems/ruby-2.3.0@global
RVM       1.26.11 (latest)
Git       1.9.1
rubygems-bundler (1.4.4)
```

Bundler settings

```
gem.test
  Set for the current user (/home/ubuntu/.bundle/config): "minitest"
gem.mit
  Set for the current user (/home/ubuntu/.bundle/config): "true"
gem.coc
  Set for the current user (/home/ubuntu/.bundle/config): "true"
cache_all
  Set for your local app (/home/ubuntu/work/knotalk/.bundle/config): "true"
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
Can you please share your Gemfile? Thanks!

**Comment by LynnCo** [comment]
@Harishkris 

> Can you please share your Gemfile? Thanks!

**Comment by RochesterinNYC** [comment]
@Harishkris any update on this?

**Comment by lynnco** [comment]
Closing to due age!
