### ISSUE TITLE
metasploit install failed

### ISSUE THREAD

**Issue by mohsennasr** [bundler/bundler#4724]
user@USER-PC:/opt/metasploit-framework$ bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/usr/local/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/home/user/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160626-2788-14mnsu2" (parent directory mode 40777)
  /usr/lib/ruby/1.9.1/fileutils.rb:708:in `remove_entry_secure'
  /usr/lib/ruby/1.9.1/tmpdir.rb:85:in `ensure in mktmpdir'
  /usr/lib/ruby/1.9.1/tmpdir.rb:85:in `mktmpdir'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  /var/lib/gems/1.9.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

Environment

  Bundler   1.12.5
  Rubygems  1.8.23
  Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
  GEM_HOME  /var/lib/gems/1.9.1
  GEM_PATH  /var/lib/gems/1.9.1:/home/user/.gem/ruby/1.9.1
  Git       1.9.1

```
  Bundler settings
```

  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by indirect** [comment]
Your home directory is world-writable, which isn't safe. You need to remove write permissions from your home directory (which appears to be `/home/user/`), and then run `rm -rf /home/user/.bundle` and try again.

**Comment by mohsennasr** [comment]
thank you for your answer. but my home directory is not world writable! my home directory permissions is "drwxr-xr-x"

**Comment by mohsennasr** [comment]
any idea?!

**Comment by LynnCo** [comment]
@mohsennasr did you figure out a resolution for this, or is it still open?

**Comment by mohsennasr** [comment]
@LynnCo unfortunately I haven't find any solution yet!

**Comment by colby-swandale** [comment]
@mohsennasr Is this still an issue for you? The latest version includes some fixes and better error messages for file permission related issues.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
