### ISSUE TITLE
`require': cannot load such file -- ffi (LoadError) when trying to start rails console

### ISSUE THREAD

**Issue by galharth** [bundler/bundler#4786]
Full stack trace:
```
/Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- ffi (LoadError)
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/sys-proctable-1.1.1-universal-darwin/lib/darwin/sys/proctable.rb:2:in `<top (required)>'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/sys-proctable-1.1.1-universal-darwin/lib/sys-proctable.rb:1:in `<top (required)>'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/galharth/Documents/productbattle/config/application.rb:7:in `<top (required)>'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/galharth/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Rails version: 4.2.5
Ruby version: 2.3.0
Bundler version: 1.10.6
OSX: El Capitan (Co-worker using windows)

**Comment by segiddins** [comment]
Can you verify that your Ruby install includes ffi? `Ruby -rffi-e 'puts FFI'`

**Comment by galharth** [comment]
Solved it by adding by running gem install ffi --platform=ruby and adding gem 'ffi' to my gemfile
