### ISSUE TITLE
No such file or directory - git clone "git://github.com/kyparn/fancybox2-rails.git" 

### ISSUE THREAD

**Issue by bahill** [bundler/bundler#4823]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby22/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOENT: No such file or directory - git clone "git://github.com/kyparn/fancybox2-rails.git" "C:/Ruby22/lib/ruby/gems/2.2.0/cache/bundler/git/fancybox2-rails-4f6d04a660d5201128754877f4fe1e08
eeff9679" --bare --no-hardlinks --quiet
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:149:in ``'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:149:in `block in git'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:72:in `call'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:72:in `with_clean_git_env'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:149:in `git'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:143:in `block in git_retry'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/retry.rb:39:in `call'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/retry.rb:39:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/retry.rb:29:in `attempt'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:142:in `git_retry'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:98:in `checkout'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/git.rb:154:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      C:/Ruby22/bin/bundle:22:in `load'
      C:/Ruby22/bin/bundle:22:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.6.6
  Ruby      2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]
  GEM_HOME  C:/Ruby22/lib/ruby/gems/2.2.0
  GEM_PATH  C:/Ruby22/lib/ruby/gems/2.2.0;I:/.gem/ruby/2.2.0
  Git       not installed
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by bahill** [comment]
I didn't have git on my path <facepalm>
