### ISSUE TITLE
redmine was working just fine and now i'm getting this random error about CLOCK_REALTIME

### ISSUE THREAD

**Issue by zach2825** [bundler/bundler#4826]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/usr/local/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
NameError: uninitialized constant Process::CLOCK_REALTIME
  /usr/lib/ruby/2.0.0/securerandom.rb:118:in `gen_random'
  /usr/lib/ruby/2.0.0/securerandom.rb:110:in `random_bytes'
  /usr/lib/ruby/2.0.0/securerandom.rb:173:in `hex'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/fetcher.rb:173:in `user_agent'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/fetcher.rb:241:in `connection'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/fetcher.rb:72:in `initialize'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:231:in `new'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:231:in `block in fetchers'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:229:in `map'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:229:in `fetchers'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:335:in `block in remote_specs'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/index.rb:9:in `build'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:334:in `remote_specs'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:81:in `specs'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lazy_specification.rb:53:in `__materialize__'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:90:in `block in materialize'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /var/lib/gems/2.0.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

Environment

```
Bundler   1.11.2
Rubygems  2.4.5.1
Ruby      2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux-gnu]
GEM_HOME  /srv/redmine/vendor/bundle/ruby/2.0.0
GEM_PATH  
Git       1.9.1
```

Bundler settings

```
build.mysql
  Set for the current user (/home/zach2825/.bundle/config): "--with-mysql-config=/usr/bin/mysql_config"
gem.test
  Set for the current user (/home/zach2825/.bundle/config): "false"
gem.mit
  Set for the current user (/home/zach2825/.bundle/config): "true"
gem.coc
  Set for the current user (/home/zach2825/.bundle/config): "true"
path
  Set for your local app (/srv/redmine/.bundle/config): "vendor/bundle"
  Set for the current user (/home/zach2825/.bundle/config): "vendor/bundle"
disable_shared_gems
  Set for your local app (/srv/redmine/.bundle/config): "1"
  Set for the current user (/home/zach2825/.bundle/config): "1"
without
  Set for your local app (/srv/redmine/.bundle/config): "development:test"
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by RochesterinNYC** [comment]
It doesn't look like this error is really being thrown in Bundler?

**Comment by colby-swandale** [comment]
ping @zach2825 are you still experiencing this issue?

**Comment by zach2825** [comment]
Sorry, I gave up a while ago and switch to Jira. I really like readmine but I didn't have time to resolve it.

Thank you for your time I'm sorry i didn't see a way to close/ remove this issue.
