### ISSUE TITLE
download_gem not being retried

### ISSUE THREAD

**Issue by jkeiser** [bundler/bundler#4846]
It appears that retry applies to fetching specs and talking to git, but not to actually retrieving the gems themselves. We have received this error multiple times in the past month, even with `bundle install ... --retry 5`:

`Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect `

Bundler 1.12.5, Rubygems 2.6.5, Ruby 2.1.8p440.

For one example:

```
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Fetching git://github.com/chef/omnibus.git
Fetching git://github.com/chef/omnibus-software.git
Fetching https://github.com/ksubrama/pedump.git
Installing awesome_print 1.7.0
Installing jmespath 1.3.1
Installing fuzzyurl 0.8.0
Installing mixlib-config 2.2.1
Installing mixlib-shellout 2.2.6
Installing chef-sugar 3.4.0
Installing cleanroom 1.0.0
Installing ffi 1.9.14 with native extensions
Installing libyajl2 1.2.0 with native extensions
Installing iostruct 0.0.4
Installing ipaddress 0.8.3
Installing mixlib-cli 1.7.0
Installing mixlib-log 1.6.0
Installing mixlib-versioning 1.1.0
Installing multipart-post 1.2.0
Installing plist 3.2.0
Installing systemu 2.6.5
Installing wmi-lite 1.0.0

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/ruby-progressbar-1.8.1.gem)
Installing thor 0.19.1
Installing progressbar 0.21.0
Installing zhexdump 0.0.2
Using bundler 1.12.5
Installing aws-sdk-core 2.5.0
Installing chef-config 12.12.15
Installing ffi-yajl 2.3.0 with native extensions
An error occurred while installing ruby-progressbar (1.8.1), and Bundler cannot
continue.
Make sure that `gem install ruby-progressbar -v '1.8.1'` succeeds before
bundling.
```

I can't find the code that's supposed to retry ECONNRESET (or indeed any rubygems request): rubygems' `Gem::RemoteFetcher` doesn't seem to take a parameter for retries, nor is bundler passing one.: https://github.com/bundler/bundler/blob/28ded71b5c399fde3ecbbe785f6077312f2c54c7/lib/bundler/rubygems_integration.rb#L277-L281

Since it happens intermittently, it's a little hard to repro, but we do enough builds to find it often. #4729 seems to have hit it as well.

**Comment by segiddins** [comment]
can you try running with `DEBUG=1` so we can get a backtrace on that? Thanks!

**Comment by jkeiser** [comment]
@segiddins sure. I'll set my builds to doing that. Not sure how long it'll take to get a repro!

**Comment by indirect** [comment]
@segiddins if `install_from_gem` doesn't have any internal retry logic, we should definitely wrap it in a retry block 😅

**Comment by scotthain** [comment]
@segiddins @indirect Here's some debug output from one of our freebsd machines. We have had a few other repros today so let @jkeiser or myself know if you need more! https://gist.github.com/scotthain/58da989cfd632f252e3d1f7c20a2919e

**Comment by jkeiser** [comment]
The relevant bit:

```
Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/multipart-post-1.2.0.gem)
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:308:in `rescue in fetch_path'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:281:in `fetch_path'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:324:in `cache_update_path'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.1.0/rubygems/remote_fetcher.rb:188:in `download'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:615:in `download_gem'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:410:in `fetch_gem'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:116:in `install'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer/gem_installer.rb:57:in `install'
/opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
```
