### ISSUE TITLE
ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work;

### ISSUE THREAD

**Issue by Tset-Noitamotua** [bundler/bundler#4887]
This was run on Window`s new [Bash Shell](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) (Bash on Ubuntu on Windows) which is in beta yet.

```
...
Fetching https://github.com/mitchellh/vagrant-spec.git
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to do its job

- What happened instead?

  Instead, what actually happened was error below


Error details

    ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/root/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160816-7933-1l9pzsl" (parent directory mode 40777)
      /usr/lib/ruby/1.9.1/fileutils.rb:708:in `remove_entry_secure'
      /usr/lib/ruby/1.9.1/tmpdir.rb:85:in `ensure in mktmpdir'
      /usr/lib/ruby/1.9.1/tmpdir.rb:85:in `mktmpdir'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  1.8.23
  Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
  GEM_HOME  /var/lib/gems/1.9.1
  GEM_PATH  /var/lib/gems/1.9.1:/root/.gem/ruby/1.9.1:/usr/share/rubygems-integration/1.9.1:/usr/share/rubygems-integration/all
  Git       1.9.1

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
...
```

**Comment by segiddins** [comment]
This should have a more informative message as of https://github.com/bundler/bundler/pull/4738, which hasn't been released yet.
In the meantime, you might want to remove the world-writable permissions bit from the parent directory

**Comment by Tset-Noitamotua** [comment]
How do one remove world-writable permissions from parent directory?

**Comment by segiddins** [comment]
`chmod o-w file`

**Comment by Tset-Noitamotua** [comment]
ok thanks   ... I run into a lot of other trouble now but I guess it`s not Bundler`s fault .  So as for me this issue can be closed.

**Comment by segiddins** [comment]
Let us know if there's anything else we can help with!

**Comment by sunilpuranik** [comment]
Doing `sudo chmod o-w tmp/` worked for me
