### ISSUE TITLE
Illformed requirement [">"]

### ISSUE THREAD

**Issue by JohNan** [bundler/bundler#4965]
```Looking up gems ["unf_ext"]
--- ERROR REPORT TEMPLATE -------------------------------------------------- What did you do?

  I ran the command `/home/pi/.rvm/gems/ruby-2.3.1@metasploit-framework/bin
- What did you expect to happen?

  I expected Bundler to install the gem

- What happened instead?

  Instead, what happened was that bundler crashed. This is working on version 1.12.5


Error details

    Gem::Requirement::BadRequirementError: Illformed requirement [">"]
      /home/pi/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.r      /home/pi/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.r      /home/pi/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.r      /home/pi/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.r      /home/pi/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.13.etasploit-framework/gems/bundler-1.13.0/lib/bundler/endpoint_specification.etasploit-framework/gems/bundler-1.13.0/lib/bundler/endpoint_specification.etasploit-framework/gems/bundler-1.13.0/lib/bundler/endpoint_specification.etasploit-framework/gems/bundler-1.13.0/lib/bundler/endpoint_specification.etasploit-framework/gems/bundler-1.13.0/lib/bundler/fetcher.rb:137:in `new'etasploit-framework/gems/bundler-1.13.0/lib/bundler/fetcher.rb:137:in `blocetasploit-framework/gems/bundler-1.13.0/lib/bundler/fetcher.rb:134:in `eachetasploit-framework/gems/bundler-1.13.0/lib/bundler/fetcher.rb:134:in `specetasploit-framework/gems/bundler-1.13.0/lib/bundler/fetcher.rb:112:in `blocetasploit-framework/gems/bundler-1.13.0/lib/bundler/retry.rb:39:in `run'   etasploit-framework/gems/bundler-1.13.0/lib/bundler/retry.rb:29:in `attemptetasploit-framework/gems/bundler-1.13.0/lib/bundler/fetcher.rb:111:in `spec  Rubygems  2.5.1                                                            Ruby      2.3.1p112 (2016-04-26 revision 54768) [armv7l-linux-eabihf]      GEM_HOME  /home/pi/.rvm/gems/ruby-2.3.1@metasploit-framework               GEM_PATH  /home/pi/.rvm/gems/ruby-2.3.1@metasploit-framework:/home/pi/.rv  RVM       1.27.0 (latest)                                                  Git       2.1.4                                                            rubygems-bundler (1.4.4)                                                 --- TEMPLATE END ----------------------------------------------------------```

**Comment by JohNan** [comment]
Sorry for the ugly formatting, I'm currently on my cell.

**Comment by chrismo** [comment]
This looks like a dup of #4959 - you should find more info there

**Comment by JohNan** [comment]
Ah crap, thank you. Sorry for the dupe, that was very sloppy of me. I actually used that auto generated search link, but it ended up empty.

I'm not sure if the other issue shows what gem it fails on, but for me it looks like it's the gem  unf_ext

**Comment by chrismo** [comment]
Hey, no worries :) Dupes are no big deal.
