### ISSUE TITLE
Bundler.require in 1.13 clears load path when it shouldn't (?)

### ISSUE THREAD

**Issue by buehmann** [bundler/bundler#5005]
## Background

On our continuous integration server, we test our Rails application with RSpec and the Knapsack gem. When Bundler v1.13 was released (we were automatically installing the most recent version of Bundler), we saw our complete test suite fail with strange errors: Undefined symbols, files could not be loaded.

This was a bit hard to debug because multiple processes running our Rails app are involved and multiple layers of Bundler. It roughly looks like this:
* bundle exec rake knapsack:rspec
  * (in Knapsack gem) system("bundle exec rspec ...")

Both the rake and the rspec process load our Rails app which itself requires Bundler as well.

## Reproducible case

Through a long series of iterations I was able to remove almost all of our application and to boil down the problem to this setup:

https://github.com/buehmann/bundler/tree/bundler-bug

Output of `bundle env` is included for both versions used below.

I briefly tried to get `rspec` out of the equation but was not successful.

I added debugging output because the $LOAD_PATH is changed by the call to `Bundler.require` which I didn't expect in this case (and which didn't happen with Bundler v1.12).

After `Bundler.require(:group)` I expect to be able to require other gems not in that group. A direct call to `bundle exec rspec spec/bug_spec.rb` (without additional Bundler layers wrapped around) works like this.

```
➜  banking (bundler-bug) bundle _1.13.1_ exec ./bug
before
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
after
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
bundler: failed to load command: rspec (/Users/buehmann/.rbenv/versions/2.3.1/bin/rspec)
LoadError: cannot load such file -- rake
  /Users/buehmann/dev/banking/spec/bug_spec.rb:9:in `require'
  /Users/buehmann/dev/banking/spec/bug_spec.rb:9:in `<top (required)>'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:100:in `setup'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86:in `run'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
  /Users/buehmann/.rbenv/versions/2.3.1/bin/rspec:22:in `load'
  /Users/buehmann/.rbenv/versions/2.3.1/bin/rspec:22:in `<top (required)>'
```

In contrast with Bundler 1.12:
```
➜  banking (bundler-bug) bundle _1.12.5_ exec ./bug
before
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
after
/Users/buehmann/dev/banking/spec
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-mocks-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.3/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/mysql2-0.4.4
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/site_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin15
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/vendor_ruby
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0
/Users/buehmann/.rbenv/versions/2.3.1/lib/ruby/2.3.0/x86_64-darwin15
No examples found.


Finished in 0.00038 seconds (files took 0.35775 seconds to load)
0 examples, 0 failures
```

**Comment by chrismo** [comment]
Interesting. This would appear to be related to #4992 - though this appears to be a case where the _fix_ for 1.13 for nested bundle exec is causing a problem. Thanks for the details, that should help a lot.

**Comment by chrismo** [comment]
Problem still exists in 1.13.2, and does not appear to be related to #4992.

Looks like this commit is what is triggering this: https://github.com/bundler/bundler/commit/a3718adf29fb63c8cf86719f909cd3fed5f0c022. Since any reset! now undoes the (essential) memoization or @setup between the `#setup` and `#require` calls, the `require` is strictly limited to the group being passed.

You can workaround this for now by including the default group in the require call as well:

`Bundler.require(:group, :default)`

I'm not sure the old behavior was supposed to work as designed vs. just coincidentally worked, so while it's a breaking change, I don't know how to prioritize trying to fix this. @indirect any thoughts?

**Comment by buehmann** [comment]
At least the old behaviour worked as documented (although the docs are not overly precise on that matter): http://bundler.io/v1.13/bundler_setup.html talks about Bundler.setup as being responsible for setting up load paths and Bundler.require as a mere tool for requiring sets of gems.

But even if the new Bundler.require behaviour were correct it would still strike me as odd that there is a difference in behaviour between the following:
```
$ bundle --version                              
Bundler version 1.13.2

$ bundle exec rspec spec/bug_spec.rb # OK
$ bundle exec bundle exec rspec spec/bug_spec.rb # LoadError: cannot load such file -- rake
```

**Comment by buehmann** [comment]
When I turn off the load optimization in "bundle exec", everything's fine:
```
$ bundle config disable_exec_load true 
$ bundle exec bundle exec rspec spec/bug_spec.rb # OK!
$ ./bug # OK!
```

**Comment by buehmann** [comment]
I was able to simplify my case even further: https://github.com/buehmann/bundler/tree/ebc677765d0fab944751a5fbe996fdd99bdfda05

There seem to be two interwoven issues:

* This behaves the same in v1.12.5 and v1.13.2 but it still confuses me:
```
$ cat bug
#!/usr/bin/env ruby
require 'bundler'

Bundler.setup(:default, :group)

Bundler.require(:group)

require 'rake'
$ ./bug
./bug:8:in `require': cannot load such file -- rake (LoadError)
	from ./bug:8:in `<main>'
```
*  When prefixed with one or two "bundle exec"s, the behaviour differs in v1.12.5 and v1.13.2:
```
$ bundle --version
Bundler version 1.12.5
$ ./bug
./bug:8:in `require': cannot load such file -- rake (LoadError)
	from ./bug:8:in `<main>'
$ bundle exec ./bug # OK
$ bundle exec bundle exec ./bug # OK
```
```
$ bundle --version
Bundler version 1.13.2
$ ./bug
./bug:8:in `require': cannot load such file -- rake (LoadError)
	from ./bug:8:in `<main>'
$ bundle exec ./bug # OK
$ bundle exec bundle exec ./bug
bundler: failed to load command: ./bug (./bug)
LoadError: cannot load such file -- rake
  /home/buehmann/devel/fidor/bundler-bug/bug:8:in `require'
  /home/buehmann/devel/fidor/bundler-bug/bug:8:in `<top (required)>'
```

**Comment by monkeyfox** [comment]
Howdy,

Just chiming in to confirm a similar experience to @buehmann, except in my case it was executing rspec through parallel_tests.

Anyhoo, setting the disable_exec_load flag to true fixed my problem as well.

**Comment by JeanMertz** [comment]
Same issue here, using `parallel_tests` to run our Cucumber test suite. For now, `disable_exec_load` is the magic switch.

**Comment by riyengar8** [comment]
FWIW, we ran into this problem as well. Our vector happened to be a task run through capistrano that was (unwittingly to us) getting the nested `bundle exec` behavior. I post this here as it took me a long time to find and realize the relevance of this thread to my problem, so if someone else comes to this the same way perhaps they will find this comment sooner.

The two workarounds mentioned here (changing the require statement of a custom group to `Bundler.setup(:custom_group, :default)`) and `disable_exec_load` both work, but for now we're just sticking to an earlier version of bundler (1.12.6) and following this thread to see what happens.

**Comment by dorongutman** [comment]
are there any updates about this issue ?

**Comment by segiddins** [comment]
@dorongutman if there were any updates, they would've been posted here
