### ISSUE TITLE
NFS shared home directory creates race condition on deploy

### ISSUE THREAD

**Issue by will-in-wi** [bundler/bundler#5021]
We have an NFS mounted home directory for the apache user. When I do a Capistrano deploy, sometimes the error below occurs. The more servers I'm deploying to, the higher the chance of an issue. We retry a couple of times, and eventually it lines up and works.

My guess is that all of the servers are trying to manipulate this file simultaneously.
- What did you do?

I ran the command `/usr/local/rbenv/versions/2.3.0/bin/bundle install --path /var/www/appname/shared/bundle --without dev…
- What did you expect to happen?

I expected Bundler to install.
- What happened instead?

Instead, what happened was the error below.

```
 Error details

     Errno::ESTALE: Stale file handle @ io_fread - /home/apache/.bundle/cache/compact_index/rubygems.org.443.29b0360b93…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `availabl…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remo…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/lazy_specification.rb:58:in `__materiali…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:91:in `block in materialize'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:88:in `map!'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:88:in `materialize'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
       /usr/local/rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `r…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:i…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `sta…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly…
       /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
       /usr/local/rbenv/versions/2.3.0/bin/bundle:22:in `load'
       /usr/local/rbenv/versions/2.3.0/bin/bundle:22:in `<main>'
```

 Environment

   Bundler   1.13.1
   Rubygems  2.6.5
   Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
   GEM_HOME  /var/www/appname/shared/bundle/ruby/2.3.0
   GEM_PATH
   Git       1.7.1

```
   Bundler settings
```

   frozen
     Set for your local app (/var/www/appname/releases/20160926181526/.bundle/config): "1"
   path
     Set for your local app (/var/www/appname/releases/20160926181526/.bundle/config): "/var/www/appname/shared/bundl…
   without
     Set for your local app (/var/www/appname/releases/20160926181526/.bundle/config): "development:test"
   disable_shared_gems
     Set for your local app (/var/www/appname/releases/20160926181526/.bundle/config): true

**Comment by segiddins** [comment]
Can you please share the full stack trace? What you've included in the issue appears to be truncated

**Comment by will-in-wi** [comment]
Sorry about that. The Airbrusshed formatter seems to truncate…

```
Error details

    Errno::ESTALE: Stale file handle @ io_fread - /home/apache/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:85:in `read'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:85:in `read'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:85:in `lines'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:48:in `checksums'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/lazy_specification.rb:58:in `__materialize__'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:91:in `block in materialize'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:88:in `map!'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:88:in `materialize'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
      /usr/local/rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
      /usr/local/rbenv/versions/2.3.0/bin/bundle:22:in `load'
      /usr/local/rbenv/versions/2.3.0/bin/bundle:22:in `<main>'
```

**Comment by will-in-wi** [comment]
Is it possible to through an env variable or something define the location bundler uses for `~/.bundle/cache/compact_index/`?

**Comment by segiddins** [comment]
@will-in-wi at the moment, there isn't

**Comment by will-in-wi** [comment]
@segiddins Do you have any suggestions for where I might start with a patch? It looks like no one is working on this and it is a huge problem for our deployments. Ideally, I could set a custom location for the compact index cache that is server/app specific.

**Comment by segiddins** [comment]
Yeah, that might work, you'd set the cache path based on `Bundler.settings[:compact_index_cache_prefix] || bundler_home.join("cache/compact_index")` or something like that

**Comment by lynnco** [comment]
I'm informally assigning this to you, @will-in-wi !

**Comment by will-in-wi** [comment]
I'm informally going to tackle it! 😄

**Comment by will-in-wi** [comment]
Looks like this _might_ have been fixed by https://github.com/bundler/bundler/pull/5043 and https://github.com/bundler/bundler/pull/4561

I'm working on confirming this…

**Comment by will-in-wi** [comment]
It looks like the above mentioned tickets have fixed this issue. Since only time and a lack of errors will confirm this for me, I'm going to close this issue and reopen it if needed.

Thanks all!

**Comment by segiddins** [comment]
Thanks for the update @will-in-wi !

**Comment by Skeeterdrums** [comment]
@will-in-wi was there any change needed in your deployment to get this setup to work? We're seeing a similar issue when running a `bundle update` from two nodes running at the same time:

```
Errno::ESTALE: Stale file handle @ rb_file_flock - /.gems/ruby/bundler.lock
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/process_lock.rb:10:in `flock'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/process_lock.rb:10:in `block in lock'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/process_lock.rb:9:in `open'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/process_lock.rb:9:in `lock'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/installer.rb:73:in `run'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/installer.rb:25:in `install'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/cli/update.rb:61:in `run'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/cli.rb:280:in `update'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
  /.gems/ruby/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
  /.gems/ruby/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /.gems/ruby/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

My best guess is that we'll need to axe the file mount and use a local (to the job) file store instead.

**Comment by will-in-wi** [comment]
@Skeeterdrums I am no longer at that job and I'm not sure i remember exactly what happened… If I recall correctly, upgrading Bundler fixed it. I know that within a year or two of filing this ticket, we rebuilt our server infrastructure to use per-app users without a shared NFS home directory.

My guess is that your problem is related but different…
