### ISSUE TITLE
    Errno::EINVAL: Invalid argument after Bundle Install

### ISSUE THREAD

**Issue by KelseyDH** [bundler/bundler#5038]
- What did you do?
  
  I ran the command `/usr/local/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what happened was...

Error details

```
Errno::EINVAL: Invalid argument
  /usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/securerandom.rb:56:in `clock_gettime'
  /usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/securerandom.rb:56:in `gen_random'
  /usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/securerandom.rb:99:in `random_bytes'
  /usr/local/Cellar/ruby/2.3.1_1/lib/ruby/2.3.0/securerandom.rb:118:in `hex'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:191:in `user_agent'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:259:in `connection'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:84:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:234:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:234:in `block in fetchers'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:232:in `map'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:232:in `fetchers'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:263:in `block (2 levels) in index'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `block in index'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:258:in `index'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:252:in `resolve'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

Environment

  Bundler   1.13.1
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  /usr/local/lib/ruby/gems/2.3.0
  GEM_PATH  /usr/local/lib/ruby/gems/2.3.0:/Users/USERHOME/.gem/ruby/2.3.0:/usr/local/Cellar/ruby/2.3.1_1/lib/ruby/gems/2.3.0
  Git       2.10.0

```
  Bundler settings
```

  jobs
    Set for the current user (/Users/USERHOME/.bundle/config): "7"
  local.someproject_core
    Set for the current user (/Users/USERHOME/.bundle/config): "/Users/USERHOME/workingspace/someproject/someproject_core"
  local.someproject_read_plugin
    Set for the current user (/Users/USERHOME/.bundle/config): "/Users/USERHOME/workingspace/someproject/someproject_read_plugin"

**Comment by lynnco** [comment]
@KelseyDH this is likely the same issue as https://github.com/rubygems/rubygems/issues/1726#event-809521202

**Comment by segiddins** [comment]
Closing as a duplicat3e of https://github.com/Homebrew/homebrew-core/issues/5413
