### ISSUE TITLE
Error running the tests in Mac os x (Sierra)

### ISSUE THREAD

**Issue by ryanfox1985** [bundler/bundler#5054]
Hello I'm getting these error when I'm running the test:

```
$ rspec ./spec/quality_spec.rb:210
Run options:
  include {:locations=>{"./spec/quality_spec.rb"=>[210]}}
  exclude {:rubygems_master=>true, :git=>"=< 2.8.1", :rubygems=>"=< 2.5.1", :ruby=>"=< 2.3.0", :realworld=>true, :sudo=>true}

The library itself
  does not contain any warnings (FAILED - 1)


Retried examples: 0

Failures:

  1) The library itself does not contain any warnings
     Failure/Error: s.platform = Bundler.local_platform

     NoMethodError:
       undefined method `local_platform' for Bundler:Module
     # ./spec/support/builders.rb:82:in `block (2 levels) in build_repo1'
     # ./spec/support/builders.rb:449:in `block in build_with'
     # ./spec/support/builders.rb:446:in `each'
     # ./spec/support/builders.rb:446:in `build_with'
     # ./spec/support/builders.rb:414:in `build_gem'
     # ./spec/support/builders.rb:81:in `block in build_repo1'
     # ./spec/support/builders.rb:377:in `update_repo'
     # ./spec/support/builders.rb:367:in `build_repo'
     # ./spec/support/builders.rb:19:in `build_repo1'
     # ./spec/spec_helper.rb:97:in `block (2 levels) in <top (required)>'

Finished in 0.23495 seconds (files took 0.32789 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/quality_spec.rb:210 # The library itself does not contain any warnings
```

Is failing this line:
https://github.com/bundler/bundler/blob/master/spec/support/builders.rb#L82

By some reason the method `Bundler.local_platform` is not visible for the test.

Regards!

**Comment by segiddins** [comment]
What commit are you running on? I cannot reproduce this

**Comment by ryanfox1985** [comment]
Hello @segiddins I will write all the output:

```
╰─ git clone https://github.com/bundler/bundler.git
Cloning into 'bundler'...
remote: Counting objects: 62526, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 62526 (delta 12), reused 0 (delta 0), pack-reused 62487
Receiving objects: 100% (62526/62526), 16.01 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (39774/39774), done.
Checking connectivity... done.
╭─ ✓  3289   …/workspace/tmp                                                                                                                                                                                                                                                                                                                                                              2.3.0    17:17:52
╰─ cd bundler
╭─ ✓  3291   …/tmp/bundler    master                                                                                                                                                                                                       2.3.0    17:17:55
╰─ git branch
* master
╭─ ✓  3292   …/tmp/bundler    master                                                                                                                                                                                                       2.3.0    17:18:22
╰─ rspec ./spec/quality_spec.rb:210
installing gems for the tests to use...
gem install 'rack:< 2' 'compact_index:~> 0.11.0' 'sinatra:1.2.7' 'rake:10.0.2' 'builder:2.1.2' 'bundler:1.12.0' fakeweb artifice ruby-graphviz --no-rdoc --no-ri
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: compact_index-0.11.0.gem (100%)
Successfully installed compact_index-0.11.0
Fetching: tilt-1.4.1.gem (100%)
Successfully installed tilt-1.4.1
Fetching: sinatra-1.2.7.gem (100%)
Successfully installed sinatra-1.2.7
Fetching: rake-10.0.2.gem (100%)
Successfully installed rake-10.0.2
Fetching: builder-2.1.2.gem (100%)
Successfully installed builder-2.1.2
Fetching: bundler-1.12.0.gem (100%)
Successfully installed bundler-1.12.0
Fetching: fakeweb-1.3.0.gem (100%)
Successfully installed fakeweb-1.3.0
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: artifice-0.6.gem (100%)
Successfully installed artifice-0.6
Fetching: ruby-graphviz-1.2.2.gem (100%)

You need to install GraphViz (http://graphviz.org/) to use this Gem.

For more information about Ruby-Graphviz :
* Doc : http://rdoc.info/projects/glejeune/Ruby-Graphviz
* Sources : http://github.com/glejeune/Ruby-Graphviz
* Mailing List : http://groups.google.com/group/ruby-graphviz

Last (important) changes :
Ruby-Graphviz no longer supports Ruby < 1.9.3

Successfully installed ruby-graphviz-1.2.2
11 gems installed
Run options:
  include {:locations=>{"./spec/quality_spec.rb"=>[210]}}
  exclude {:rubygems_master=>true, :git=>"=< 2.8.1", :rubygems=>"=< 2.5.1", :ruby=>"=< 2.3.0", :realworld=>true, :sudo=>true}

The library itself
  does not contain any warnings (FAILED - 1)


Retried examples: 0

Failures:

  1) The library itself does not contain any warnings
     Failure/Error: s.platform = Bundler.local_platform

     NoMethodError:
       undefined method `local_platform' for Bundler:Module
     # ./spec/support/builders.rb:82:in `block (2 levels) in build_repo1'
     # ./spec/support/builders.rb:449:in `block in build_with'
     # ./spec/support/builders.rb:446:in `each'
     # ./spec/support/builders.rb:446:in `build_with'
     # ./spec/support/builders.rb:414:in `build_gem'
     # ./spec/support/builders.rb:81:in `block in build_repo1'
     # ./spec/support/builders.rb:377:in `update_repo'
     # ./spec/support/builders.rb:367:in `build_repo'
     # ./spec/support/builders.rb:19:in `build_repo1'
     # ./spec/spec_helper.rb:97:in `block (2 levels) in <top (required)>'

Finished in 0.30105 seconds (files took 14.8 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/quality_spec.rb:210 # The library itself does not contain any warnings
``` 

Regards.

**Comment by ryanfox1985** [comment]
I got this error:

```
╰─ bin/rspec ./spec/quality_spec.rb:210
/Users/fox/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'automatiek' (~> 0.1.0) among 353 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/fox/.rvm/gems/ruby-2.3.0:/Users/fox/.rvm/gems/ruby-2.3.0@global', execute `gem env` for more information
        from /Users/fox/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
        from /Users/fox/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from bin/rspec:10:in `block in <main>'
        from bin/rspec:9:in `each'
        from bin/rspec:9:in `<main>'
```

**Comment by segiddins** [comment]
Have you run `bin/rake spec:deps`?

**Comment by ryanfox1985** [comment]
Hi, it's working with:

```
rake spec:deps
rake spec

....

Finished in 30 minutes 14 seconds (files took 1.47 seconds to load)
2108 examples, 0 failures, 9 pending
```

There is a way to execute one specific test like `rspec ./spec/quality_spec.rb:210`?

Regards.

**Comment by segiddins** [comment]
`bin/rspec spec/quality_spec` should do it

**Comment by lynnco** [comment]
@ryanfox1985 looks like your issue is resolved?
