### ISSUE TITLE
Zlib::GzipFile::Error: not in gzip format

### ISSUE THREAD

**Issue by jaredbeck** [bundler/bundler#5073]
```
bundle update
Fetching git@github.com:josevalim/inherited_resources.git
Fetching git@github.com:textacular/textacular.git
Fetching gem metadata from https://rubygems.org/...
Retrying fetcher due to error (2/4): Zlib::GzipFile::Error not in gzip format.
Retrying fetcher due to error (3/4): Zlib::GzipFile::Error not in gzip format.
Retrying fetcher due to error (4/4): Zlib::GzipFile::Error not in gzip format.
```

- What did you do?

  I ran the command `/Users/jared/.rbenv/versions/2.3.1/bin/bundle update`

- What did you expect to happen?

  I expected it to update

- What happened instead?

  Got Zlib::GzipFile::Error

```
Error details

    Zlib::GzipFile::Error: not in gzip format
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:47:in `initialize'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:47:in `new'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:47:in `block in update'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:72:in `update_info'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:43:in `block in dependencies'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/fetcher/compact_index.rb:86:in `block (3 levels) in compact_index_client'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/worker.rb:65:in `apply_func'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/worker.rb:60:in `block in process_queue'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/worker.rb:57:in `loop'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/worker.rb:57:in `process_queue'
      /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment
      
  Bundler   1.13.2
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  GEM_PATH  /Users/jared/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0:/Users/jared/.gem/ruby/2.3.0
  Git       2.10.1
      
      Bundler settings
      
  ignore_messages.httparty
    Set for the current user (/Users/jared/.bundle/config): "true"
  ignore_messages
    Set for the current user (/Users/jared/.bundle/config): "true"
```

**Comment by jaredbeck** [comment]
Given that:

1. this error occurs in compact_index_client/updater.rb
1. it occurs after `Fetching gem metadata from https://rubygems.org/...`

one hypothesis could be that there is an issue with rubygems.org. Their [status page][1] says all is well, but maybe they made some change?

[1]: https://status.rubygems.org/

**Comment by jeffrafter** [comment]
@jaredbeck I thought the same, there have been some recent updates to the stack... but this was all working well recently.

**Comment by jeffrafter** [comment]
Workaround: I was trying to install the stripe gem. 

1. `gem install stripe`
2. bundle install --local

Works for now!

**Comment by lloydwatkin** [comment]
Just seems to have resolved itself now for me.

**Comment by blimmer** [comment]
This is still broken for me for some reason.

**Comment by ryaan-anthony** [comment]
I'm having this issue too. --local is not what we want.

--local
    Do not attempt to connect to rubygems.org, instead using just the 
    gems located in vendor/cache. Note that if a more appropriate 
    platform-specific gem exists on rubygems.org, this will bypass 
    the normal lookup.

**Comment by npepinpe** [comment]
I just started having issues with this; could be a rubygems.org related issue? It doesn't happen consistently.

**Comment by woqer** [comment]
Same issue here... Still the status page reports nothing https://status.rubygems.org/

**Comment by jaredbeck** [comment]
rubygems.org recently introduced fast.ly as a CDN. There might be an issue with gzip on fast.ly or with their configuration. All wild guessing on my part. I've pinged @dwradcliffe on twitter, maybe he knows.

**Comment by marrrt** [comment]
Happens consistently for me.

**Comment by lloydwatkin** [comment]
Maybe my caches expired and so I get fresh data. Could you try from another machine?

**Comment by tomg65** [comment]
Same issue.... on different machines

**Comment by chadwtaylor** [comment]
+1

**Comment by inestyne** [comment]
+1, holey mole!!

**Comment by inestyne** [comment]
-1, It's back!!

**Comment by dwradcliffe** [comment]
Should be working fine now. We were rolling out some changes on the servers and something is not right with gzip, as you all saw. Sorry for the troubles :(

**Comment by chadwtaylor** [comment]
-1, All good now, thanks.

**Comment by jaredbeck** [comment]
Closing per David's comment.
