### ISSUE TITLE
bundle update 

### ISSUE THREAD

**Issue by madhu-b** [bundler/bundler#5103]
Liftoffs-MacBook-Pro:Mumo liftoff$ bundle update
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/usr/local/bin/bundle update`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what happened was...

Error details

```
Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/1w/z2m7z21s455g8llk2yznp81h0000gn/T/bundler-compact-index-20161020-18074-1y1ym6j/versions, /Users/liftoff/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/fetcher/compact_index.rb:67:in `available?'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/fetcher.rb:157:in `use_api'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/source/rubygems.rb:332:in `select'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/index.rb:10:in `build'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/source/rubygems.rb:336:in `remote_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/source/rubygems.rb:83:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:261:in `block (2 levels) in index'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:259:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:259:in `block in index'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/index.rb:10:in `build'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:256:in `index'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:250:in `resolve'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:174:in `specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/definition.rb:162:in `resolve_remotely!'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/installer.rb:225:in `resolve_if_need'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/installer.rb:78:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/installer.rb:24:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/update.rb:61:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:228:in `update'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:11:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/exe/bundle:34:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/exe/bundle:26:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

Environment

  Bundler   1.13.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  /usr/local/lib/ruby/gems/2.3.0
  GEM_PATH  /usr/local/lib/ruby/gems/2.3.0:/Users/liftoff/.gem/ruby/2.3.0:/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/gems/2.3.0
  Git       2.7.4 (Apple Git-66)
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by lynnco** [comment]
@madhu-b Look into how the other issues with permission errors were resolved https://github.com/bundler/bundler/search?q=Errno+EACCES+Permission+denied&type=Issues&utf8=%E2%9C%93. We'll be improving the permissions handling for Bundler 1.14

**Comment by segiddins** [comment]
@lynnco that error will also be handled by `#filesystem_access` on master, as an `EACCESS`
