### ISSUE TITLE
Your bundler is locked to byebug (8.2.2)

### ISSUE THREAD

**Issue by bgvo** [bundler/bundler#5122]
Something strange is happening or I just don't know how to interpret the output right. Whenever I update a gem this error comes up. Just before getting this error I was having the same one but with byebug (8.2.2). How can I get rid of this? 

```
/var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to byebug (8.2.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of byebug (8.2.5) has removed it. You'll need to update your bundle to a different version of byebug (8.2.5) that hasn't been removed in order to install. (Bundler::GemNotFound)
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:173:in `specs'
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:233:in `specs_for'
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/definition.rb:222:in `requested_specs'
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/runtime.rb:118:in `block in definition_method'
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/runtime.rb:19:in `setup'
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler.rb:99:in `setup'
    from /var/lib/gems/2.3.0/gems/bundler-1.13.4/lib/bundler/setup.rb:20:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Here is the output of running `bundle install` just before getting the error:

```
root@hybrid:/home/gemssy/gemfeed/data-gatherer# bundle update byebug
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.0
Using rack 1.6.4
Using mime-types 2.99
Using arel 6.0.3
Using addressable 2.3.8
Using ruby-hmac 0.4.0
Using awesome_print 1.6.1
Using bson 4.0.1
Using bundler 1.13.4
Installing byebug 8.2.5 (was 8.2.2) with native extensions
Using timers 1.1.0
Using chronic 0.10.2
Using coderay 1.1.0
Using concurrent-ruby 1.0.0
Using connection_pool 2.2.0
Using diff-lcs 1.2.5
Using thor 0.19.1
Using multi_xml 0.5.5
Using method_source 0.8.2
Using mimemagic 0.3.0
Using origin 2.2.0
Using stringex 2.5.2
Using redis 3.3.1
Using retryable 1.3.6
Using rspec-support 3.3.0
Using tilt 2.0.2
Using rdoc 4.2.2
Using tzinfo 1.2.2
Using nokogiri 1.6.3.1
Using rack-test 0.6.3
Using rack-protection 1.5.3
Using mail 2.6.3
Using mongo 2.2.2
Using celluloid 0.15.2
Using whenever 0.9.4
Using sprockets 3.5.2
Using foreman 0.78.0
Using httparty 0.13.7
Using pry 0.10.3 from https://github.com/pry/pry (at master@ac2e46a)
Using redis-namespace 1.5.2
Using rspec-core 3.3.2
Using rspec-expectations 3.3.1
Using rspec-mocks 3.3.2
Using sdoc 0.4.1
Using activesupport 4.2.1
Using loofah 2.0.3
Using amazon-ecs 2.4.0
Using aws-sdk-v1 1.53.0
Using saxerator 0.9.5
Using sinatra 1.4.7
Using pry-byebug 3.3.0
Using pry-rails 0.3.4
Using sidekiq 3.2.5
Using rspec 3.3.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.1
Using climate_control 0.0.3
Using rails-html-sanitizer 1.0.3
Using aws-sdk 1.53.0
Using rails-dom-testing 1.0.7
Using activejob 4.2.1
Using activerecord 4.2.1
Using mongoid 5.0.2
Using cocaine 0.5.8
Using actionview 4.2.1
Using mongoid-compatibility 0.3.1
Using paperclip 4.3.5
Using actionpack 4.2.1
Using mongoid-slug 5.1.1
Using mongoid-paperclip 0.0.10
Using paperclip-mimemagic 0.0.1 from https://github.com/miyagawa/paperclip-mimemagic.git (at master@bcaa889)
Using actionmailer 4.2.1
Using railties 4.2.1
Using sprockets-rails 3.0.1
Using rails 4.2.1
Bundle updated!
```

As you see, `byebug` was installed. But then not seen by Bundler.

**Comment by segiddins** [comment]
This should have a more helpful error message soon. In the meantime, run `bundle install` first and then you should be able to use that gem

**Comment by lynnco** [comment]
@bgvo

> This should have a more helpful error message soon. In the meantime, run bundle install first and then you should be able to use that gem

**Comment by bgvo** [comment]
That won't fix the issue. Same message would keep appearing.

**Comment by indirect** [comment]
Please follow the steps in [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md), and report back with the requested information if that doesn't solve your problem. Thanks!

**Comment by JochenFromm** [comment]
I am having the same problem for a different gem during a capistrano deploy, stack trace below, for bundler `1.13.2`. 

```
*** [err :: my-app] rake aborted!
*** [err :: my-app] Bundler::GemNotFound: Your bundle is locked to record_tag_helper (1.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of record_tag_helper (1.0.0) has removed it. You'll need to update your bundle to a different version of record_tag_helper (1.0.0) that hasn't been removed in order to install.
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/definition.rb:179:in `rescue in specs'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/definition.rb:173:in `specs'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/definition.rb:233:in `specs_for'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/definition.rb:222:in `requested_specs'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/runtime.rb:118:in `block in definition_method'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/runtime.rb:19:in `setup'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler.rb:99:in `setup'
*** [err :: my-app] /usr/local/rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/setup.rb:20:in `<top (required)>'
```

**Comment by segiddins** [comment]
Ping on the information requested from [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md) ?

**Comment by segiddins** [comment]
Closing due to lack of response.
