### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by tipyn** [bundler/bundler#5134]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/usr/local/bin/bundle install --deployment --verbose --without test --without development`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what happened was...

Error details

```
Errno::ENOSPC: No space left on device @ fptr_finalize - /var/www/discourse/.bundle/config
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:248:in `close'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:248:in `open'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:248:in `open'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:248:in `block in set_key'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:245:in `set_key'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:77:in `[]='
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:230:in `normalize_settings'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:54:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

Environment

  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  Git       2.7.4

```
  Bundler settings
```

  frozen
    Set for your local app (/var/www/discourse/.bundle/config): "1"
  path
    Set for your local app (/var/www/discourse/.bundle/config): "vendor/bundle"
  without
    Set for your local app (/var/www/discourse/.bundle/config): "development"
  disable_shared_gems
    Set for your local app (/var/www/discourse/.bundle/config): true
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
We should handle `Errno::ENOSPC` in `filesystem_access`

**Comment by tipyn** [comment]
running ./launcher cleanup seemed to fix this.

**Comment by lynnco** [comment]
@tipyn so this issue can be closed?

(@segiddins's comment notwithstanding)
