### ISSUE TITLE
NoMethodError: undefined method `to_specs' for nil:NilClass

### ISSUE THREAD

**Issue by jayaram2701** [bundler/bundler#5140]
Here the trace

```
/Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:201:in `map'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:201:in `start'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/resolver.rb:181:in `resolve'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/user/.rvm/gems/ruby-2.2.3/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/user/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `load'
      /Users/user/.rvm/gems/ruby-2.2.3/bin/bundle:23:in `<main>'
      /Users/user/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
      /Users/user/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lynnco** [comment]
@jayaram2701 please provide the additional information described in: https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems

**Comment by jayaram2701** [comment]
Yeah, I found out the issue, its the problem with the latest bundler which corrupts the lock file. Have used older version and this got fixed.

Thanks Lynnco

**Comment by samof76** [comment]
Even I faced this issue today and resolved it as per @jayaram2701 's guidance. But I suppose this means the issue would need to be kept open.
