### ISSUE TITLE
`bundle install` causes SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by derekameer** [bundler/bundler#5146]
- What did you do?
  I went through the sharetribe installation process, from https://github.com/sharetribe/sharetribe:
```
git clone git://github.com/sharetribe/sharetribe.git
cd sharetribe
git checkout latest
```
  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install the required gems

- What happened instead?

  Instead, what happened was a SystemStackError: stack level too deep

Error details
```
    SystemStackError: stack level too deep
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1511:in `rescue in add_bindir'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1503:in `add_bindir'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:358:in `files'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:1260:in `remove_unresolved_default_spec'
      
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:45:in `require'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:424:in `gem'
      <Repetition of above two lines many times>
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:46:in `require'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:188:in `install'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:20:in `dispatch'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:11:in `start'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:105:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:22:in `load'
      /usr/local/bin/bundle:22:in `<main>'
```
Environment

  Bundler   1.13.6
  Rubygems  2.6.8
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
  Git       2.9.3 (Apple Git-75)
  Platform  x86_64-darwin-16
  OpenSSL   OpenSSL 1.0.2j  26 Sep 2016

**Comment by derekameer** [comment]
I'm a bit new to Ruby...turns out I should use RVM and Ruby 2.3.1 (*without* p112) instead of the above OS version. Bundler works as it should with Ruby 2.3.1
