### ISSUE TITLE
 An established connection was aborted by the software in your host machine. - SSL_connect

### ISSUE THREAD

**Issue by rajcybage** [bundler/bundler#5158]
```````````
- What did you do?

  I ran the command `C:/RailsInstaller/Ruby2.2.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ECONNABORTED: An established connection was aborted by the software in your host machine. - SSL_connect
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:858:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/net/http/persistent.rb:700:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/net/http/persistent.rb:631:in `connection_for'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/net/http/persistent.rb:994:in `request'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/downloader.rb:48:in `request'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/downloader.rb:16:in `fetch'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:81:in `block in compact_index_client'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:42:in `call'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:42:in `block in update'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'

```````````````

My Gemfile consist

``````
source 'http://rubygems.org'

ruby File.read('.ruby-version').strip

# gems that have rails engines are are always needed
group :preload do
  gem 'rails', '5.0.0.1'
  gem 'dotenv'
  gem 'sse-rails-engine'
  gem 'connection_pool'

  # AR extensions
  gem 'goldiloader'
  gem 'kaminari', '~> 0.17.0'
  gem 'active_model_serializers'
  gem 'paper_trail'
  gem 'soft_deletion'
  gem 'doorkeeper'

  # Logging
  gem 'lograge'
  gem 'logstash-event'
end
``````````````````````

**Comment by lynnco** [comment]
@rajcybage from the title, I am fairly confident that you are experiencing internet issues not directly related to bundler. Issues of the "turn it off and then back on again" sort. 

So I'm going to close this issue, but will re-open it if required.
