### ISSUE TITLE
`bundle gem GEMNAME.gemspec` gives wild stacktrace

### ISSUE THREAD

**Issue by joallard** [bundler/bundler#5184]
- What did you do?

  I ran the command `bundle gem whos.gemspec`

- What did you expect to happen?

  I expected Bundler to... build the gem?

- What happened instead?

  Instead, what happened was... Bundler did not build the gem ;)

Instead, I get an uncaught exception and a stacktrace 😄 

Error details

```
    NameError: wrong constant name Whos.gemspec
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/gem.rb:204:in `const_defined?'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/gem.rb:204:in `block in ensure_safe_gem_name'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/gem.rb:204:in `each'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/gem.rb:204:in `inject'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/gem.rb:204:in `ensure_safe_gem_name'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/gem.rb:49:in `run'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:413:in `gem'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/jon/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
      /Users/jon/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

#### Environment

  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  Git       2.10.2

It's probably a stupid error on my part somewhere, but maybe this could have been caught and turned into a friendlier error message? Looking at the stack trace, it's not really clear what to fix in the gem. Hmm...

For reference, here's the gem:
https://github.com/joallard/whos

**Comment by segiddins** [comment]
try `bundle gem whos` instead, but we definitely should give a better error message

**Comment by joallard** [comment]
Ouch.

Yes please haha!

**Comment by joallard** [comment]
Wait no, running `bundle gem whos` creates another gem `whos` inside of the gem dir.

**Comment by segiddins** [comment]
yeah, `bundle gem` creates a new gem http://bundler.io/v1.13/man/bundle-gem.1.html

**Comment by joallard** [comment]
Okay, I was looking for `gem build`, I should clearly learn to read docs. (Got mixed up between Bundler and Gem commands)
