### ISSUE TITLE
Error using on rubinius

### ISSUE THREAD

**Issue by LTheGreats** [bundler/bundler#5196]
I ran the command `/home/user/rubinius/gems/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to to install the gem dependencies.

- What happened instead?

  Instead, I got a big error.

Error details

    Rubinius::ObjectBoundsExceededError: Tuple::at_prim: index 3 out of bounds for size 3
      core/hash.rb:728:in `include? (key?)'
      /home/user/rubinius/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:185:in `include?'
      /home/user/rubinius/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:237:in `add?'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `dependencies'
      core/proc.rb:20:in `call'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `compact_index_client'
      core/proc.rb:20:in `call'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `process_queue'
      core/kernel.rb:585:in `loop'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
      /home/user/rubinius/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `initialize'
      core/proc.rb:20:in `call'

Environment
      
  Bundler   1.13.6
  Rubygems  2.6.6
  Ruby      2.3.1p0 (2016-11-17 revision 0) [x86_64-linux-gnu]
  GEM_HOME  /home/user/rubinius/gems
  GEM_PATH  /home/user/rubinius/gems:/home/user/.gem/rbx/2.3
  Git       2.7.4

**Comment by LTheGreats** [comment]
Never mind, I found out that this happened because I was using rbenv
