### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by honghaoli** [bundler/bundler#5206]
I never used Jekyll before.
I just tried the simplest case shown on the website
https://jekyllrb.com/docs/quickstart/
`$ gem install jekyll bundler`
`$ jekyll new myblog`

There are lots of similar error, but I cannot find any solutions.

The error templates runs for >8000 lines, I only include the head and tail.

`--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/honghaoli/.rvm/rubies/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    SystemStackError: stack level too deep
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1506:in `block in add_bindir'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1506:in `map'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1506:in `add_bindir'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:358:in `files'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:1260:in `remove_unresolved_default_spec'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:45:in `require'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:415:in `gem'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:46:in `require'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:415:in `gem'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:46:in `require'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:415:in `gem'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:46:in `require'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:415:in `gem'`

...

after > 8000 lines:

`      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:20:in `dispatch'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:11:in `start'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:105:in `with_friendly_errors'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/bin/bundle:22:in `load'
      /Users/honghaoli/.rvm/rubies/ruby-2.3.0/bin/bundle:22:in `<main>'
      /Users/honghaoli/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
      /Users/honghaoli/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.6.8
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
  GEM_HOME  /Users/honghaoli/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/honghaoli/.rvm/gems/ruby-2.3.0:/Users/honghaoli/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.9.3 (Apple Git-75)
  Platform  x86_64-darwin-16
  OpenSSL   OpenSSL 1.0.2j  26 Sep 2016
  rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------
`

**Comment by honghaoli** [comment]
After uninstalling everything and reinstall, now it works. I guess I somehow messed up with bundler.
