### ISSUE TITLE
Unable to generate new gems

### ISSUE THREAD

**Issue by qubitrenegade** [bundler/bundler#5226]
I was getting an error when running `bundle gem test` so I `rm -rf ~/.bundle`

When I run `bundle gem test`, I get the error: `TypeError: no implicit conversion from nil to integer`

I am running as root to obfuscate specifics about my system (namely usernames and homedir layout), this same error occurs when run as my user account.

I am using the most recent ChefDK and included ruby utilities, such as Bundler.

What would cause this?  I've never had this issue with Bundler before, and we're using the same version of ChefDK across the enterprise.

Thanks!

```
# bundle gem test
Creating gem 'test'...
Do you want to generate tests with your gem?
Type 'rspec' or 'minitest' to generate those test files now and in the future. rspec/minitest/(none): rspec
Do you want to license your code permissively under the MIT license?
This means that any other developer or company will be legally allowed to use your code for free as long as they admit you created it. You can read more about the MIT license at http://choosealicense.com/licenses/mit. y/(n): y
MIT License enabled in config
Do you want to include a code of conduct in gems you generate?
C--- ERROR REPORT TEMPLATE -------------------------------------------------------efer collaborative, safe spaces. You can read more about the c- What did you do?contributor-covenant.org. Having a code of conduct means agreeing to the responsibility of enforcing it, so be sure that you are prepared to do that. Be sure that your email address is specified as a contact in the generated code of conduct so that people know who to co  I ran the command `/opt/chefdk/embedded/bin/bundle gem test`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    TypeError: no implicit conversion from nil to integer
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:2742:in `[]'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:2742:in `update_line'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:3542:in `rl_redisplay'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:3960:in `readline_internal_setup'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:4807:in `readline_internal'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:4830:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.3/lib/readline.rb:45:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/line_editor/readline.rb:20:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/line_editor.rb:7:in `readline'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:395:in `ask_simply'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:68:in `ask'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:111:in `yes?'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/ui/shell.rb:56:in `yes?'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/gem.rb:155:in `ask_and_set'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/gem.rb:100:in `run'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:384:in `gem'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /opt/chefdk/embedded/bin/bundle:22:in `load'
      /opt/chefdk/embedded/bin/bundle:22:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.6.7
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /root/.chefdk/gem/ruby/2.3.0
  GEM_PATH  /root/.chefdk/gem/ruby/2.3.0:/opt/chefdk/embedded/lib/ruby/gems/2.3.0
  Git       1.7.1

      Bundler settings

  gem.test
    Set for the current user (/root/.bundle/config): "rspec"
  gem.mit
    Set for the current user (/root/.bundle/config): true
  orig_path
    Set via BUNDLE_ORIG_PATH: "/root/.gvm/vertx/current/bin:/root/.gvm/springboot/current/bin:/root/.gvm/lazybones/current/bin:/root/.gvm/jbossforge/current/bin:/root/.gvm/jbake/current/bin:/root/.gvm/groovyserv/current/bin:/root/.gvm/groovy/current/bin:/root/.gvm/griffon/current/bin:/root/.gvm/grails/current/bin:/root/.gvm/gradle/current/bin:/root/.gvm/glide/current/bin:/root/.gvm/gaiden/current/bin:/root/.gvm/crash/current/bin:/root/.gvm/asciidoctorj/current/bin:/opt/chefdk/bin:/root/.chefdk/gem/ruby/2.3.0/bin:/opt/chefdk/embedded/bin:/opt/chefdk/bin:/root/.chefdk/gem/ruby/2.3.0/bin:/opt/chefdk/embedded/bin:/opt/terraform:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/chefdk/gitbin:/opt/packer:/opt/chefdk/gitbin:/root/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/root/.chefdk/gem/ruby/2.3.0:/opt/chefdk/embedded/lib/ruby/gems/2.3.0"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=no+implicit+conversion+from+nil+to+integer&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

**Comment by segiddins** [comment]
This looks to actually be an issue with readline:/

**Comment by segiddins** [comment]
Looks like the same thing as https://github.com/ConnorAtherton/rb-readline/issues/120#issuecomment-227172620, I recommend you open up an issue or PR on https://github.com/ConnorAtherton/rb-readline -- they're responsible for the code that's failing here.
