### ISSUE TITLE
Exception when debugging Calabash tests

### ISSUE THREAD

**Issue by nyarlathotep77** [bundler/bundler#5234]
- What did you do?

  I ran the command `~/.rvm/gems/ruby-2.3.1/bin/bundle exec calabash-android run myapp.apk -p android`

- What did you expect to happen?
  I expected the debugger session to start.

- What happened instead?
  Instead, what happened was...

Error details

```
    NoMethodError: undefined method `close' for nil:NilClass
Did you mean?  clone
      (eval):6:in `exec'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:52:in `kernel_exec'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:33:in `run'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
     ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      ~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      ~/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
      ~/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
     ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
      ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Environment

```      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  ~/.rvm/gems/ruby-2.3.1
  GEM_PATH  ~/.rvm/gems/ruby-2.3.1:~/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.9.3 (Apple Git-75)
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  bin_path
    Set via BUNDLE_BIN_PATH: "~/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "~/dev/workspace/everylife-git/e2e/Gemfile"
```

**Comment by hmistry** [comment]
Not sure what's causing this error but I'm no expert. Does calabash work without using `bundle exec`?

**Comment by segiddins** [comment]
It seems to be failing in `Kernel.exec` which is quite odd

**Comment by colby-swandale** [comment]
ping @nyarlathotep77 is this still a problem on the latest release of bundler?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
