### ISSUE TITLE
uninitialized constant Bundler  Fetcher  Downloader  URICredentialsFilter

### ISSUE THREAD

**Issue by cyril-lemaire** [bundler/bundler#5253]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/alshock/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install my rails project dependencies (rails 5.0 ruby 2.3, dependencies listed below)

- What happened instead?

  Instead, what happened was this bug. The bundler failed to install and told me to report this issue.

Error details

```
    NameError: uninitialized constant Bundler::Fetcher::Downloader::URICredentialsFilter
Did you mean?  Bundler::URICredentialsFilter
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:61:in `rescue in request'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:41:in `request'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:16:in `fetch'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:115:in `call'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:42:in `block in update'
      /home/alshock/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `block in dependencies'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `block (3 levels) in compact_index_client'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `block in process_queue'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `loop'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
      /home/alshock/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

```

Environment
      
```
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/alshock/.rvm/gems/ruby-2.3.0
  GEM_PATH  /home/alshock/.rvm/gems/ruby-2.3.0:/home/alshock/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.7.4
  rubygems-bundler (1.4.4)
```
--- TEMPLATE END ----------------------------------------------------------------

List of dependencies used:
```
Gem actioncable-5.0.0.1
  actionpack (= 5.0.0.1)
  blade (~> 0.5.1, development)
  nio4r (~> 1.2)
  websocket-driver (~> 0.6.1)

Gem actionmailer-5.0.0.1
  actionpack (= 5.0.0.1)
  actionview (= 5.0.0.1)
  activejob (= 5.0.0.1)
  mail (>= 2.5.4, ~> 2.5)
  rails-dom-testing (~> 2.0)

Gem actionpack-5.0.0.1
  actionview (= 5.0.0.1)
  activemodel (= 5.0.0.1, development)
  activesupport (= 5.0.0.1)
  rack (~> 2.0)
  rack-test (~> 0.6.3)
  rails-dom-testing (~> 2.0)
  rails-html-sanitizer (>= 1.0.2, ~> 1.0)

Gem actionview-5.0.0.1
  actionpack (= 5.0.0.1, development)
  activemodel (= 5.0.0.1, development)
  activesupport (= 5.0.0.1)
  builder (~> 3.1)
  erubis (~> 2.7.0)
  rails-dom-testing (~> 2.0)
  rails-html-sanitizer (>= 1.0.2, ~> 1.0)

Gem activejob-5.0.0.1
  activesupport (= 5.0.0.1)
  globalid (>= 0.3.6)

Gem activemodel-5.0.0.1
  activesupport (= 5.0.0.1)

Gem activerecord-5.0.0.1
  activemodel (= 5.0.0.1)
  activesupport (= 5.0.0.1)
  arel (~> 7.0)

Gem activesupport-5.0.0.1
  concurrent-ruby (>= 1.0.2, ~> 1.0)
  i18n (~> 0.7)
  minitest (~> 5.1)
  tzinfo (~> 1.1)

Gem arel-7.1.4
  minitest (~> 5.4, development)
  rake (>= 0, development)
  rdoc (~> 4.0, development)

Gem bcrypt-3.1.11
  rake-compiler (~> 0.9.2, development)
  rdoc (~> 3.12, development)
  rspec (>= 3, development)

Gem bigdecimal-1.2.8

Gem builder-3.2.2

Gem bundler-1.13.6
  automatiek (~> 0.1.0, development)
  mustache (= 0.99.6, development)
  rake (~> 10.0, development)
  rdiscount (~> 2.2, development)
  ronn (~> 0.7.3, development)
  rspec (~> 3.5, development)

Gem bundler-unload-1.0.2
  bundler (>= 0, development)

Gem byebug-9.0.6
  bundler (~> 1.7, development)

Gem coderay-1.1.1

Gem coffee-rails-4.2.1
  coffee-script (>= 2.2.0)
  railties (< 5.2.x, >= 4.0.0)

Gem coffee-script-2.4.1
  coffee-script-source (>= 0)
  execjs (>= 0)
  json (>= 0, development)
  rake (>= 0, development)

Gem coffee-script-source-1.10.0

Gem coffee-script-source-1.11.1

Gem concurrent-ruby-1.0.2

Gem debug_inspector-0.0.2

Gem devise-4.2.0
  bcrypt (~> 3.0)
  orm_adapter (~> 0.1)
  railties (< 5.1, >= 4.1.0)
  responders (>= 0)
  warden (~> 1.2.3)

Gem did_you_mean-1.0.0
  bundler (~> 1.5, development)
  minitest (>= 0, development)
  rake (>= 0, development)

Gem erubis-2.7.0

Gem execjs-2.7.0
  rake (>= 0, development)

Gem executable-hooks-1.3.2
  tf (>= 0, development)

Gem ffi-1.9.14
  rake (~> 10.1, development)
  rake-compiler (~> 0.9, development)
  rake-compiler-dock (~> 0.5.2, development)
  rspec (~> 2.14.1, development)
  rubygems-tasks (~> 0.2.4, development)

Gem gem-wrappers-1.2.7
  minitest (>= 0, development)
  rake (>= 0, development)

Gem globalid-0.3.7
  activesupport (>= 4.1.0)
  rake (>= 0, development)

Gem i18n-0.7.0

Gem io-console-0.4.5

Gem jbuilder-2.6.0
  activesupport (< 5.1, >= 3.0.0)
  multi_json (~> 1.2)

Gem jbuilder-2.6.1
  activesupport (< 5.1, >= 3.0.0)
  multi_json (~> 1.2)

Gem jquery-rails-4.2.1
  rails-dom-testing (< 3, >= 1)
  railties (>= 4.2.0)
  thor (< 2.0, >= 0.14)

Gem json-1.8.3

Gem listen-3.0.8
  bundler (>= 1.3.5, development)
  rb-fsevent (>= 0.9.4, ~> 0.9)
  rb-inotify (>= 0.9.7, ~> 0.9)

Gem loofah-2.0.3
  hoe (~> 3.13, development)
  hoe-bundler (>= 0, development)
  hoe-debugging (>= 0, development)
  hoe-gemspec (>= 0, development)
  hoe-git (>= 0, development)
  json (>= 0, development)
  minitest (~> 2.2, development)
  nokogiri (>= 1.5.9)
  rake (>= 0.8, development)
  rdoc (~> 4.0, development)
  rr (~> 1.1.0, development)

Gem mail-2.6.4
  bundler (>= 1.0.3, development)
  mime-types (< 4, >= 1.16)
  rake (> 0.8.7, development)
  rdoc (>= 0, development)
  rspec (~> 3.0, development)

Gem method_source-0.8.2
  bacon (~> 1.1.0, development)
  rake (~> 0.9, development)

Gem mime-types-3.1
  fivemat (~> 1.3, development)
  hoe (~> 3.15, development)
  hoe-doofus (~> 1.0, development)
  hoe-gemspec2 (~> 1.1, development)
  hoe-git (~> 1.6, development)
  hoe-rubygems (~> 1.0, development)
  hoe-travis (~> 1.2, development)
  mime-types-data (~> 3.2015)
  minitest (~> 5.9, development)
  minitest-autotest (~> 1.0, development)
  minitest-bonus-assertions (~> 2.0, development)
  minitest-focus (~> 1.0, development)
  minitest-hooks (~> 1.4, development)
  minitest-rg (~> 5.2, development)
  rake (~> 10.0, development)
  rdoc (~> 4.0, development)
  simplecov (~> 0.7, development)

Gem mime-types-data-3.2016.0521
  hoe (~> 3.15, development)
  hoe-doofus (~> 1.0, development)
  hoe-gemspec2 (~> 1.1, development)
  hoe-git (~> 1.6, development)
  hoe-rubygems (~> 1.0, development)
  mime-types (~> 3.0, development)
  nokogiri (~> 1.6, development)
  rake (~> 10.0, development)
  rdoc (~> 4.0, development)

Gem mini_magick-4.6.0
  posix-spawn (>= 0, development)
  rake (>= 0, development)
  rspec (~> 3.1.0, development)

Gem mini_portile2-2.1.0
  bundler (~> 1.7, development)
  minitar (~> 0.5.4, development)
  minitest (~> 5.8.0, development)
  minitest-hooks (~> 1.4.0, development)
  rake (~> 10.0, development)

Gem minitest-5.8.3
  hoe (~> 3.14, development)
  rdoc (~> 4.0, development)

Gem minitest-5.9.1
  hoe (~> 3.15, development)
  rdoc (~> 4.0, development)

Gem minitest-5.10.0
  hoe (~> 3.15, development)
  rdoc (~> 4.0, development)

Gem multi_json-1.12.1
  bundler (~> 1.0, development)

Gem mysql2-0.4.5

Gem net-telnet-0.1.1
  bundler (~> 1.9, development)
  rake (~> 10.0, development)

Gem nio4r-1.2.1
  bundler (>= 0, development)
  rake (>= 0, development)

Gem nokogiri-1.6.8.1
  hoe (~> 3.15, development)
  hoe-bundler (~> 1.2.0, development)
  hoe-debugging (~> 1.2.1, development)
  hoe-gemspec (~> 1.0.0, development)
  hoe-git (~> 1.6.0, development)
  mini_portile2 (~> 2.1.0)
  minitest (~> 5.8.4, development)
  racc (~> 1.4.14, development)
  rake (~> 10.5.0, development)
  rake-compiler (~> 0.9.2, development)
  rake-compiler-dock (~> 0.5.1, development)
  rdoc (~> 4.0, development)
  rexical (~> 1.0.5, development)

Gem orm_adapter-0.5.0
  activerecord (>= 3.2.15, development)
  bson_ext (>= 1.3.0, development)
  bundler (>= 1.0.0, development)
  datamapper (>= 1.0, development)
  dm-active_model (>= 1.0, development)
  dm-sqlite-adapter (>= 1.0, development)
  git (>= 1.2.5, development)
  mongo_mapper (~> 0.11.0, development)
  mongoid (~> 2.8.0, development)
  rake (>= 0.8.7, development)
  rspec (>= 2.4.0, development)
  sqlite3 (>= 1.3.2, development)
  yard (>= 0.6.0, development)

Gem power_assert-0.2.6
  rake (>= 0, development)
  simplecov (>= 0, development)
  test-unit (>= 0, development)

Gem pry-0.10.4
  bundler (~> 1.0, development)
  coderay (~> 1.1.0)
  method_source (~> 0.8.1)
  slop (~> 3.4)

Gem pry-rails-0.3.4
  appraisal (>= 0, development)
  minitest (>= 0, development)
  pry (>= 0.9.10)

Gem psych-2.0.17

Gem puma-3.6.2
  hoe (~> 3.14, development)
  rack (< 2.0, >= 1.1, development)
  rake-compiler (~> 0.8, development)
  rdoc (~> 4.0, development)

Gem rack-2.0.1
  concurrent-ruby (>= 0, development)
  minitest (~> 5.0, development)
  minitest-sprint (>= 0, development)
  rake (>= 0, development)

Gem rack-test-0.6.3
  rack (>= 1.0)

Gem rails-5.0.0.1
  actioncable (= 5.0.0.1)
  actionmailer (= 5.0.0.1)
  actionpack (= 5.0.0.1)
  actionview (= 5.0.0.1)
  activejob (= 5.0.0.1)
  activemodel (= 5.0.0.1)
  activerecord (= 5.0.0.1)
  activesupport (= 5.0.0.1)
  bundler (< 2.0, >= 1.3.0)
  railties (= 5.0.0.1)
  sprockets-rails (>= 2.0.0)

Gem rails-dom-testing-2.0.1
  activesupport (< 6.0, >= 4.2.0)
  bundler (~> 1.3, development)
  minitest (>= 0, development)
  nokogiri (~> 1.6.0)
  rake (>= 0, development)

Gem rails-html-sanitizer-1.0.3
  bundler (~> 1.3, development)
  loofah (~> 2.0)
  minitest (>= 0, development)
  rails-dom-testing (>= 0, development)
  rake (>= 0, development)

Gem railties-5.0.0.1
  actionpack (= 5.0.0.1)
  actionview (= 5.0.0.1, development)
  activesupport (= 5.0.0.1)
  method_source (>= 0)
  rake (>= 0.8.7)
  thor (< 2.0, >= 0.18.1)

Gem rake-10.4.2
  hoe (~> 3.13, development)
  minitest (~> 5.4, development)
  rdoc (~> 4.0, development)

Gem rake-11.3.0
  bundler (~> 1.11, development)
  minitest (~> 5.8, development)
  rdoc (~> 4.0, development)

Gem rb-fsevent-0.9.8
  bundler (~> 1.0, development)
  guard-rspec (~> 4.2, development)
  rspec (~> 2.11, development)

Gem rb-inotify-0.9.7
  ffi (>= 0.5.0)
  yard (>= 0.4.0, development)

Gem rdoc-4.2.1

Gem responders-2.3.0
  railties (< 5.1, >= 4.2.0)

Gem rubygems-bundler-1.4.4
  bundler-unload (>= 1.0.2)
  executable-hooks (>= 1.3.2)
  tf (>= 0, development)

Gem rvm-1.11.3.9

Gem sass-3.4.22
  maruku (>= 0.5.9, development)
  minitest (>= 5, development)
  yard (>= 0.5.3, development)

Gem sass-rails-5.0.6
  railties (< 6, >= 4.0.0)
  sass (~> 3.1)
  sprockets (< 4.0, >= 2.8)
  sprockets-rails (< 4.0, >= 2.0)
  sqlite3 (>= 0, development)
  tilt (< 3, >= 1.1)

Gem slop-3.6.0
  minitest (~> 5.0.0, development)
  rake (>= 0, development)

Gem spring-2.0.0
  activesupport (>= 4.2)
  bump (>= 0, development)
  rake (>= 0, development)

Gem spring-watcher-listen-2.0.1
  activesupport (>= 0, development)
  bundler (~> 1.6, development)
  listen (< 4.0, >= 2.7)
  rake (>= 0, development)
  spring (< 3.0, >= 1.2)

Gem sprockets-3.7.0
  closure-compiler (~> 1.1, development)
  coffee-script (~> 2.2, development)
  coffee-script-source (~> 1.6, development)
  concurrent-ruby (~> 1.0)
  eco (~> 1.0, development)
  ejs (~> 1.0, development)
  execjs (~> 2.0, development)
  minitest (~> 5.0, development)
  nokogiri (~> 1.3, development)
  rack (< 3, > 1)
  rack-test (~> 0.6, development)
  rake (~> 10.0, development)
  sass (~> 3.1, development)
  uglifier (~> 2.3, development)
  yui-compressor (~> 0.12, development)

Gem sprockets-rails-3.2.0
  actionpack (>= 4.0)
  activesupport (>= 4.0)
  railties (>= 4.0, development)
  rake (>= 0, development)
  sass (>= 0, development)
  sprockets (>= 3.0.0)
  uglifier (>= 0, development)

Gem sqlite3-1.3.12
  hoe (~> 3.15, development)
  hoe-bundler (~> 1.0, development)
  mini_portile (~> 0.6.2, development)
  minitest (~> 5.9, development)
  rake-compiler (~> 0.9.3, development)
  rake-compiler-dock (~> 0.5.2, development)
  rdoc (~> 4.0, development)

Gem streamio-ffmpeg-3.0.2
  multi_json (~> 1.8)
  rake (~> 10.1, development)
  rspec (~> 3, development)

Gem test-unit-3.1.5
  bundler (>= 0, development)
  kramdown (>= 0, development)
  packnga (>= 0, development)
  power_assert (>= 0)
  rake (>= 0, development)
  yard (>= 0, development)

Gem thor-0.19.1
  bundler (~> 1.0, development)

Gem thor-0.19.4
  bundler (~> 1.0, development)

Gem thread_safe-0.3.5
  atomic (= 1.1.16, development)
  minitest (>= 4, development)
  rake (>= 0, development)

Gem tilt-2.0.5

Gem turbolinks-5.0.1
  turbolinks-source (~> 5)

Gem turbolinks-source-5.0.0

Gem tzinfo-1.2.2
  thread_safe (~> 0.1)

Gem uglifier-3.0.3
  bundler (~> 1.3, development)
  execjs (< 3, >= 0.3.0)
  rake (~> 11.3, development)
  rspec (~> 3.0, development)
  sourcemap (~> 0.1.1, development)

Gem uglifier-3.0.4
  bundler (~> 1.3, development)
  execjs (< 3, >= 0.3.0)
  rake (~> 11.3, development)
  rspec (~> 3.0, development)
  sourcemap (~> 0.1.1, development)

Gem warden-1.2.6
  rack (>= 1.0)

Gem web-console-3.4.0
  actionview (>= 5.0)
  activemodel (>= 5.0)
  debug_inspector (>= 0)
  railties (>= 5.0)

Gem websocket-driver-0.6.4
  eventmachine (>= 0, development)
  permessage_deflate (>= 0, development)
  rake-compiler (~> 0.8.0, development)
  rspec (>= 0, development)
  websocket-extensions (>= 0.1.0)

Gem websocket-extensions-0.1.2
  rspec (>= 0, development)
```

**Comment by segiddins** [comment]
Can you please share a Gemfile we can use to reproduce this? Thanks!

**Comment by lynnco** [comment]
@cyril-lemaire 

> Can you please share a Gemfile we can use to reproduce this? Thanks!

**Comment by segiddins** [comment]
Closing due to lack of response.
