### ISSUE TITLE
Ruby 2.4 net/http incompatibility

### ISSUE THREAD

**Issue by voxik** [bundler/bundler#5268]
Testing Bundler 1.13.6 against Ruby 2.4, I got errors such as:

```
when a gem has no architecture
$ /usr/bin/ruby -I/builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib:/builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/spec -r/builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/spec/support/fakeweb/windows.rb -rsupport/hax /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/exe/bundle install --no-color
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/exe/bundle install --no-color`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...


Error details

    NoMethodError: undefined method `close' for #<FakeWeb::StubSocket:0x0055f99f26f2c0>
      /usr/share/ruby/net/http.rb:981:in `do_finish'
      /usr/share/ruby/net/http.rb:976:in `finish'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:1005:in `request'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:48:in `request'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:16:in `fetch'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:115:in `call'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:42:in `block in update'
      /usr/share/ruby/tmpdir.rb:89:in `mktmpdir'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/exe/bundle:34:in `block in <main>'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/exe/bundle:26:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.6.8
  Ruby      2.4.0p-1 (2016-12-21 revision 57136) [x86_64-linux]
  GEM_HOME  /builddir/build/BUILD/rubygem-bundler-1.13.6/usr/share/gems/gems/bundler-1.13.6/tmp/gems/system
  Git       2.11.0
      
      Bundler settings
      
  disable_postit
    Set via BUNDLE_DISABLE_POSTIT: "1"
  spec_run
    Set via BUNDLE_SPEC_RUN: "true"
  plugins
    Set via BUNDLE_PLUGINS: "true"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60close%27+for+%23%3CFakeWeb++StubSocket+0x0055f99f26f2c0%3E&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
# $? => 1
```

I suspect this is caused by https://github.com/ruby/ruby/commit/f845a9ef76c0195254ded79c85c24332534f4057#diff-8c2ab8e0fb4f052e1d95ab6334e192c1 Probably worth of looking into prior Ruby 2.4 is released ....

**Comment by segiddins** [comment]
Bundler master is currently passing on ruby-head, and it seems like this is an issue with FakeWeb rather than bundler?

**Comment by voxik** [comment]
I've noticed the 032d71f02cc8d5d669e463c325e7e57caf35539b commit which is probably changing the behavior from Bundler side. I should probably check that out ...

**Comment by segiddins** [comment]
Bundler only used to use fake web in its specs, it has nothing to do with using bundler itself

**Comment by voxik** [comment]
Yes, you are right. I applied the patch 032d71f and the test failures went away. So probably nothing to solve here. Thx for checking.
