### ISSUE TITLE
[1.14.0.pre.1] bundle outdated - NoMethodError: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by shaicoleman** [bundler/bundler#5294]
## Backtrace

```
NoMethodError: undefined method `name' for nil:NilClass
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/resolver.rb:204:in `block in start'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/resolver.rb:204:in `reject'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/resolver.rb:204:in `start'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/resolver.rb:181:in `resolve'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/definition.rb:251:in `resolve'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/definition.rb:175:in `specs'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/definition.rb:163:in `resolve_remotely!'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/cli/outdated.rb:53:in `block in run'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/cli/outdated.rb:59:in `run'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/cli.rb:288:in `outdated'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/cli.rb:20:in `dispatch'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/cli.rb:11:in `start'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/exe/bundle:32:in `block in <top (required)>'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /home/shai/.rvm/gems/ruby-2.3.3@myproject/gems/bundler-1.14.0.pre.1/exe/bundle:24:in `<top (required)>'
  bin/bundle:3:in `load'
  bin/bundle:3:in `<main>'
```

## Environment

```
Bundler   1.14.0.pre.1
Rubygems  2.5.2
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
GEM_HOME  /home/shai/.rvm/gems/ruby-2.3.3@myproject
GEM_PATH  /home/shai/.rvm/gems/ruby-2.3.3@myproject:/home/shai/.rvm/gems/ruby-2.3.3@global
RVM       1.27.0 (master)
Git       2.11.0
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.2g  1 Mar 2016
rubygems-bundler (1.4.4)
```

## Bundler settings

```
jobs
  Set for the current user (/home/shai/.bundle/config): "8"
gemfile
  Set via BUNDLE_GEMFILE: "/home/shai/myproject/Gemfile"
```

**Comment by segiddins** [comment]
Can you please also share your gemfile and lockfile so we can reproduce the issue? Thanks!

**Comment by shaicoleman** [comment]
Here's a minimal Gemfile that reproduces this issues:
```
source 'https://rubygems.org'

gem 'rails', '~> 5.0.1'
gem 'jazz_hands2', git: 'git@github.com:shaicoleman/jazz_hands2'
```

This will fail when running a bundle update

**Comment by segiddins** [comment]
Thanks! We'll try and look into it

**Comment by segiddins** [comment]
Reproduced, thanks! Trying to understand why the resolver is hitting this bug now

**Comment by segiddins** [comment]
I have a fix for this in Molinillo, just need to come up with a test case for it
