### ISSUE TITLE
bundler >1.14 using wrong version of system Ruby

### ISSUE THREAD

**Issue by zefd1** [bundler/bundler#5367]
I'm having an issue where bundler 1.14.2 is using a system Ruby (2.4.0) instead of RVM (2.2.2) for core_ext. The result is an error that claims a gem called `ruby` is missing (I define a `required_ruby_version` in my gemspec). The last two lines of the stack trace show bundler using the wrong Ruby in `kernel_require`.

```
$ bundle exec rspec
/Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/resolver.rb:207:in `rescue in start': Bundler could not find compatible versions for gem "ruby": (Bundler::VersionConflict)
  In Gemfile:
    ruby

    opower_etl was resolved to 0.1.3, which depends on
      ruby (~> 2.2.2)

Could not find gem 'ruby (~> 2.2.2)', which is required by gem 'opower_etl', in any of the sources.
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/resolver.rb:201:in `start'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/resolver.rb:181:in `resolve'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/definition.rb:252:in `resolve'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/definition.rb:176:in `specs'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/definition.rb:235:in `specs_for'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/definition.rb:224:in `requested_specs'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/runtime.rb:118:in `block in definition_method'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/runtime.rb:19:in `setup'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler.rb:100:in `setup'
    from /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2/gems/bundler-1.14.2/lib/bundler/setup.rb:20:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
The error appears in bundler version 1.14.0 and above; I don't see this when I use bundler version 1.13.7 or below.

**Comment by zefd1** [comment]
## Environment

```
Bundler   1.14.2
Rubygems  2.4.6
Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
GEM_HOME  /Users/zef.delgadillo/.rvm/gems/ruby-2.2.0@opower_etl_2
GEM_PATH  /Users/zef.delgadillo/.rvm/gems/ruby-2.2.0@opower_etl_2:/Users/zef.delgadillo/.rvm/gems/ruby-2.2.0@global
RVM       1.28.0 (latest)
Git       2.4.3
Platform  x86_64-darwin-14
rubygems-bundler (1.4.4)
```
## Gemfile

### Gemfile

```ruby
source 'http://gemserver.va.opower.it'

gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    opower_etl (0.1.4)
      activesupport (~> 4.2.3)
      awesome_print (~> 1.1.0)
      faker (~> 1.4)
      logging (~> 1.8)
      parallel (~> 0.6)
      sysexits (= 1.0.2)
      thor (= 0.18.1)

GEM
  remote: http://gemserver.va.opower.it/
  specs:
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    arrayfields (4.7.4)
    ast (1.1.0)
    awesome_print (1.1.0)
    backports (3.3.5)
    bluff (0.1.0)
    cane (2.5.2)
      parallel
    chronic (0.10.2)
    churn (0.0.28)
      chronic (>= 0.2.3)
      hirb
      json_pure
      main
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.1)
    code_analyzer (0.4.7)
      sexp_processor
    coderay (1.1.1)
    colored (1.2)
    diff-lcs (1.3)
    erubis (2.7.0)
    faker (1.7.2)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fattr (2.2.1)
    ffi (1.9.17)
    flay (2.0.1)
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.0)
    flog (3.2.2)
      ruby_parser (~> 3.1, > 3.1.0)
      sexp_processor (~> 4.0)
    formatador (0.2.5)
    git (1.3.0)
    github_project (0.0.2)
      git (~> 1.2)
      octokit (~> 2.7)
    guard (1.8.3)
      formatador (>= 0.2.4)
      listen (~> 1.3)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-reek (0.0.4)
      guard
      reek
    guard-rspec (1.2.2)
      guard (>= 1.1)
    guard-rubocop (0.2.2)
      guard (~> 1.8)
      rubocop (~> 0.10)
    hirb (0.7.3)
    i18n (0.7.0)
    japgolly-Saikuro (1.1.1.0)
    json (1.8.6)
    json_pure (2.0.3)
    listen (1.3.1)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      rb-kqueue (>= 0.2)
    little-plugger (1.1.4)
    logging (1.8.2)
      little-plugger (>= 1.1.3)
      multi_json (>= 1.8.4)
    lumberjack (2.0.1)
    main (6.2.2)
      arrayfields (~> 4.7, >= 4.7.4)
      chronic (~> 0.6, >= 0.6.2)
      fattr (~> 2.2, >= 2.2.0)
      map (~> 6.1, >= 6.1.0)
    map (6.2.0)
    method_source (0.8.2)
    metric_fu (4.2.1)
      arrayfields (= 4.7.4)
      bluff
      cane (= 2.5.2)
      churn (= 0.0.28)
      coderay
      fattr (= 2.2.1)
      flay (= 2.0.1)
      flog (= 3.2.2)
      japgolly-Saikuro (>= 1.1.1.0)
      map (= 6.2.0)
      metric_fu-roodi (>= 2.2.1)
      multi_json
      parallel (= 0.6.2)
      rails_best_practices (= 1.13.2)
      redcard
      reek (= 1.3.1)
      ruby2ruby (~> 2.0, >= 2.0.2)
      ruby_parser (~> 3.0, >= 3.1.1)
      sexp_processor (~> 4.0)
    metric_fu-roodi (3.0.0)
    minitest (5.10.1)
    multi_json (1.12.1)
    multipart-post (2.0.0)
    octokit (2.7.2)
      sawyer (~> 0.5.2)
    parallel (0.6.2)
    parser (2.0.0)
      ast (~> 1.1)
      slop (~> 3.4, >= 3.4.5)
    powerpack (0.0.9)
    progressbar (1.8.2)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rails_best_practices (1.13.2)
      activesupport
      awesome_print
      code_analyzer
      colored
      erubis
      i18n
      progressbar
    rainbow (1.1.4)
    rake (10.0.4)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rb-kqueue (0.2.4)
      ffi (>= 0.5.0)
    redcard (1.1.0)
    redcarpet (2.3.0)
    reek (1.3.1)
      ruby2ruby (~> 2.0.2)
      ruby_parser (~> 3.1.1)
      sexp_processor
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rubocop (0.11.1)
      backports (~> 3.3.3)
      parser (~> 2.0.0.pre6)
      powerpack (~> 0.0.3)
      rainbow (>= 1.1.4)
    ruby2ruby (2.0.8)
      ruby_parser (~> 3.1)
      sexp_processor (~> 4.0)
    ruby_parser (3.1.3)
      sexp_processor (~> 4.1)
    sawyer (0.5.5)
      addressable (~> 2.3.5)
      faraday (~> 0.8, < 0.10)
    sexp_processor (4.7.0)
    simplecov (0.7.1)
      multi_json (~> 1.0)
      simplecov-html (~> 0.7.1)
    simplecov-html (0.7.1)
    slop (3.6.0)
    sysexits (1.0.2)
    thor (0.18.1)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yard (0.8.7.6)

PLATFORMS
  ruby

DEPENDENCIES
  github_project (~> 0.0)
  guard (~> 1.8.0)
  guard-reek (~> 0.0.4)
  guard-rspec
  guard-rubocop (~> 0.2.1)
  metric_fu (~> 4.2.0)
  opower_etl!
  rainbow (= 1.1.4)
  rake (~> 10.0.1)
  redcarpet (~> 2.3.0)
  rspec (~> 3.1)
  rubocop (~> 0.11.1)
  simplecov (~> 0.7.0)
  yard (~> 0.8.7)

BUNDLED WITH
   1.14.2
```

## Gemspecs

### opower_etl.gemspec

```ruby
# -*- encoding: utf-8 -*-
# vim: ft=ruby

require File.expand_path('../lib/opower_etl/version', __FILE__)

Gem::Specification.new do |gem|
  gem.authors       = ['Ben Harack']
  gem.email         = ['ben.harack@opower.com']
  gem.description   = %q{Opower's homegrown ruby ETL framework}
  gem.summary       = %q{A custom ETL framework for integration with the Stargate ecosystem}
  gem.homepage      = "https://github.va.opower.it/techops/opower_etl"

  gem.files         = `git ls-files`.split($\)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.name          = 'opower_etl'
  gem.require_paths = %w(lib lib/opower_etl lib/opower_etl/commands)
  gem.version       = OpowerEtl::VERSION
  gem.required_ruby_version = '~> 2.2.0'

  # dependencies.
  gem.add_dependency('thor', '0.18.1')
  gem.add_dependency('sysexits', '1.0.2')
  gem.add_dependency('awesome_print', '~> 1.1.0')
  gem.add_dependency('faker', '~> 1.4')
  gem.add_runtime_dependency('logging', '~> 1.8')
  gem.add_runtime_dependency('parallel', '~> 0.6')
  gem.add_runtime_dependency('activesupport', '~> 4.2.3')


  # development dependencies.
  gem.add_development_dependency('rspec', '~> 3.1')
  gem.add_development_dependency('simplecov', '~> 0.7.0')
  gem.add_development_dependency('guard', '~> 1.8.0')
  gem.add_development_dependency('guard-rspec')
  gem.add_development_dependency('rubocop', '~> 0.11.1')
  gem.add_development_dependency('rainbow', '1.1.4')
  gem.add_development_dependency('guard-rubocop', '~> 0.2.1')
  gem.add_development_dependency('metric_fu', '~> 4.2.0')
  gem.add_development_dependency('guard-reek', '~> 0.0.4')
  gem.add_development_dependency('rake', '~> 10.0.1')
  gem.add_development_dependency('yard', '~> 0.8.7')
  gem.add_development_dependency('redcarpet', '~> 2.3.0')
  gem.add_development_dependency('github_project', '~> 0.0')

end
```

**Comment by segiddins** [comment]
You're running on 2.2.0, which is indeed less than 2.2.2

**Comment by zefd1** [comment]
@segiddins I must have switched my rvm to 2.2.0 before running `bundle env` (and after the stack trace I posted, which has `2.2.2` in the path). 

Here's a run of `bundle env` after switching back to 2.2.2.
## Environment

```
Bundler   1.14.2
Rubygems  2.4.8
Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
GEM_HOME  /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2
GEM_PATH  /Users/zef.delgadillo/.rvm/gems/ruby-2.2.2:/Users/zef.delgadillo/.rvm/gems/ruby-2.2.2@global
RVM       1.28.0 (latest)
Git       2.4.3
Platform  x86_64-darwin-14
rubygems-bundler (1.4.4)
```

## Gemfile

### Gemfile

```ruby
source 'http://gemserver.va.opower.it'

gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    opower_etl (0.1.3)
      activesupport (~> 4.2.3)
      awesome_print (~> 1.1.0)
      faker (~> 1.4)
      logging (~> 1.8)
      parallel (~> 0.6)
      sysexits (= 1.0.2)
      thor (= 0.18.1)

GEM
  remote: http://gemserver.va.opower.it/
  specs:
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    arrayfields (4.7.4)
    ast (1.1.0)
    awesome_print (1.1.0)
    backports (3.3.5)
    bluff (0.1.0)
    cane (2.5.2)
      parallel
    chronic (0.10.2)
    churn (0.0.28)
      chronic (>= 0.2.3)
      hirb
      json_pure
      main
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.1)
    code_analyzer (0.4.7)
      sexp_processor
    coderay (1.1.1)
    colored (1.2)
    diff-lcs (1.3)
    erubis (2.7.0)
    faker (1.7.2)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fattr (2.2.1)
    ffi (1.9.17)
    flay (2.0.1)
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.0)
    flog (3.2.2)
      ruby_parser (~> 3.1, > 3.1.0)
      sexp_processor (~> 4.0)
    formatador (0.2.5)
    git (1.3.0)
    github_project (0.0.2)
      git (~> 1.2)
      octokit (~> 2.7)
    guard (1.8.3)
      formatador (>= 0.2.4)
      listen (~> 1.3)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-reek (0.0.4)
      guard
      reek
    guard-rspec (1.2.2)
      guard (>= 1.1)
    guard-rubocop (0.2.2)
      guard (~> 1.8)
      rubocop (~> 0.10)
    hirb (0.7.3)
    i18n (0.7.0)
    japgolly-Saikuro (1.1.1.0)
    json (1.8.6)
    json_pure (2.0.3)
    listen (1.3.1)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      rb-kqueue (>= 0.2)
    little-plugger (1.1.4)
    logging (1.8.2)
      little-plugger (>= 1.1.3)
      multi_json (>= 1.8.4)
    lumberjack (2.0.1)
    main (6.2.2)
      arrayfields (~> 4.7, >= 4.7.4)
      chronic (~> 0.6, >= 0.6.2)
      fattr (~> 2.2, >= 2.2.0)
      map (~> 6.1, >= 6.1.0)
    map (6.2.0)
    method_source (0.8.2)
    metric_fu (4.2.1)
      arrayfields (= 4.7.4)
      bluff
      cane (= 2.5.2)
      churn (= 0.0.28)
      coderay
      fattr (= 2.2.1)
      flay (= 2.0.1)
      flog (= 3.2.2)
      japgolly-Saikuro (>= 1.1.1.0)
      map (= 6.2.0)
      metric_fu-roodi (>= 2.2.1)
      multi_json
      parallel (= 0.6.2)
      rails_best_practices (= 1.13.2)
      redcard
      reek (= 1.3.1)
      ruby2ruby (~> 2.0, >= 2.0.2)
      ruby_parser (~> 3.0, >= 3.1.1)
      sexp_processor (~> 4.0)
    metric_fu-roodi (3.0.0)
    minitest (5.10.1)
    multi_json (1.12.1)
    multipart-post (2.0.0)
    octokit (2.7.2)
      sawyer (~> 0.5.2)
    parallel (0.6.2)
    parser (2.0.0)
      ast (~> 1.1)
      slop (~> 3.4, >= 3.4.5)
    powerpack (0.0.9)
    progressbar (1.8.2)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rails_best_practices (1.13.2)
      activesupport
      awesome_print
      code_analyzer
      colored
      erubis
      i18n
      progressbar
    rainbow (1.1.4)
    rake (10.0.4)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rb-kqueue (0.2.4)
      ffi (>= 0.5.0)
    redcard (1.1.0)
    redcarpet (2.3.0)
    reek (1.3.1)
      ruby2ruby (~> 2.0.2)
      ruby_parser (~> 3.1.1)
      sexp_processor
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rubocop (0.11.1)
      backports (~> 3.3.3)
      parser (~> 2.0.0.pre6)
      powerpack (~> 0.0.3)
      rainbow (>= 1.1.4)
    ruby2ruby (2.0.8)
      ruby_parser (~> 3.1)
      sexp_processor (~> 4.0)
    ruby_parser (3.1.3)
      sexp_processor (~> 4.1)
    sawyer (0.5.5)
      addressable (~> 2.3.5)
      faraday (~> 0.8, < 0.10)
    sexp_processor (4.7.0)
    simplecov (0.7.1)
      multi_json (~> 1.0)
      simplecov-html (~> 0.7.1)
    simplecov-html (0.7.1)
    slop (3.6.0)
    sysexits (1.0.2)
    thor (0.18.1)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yard (0.8.7.6)

PLATFORMS
  ruby

DEPENDENCIES
  github_project (~> 0.0)
  guard (~> 1.8.0)
  guard-reek (~> 0.0.4)
  guard-rspec
  guard-rubocop (~> 0.2.1)
  metric_fu (~> 4.2.0)
  opower_etl!
  rainbow (= 1.1.4)
  rake (~> 10.0.1)
  redcarpet (~> 2.3.0)
  rspec (~> 3.1)
  rubocop (~> 0.11.1)
  simplecov (~> 0.7.0)
  yard (~> 0.8.7)

BUNDLED WITH
   1.14.2
```

## Gemspecs

### opower_etl.gemspec

```ruby
# -*- encoding: utf-8 -*-
# vim: ft=ruby

require File.expand_path('../lib/opower_etl/version', __FILE__)

Gem::Specification.new do |gem|
  gem.authors       = ['Ben Harack']
  gem.email         = ['ben.harack@opower.com']
  gem.description   = %q{Opower's homegrown ruby ETL framework}
  gem.summary       = %q{A custom ETL framework for integration with the Stargate ecosystem}
  gem.homepage      = "https://github.va.opower.it/techops/opower_etl"

  gem.files         = `git ls-files`.split($\)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.name          = 'opower_etl'
  gem.require_paths = %w(lib lib/opower_etl lib/opower_etl/commands)
  gem.version       = OpowerEtl::VERSION
  gem.required_ruby_version = '~> 2.2.0'

  # dependencies.
  gem.add_dependency('thor', '0.18.1')
  gem.add_dependency('sysexits', '1.0.2')
  gem.add_dependency('awesome_print', '~> 1.1.0')
  gem.add_dependency('faker', '~> 1.4')
  gem.add_runtime_dependency('logging', '~> 1.8')
  gem.add_runtime_dependency('parallel', '~> 0.6')
  gem.add_runtime_dependency('activesupport', '~> 4.2.3')


  # development dependencies.
  gem.add_development_dependency('rspec', '~> 3.1')
  gem.add_development_dependency('simplecov', '~> 0.7.0')
  gem.add_development_dependency('guard', '~> 1.8.0')
  gem.add_development_dependency('guard-rspec')
  gem.add_development_dependency('rubocop', '~> 0.11.1')
  gem.add_development_dependency('rainbow', '1.1.4')
  gem.add_development_dependency('guard-rubocop', '~> 0.2.1')
  gem.add_development_dependency('metric_fu', '~> 4.2.0')
  gem.add_development_dependency('guard-reek', '~> 0.0.4')
  gem.add_development_dependency('rake', '~> 10.0.1')
  gem.add_development_dependency('yard', '~> 0.8.7')
  gem.add_development_dependency('redcarpet', '~> 2.3.0')
  gem.add_development_dependency('github_project', '~> 0.0')

end
```

**Comment by zefd1** [comment]
I'll try to dig into this further and re-open once I have more details.

**Comment by segiddins** [comment]
Cool, thanks!
