### ISSUE TITLE
bundle install is not installing project vendor cached git gems, but using the cache as the install location

### ISSUE THREAD

**Issue by bughit** [bundler/bundler#5398]
My understanding is that the cache is only supposed to be used as a source for installation of gems, and not function as the install location, from which the code is ultimately loaded.

The normal git gem system install location is `~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/`, so when I bundle install (normally, without --path or --deployment) a gem that is cached in the project's vendor/cache I expect it to end up in `~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/`

It doesn't, and `bundle show` shows its location in `$PROJECT/vendor/cache/`.

If it's removed from  `$PROJECT/vendor/cache/`  and bundle reinstalled, it does get installed to `~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/` but `bundle show` still shows `$PROJECT/vendor/cache/`

Is this expected behavior?  Does not seem like a good idea.

**Comment by bughit** [comment]
The same thing is happening in production where the bundle is created with `--deployment --local`, but bundle show for a git gem still shows the cache location.

**Comment by bughit** [comment]
as a consequence, deleting the gem from the cache effectively uninstalls it, breaking dependents

This has got to be a bug, no way should the removal of a gem from an install cache, be equivalent to uninstalling

**Comment by segiddins** [comment]
What's the output of `bundle env`?

**Comment by bughit** [comment]
## Environment

```
Bundler   1.14.3
Rubygems  2.6.8
Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
Git       2.11.0
Platform  x86_64-linux
```

## Bundler settings

```
cache_all
  Set for your local app (/tmp/bundler_cache_bug/.bundle/config): "true"
```

## Gemfile

### Gemfile

```ruby
gem 'timecop', github: 'travisjeffery/timecop'
```

### Gemfile.lock

```
GIT
  remote: git://github.com/travisjeffery/timecop.git
  revision: b0a84cd674a380fb76285320b6d73088fc87f5df
  specs:
    timecop (0.8.0)

GEM
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  timecop!

BUNDLED WITH
   1.14.3
```

**Comment by segiddins** [comment]
@indirect any ideas?

**Comment by indirect** [comment]
This could be working as intended? I don't actually know. Git gems are already an exception to the caching rules. I'd be fine with PR to add the regular install location, but I wouldn't go so far as to call this a bug.

In principle, I agree that it makes the most sense to install git gems to the same location from the git cache. That said, I don't think we have ever guaranteed that we will install git gems into that location.

**Comment by bughit** [comment]
> This could be working as intended?

The install cache is meant to hold gems downloaded from their source in order to avoid downloading them again (for perf or security reasons).  It is also meant to be deletable and refillable from the source on demand.  

The system install location for git gems, which is supposed to be targeted by the `--system` flag (which is the default, but to drive the point I'll pass it explicitly) is `$RUBY/lib/ruby/gems/$VERSION/bundler/` .  It is certainly not the project's local install cache.

There are actually two clear bugs here:

1. `bundle install --system` does not install into `--system`, it does nothing, because a git gem being in the local install cache is taken to be already installed in `--system`, which is nonsensical.

2. even when a git gem is already in the `--system` install location, bundler will still load it from the install cache

**Comment by segiddins** [comment]
I don't think anyone on the team will get around to fixing this anytime soon, but a PR doing so would be 💯

**Comment by bughit** [comment]
This has the following additional consequence

If a gem has a native extension it will get installed into the global git gem location, but because the gem is loaded from the cache which does not have the native extension, loading will fail.  I noticed it while experimenting with puma (`gem 'puma', github: 'puma'`)

```
LoadError: cannot load such file -- puma/puma_http11
vendor/cache/puma-5bbe6f3ba610/lib/puma/server.rb:15:in `require'
```

> I don't think anyone on the team will get around to fixing this anytime soon

given the above, that loading gems from the cache is both conceptually and practically broken, why not?

**Comment by segiddins** [comment]
> given the above, that loading gems from the cache is both conceptually and practically broken, why not?

Because we're a small team, and I personally have other priorities for my Bundler work over the next month.

**Comment by indirect** [comment]
@bughit first, thank you for reporting this bug. Figuring out the problem is very helpful. 👍 

Now, let's talk about open source: you get to use Bundler for free. If this bug is a problem for you, you are easily able to fix it, because you also get the source code of Bundler for free. That's the beauty of open source.

The flip side of open source is that _we don't owe you anything_. Reporting bugs is great, and asking if we have time to fix it is great. When you demand that we fix your bug right away, for free, simply because it makes your life inconvenient... we don't want to help you anymore.

I hope that helps.

**Comment by bughit** [comment]
I pointed out that the severity is higher than it first seemed. Using `gem 'puma', github: 'puma'`, running bundle install and then not being able to run puma, is more serious than the original symptoms. You didn't want to know about that?  You're welcome. 

And asked if in light of that, why not fix this.  That is a question, stemming from a revaluation of severity, not a demand.

**Comment by chrismo** [comment]
I tried a simple Gemfile with just `gem 'puma', github: 'puma'` and it seems to be working fine - I presume there more steps than just this?

## Environment

```
Bundler   1.15.1
Rubygems  2.6.8
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin14]
Git       2.10.0
Platform  x86_64-darwin-14
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org' do
  gem 'puma', github: 'puma'
end
```

### Gemfile.lock

```
GIT
  remote: git://github.com/puma/puma.git
  revision: 5bbe6f3ba610ce3e3cfd95932c9b935769916e45
  specs:
    puma (3.9.1)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  puma!

BUNDLED WITH
   1.15.1
```

```
$ bundle install
The git source `git://github.com/puma/puma.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Using puma 3.9.1 from git://github.com/puma/puma.git (at master@5bbe6f3)
Using bundler 1.15.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle exec puma -V
puma version 3.9.1```

**Comment by bughit** [comment]
doesn't look like you're vendor caching gems in your project
[bundler_cache_bug.zip](https://github.com/bundler/bundler/files/1126609/bundler_cache_bug.zip)
in the attached project, bundle install, run puma

**Comment by bughit** [comment]
as to the fix,

I discovered that if you run bundle install a second time it will add the binary extension into the cache and puma will start loading (from the cache), which may suggest that could be the fix, however I would argue that's not a proper one.  This would be continued abuse of the cache to function as the install location.

Binary extensions should not be stored in the cache, they should be built during bundle install and installed in the appropriate (system or local) git gem location along with the rest of the gem.

**Comment by chrismo** [comment]
Ok, the key bit I was missing: `bundle pack --all`. The .zip you sent didn't include the .bundle dir which had the cache_all setting. Your bundle env dump above had that, and I was able to piece that together. Here's the reproducible case for me:

```
$ bundle env
The git source `git://github.com/puma/puma.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
## Environment

Bundler   1.14.3
Rubygems  2.6.8
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin14]
Git       2.10.0
Platform  x86_64-darwin-14

## Gemfile

### Gemfile

source 'https://rubygems.org' do
  gem 'puma', github: 'puma'
end

### Gemfile.lock

<No /private/tmp/5398/Gemfile.lock found>

$ bundle pack --all
The git source `git://github.com/puma/puma.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/puma/puma.git
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using puma 3.9.1 from git://github.com/puma/puma.git (at master@5bbe6f3)
Using bundler 1.14.3
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Updating files in vendor/cache
$ bundle exec puma -h
bundler: failed to load command: puma (/Users/chrismo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bin/puma)
LoadError: cannot load such file -- puma/puma_http11
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/server.rb:15:in `require'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/server.rb:15:in `<top (required)>'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/runner.rb:1:in `require'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/runner.rb:1:in `<top (required)>'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/cluster.rb:1:in `require'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/cluster.rb:1:in `<top (required)>'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/launcher.rb:4:in `require'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/launcher.rb:4:in `<top (required)>'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/cli.rb:5:in `require'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/lib/puma/cli.rb:5:in `<top (required)>'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/bin/puma:6:in `require'
  /private/tmp/5398/vendor/cache/puma-5bbe6f3ba610/bin/puma:6:in `<top (required)>'
  /Users/chrismo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bin/puma:22:in `load'
  /Users/chrismo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bin/puma:22:in `<top (required)>'
```

**Comment by chrismo** [comment]
Same issue in 1.15.1 as well.

And as you say, the problem seems to correct itself by doing a `bundle install` after the `bundle pack --all`.

**Comment by bughit** [comment]
The zip attached in https://github.com/bundler/bundler/issues/5398#issuecomment-313280867
https://github.com/bundler/bundler/files/1126609/bundler_cache_bug.zip
does have .bundle folder with a config file with `BUNDLE_CACHE_ALL: "true"`
I just double checked.

You do not need to run `bundle pack --all` to repro.  Running bundle install should both  cache and install the gem.  It does not.  The fact that a second `bundle install` "fixes" (see https://github.com/bundler/bundler/issues/5398#issuecomment-313284466 for why fixes is in quotes) it does not change that there is a bug.

**Comment by chrismo** [comment]
Ah, right, my mistake. I always forget Finder hides . folders. :/ 

If starting from a blank directory, like I was, then `bundle pack --all` seems to be necessary in order to establish the `cache_all` setting in the first place.

Yeah, I didn't mean to imply there was no bug, just highlighting the workaround you'd found.
