### ISSUE TITLE
Unable to reference built-in constants with bundler 1.14.5

### ISSUE THREAD

**Issue by PikachuEXE** [bundler/bundler#5474]
My app is using a gem [`http-exceptions`](https://github.com/rainforestapp/http-exceptions)
It's [referencing some built-in constants like `SocketError` or `Net`](https://github.com/rainforestapp/http-exceptions/blob/master/lib/http/exceptions/configuration.rb)

I test by running `bundle exec rspec` inside that project.
1.14.5 failed, 1.14.4 works.

### What you're trying to accomplish
Load gem [`http-exceptions`](https://github.com/rainforestapp/http-exceptions)

### The command you ran
`bundle install && bundle exec rspec`, under gem project folder

### What you expected to happen
No error happened

### What actually happened
An error thrown, complaining absence of top level constants like `SocketError`

### The exception backtrace(s), if any
```
/users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:5:in `<class:Configuration>': uninitialized constant Http::Exceptions::Configuration::SocketError (NameError)
Did you mean?  KeyError
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:3:in `<module:Exceptions>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:2:in `<module:Http>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions/configuration.rb:1:in `<top (required)>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions.rb:2:in `require'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/lib/http/exceptions.rb:2:in `<top (required)>'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/spec/spec_helper.rb:1:in `require'
	from /users/pikachuexe/projects/ruby/gems/http-exceptions/spec/spec_helper.rb:1:in `<top (required)>'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `require'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/rspec:22:in `load'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/rspec:22:in `<main>'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /users/pikachuexe/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```
Everything output by running bundle env
```
Bundler   1.14.5
Rubygems  2.6.10
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
GEM_HOME  /users/pikachuexe/.rvm/gems/ruby-2.3.3
GEM_PATH  /users/pikachuexe/.rvm/gems/ruby-2.3.3:/users/pikachuexe/.rvm/gems/ruby-2.3.3@global
RVM       1.28.0 (master)
Git       2.12.0
Platform  x86_64-darwin-16
rubygems-bundler (1.4.4)
```

## Bundler settings

```
jobs
  Set for the current user (/users/pikachuexe/.bundle/config): "8"
gem.test
  Set for the current user (/users/pikachuexe/.bundle/config): "rspec"
```

### Gemfile

```ruby
source 'https://rubygems.org'

# Specify your gem's dependencies in http-exceptions.gemspec
gemspec

gem 'rspec'
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    http-exceptions (0.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    rake (12.0.0)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (~> 1.6)
  http-exceptions!
  rake
  rspec

BUNDLED WITH
   1.14.5
```

### http-exceptions.gemspec

```ruby
# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'http/exceptions/version'

Gem::Specification.new do |spec|
  spec.name          = "http-exceptions"
  spec.version       = Http::Exceptions::VERSION
  spec.authors       = ["Simon Mathieu"]
  spec.email         = ["simon.math@gmail.com"]
  spec.summary       = %q{An easy way to rescue exceptions that might be thrown by your Http library}
  spec.description   = %q{An easy way to rescue exceptions that might be thrown by your Http library}
  spec.homepage      = ""
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0")
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]

  spec.add_development_dependency "bundler", "~> 1.6"
  spec.add_development_dependency "rake"
end
```

**Comment by colby-swandale** [comment]
Please follow [ISSUES.md](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) so that we can better help diagnose your problem.

**Comment by PikachuEXE** [comment]
Sorry I forgot read
Maybe it's good to have github issue template too

Anyway updated description following ISSUES.md

**Comment by segiddins** [comment]
Did you ever require anything that defines SocketError?

**Comment by PikachuEXE** [comment]
I solved by requiring those standard libraries.
Just don't quite understand why it works before
