### ISSUE TITLE
Net::HTTP not found anymore in bundler

### ISSUE THREAD

**Issue by kouno** [bundler/bundler#5477]
Gemfile:
```
source "https://rubygems.org"
```

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES

BUNDLED WITH
   1.14.5
```

On bundler 1.14.4:
```
$ bundle exec irb
irb(main):001:0> Net::HTTP
=> Net::HTTP
```

On bundler 1.14.5:
```
$ bundle exec irb
irb(main):001:0> Net::HTTP
NameError: uninitialized constant Net
Did you mean?  Set
        from (irb):1
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/bin/irb:11:in `<top (required)>'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `load'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/exec.rb:27:in `run'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:335:in `exec'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
        from /Users/vincent.bonmalais/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

Ruby version: 2.3.1

`irb` by itself would not load Net::HTTP. So it sounds fair to not load Net::HTTP by default, but it was surprising to suddenly run into this error.

I assume this wasn't an explicit change as well since I don't see it in the CHANGELOG file. It might also not need any fix but I thought I'd raise it in case someone else ran into this.

**Comment by segiddins** [comment]
Since `Net::HTTP` isn't loaded by default in ruby, Bundler shouldn't be loading it -- if you need to use anything not loaded by default, you need to require it

**Comment by kouno** [comment]
Sounds good. Thanks for the input.
