### ISSUE TITLE
Unable to execute rake jobs

### ISSUE THREAD

**Issue by samnissen** [bundler/bundler#5478]
I'm trying to execute a rake task, but cannot as bundler requires rake, but cannot find it. It doesn't make any sense -- rake is there, `bundle install` works just fine, `rails c production` loads etc.

Command:
```shell
$ rake my_namespace:my_task
```

Backtrace:
```ruby
/home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `map!'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `materialize'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/definition.rb:176:in `specs'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/definition.rb:235:in `specs_for'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/definition.rb:224:in `requested_specs'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:19:in `setup'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler.rb:100:in `setup'
	from /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Gemfile, environment details, etc. here: https://gist.github.com/samnissen/3fd9230921127d7c11cf871f326b526a

**Comment by hmistry** [comment]
have you tried `bundle exec rake my_namespace:my_task` or `bin/rake ...`?

**Comment by samnissen** [comment]
@hmistry Yes. Both result in the same error message.

**Comment by kwisatz** [comment]
Exact same think here using the jekyll docker image:

```
kwisatz@duncan:~/website - master $ docker-compose run serve bundle config
Running `bundle config` with bundler 1.14.4
Settings are listed in order of priority. The top value will be used.
without
Set for your local app (/srv/jekyll/.bundle/config): "test:deploy"
Set via BUNDLE_WITHOUT: "test:deploy"

disable_shared_gems
Set for your local app (/srv/jekyll/.bundle/config): "true"

path
Set via BUNDLE_PATH: ".docker/bundle"
```

**Comment by fbukevin** [comment]
I got the error alike:

```
↪ rails s rake                                                                                                         15:38:15
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Ignoring nokogiri-1.6.8 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8
Could not find rake-12.0.0 in any of the sources
Run `bundle install` to install missing gems
```

**Comment by udev** [comment]
Same problem. Happens on every new project. I'm using RubyMine.

```
/usr/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) -Ilib /Applications/RubyMine.app/Contents/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb
Testing started at 11:14 AM ...
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-11.3.0 in any of the sources (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

Process finished with exit code 1
```

RubyMine 2017.1
Build #RM-171.3780.96, built on March 20, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3

**Comment by segiddins** [comment]
What is the output of `bundle env`?

**Comment by samnissen** [comment]
@segiddins I've added it to my output: https://gist.github.com/samnissen/3fd9230921127d7c11cf871f326b526a#file-output-sh-L470

My attempts to solve this might have caused some drift between the results there and my previous information, but none of the fundamentals have changed.

**Comment by segiddins** [comment]
What happens if you run `bundle exec rake`?

**Comment by samnissen** [comment]
`bundle exec rake my_namespace:my_task` or `bin/rake my_namespace:my_task` do not change the resulting error message

**Comment by kwisatz** [comment]
Here's my bundle env: https://gist.github.com/kwisatz/97ad8c7914a67f23849295f3bd116dc2
And bundle exec rake:

```
kwisatz@mazer:~/ master $ docker-compose run serve bundle exec rake
Could not find rake-12.0.0 in any of the sources
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:10:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:71:in `kernel_load'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
Run `bundle install` to install missing gems.
```

**Comment by segiddins** [comment]
Thanks! Looks like a real bug

**Comment by segiddins** [comment]
@kwisatz looking at your environment, bundler is behaving as intended. Since the only thing that has declared a dependency on rake is capistrano, which is in the deploy group, running with `BUNDLE_WITHOUT=test:deploy` will indeed cause bundler to not activate rake. Either add rake as a dependency outside of the `without` groups, or remove the deploy group from without.

**Comment by segiddins** [comment]
@samnissen I was unable to reproduce the issue with the Gemfile & Gemfile.lock that you shared

**Comment by samnissen** [comment]
@segiddins I have finally realized my very silly mistake. Hopefully my embarrassment can save someone else's. I have followed some advice to fix [an issue with the gem mini_magick](https://github.com/minimagick/minimagick/issues/141) that looks a bit like this:

```bash
$ cat config/environments/production.rb
# ...
ENV['PATH'] = "/usr/bin:#{ENV['PATH']}"
```

I finally realized that causes this weird situation:
```bash
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
```
```bash
$ irb
2.4.0 :001 > `ruby -v`
 => "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]\n"
2.4.0 :001 > quit
```
```bash
$ rails c production
Loading production environment (Rails 5.0.1)
2.4.0 :001 > `ruby -v`
 => "ruby 2.0.0p648 (2015-12-16) [x86_64-linux]\n"
```

As you can see, Rails is picking up a different version of Ruby -- indeed, the system Ruby, and not my RVM-managed Ruby 2.4.

For reference, a fix to the mini_magick issues that does not cause Rails to pick up the wrong Ruby version is to symlink mogrify (and not add the line to production.rb):

```bash
$ sudo ln -s /usr/bin/mogrify /usr/local/bin/mogrify
```

Thanks, and sorry for wasting your time.

As a final note: Is there any way to make it so Bundler can detect mismatches like this? That would be very cool!

**Comment by hmistry** [comment]
@samnissen Thanks for coming back and telling us the root cause and solution... really appreciate it.
