### ISSUE TITLE
Error in bundler. block (3 levels) in unmet_dependency_names : undefined method `name' for ["ruby-ajp", ">= 0.2.0"]:Array (NoMethodError)

### ISSUE THREAD

**Issue by fbaskara** [bundler/bundler#5511]
Today got a deployment fails with this error, similar to issue #2615

```
[directoryHooksExecutor.py-29] [root directoryHooksExecutor info] Output from script: /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `block (3 levels) in unmet_dependency_names': undefined method `name' for ["ruby-ajp", ">= 0.2.0"]:Array (NoMethodError)
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `map'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:95:in `block (2 levels) in unmet_dependency_names'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:94:in `map'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:94:in `block in unmet_dependency_names'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:93:in `map'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:93:in `unmet_dependency_names'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:240:in `remote_specs'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:163:in `fetch_specs'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:67:in `specs'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:192:in `block (2 levels) in index'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:189:in `each'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:189:in `block in index'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/index.rb:9:in `build'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:185:in `index'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:179:in `resolve'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
	from /opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in `resolve_remotely!'
	from /opt/elasticbeanstalk/hooks/appdeploy/pre/13_test_for_puma.rb:10:in `rescue in <main>'
	from /opt/elasticbeanstalk/hooks/appdeploy/pre/13_test_for_puma.rb:7:in `<main>'
```

Was working yesterday.
I might be missing something simple here.

**Comment by segiddins** [comment]
What's the output of `bundle env`?

**Comment by fbaskara** [comment]
Thanks for the quick reply.

Here's the output:

```
$ bundle env
Bundler 1.3.5
Ruby 2.1.2 (2014-05-08 patchlevel 95) [x86_64-linux]
Rubygems 2.2.2
GEM_HOME /home/ec2-user/.gem/ruby/2.1.2
GEM_PATH /home/ec2-user/.gem/ruby/2.1.2:/opt/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0

Bundler settings
  without
    Set via BUNDLE_WITHOUT: "test:development"


Gemfile
source 'https://rubygems.org' 
#ruby '1.9.3'
ruby '2.1.2'

gem 'puma'
gem 'unicorn'
gem 'foreman'

gem 'rails', '4.0.0'
gem 'bcrypt-ruby', '3.0.1'
gem 'faker', '1.0.1'
# gem 'will_paginate', '3.0.3'
# gem 'bootstrap-will_paginate', '0.0.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development do
  # gem 'sqlite3'
  gem 'thin'
  gem 'quiet_assets'
  gem 'bullet'
  gem "spring"
  gem 'awesome_print'
end

group :test do
  gem 'webmock'
  gem 'vcr'
  gem 'turn'
  gem 'rake'
end

group :production do
  gem 'rails_12factor'
end

gem 'pg', '0.15.1'
gem 'redis'

#gem 'devise', '2.2.3' # 2.2.3 still has token_authenticable
gem 'devise' # rails 4 requires newer version of devise
gem 'devise-token_authenticatable' # rails4, use this for backward compatibility
#gem 'devise_invitable', '1.1.7'
gem 'devise_invitable' # rails4 upg
gem 'devise-async'

gem 'httparty'
gem 'typhoeus'
gem 'hashie'
gem 'addressable'

gem 'protected_attributes' # rails4 gem

# Gems used only for assets and not required
# in production environments by default.
#group :assets do #rails4 removes assets group
  #gem 'sass-rails',   '~> 3.2.3'
  #gem 'sass-rails' #rails4 upg
  #gem 'coffee-rails', '~> 3.2.1'
  gem 'coffee-rails' #rails4 upg
  #gem 'bootstrap-sass', '2.0.4'
  #gem 'bootstrap-sass' #rails4 upg
  
  # gem 'bootstrap-sass', '~> 3.2.0'
  # gem 'sass-rails', '>= 3.2'
  
  gem 'sass-rails', '~> 4.0.2'
  gem 'bootstrap-sass', '~> 3.3.0'
  
  # gem 'simple_form', '~> 3.1.0.rc1' #, github: 'plataformatec/simple_form', branch: 'master'
  gem 'simple_form', '~> 3.1.0'
  
  gem 'font-awesome-sass'
  gem 'autoprefixer-rails'
  
  #gem "bootstrap-sass", "~> 3.1.1.0"
  #gem 'sass-rails', '~> 4.0.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  #gem 'uglifier', '>= 1.0.3'
  gem 'uglifier' #rails 4 upg
  #gem 'chosen-rails'
#end

gem 'traceroute', '~> 0.4.0'

gem 'jquery-rails'
gem 'kaminari'
gem 'kaminari-bootstrap'

#gem 'client_side_validations'
gem 'gon'

gem 'rails-settings-cached'
gem 'rabl'

gem 'paperclip', "~> 3.0"
gem 'rmagick'
gem 'delayed_paperclip'

gem 'aws-sdk'
gem 'aws-s3'

gem 'fast_seeder'
gem 'versioned_seeds'

#gem 'delayed_job_active_record', '0.4.4'
gem 'delayed_job_active_record' # rails4 upg
# gem 'hirefire-resource'
gem 'daemons'

gem 'urbanairship'

gem 'leaderboard'

gem 'rest-client'

gem 'zendesk_api'

gem 'simple_xlsx_reader'

gem 'play_billing_validator'

#gem 'posix-spawn' ## http://adamniedzielski.github.io/blog/2014/02/05/fighting-paperclip-errno-enomem-error/

# gem 'nokogiri'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'


Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.0.0)
      actionpack (= 4.0.0)
      mail (~> 2.5.3)
    actionpack (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
    activerecord (4.0.0)
      activemodel (= 4.0.0)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.0)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.3)
    activesupport (4.0.0)
      i18n (~> 0.6, >= 0.6.4)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    addressable (2.3.6)
    ansi (1.4.3)
    arel (4.0.2)
    autoprefixer-rails (3.1.2.20141016)
      execjs
    awesome_print (1.6.1)
    aws-s3 (0.6.3)
      builder
      mime-types
      xml-simple
    aws-sdk (1.57.0)
      aws-sdk-v1 (= 1.57.0)
    aws-sdk-v1 (1.57.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    bcrypt (3.1.9)
    bcrypt-ruby (3.0.1)
    bootstrap-sass (3.3.1.0)
      sass (~> 3.2)
    builder (3.1.4)
    bullet (4.14.0)
      activesupport (>= 3.0.0)
      uniform_notifier (>= 1.6.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.4)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.8.0)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    daemons (1.1.9)
    delayed_job (4.0.4)
      activesupport (>= 3.0, < 4.2)
    delayed_job_active_record (4.0.2)
      activerecord (>= 3.0, < 4.2)
      delayed_job (>= 3.0, < 4.1)
    delayed_paperclip (2.8.0)
      paperclip (>= 3.3)
    devise (3.4.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.9.0)
      devise (~> 3.2)
    devise-token_authenticatable (0.3.0)
      devise (~> 3.4.0)
    devise_invitable (1.4.0)
      actionmailer (>= 3.2.6, < 5)
      devise (>= 3.2.0)
    dotenv (0.11.1)
      dotenv-deployment (~> 0.0.2)
    dotenv-deployment (0.0.2)
    erubis (2.7.0)
    ethon (0.7.1)
      ffi (>= 1.3.0)
    eventmachine (1.0.3)
    execjs (2.2.2)
    faker (1.0.1)
      i18n (~> 0.4)
    faraday (0.9.1)
      multipart-post (>= 1.2, < 3)
    fast_seeder (0.1.0)
      rails (~> 4.0)
    ffi (1.9.6)
    font-awesome-sass (4.2.2)
      sass (~> 3.2)
    foreman (0.75.0)
      dotenv (~> 0.11.1)
      thor (~> 0.19.1)
    gon (5.2.0)
      actionpack (>= 2.3.0)
      json
      multi_json
      request_store (>= 1.0.5)
    hashie (3.3.1)
    hike (1.2.3)
    httparty (0.13.1)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.11)
    inflection (1.0.0)
    jquery-rails (3.1.2)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.1)
    kaminari (0.16.1)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kaminari-bootstrap (3.0.1)
      kaminari (>= 0.13.0)
      rails
    kgio (2.9.2)
    leaderboard (3.7.0)
      redis
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    mini_portile (0.6.0)
    minitest (4.7.5)
    multi_json (1.10.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    netrc (0.10.2)
    nokogiri (1.6.3.1)
      mini_portile (= 0.6.0)
    orm_adapter (0.5.0)
    paperclip (3.5.4)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.3)
      mime-types
    pg (0.15.1)
    play_billing_validator (0.0.3)
    polyglot (0.3.5)
    protected_attributes (1.0.3)
      activemodel (>= 4.0.0, < 5.0)
    puma (2.9.1)
      rack (>= 1.1, < 2.0)
    quiet_assets (1.0.3)
      railties (>= 3.1, < 5.0)
    rabl (0.11.2)
      activesupport (>= 2.3.14)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.0)
      actionmailer (= 4.0.0)
      actionpack (= 4.0.0)
      activerecord (= 4.0.0)
      activesupport (= 4.0.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.0)
      sprockets-rails (~> 2.0.0)
    rails-settings-cached (0.4.1)
      rails (>= 4.0.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.2)
    rails_stdout_logging (0.0.3)
    railties (4.0.0)
      actionpack (= 4.0.0)
      activesupport (= 4.0.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.13.0)
    rake (10.3.2)
    redis (3.1.0)
    request_store (1.1.0)
    responders (1.1.1)
      railties (>= 3.2, < 4.2)
    rest-client (1.7.2)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rmagick (2.13.3)
    rubyzip (1.1.7)
    safe_yaml (1.0.4)
    sass (3.2.19)
    sass-rails (4.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.0)
      sprockets (~> 2.8, <= 2.11.0)
      sprockets-rails (~> 2.0)
    simple_form (3.1.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    simple_xlsx_reader (1.0.2)
      nokogiri
      rubyzip
    spring (1.1.3)
    sprockets (2.11.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    thin (1.6.3)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    traceroute (0.4.0)
      rails (>= 3.0.0)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    turn (0.9.7)
      ansi
      minitest (~> 4)
    typhoeus (0.6.9)
      ethon (>= 0.7.1)
    tzinfo (0.3.42)
    uglifier (2.5.3)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unicorn (4.8.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    uniform_notifier (1.6.2)
    urbanairship (2.4.1)
      json
    vcr (2.9.3)
    versioned_seeds (0.5.2)
    warden (1.2.3)
      rack (>= 1.0)
    webmock (1.20.0)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
    xml-simple (1.1.4)
    zendesk_api (1.6.1)
      faraday (~> 0.9)
      hashie (>= 1.2, < 4.0)
      inflection
      mime-types
      multi_json
      multipart-post (~> 2.0)

PLATFORMS
  ruby

DEPENDENCIES
  addressable
  autoprefixer-rails
  awesome_print
  aws-s3
  aws-sdk
  bcrypt-ruby (= 3.0.1)
  bootstrap-sass (~> 3.3.0)
  bullet
  coffee-rails
  daemons
  delayed_job_active_record
  delayed_paperclip
  devise
  devise-async
  devise-token_authenticatable
  devise_invitable
  faker (= 1.0.1)
  fast_seeder
  font-awesome-sass
  foreman
  gon
  hashie
  httparty
  jquery-rails
  kaminari
  kaminari-bootstrap
  leaderboard
  paperclip (~> 3.0)
  pg (= 0.15.1)
  play_billing_validator
  protected_attributes
  puma
  quiet_assets
  rabl
  rails (= 4.0.0)
  rails-settings-cached
  rails_12factor
  rake
  redis
  rest-client
  rmagick
  sass-rails (~> 4.0.2)
  simple_form (~> 3.1.0)
  simple_xlsx_reader
  spring
  thin
  traceroute (~> 0.4.0)
  turn
  typhoeus
  uglifier
  unicorn
  urbanairship
  vcr
  versioned_seeds
  webmock
  zendesk_api
```

**Comment by segiddins** [comment]
Wow, bundler 1.3.5 predates even me! Can you try updating to 1.14.6, the latest bundler release?

**Comment by colby-swandale** [comment]
ping @fbaskara

**Comment by fbaskara** [comment]
Updating to bundler 1.14.6 seems to solve the problem. Thanks a lot!

**Comment by segiddins** [comment]
Glad to hear you were able to get everything working!

**Comment by Chris-Boyle** [comment]
Still seeing this issue

**Comment by colby-swandale** [comment]
@Chris-Boyle can you please open a new github issue with this report.

**Comment by Chris-Boyle** [comment]
@colby-swandale https://github.com/bundler/bundler/issues/5575
