### ISSUE TITLE
Bundler cannot run on Windows when username contains non-ASCII characters

### ISSUE THREAD

**Issue by galopin** [bundler/bundler#5566]
I have the following issue on my Windows set-up:

```
$ echo $HOME
/c/Documents and Settings/Michaël

$ bundle -v
C:/Ruby200/lib/ruby/site_ruby/2.0.0/rbreadline.rb:1097:in `<module:RbReadline>': HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory (RuntimeError)
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rbreadline.rb:17:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/readline.rb:10:in `<module:Readline>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/readline.rb:8:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/line_editor/readline.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/line_editor.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:8:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/vendored_thor.rb:3:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:4:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/exe/bundle:23:in `<top (required)>'
        from C:/Ruby200/bin/bundle:22:in `load'
        from C:/Ruby200/bin/bundle:22:in `<main>'
```

The problem comes from a patch that was applied years ago to the [Pure-Ruby Readline](https://github.com/ConnorAtherton/rb-readline) implementation — the original issue (https://github.com/ConnorAtherton/rb-readline/issues/8) was fixed by this pull request (https://github.com/ConnorAtherton/rb-readline/pull/89).

My HOME environment variable is _properly set_ and points to a _valid directory_ but I strongly suspect that `ENV['HOME']` string encoding gets somehow corrupted. And that Bundler cannot handle, as a consequence, such things as diacritic marks in Windows username — see [`user_home()`](https://github.com/bundler/bundler/blob/6e14ebe9f75506bddf623fb83d275deaaca8d8b8/lib/bundler.rb#L147-L167)  and [`tmp_home_path()`](https://github.com/bundler/bundler/blob/6e14ebe9f75506bddf623fb83d275deaaca8d8b8/lib/bundler.rb#L169-L181).

BTW, I found [another issue](https://bugs.ruby-lang.org/issues/9715) on the Ruby trunk which might be related .

Is there anything you can do to improve this situation?

**Comment by segiddins** [comment]
This looks like an issue with Readline? I don't really see how this issue is particular to bundler

**Comment by galopin** [comment]
@segiddins  If I ran the following Ruby script, no exception is raised yet the [assign and if statements](https://github.com/ConnorAtherton/rb-readline/blob/master/lib/rbreadline.rb#L1095-L1098) are taken directly from Readline.

```
p ENV['HOME']
p ENV['HOME'].encoding
p ENV['HOME'].bytes

puts '--'

ENV["HOME"] ||= "#{ENV["HOMEDRIVE"]}#{ENV["HOMEPATH"]}"
if !File.directory? ENV['HOME']
  raise RuntimeError.new('HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory')
end
```

yields:

```
"C:\\Documents and Settings\\Micha\x89l"
#<Encoding:CP850>
[67, 58, 92, 68, 111, 99, 117, 109, 101, 110, 116, 115, 32, 97, 110, 100, 32, 83, 101, 116, 116, 105, 110, 103, 115, 92, 77, 105, 99, 104, 97, 137, 108]
--
```

So IMHO Readline does not seem to be the culprit. Having non-ASCII in a Windows username seems to be a real impediment, [pip](https://github.com/pfmoore/pip/blob/7aa8528747d7a8a01f22a981e0b524edc7075ee3/CHANGES.txt#L44-L45) and [boto](https://github.com/boto/botocore/pull/1170) were plagued by the same issue until recently…

If it happens with Python-based tools, surely there must be the same kind of issue with Ruby-based tools. I'm not sure Bundler is responsible for this -- is it Thor? -- but I bet you are better informed than me on the innards of Bundler.

All I can say is that I patched Readline to bypass the exception statement and that Bundler complains loudly hereafter that my home directory is not writable:

```
$ bundle
C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:179:in `rescue in tmp_home_path': `C:/Documents and Settings/MichaÙl` is not writable. (Encoding::CompatibilityError)
Bundler also failed to create a temporary home directory at `C:/Documents and Settings/MichaÙl/Local Settings/Application Data/Temp/bundler/home':
incompatible character encodings: Windows-1252 and UTF-8
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:169:in `tmp_home_path'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:159:in `user_home'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:183:in `user_bundle_path'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/settings.rb:288:in `global_config_file'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/settings.rb:49:in `initialize'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:248:in `new'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:248:in `rescue in settings'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler.rb:246:in `settings'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/env.rb:32:in `report'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:95:in `request_issue_report_for'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:45:in `log_error'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
        from C:/Ruby200/bin/bundle:22:in `load'
        from C:/Ruby200/bin/bundle:22:in `<main>'
```

As you can see, Bundler exception displays my `HOME` directory as `C:/Documents and Settings/MichaÙl` instead of `C:/Documents and Settings/Michaël`. And reports incompatible character encodings: Windows-1252 and UTF-8.

You and your fellow developers should conduct some tests and verify why Bundler cannot run in this situation. And hopefully fix this in the near future.

Thank you.

**Comment by segiddins** [comment]
But can you `require "readline"` without the exception being raised?

**Comment by galopin** [comment]
Yup. Inserting `require "readline"` at the very top of the sample script does not raise the exception…

**Comment by segiddins** [comment]
Cool, someone with a Windows machine handy will have to look into this

**Comment by galopin** [comment]
@segiddins @colby-swandale @indirect Samuel, Colby, can we involve André on this topic? I'm aware that Ruby is far from being the perfect language for handling UTF-8 strings but I'd like to know if this annoying issue — see Puppet issue \#6034 “[Bundler Fails when Running Under a Unicode Windows User](https://tickets.puppetlabs.com/browse/PUP-6034)” — can be fixed at the userland level. Thank you.

**Comment by colby-swandale** [comment]
@galopin I'm positive this issue can be resolved, the problem is that none of the core team run Windows. So we're not really able to spend time looking into this issue.

> Cool, someone with a Windows machine handy will have to look into this

**Comment by galopin** [comment]
@colby-swandale @segiddins Understood. In the meantime, you might want to have a look at how Puppet solved its numerous encoding issues with environment variables on Windows — please see:

- PUP-5726 "[Support Windows Unicode env vars](https://tickets.puppetlabs.com/browse/PUP-5726)"  
    ; [pull request \#4592](https://github.com/puppetlabs/puppet/pull/4592) and [subsequent commit](https://github.com/puppetlabs/puppet/commit/7e9a8fcc92c256121f4cb92fd7e2fe528febde96)
- PUP-5768 "[Fix problematic usage of ENV for Windows](https://tickets.puppetlabs.com/browse/PUP-5768)"
    ; [pull request \#4764](https://github.com/puppetlabs/puppet/pull/4764) and [subsequent commit](https://github.com/puppetlabs/puppet/pull/4764/commits/e86bdccb1d39f0ee40e17729412d2c412cb5d1fd)

I wonder if Puppet folks could devote some time to fix this issue in Bundler codebase…

**Comment by indirect** [comment]
@galopin Hi. Both @segiddins and @colby-swandale are members of the Bundler core team, so it comes across as a disrespectful jerk move to demand that you want to hear from me instead of them.

As for this particular issue, it looks to me like something that needs to be resolved upstream, either in readline or in ruby itself. Your approach in this ticket has been both demanding and rude, repeatedly refusing to listen to the responses that you've already gotten from the core team. The combination of those things means this issue is not a high priority for any of us to look at.

**Comment by galopin** [comment]
@indirect Hi André, sorry but it would seem you pick up this thread on the wrong foot. I didn't mean to be rude or disrespectful at all. Inquisitive, sure. As you expressed some doubts in the past about the Ruby capacity to handle UTF-8 strings properly, I though it was a good idea to get your input on this particular topic. Looks like I was mistaken 😕 As a final note, you shouldn't jump to conclusions and blame me for wanting to solve such a blocking issue on Windows ⁉️

**Comment by indirect** [comment]
@galopin I don't blame you for wanting to solve the issue. Reporting the problem: good. Including instructions to reproduce the problem: good. Links to similar problems: good.

Asking me to join the thread after the core team already responded to you: not good. Telling us to look at puppet tickets after we told you we can't fix it ourselves: not good. Asking us if the puppet team will fix it: not good.

This is a problem, and we would like to fix it. It is not even clear yet if this is a problem in Bundler, so investigating whether this can be fixed in Bundler or whether it needs to be fixed in Readline, or perhaps even in Ruby itself, would be an actively helpful thing you could do.

Even more helpful would be to work on a PR to fix this issue, if the problem is in fact in Bundler. As we've already said, we would be happy to support anyone who wants to work on a fix for this issue.

I hope that helps.

**Comment by galopin** [comment]
@segiddins @colby-swandale @indirect I've done my homework and devised a hotfix that allowed me to run Bundler from the command line on my Windows set-up❗️

Here's what I did. First, I backed up the following source files:

```bash
$ pushd /c/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.14.6/lib
$ perl -i~ -wple '' bundler.rb
$ perl -i~ -wple '' bundler/rubygems_integration.rb
$ subl bundler.rb bundler/rubygems_integration.rb
$ popd
```
Then I performed two slight changes in:

1. `bundler.rb`
    ; see [highlighted source](https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L20) in master branch

```diff
$ diff -u bundler.rb~ bundler.rb
--- bundler.rb~ 2017-03-28 18:40:53.033125400 +0200
+++ bundler.rb  2017-05-19 17:25:40.170392700 +0200
@@ -17,7 +17,7 @@
 module Bundler
   environment_preserver = EnvironmentPreserver.new(ENV, %w(PATH GEM_PATH))
   ORIGINAL_ENV = environment_preserver.restore
-  ENV.replace(environment_preserver.backup)
+  ENV = environment_preserver.backup
   SUDO_MUTEX = Mutex.new

   autoload :Definition,             "bundler/definition"
```
> Doing this prevents `$ENV['HOME'].encoding` to be changed from `#<Encoding:CP850>` to `#<Encoding:ASCII-8BIT>`.

2. in `bundler/rubygems_integration.rb`
    ; see [highlighted source](https://github.com/bundler/bundler/blob/master/lib/bundler/rubygems_integration.rb#L145-L147) in master branch

```diff
$ diff -u bundler/rubygems_integration.rb~ bundler/rubygems_integration.rb
--- bundler/rubygems_integration.rb~    2017-03-28 18:40:53.173346600 +0200
+++ bundler/rubygems_integration.rb     2017-05-19 16:59:13.151341100 +0200
@@ -135,7 +135,7 @@
     end

     def user_home
-      Gem.user_home
+      Gem.user_home.encode('UTF-8')
     end

     def gem_path
```
> Doing this prevents `Bundler.rubygems.user_home.encoding` to be set to `#<Encoding:Windows-1252>`, aka `CP 1252`. I have absolutely no idea why `Gem.user_home.encoding` (`CP 1252`) differs from `$ENV['HOME'].encoding` (`CP 850`) ⁉️ 

Then back to the command line:

```
$ jekyll new yet-another-site
Running bundle install in C:/Documents and Settings/Michaël/Mes documents/Jekyll/yet-another-site...
  Bundler: `C:/Documents and Settings/Micha├½l` is not writable.
  Bundler: Bundler will use `C:/DOCUME~1/MICHAL~1/LOCALS~1/Temp/bundler/home/Micha├½l' as your home directory temporarily.
  Bundler: Fetching gem metadata from https://rubygems.org/...........
  Bundler: Fetching version metadata from https://rubygems.org/..
  Bundler: Fetching dependency metadata from https://rubygems.org/.
  Bundler: Resolving dependencies...
  Bundler: Using public_suffix 2.0.5
  Bundler: Using colorator 1.1.0
  Bundler: Using ffi 1.9.18 (x86-mingw32)
  Bundler: Using forwardable-extended 2.6.0
  Bundler: Installing sass 3.4.24
  Bundler: Installing rb-fsevent 0.9.8
  Bundler: Using kramdown 1.13.2
  Bundler: Using liquid 3.0.6
  Bundler: Using mercenary 0.3.6
  Bundler: Using rouge 1.11.1
  Bundler: Using safe_yaml 1.0.4
  Bundler: Using thread_safe 0.3.6
  Bundler: Using bundler 1.14.6
  Bundler: Installing addressable 2.5.1
  Bundler: Installing rb-inotify 0.9.8
  Bundler: Using pathutil 0.14.0
  Bundler: Using jekyll-sass-converter 1.5.0
  Bundler: Using tzinfo 1.2.3
  Bundler: Using listen 3.0.8
  Bundler: Using tzinfo-data 1.2017.2
  Bundler: Using jekyll-watch 1.5.0
  Bundler: Using jekyll 3.4.3
  Bundler: Installing jekyll-feed 0.9.2
  Bundler: Installing minima 2.1.1
  Bundler: Bundle complete! 4 Gemfile dependencies, 24 gems now installed.
  Bundler: Use `bundle show [gemname]` to see where a bundled gem is installed.
New jekyll site installed in C:/Documents and Settings/Michaël/Mes documents/Jekyll/yet-another-site.

$ cat yet-another-siteGemfile
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.4.3"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

$ cat yet-another-site/Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    colorator (1.1.0)
    ffi (1.9.18-x86-mingw32)
    forwardable-extended (2.6.0)
    jekyll (3.4.3)
      addressable (~> 2.4)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-feed (0.9.2)
      jekyll (~> 3.3)
    jekyll-sass-converter (1.5.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.13.2)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    minima (2.1.1)
      jekyll (~> 3.3)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    public_suffix (2.0.5)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.8)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.24)
    thread_safe (0.3.6)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    tzinfo-data (1.2017.2)
      tzinfo (>= 1.0.0)

PLATFORMS
  x86-mingw32

DEPENDENCIES
  jekyll (= 3.4.3)
  jekyll-feed (~> 0.6)
  minima (~> 2.0)
  tzinfo-data

RUBY VERSION
   ruby 2.0.0p648

BUNDLED WITH
   1.14.6
```
> Bundler created the _correct_ directory in my temporary folder `C:\Documents and Settings\Michaël\Local Settings\Temp\bundler\home\Michaël` _despite_ the gibberish in Jekyll command ouput above…

Voilà! Of course, this is not a pull request per se but it is a start.

**Comment by ajwann** [comment]
@galopin If you upgrade to Ruby 2.5.x do you still encounter this issue? I'm trying to reproduce the problem with no luck, and I'm currently on 2.5.

**Comment by galopin** [comment]
@ajwann Adam, running Ruby 2.5.x under Windows is not really a very recommended set-up. Does the Bundler team has an AppVeyor build environment in working condition? If yes, it would be great to be able to check if Bundler effectively works "as is" with earlier versions of Ruby when the username contains non-ASCII characters.

The problem originates from this specific statement where Ruby mangles the encoding of bytes stored in `ENV` hash variable — especially `$ENV['HOME']`:

https://github.com/bundler/bundler/blob/c5305b031074fe78d52c130e80d2e6ea8545a505/lib/bundler.rb#L20

The [above hotfix](#issuecomment-302752683) works for me but I'm in no position to tell if it would work for others 😕 

Perhaps Ruby 2.5 has seen some most welcome internal changes. I dunno. To be quite candid, I pretty much gave up on Ruby and switched focus to Python 3, which behaves [much](https://www.python.org/dev/peps/pep-0528/)  [better](https://www.python.org/dev/peps/pep-0529/) on various Windows environments…

**Comment by viktorija** [comment]
I'm facing the same issue. The above hotfix didn't work for me. :/ What's worse, I'm unable to change username (company policies).
