### ISSUE TITLE
Not a directory @ rb_sysopen - bin/pry

### ISSUE THREAD

**Issue by yuiopt** [bundler/bundler#5586]
# Error Report

## Backtrace

```
Errno::ENOTDIR: Not a directory @ rb_sysopen - bin/pry
  /Users/myuser/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:2830:in `read'
  /Users/myuser/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:2830:in `block in validate'
  /Users/myuser/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:2828:in `each'
  /Users/myuser/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:2828:in `validate'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:60:in `block in validate'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/ui/shell.rb:124:in `with_level'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/ui/shell.rb:83:in `silence'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:60:in `validate'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/source/path.rb:158:in `block in load_spec_files'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/source/path.rb:152:in `each'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/source/path.rb:152:in `load_spec_files'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/source/git.rb:193:in `load_spec_files'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/source/path.rb:97:in `local_specs'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/source/git.rb:161:in `specs'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/lazy_specification.rb:75:in `__materialize__'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/spec_set.rb:83:in `block in materialize'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/definition.rb:216:in `missing_dependencies'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/installer.rb:219:in `block in resolve_if_need'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/ui/shell.rb:124:in `with_level'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/ui/shell.rb:83:in `silence'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/installer.rb:216:in `resolve_if_need'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/installer.rb:78:in `run'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli/install.rb:70:in `run'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:181:in `block in install'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/settings.rb:99:in `temporary'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:180:in `install'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /Users/myuser/.rvm/gems/ruby-2.4.1/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
  /Users/myuser/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
  /Users/myuser/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
  /Users/myuser/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  /Users/myuser/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
GEM_HOME  /Users/myuser/.rvm/gems/ruby-2.4.1
GEM_PATH  /Users/myuser/.rvm/gems/ruby-2.4.1:/Users/myuser/.rvm/gems/ruby-2.4.1@global
RVM       1.27.0 (latest)
Git       2.8.4 (Apple Git-73)
Platform  x86_64-darwin-16
OpenSSL   OpenSSL 1.0.2k  26 Jan 2017
rubygems-bundler (1.4.4)
```
```

**Comment by segiddins** [comment]
Could you please also share your Gemfile? Thanks!

**Comment by yuiopt** [comment]
@segiddins OK,the Gemfile actually  is in the Metafploit Framework root dir, and I uninstalled ruby-2.4.1 using rvm command ,The error just gone.
