### ISSUE TITLE
symlink function is unimplemented on this machine

### ISSUE THREAD

**Issue by Jorge199** [bundler/bundler#5604]
symlink() function is unimplemented on this machine
I tried install these gems on my project

```ruby
gem 'spree', '~> 3.2.0'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'
```

i use windows 10

**Comment by colby-swandale** [comment]
Sorry that you're having trouble with Bundler. Can you please provide more information about your problem to help us diagnose you're problem.

Mainly a stack trace when you run bundler and the output of `bundle env`.

Thanks

**Comment by bodrovis** [comment]
@colby-swandale I started to see this error today on Windows machine as well. I have a Rails 5 project and when I do `bundle update` this error appears (everything was working yesterday):

```
NotImplementedError: symlink() function is unimplemented on this machine
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:388:in `symlink'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:388:in `block (2 levels) in extract_tar_gz'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:65:in `each'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:365:in `block in extract_tar_gz'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:459:in `block in open_tar_gz'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:456:in `wrap'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:456:in `open_tar_gz'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:364:in `extract_tar_gz'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:345:in `block (2 levels) in extract_files'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:65:in `each'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:342:in `block in extract_files'
  F:/Ruby225/lib/ruby/2.2.0/open-uri.rb:36:in `open'
  F:/Ruby225/lib/ruby/2.2.0/open-uri.rb:36:in `open'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:30:in `with_read_io'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:339:in `extract_files'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:772:in `extract_files'
  F:/Ruby225/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:302:in `install'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:145:in `block in install'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:187:in `preserve_paths'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:135:in `install'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/installer/gem_installer.rb:55:in `install'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:114:in `block in worker_pool'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/worker.rb:63:in `call'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/worker.rb:63:in `apply_func'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/worker.rb:58:in `block in process_queue'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
  F:/Ruby225/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]
GEM_HOME  F:/Ruby225/lib/ruby/gems/2.2.0
GEM_PATH  F:/Ruby225/lib/ruby/gems/2.2.0;C:/Users/supreme/.gem/ruby/2.2.0
Git       2.9.0.windows.1
Platform  x86-mingw32
OpenSSL   OpenSSL 1.0.1l 15 Jan 2015
```

## Bundler settings

```
build.nokogiri
  Set for the current user (C:/Users/supreme/.bundle/config): "--use-system-libraries"
```

I've read this file https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md but it did not help - I am still getting the error after I do `bundle update`. I think this is somehow caused by the new version of the `haml` gem (version 5 was released yesterday). At least, setting 

```ruby
gem 'haml', '~> 4.0.7'
```

in the Gemfile fixes this problem.

**Comment by bodrovis** [comment]
`bundle env`: 

## Environment

```
Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]
Git       2.9.0.windows.1
Platform  x86-mingw32
```

## Bundler settings

```
build.nokogiri
  Set for the current user (C:/Users/supreme/.bundle/config): "--use-system-libraries"
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'
#ruby "2.3.1"

# force ssl to fetch from github
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Core
gem 'rails', '5.0.2'
gem 'puma'

# Assets
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 3.1.1'
gem 'coffee-rails', '~> 4.2'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'turbolinks', '~> 5.x'
gem 'jquery-rails'
# TODO: update to 5 after this issue is resolved:
# https://github.com/bundler/bundler/issues/5604#issuecomment-297706501
#gem 'haml', '~> 4.0.7'

# Auth
gem "devise", '~> 4.2'
gem 'cancancan'

# Payments
# TODO: update to 2.74
gem "braintree", '~> 2.73'

# DB and friends
gem 'pg', '~> 0.15'
gem 'redis', '~> 3.0'
gem 'kaminari', '>= 1'

# Files
gem "shrine"
gem "aws-sdk", "~> 2.1"
gem 'mimemagic'

# Performance Monitoring
gem 'newrelic_rpm'

# background processing
# TODO: update to 5
gem 'sidekiq', '~> 4.2'

# Admin
gem 'rails_admin', github: 'sferik/rails_admin' # current stable version has outdated kaminari
# as soon as a new stable is released, :github option must be removed

# Various
gem 'jbuilder', '~> 2.0'
gem "figaro"

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'byebug'
  gem 'pry-rails'
  gem 'mocha'
end

group :development do
  gem 'web-console', '~> 3.0'
  gem 'spring'
  gem 'annotate' # annotate your models
  gem 'lol_dba' # find missing indexes
  gem 'letter_opener'
  gem 'better_errors'
  gem 'binding_of_caller'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by segiddins** [comment]
It looks like you're installing a gem that includes symlinks on an FS that does not support them

**Comment by bodrovis** [comment]
Well, as I said setting haml back to version 4 fixes it, so probably I should report it in the haml's repo?..

**Comment by segiddins** [comment]
Probably

**Comment by bodrovis** [comment]
**For people who are getting this error with Haml 5**:

I was able to solve it by updating Ruby to 2.3.3 x32. Probably unrelated, but I also updated OpenSSL and Git (enabled symlinks in the options).
