### ISSUE TITLE
Exceeding max allowed process count  on accounts with limits.

### ISSUE THREAD

**Issue by HugeTerrificSpider** [bundler/bundler#5607]
On web hosting server ( paid remote server ) I cannot build libv8, because building system runs out of available processes. Process limit is set to fixed value on that account. So far I see no way to pass that limit to bundler and building system runs out of available processes count and aborts because of that.

bundle env

## Environment

```
Bundler   1.14.6
Rubygems  2.6.10
Ruby      2.2.6p396 (2016-11-15 revision 56800) [x86_64-freebsd10.3]
GEM_HOME  /home/server_user/.rvm/gems/ruby-2.2.6
GEM_PATH  /home/server_user/.rvm/gems/ruby-2.2.6:/home/server_user/.rvm/gems/ruby-2.2.6@global
RVM       1.28.0 (latest)
Git       2.11.0
Platform  x86_64-freebsd-10
```

## Bundler settings

```
build.charlock_holmes
  Set for your local app (/usr/home/server_user/.bundle/config): "--with-icu-dir=/usr/local"
  Set for the current user (/home/server_user/.bundle/config): "--with-icu-dir=/usr/local"
build.nokogiri
  Set for your local app (/usr/home/server_user/.bundle/config): "--with-xml2-include=/usr/local/libxml2 --with-xml2-lib=/usr/local/lib/ --with-iconv-include=/usr/local/include --with-iconv-lib=/usr/local/lib --use-system-libraries,"
  Set for the current user (/home/server_user/.bundle/config): "--with-xml2-include=/usr/local/libxml2 --with-xml2-lib=/usr/local/lib/ --with-iconv-include=/usr/local/include --with-iconv-lib=/usr/local/lib --use-system-libraries,"
```

**Comment by segiddins** [comment]
Bundler itself doesn't spawn subprocesses, except for `git` and building native extensions (which is really done by RubyGems). Can you share the backtrace where bundler is aborting?

**Comment by HugeTerrificSpider** [comment]
@segiddins 
```
$ cat Gemfile 
gem "libv8", github: "cowboyd/libv8", submodules: true

$ bundle install
The git source `git://github.com/cowboyd/libv8.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/cowboyd/libv8.git
Submodule 'vendor/depot_tools' (https://chromium.googlesource.com/chromium/tools/depot_tools.git) registered for path 'vendor/depot_tools'
Cloning into '/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools'...
Resolving dependencies...
Using libv8 5.7.492.65.0beta1 from git://github.com/cowboyd/libv8.git (at master@c0d4233)
Using bundler 1.14.6
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/ext/libv8
/home/spider/.rvm/rubies/ruby-2.3.3/bin/ruby -r ./siteconf20170424-52099-13q2vw5.rb extconf.rb
creating Makefile

v8/third_party/instrumented_libraries (ERROR)
----------------------------------------
[0:00:50] Started.
[0:00:50] 
Traceback (most recent call last):
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_scm.py", line 908, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_scm.py", line 1197, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_utils.py", line 303, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_utils.py", line 498, in CheckCallAndFilter
    **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/subprocess2.py", line 262, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 35] Resource temporarily unavailable.
Check that /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor or git exist and have execution permission.
----------------------------------------
Traceback (most recent call last):
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient.py", line 2129, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient.py", line 2115, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient.py", line 1877, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient.py", line 1364, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_utils.py", line 1048, in run
    self.item.run(*self.args, **self.kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient.py", line 773, in run
    file_list)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_scm.py", line 156, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_scm.py", line 438, in update
    self._Clone(revision, url, options)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_scm.py", line 908, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_scm.py", line 1197, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_utils.py", line 303, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/gclient_utils.py", line 498, in CheckCallAndFilter
    **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/subprocess2.py", line 262, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 35] Resource temporarily unavailable.
Check that /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor or git exist and have execution permission.
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/fetch.py", line 300, in <module>
    sys.exit(main())
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/fetch.py", line 295, in main
    return run(options, spec, root)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/fetch.py", line 289, in run
    return checkout.init()
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/fetch.py", line 132, in init
    self.run_gclient(*sync_cmd)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/vendor/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/ext/libv8/builder.rb:113:in `block in setup_build_deps!': unable to fetch v8 source
(RuntimeError)
	from /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/ext/libv8/builder.rb:111:in `chdir'
	from /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/ext/libv8/builder.rb:111:in `setup_build_deps!'
	from /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/ext/libv8/builder.rb:67:in `build_libv8!'
	from /usr/home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/libv8-c0d4233fdd37 for inspection.
Results logged to /home/spider/.rvm/gems/ruby-2.3.3/bundler/gems/extensions/x86_64-freebsd-10/2.3.0/libv8-c0d4233fdd37/gem_make.out

An error occurred while installing libv8 (5.7.492.65.0beta1), and Bundler cannot continue.

```

**Comment by HugeTerrificSpider** [comment]
`OSError: Execution failed with error: [Errno 35] Resource temporarily unavailable.`

I suppose it's caused by max processes limit set for my account.

**Comment by segiddins** [comment]
Does `gem install libv8` succeed for you?

**Comment by HugeTerrificSpider** [comment]
@segiddins 

```
$ gem install libv8
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    current directory: /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/ext/libv8
/home/spide/.rvm/rubies/ruby-2.2.6/bin/ruby -r ./siteconf20170424-25391-1h47ct5.rb extconf.rb
creating Makefile

v8/third_party/icu (ERROR)
----------------------------------------
[0:01:05] Started.
[0:01:05] 
Traceback (most recent call last):
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_scm.py", line 962, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_scm.py", line 1249, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_utils.py", line 293, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_utils.py", line 557, in CheckCallAndFilter
    **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/subprocess2.py", line 262, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 35] Resource temporarily unavailable.
Check that /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor or git exist and have execution permission.
----------------------------------------
Traceback (most recent call last):
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient.py", line 2360, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient.py", line 2346, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient.py", line 2099, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient.py", line 1550, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_utils.py", line 1112, in run
    self.item.run(*self.args, **self.kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient.py", line 850, in run
    file_list)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_scm.py", line 166, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_scm.py", line 450, in update
    self._Clone(revision, url, options)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_scm.py", line 962, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_scm.py", line 1249, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_utils.py", line 293, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/gclient_utils.py", line 557, in CheckCallAndFilter
    **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/subprocess2.py", line 262, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 35] Resource temporarily unavailable.
Check that /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor or git exist and have execution permission.
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "managed": False,
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 353, in <module>
    sys.exit(main())
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 348, in main
    return run(options, spec, root)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 342, in run
    return checkout.init()
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:109:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:107:in `chdir'
	from /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:107:in `setup_build_deps!'
	from /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:63:in `build_libv8!'
	from /usr/home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/spide/.rvm/gems/ruby-2.2.6/gems/libv8-5.3.332.38.5 for inspection.
Results logged to /home/spide/.rvm/gems/ruby-2.2.6/extensions/x86_64-freebsd-10/2.2.0/libv8-5.3.332.38.5/gem_make.out
```

**Comment by ignisf** [comment]
Hello, libv8 maintainer here. This really does not look like an issue with Bundler. Seems to me it's due to Google's `depot_tools` spawning a bunch of processes to fetch `v8` and its dependencies' sources.

**Comment by segiddins** [comment]
Agreed -- thanks for confirming @ignisf !
