### ISSUE TITLE
Fail to load native extension when using custom git source and having an existing cache

### ISSUE THREAD

**Issue by Soulou** [bundler/bundler#5648]
This issue may look like to #4106 but as stated, I decided to open a new issue, here is the workflow to reproduce the bug. I've reproduced it with version on the 1.13 branch and 1.14 branch

1. Create a new rails project

```
rails new bundler-test
cd bundler-test
```

2. Add the following gem in your Gemfile:

```
gem 'ox', git: 'https://github.com/hiptest/ox.git', branch: 'add_tolerant_mode_to_builder'  # Fast XML reader/writer
```

3. Run bundler to freeze deps:

```
bundle install
```

4. Run bundler in deployment mode:

```
bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
```

Here the `.so` file is built correctly, as a static library:

```
└> ls -ld vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so
-rwxr-xr-x 1 leo leo 997064 May  9 15:39 vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so
┌[leo☮soulou7]-(~/Scalingo/SampleProjects/sample-ruby-ox)-[git://master ✗]-
└> ldd vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so
	linux-vdso.so.1 (0x00007ffc8cb4e000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f840811d000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f8407e8a000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f8407c86000)
	libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007f8407a4e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f840773b000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8407395000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x0000558cbbd93000)
```

The environment car be loaded correctly:

```
└> bundle exec rake -P
rake about
...
```

5. RE-Run bundler

```
bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
```

The file is now different as well as its dependencies

```
└> ls -ld vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so                                   
-rwxr-xr-x 1 leo leo 1003058 May  9 15:41 vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so
┌[leo☮soulou7]-(~/Scalingo/SampleProjects/sample-ruby-ox)-[git://master ✗]-
└> ldd vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so   
	linux-vdso.so.1 (0x00007ffc31be3000)
	libruby.so.2.3 => not found
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff54c54c000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007ff54c1a8000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000055cf19eb6000)
```

And obviously the environment does not load anymore:

```
└> bundle exec rake -P
rake aborted!
LoadError: libruby.so.2.3: cannot open shared object file: No such file or directory - sample-ruby-ox/vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so
sample-ruby-ox/vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/lib/ox.rb:79:in `require'
sample-ruby-ox/vendor/bundle/ruby/2.3.0/bundler/gems/ox-8211624ae976/lib/ox.rb:79:in `<top (required)>'
sample-ruby-ox/config/application.rb:7:in `<top (required)>'
sample-ruby-ox/Rakefile:4:in `require_relative'
```

So the `bundle install` operation is not repeatable here, it looks like a bug from bundler to me.

**Comment by colby-swandale** [comment]
Thanks for reporting this issue. I can't recreate this issue using the steps but can you please attach the output of `bundle env` so we can get some information about your environment.

**Comment by Soulou** [comment]
Here it is:

```
└> bundle env
Environment

    Bundler   1.13.6
    Rubygems  2.5.2
    Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
    Git       2.12.2

Bundler settings

    frozen
      Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "1"
    path
      Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "vendor/bundle"
    bin
      Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "vendor/bundle/bin"
    jobs
      Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "4"
    without
      Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "development:test"
    disable_shared_gems
      Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "true"

Gemfile

    source 'https://rubygems.org'
    
    git_source(:github) do |repo_name|
      repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
      "https://github.com/#{repo_name}.git"
    end
    
    
    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '~> 5.0.2'
    # Use sqlite3 as the database for Active Record
    gem 'sqlite3'
    # Use Puma as the app server
    gem 'puma', '~> 3.0'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.2'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby
    
    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
    gem 'turbolinks', '~> 5'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.5'
    # Use Redis adapter to run Action Cable in production
    # gem 'redis', '~> 3.0'
    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'
    
    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development
    
    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug', platform: :mri
    end
    
    group :development do
      # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
      gem 'web-console', '>= 3.3.0'
      gem 'listen', '~> 3.0.5'
      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'
      gem 'spring-watcher-listen', '~> 2.0.0'
    end
    
    # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
    
    gem 'ox', git: 'https://github.com/hiptest/ox.git', branch: 'add_tolerant_mode_to_builder'  # Fast XML reader/writer

Gemfile.lock

    GIT
      remote: https://github.com/hiptest/ox.git
      revision: 8211624ae9764c5fc147e1450850fde46f339ab1
      branch: add_tolerant_mode_to_builder
      specs:
        ox (2.4.13)
    
    GEM
      remote: https://rubygems.org/
      specs:
        actioncable (5.0.2)
          actionpack (= 5.0.2)
          nio4r (>= 1.2, < 3.0)
          websocket-driver (~> 0.6.1)
        actionmailer (5.0.2)
          actionpack (= 5.0.2)
          actionview (= 5.0.2)
          activejob (= 5.0.2)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 2.0)
        actionpack (5.0.2)
          actionview (= 5.0.2)
          activesupport (= 5.0.2)
          rack (~> 2.0)
          rack-test (~> 0.6.3)
          rails-dom-testing (~> 2.0)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        actionview (5.0.2)
          activesupport (= 5.0.2)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 2.0)
          rails-html-sanitizer (~> 1.0, >= 1.0.3)
        activejob (5.0.2)
          activesupport (= 5.0.2)
          globalid (>= 0.3.6)
        activemodel (5.0.2)
          activesupport (= 5.0.2)
        activerecord (5.0.2)
          activemodel (= 5.0.2)
          activesupport (= 5.0.2)
          arel (~> 7.0)
        activesupport (5.0.2)
          concurrent-ruby (~> 1.0, >= 1.0.2)
          i18n (~> 0.7)
          minitest (~> 5.1)
          tzinfo (~> 1.1)
        arel (7.1.4)
        bindex (0.5.0)
        builder (3.2.3)
        byebug (9.0.6)
        coffee-rails (4.2.1)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.2.x)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.12.2)
        concurrent-ruby (1.0.5)
        erubis (2.7.0)
        execjs (2.7.0)
        ffi (1.9.18)
        globalid (0.4.0)
          activesupport (>= 4.2.0)
        i18n (0.8.1)
        jbuilder (2.6.3)
          activesupport (>= 3.0.0, < 5.2)
          multi_json (~> 1.2)
        jquery-rails (4.3.1)
          rails-dom-testing (>= 1, < 3)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        listen (3.0.8)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)
        loofah (2.0.3)
          nokogiri (>= 1.5.9)
        mail (2.6.5)
          mime-types (>= 1.16, < 4)
        method_source (0.8.2)
        mime-types (3.1)
          mime-types-data (~> 3.2015)
        mime-types-data (3.2016.0521)
        mini_portile2 (2.1.0)
        minitest (5.10.1)
        multi_json (1.12.1)
        nio4r (2.0.0)
        nokogiri (1.7.1)
          mini_portile2 (~> 2.1.0)
        puma (3.8.2)
        rack (2.0.1)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (5.0.2)
          actioncable (= 5.0.2)
          actionmailer (= 5.0.2)
          actionpack (= 5.0.2)
          actionview (= 5.0.2)
          activejob (= 5.0.2)
          activemodel (= 5.0.2)
          activerecord (= 5.0.2)
          activesupport (= 5.0.2)
          bundler (>= 1.3.0, < 2.0)
          railties (= 5.0.2)
          sprockets-rails (>= 2.0.0)
        rails-dom-testing (2.0.2)
          activesupport (>= 4.2.0, < 6.0)
          nokogiri (~> 1.6)
        rails-html-sanitizer (1.0.3)
          loofah (~> 2.0)
        railties (5.0.2)
          actionpack (= 5.0.2)
          activesupport (= 5.0.2)
          method_source
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (12.0.0)
        rb-fsevent (0.9.8)
        rb-inotify (0.9.8)
          ffi (>= 0.5.0)
        sass (3.4.23)
        sass-rails (5.0.6)
          railties (>= 4.0.0, < 6)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (>= 1.1, < 3)
        spring (2.0.1)
          activesupport (>= 4.2)
        spring-watcher-listen (2.0.1)
          listen (>= 2.7, < 4.0)
          spring (>= 1.2, < 3.0)
        sprockets (3.7.1)
          concurrent-ruby (~> 1.0)
          rack (> 1, < 3)
        sprockets-rails (3.2.0)
          actionpack (>= 4.0)
          activesupport (>= 4.0)
          sprockets (>= 3.0.0)
        sqlite3 (1.3.13)
        thor (0.19.4)
        thread_safe (0.3.6)
        tilt (2.0.7)
        turbolinks (5.0.1)
          turbolinks-source (~> 5)
        turbolinks-source (5.0.0)
        tzinfo (1.2.3)
          thread_safe (~> 0.1)
        uglifier (3.2.0)
          execjs (>= 0.3.0, < 3)
        web-console (3.5.0)
          actionview (>= 5.0)
          activemodel (>= 5.0)
          bindex (>= 0.4.0)
          railties (>= 5.0)
        websocket-driver (0.6.5)
          websocket-extensions (>= 0.1.0)
        websocket-extensions (0.1.2)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      byebug
      coffee-rails (~> 4.2)
      jbuilder (~> 2.5)
      jquery-rails
      listen (~> 3.0.5)
      ox!
      puma (~> 3.0)
      rails (~> 5.0.2)
      sass-rails (~> 5.0)
      spring
      spring-watcher-listen (~> 2.0.0)
      sqlite3
      turbolinks (~> 5)
      tzinfo-data
      uglifier (>= 1.3.0)
      web-console (>= 3.3.0)
    
    BUNDLED WITH
       1.13.6
```

**Comment by Soulou** [comment]
I'm currently doing a test with ruby `2.4.1` and bundler `1.14.6 `

**Comment by Soulou** [comment]
Exactly the same problem with these versions:

```
└> rake -P                                                                                                     
rake aborted!
LoadError: libruby.so.2.3: cannot open shared object file: No such file or directory - sample-ruby-ox/vendor/bundle/ruby/2.4.0/bundler/gems/ox-8211624ae976/ext/ox/ox.so
```

```
└> bundle env         
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Git       2.12.2
Platform  x86_64-linux
```

## Bundler settings

```
bin
  Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "vendor/bundle/bin"
jobs
  Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "4"
frozen
  Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "1"
path
  Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "vendor/bundle"
without
  Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "development:test"
disable_shared_gems
  Set for your local app (/run/mount/crypt/Scalingo/SampleProjects/sample-ruby-ox/.bundle/config): "true"
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.2'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'ox', git: 'https://github.com/hiptest/ox.git', branch: 'add_tolerant_mode_to_builder'  # Fast XML reader/writer
```

### Gemfile.lock

```
GIT
  remote: https://github.com/hiptest/ox.git
  revision: 8211624ae9764c5fc147e1450850fde46f339ab1
  branch: add_tolerant_mode_to_builder
  specs:
    ox (2.4.13)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.2)
      actionpack (= 5.0.2)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.2)
      actionpack (= 5.0.2)
      actionview (= 5.0.2)
      activejob (= 5.0.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.2)
      actionview (= 5.0.2)
      activesupport (= 5.0.2)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.2)
      activesupport (= 5.0.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.2)
      activesupport (= 5.0.2)
      globalid (>= 0.3.6)
    activemodel (5.0.2)
      activesupport (= 5.0.2)
    activerecord (5.0.2)
      activemodel (= 5.0.2)
      activesupport (= 5.0.2)
      arel (~> 7.0)
    activesupport (5.0.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (7.1.4)
    bindex (0.5.0)
    builder (3.2.3)
    byebug (9.0.6)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    erubis (2.7.0)
    execjs (2.7.0)
    ffi (1.9.18)
    globalid (0.4.0)
      activesupport (>= 4.2.0)
    i18n (0.8.1)
    jbuilder (2.6.3)
      activesupport (>= 3.0.0, < 5.2)
      multi_json (~> 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.5)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    multi_json (1.12.1)
    nio4r (2.0.0)
    nokogiri (1.7.1)
      mini_portile2 (~> 2.1.0)
    puma (3.8.2)
    rack (2.0.2)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.2)
      actioncable (= 5.0.2)
      actionmailer (= 5.0.2)
      actionpack (= 5.0.2)
      actionview (= 5.0.2)
      activejob (= 5.0.2)
      activemodel (= 5.0.2)
      activerecord (= 5.0.2)
      activesupport (= 5.0.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.2)
      activesupport (>= 4.2.0, < 6.0)
      nokogiri (~> 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.0.2)
      actionpack (= 5.0.2)
      activesupport (= 5.0.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.8)
      ffi (>= 0.5.0)
    sass (3.4.23)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    spring (2.0.1)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.7)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.3)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    web-console (3.5.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.2)
  jbuilder (~> 2.5)
  jquery-rails
  listen (~> 3.0.5)
  ox!
  puma (~> 3.0)
  rails (~> 5.0.2)
  sass-rails (~> 5.0)
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.14.6
```

**Comment by Soulou** [comment]
@colby-swandale are you using RVM or rbenv? It seems that with RVM it works correctly but it's not the case with `rbenv`

Actually I did manage to reproduce this behavior in two different environments:

1. With rbenv on my local workstation
2. In Scalingo deployment environment (docker container based on ubuntu trusty, ruby deployed with heroku buildpack `https://github.com/heroku/heroku-buildpack-ruby`

**Comment by segiddins** [comment]
I can't reproduce this on OS X, `vendor/bundle/ruby/2.4.0/bundler/gems/ox-8211624ae976/ext/ox/ox.bundle` is present still after installing a second time

**Comment by colby-swandale** [comment]
Thanks, i can reproduce this problem on linux/ubuntu.

**Comment by colby-swandale** [comment]
This does not reproduce for me if i use the `master` branch instead.

**Comment by Soulou** [comment]
Hi @colby-swandale, you mean the `master` branch of the gem itself, or the `master` branch of bundler?

**Comment by colby-swandale** [comment]
the `master` branch of the gem (sorry that wasn't clear)

**Comment by Soulou** [comment]
I confirm that on `master` of `github.com/hiptest/ox`, I can't reproduce the problem.

* Does this mean the problem is related to the `ox` gem build script
* What could lead to such behavior?

**Comment by Soulou** [comment]
Between `master` and the branch I'm giving in the Gemfile, there is only one commit:

```
https://github.com/hiptest/ox/commit/8211624ae9764c5fc147e1450850fde46f339ab1
```

How could such a commit change the behavior?

**Comment by colby-swandale** [comment]
The branch is 1 commit ahead of master but it's also 9 commits behind master, so there might be a commit that addresses some build issue. Sorry but, Im not very familiar with native extensions in ruby (something i need to read up on more to really give you an informative answer). @segiddins do you have any thoughts about this?

**Comment by Soulou** [comment]
I was actually speaking about being 1 commit ahead of master in the fork. I've actually tested `hiptest/ox#master` and `hiptest/ox/#add_tolerant_mode_to_builder`, it worked correctly with the former, but failed with the `add_tolerant_mode_to_builder` branch.

**Comment by segiddins** [comment]
https://github.com/hiptest/ox/commit/8211624ae9764c5fc147e1450850fde46f339ab1 added `ext/ox/ox.so` to git, which probably was unintentional

**Comment by cbliard** [comment]
My bad :-( Thanks for figuring it out.

**Comment by Soulou** [comment]
Oh! just seen it.. It seems so obvious now. Thanks @segiddins for find this information. I feel a little dumb now.. Closing the issue, thanks again for your help

**Comment by segiddins** [comment]
No worries! I only saw it after you pointed out the issue had to be in that commit (and it also explains why I didn't see anything on macOS)
