### ISSUE TITLE
Remove hard dependency on io/console (by updating Thor)

### ISSUE THREAD

**Issue by Iristyle** [bundler/bundler#5654]
On some platforms, the `io-console` gem may not be readily available through a package manager, and installing development packages in order to compile native code may be undesirable.

Thor is the culprit here as it specifies a hard dependency on `io/console` at https://github.com/erikhuda/thor/blob/v0.19.1/lib/thor/shell/basic.rb#L2

Thor has addressed this problem in https://github.com/erikhuda/thor/pull/539, so updating / vendoring a new Thor when that code is released will automatically solve this problem.  This note is left in the issue tracker here in the event anyone else encounters this issue.  It should just be a matter of time before it's naturally fixed by re-vendoring Thor.

On affected platforms, a failure may look like:

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- io/console (LoadError)
  from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:2:in `<top (required)>'
  from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/shell/color.rb:1:in `<top (required)>'
  from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/shell.rb:17:in `shell'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/ui/shell.rb:15:in `initialize'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/cli.rb:13:in `new'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/cli.rb:13:in `rescue in start'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/cli.rb:17:in `start'
  from /usr/local/share/gems/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
  from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  from /usr/local/share/gems/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
  from /usr/local/bin/bundle:23:in `load'
  from /usr/local/bin/bundle:23:in `<main>'
```

**Comment by segiddins** [comment]
We're waiting for Thor to cut a new release

**Comment by segiddins** [comment]
Done in 1.15.4.
