### ISSUE TITLE
gem pristine fails on gems with native extensions

### ISSUE THREAD

**Issue by x-yuri** [bundler/bundler#5664]
```
$ cat Gemfile
source "https://rubygems.org"
gem 'nokogiri'

$ bundle
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/.
Using mini_portile2 2.1.0
Using bundler 1.14.6
Installing nokogiri 1.7.2 with native extensions
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle exec gem pristine nokogiri
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: /home/yuri/.gem/ruby/2.3.3/gems/nokogiri-1.7.2/ext/nokogiri
/home/yuri/.rubies/ruby-2.3.3/bin/ruby -r ./siteconf20170516-12336-ldzlij.rb extconf.rb
/home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find nokogiri-1.7.2 in any of the sources (Bundler::GemNotFound)
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
        from /home/yuri/.gem/ruby/2.3.3/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
        from /home/yuri/.rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/yuri/.rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

extconf failed, exit code 1

Gem files will remain installed in /home/yuri/.gem/ruby/2.3.3/gems/nokogiri-1.7.2 for inspection.
Results logged to /home/yuri/.gem/ruby/2.3.3/extensions/x86_64-linux/2.3.0-static/nokogiri-1.7.2/gem_make.out
```

```
$ gem pristine nokogiri
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored nokogiri-1.6.6.2
Building native extensions.  This could take a while...
Restored nokogiri-1.6.7.1
Building native extensions.  This could take a while...
Restored nokogiri-1.6.8
Building native extensions.  This could take a while...
Restored nokogiri-1.6.8.1
Building native extensions.  This could take a while...
Restored nokogiri-1.7.0.1
Building native extensions.  This could take a while...
Restored nokogiri-1.7.1
```

**Comment by colby-swandale** [comment]
Thanks for the bug report! i was able to recreate this problem myself.

**Comment by segiddins** [comment]
Reproduced as well, in the meantime I recommend running `bundle pristine`

**Comment by segiddins** [comment]
actually, I don't think theres a way to make this work. `bundle exec` ensures that all ruby subprocesses will act as if they themselves have been `bundle exec`'d (by adding `-rbundle/setup` to `RUBYOPT`), and after `rm`ing the gem, RubyGems spawns a ruby subprocess to build the new extension

**Comment by colby-swandale** [comment]
@segiddins should this be closed or can something be actioned for this?

**Comment by segiddins** [comment]
I can't think of an actionable fix, sorry.

**Comment by colby-swandale** [comment]
I'm going to close this, as the recommendation is to use `bundle pristine` instead.
