### ISSUE TITLE
bundle install --force with git source

### ISSUE THREAD

**Issue by avit** [bundler/bundler#5678]
Running `bundle install --force` with a gem sourced from github is failing with the following error. It looks like the `--tags` option is getting the install path:

```
Bundler::Source::Git::GitNotAllowedError: Bundler is trying to run a `git fetch --force --quiet --tags "/usr/local/bundle/cache/bundler/git/state_machine-3fdb6d8ec7f53fb6706f0e58ef5abd9313f708ca"` at runtime. You probably need to run
`bundle install`. However, this error message could probably be more useful. Please submit a ticket at http://github.com/bundler/bundler/issues with steps to reproduce as well as the following

CALLER: /usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git/git_proxy.rb:159:in `new'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git/git_proxy.rb:159:in `git'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git/git_proxy.rb:153:in `block in git_retry'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/retry.rb:39:in `call'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/retry.rb:39:in `run'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/retry.rb:29:in `attempt'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git/git_proxy.rb:152:in `git_retry'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git/git_proxy.rb:129:in `block in copy_to'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/shared_helpers.rb:55:in `chdir'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/shared_helpers.rb:55:in `block in chdir'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/shared_helpers.rb:54:in `chdir'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git/git_proxy.rb:128:in `copy_to'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/source/git.rb:180:in `install'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/installer/gem_installer.rb:55:in `install'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/installer/parallel_installer.rb:115:in `block in worker_pool'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/worker.rb:63:in `call'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/worker.rb:63:in `apply_func'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/worker.rb:58:in `block in process_queue'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/worker.rb:55:in `loop'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/worker.rb:55:in `process_queue'
/usr/local/bundle/gems/bundler-1.15.0/lib/bundler/worker.rb:89:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler   1.15.0
Rubygems  2.6.10
Ruby      2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
GEM_HOME  /usr/local/bundle
GEM_PATH  
Git       2.1.4
Platform  x86_64-linux
```

## Bundler settings

```
disable_shared_gems
  Set for your local app (/usr/local/bundle/config): "true"
gems.contribsys.com
  Set for your local app (/usr/local/bundle/config): "66bc9802:eb8ffad3"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
```

### Gemfile

```ruby
source "https://rubygems.org"
gem "state_machine", github: "avit/state_machine", branch: "integration"
```

### Gemfile.lock

```
GIT
  remote: git://github.com/avit/state_machine.git
  revision: 60f9ca14c88c9604b45ae15a19716eefe9b39162
  branch: integration
  specs:
    state_machine (1.2.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  state_machine!

BUNDLED WITH
   1.15.0
```

**Comment by segiddins** [comment]
Repro'ed, but the issue isn't the git command we run, it's that bundler thinks it shouldn't be allowed to run git commands here.
