### ISSUE TITLE
NameError: uninitialized constant GraphViz

### ISSUE THREAD

**Issue by nfredrik** [bundler/bundler#5706]
Installed Graphiz and tried to execute:

$ bundle viz

got

## Backtrace

```
NameError: uninitialized constant GraphViz
Did you mean?  Graphviz
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/graph.rb:105:in `g'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/graph.rb:114:in `block in run'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/graph.rb:113:in `each'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/graph.rb:113:in `run'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/graph.rb:26:in `viz'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/cli/viz.rb:16:in `run'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/cli.rb:427:in `viz'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/cli.rb:20:in `dispatch'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/cli.rb:10:in `start'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/exe/bundle:35:in `block in <top (required)>'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /Users/fabv/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.0/exe/bundle:27:in `<top (required)>'
  /Users/fabv/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
  /Users/fabv/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
  /Users/fabv/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  /Users/fabv/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
What version of the graphviz gem do you have installed, out of curiosity?

**Comment by nfredrik** [comment]
graphviz (0.4.0)

**Comment by segiddins** [comment]
One last question... what's the output of `gem list graphviz`? (I have a hunch I know what the problem is)
