### ISSUE TITLE
Setting BUNDLE_GEMFILE=Gemfile causes Bundler.setup to fail when in deployment mode

### ISSUE THREAD

**Issue by mattbrictson** [bundler/bundler#5712]
Starting with Bundler 1.15.0, `Bundler.setup` fails with an `ArgumentError` raised from `Pathname#relative_path_from` when the following conditions are met:

* Bundler is in deployment mode; and
* A Gemfile is explicitly specified via the `BUNDLE_GEMFILE` environment variable; and
* That Gemfile is *not* an absolute path (e.g. `BUNDLE_GEMFILE=Gemfile`)

```
Bundler   1.15.1
Rubygems  2.6.12
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
Git       2.13.1
Platform  x86_64-darwin-15
```

Steps to reproduce:

```
$ touch Gemfile
$ bundle install
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle install --deployment
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into ./vendor/bundle.
$ BUNDLE_GEMFILE=Gemfile ruby -rbundler -e Bundler.setup
ruby/2.4.0/pathname.rb:520:in `relative_path_from': different prefix: "" and "/Users/mbrictson/Downloads/bundler-defect" (ArgumentError)
  from ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:392:in `ensure_equivalent_gemfile_and_lockfile'
  from ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:14:in `setup'
  from ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
  from -e:1:in `<main>'
```

This bug seems to have been introduced in f145aa11a5b47b438263aace8bd45dd2d752411c.

**Comment by mattbrictson** [comment]
I have an idea for a fix, which is to simply add `expand_path`:

```diff
--- a/lib/bundler/definition.rb
+++ b/lib/bundler/definition.rb
@@ -389,7 +389,7 @@ module Bundler
       msg = String.new
       msg << "You are trying to install in deployment mode after changing\n" \
              "your Gemfile. Run `bundle install` elsewhere and add the\n" \
-             "updated #{Bundler.default_lockfile.relative_path_from(SharedHelpers.pwd)} to version control."
+             "updated #{Bundler.default_lockfile.expand_path.relative_path_from(SharedHelpers.pwd)} to version control."
 
       unless explicit_flag
```

Would that be an acceptable PR?

**Comment by segiddins** [comment]
I don't think so, since just running `ruby -rbundler -e Bundler.setup` without setting the env var works fine... I think the following is the correct fix:

```diff
diff --git a/lib/bundler/shared_helpers.rb b/lib/bundler/shared_helpers.rb
index b3354972d..cc6f80cdb 100644
--- a/lib/bundler/shared_helpers.rb
+++ b/lib/bundler/shared_helpers.rb
@@ -174,7 +174,7 @@ module Bundler
 
     def find_gemfile
       given = ENV["BUNDLE_GEMFILE"]
-      return given if given && !given.empty?
+      return File.expand_path(given) if given && !given.empty?
       find_file("Gemfile", "gems.rb")
     end
 
```

But it will also require test coverage to merge. If you want to send that in as a PR, that would be 💯, otherwise I can do it.

**Comment by mattbrictson** [comment]
Looks good. I'll try to put together a PR with test coverage.

**Comment by mattbrictson** [comment]
It looks like I won't have time to submit a PR this week. Sorry!

**Comment by gxespino** [comment]
Can be closed.

**Comment by mattbrictson** [comment]
❤️ ❤️ ❤️
