### ISSUE TITLE
Bundler throws an exception if you have MANPATH set in your environment.

### ISSUE THREAD

**Issue by jules2689** [bundler/bundler#5730]
Bundler master fails when you have MANPATH set in your environment:

e.g.
```shell
~/src/github.com/Shopify/shopify(master*) ➜ echo $MANPATH
/Users/juliannadeau/.nvm/versions/node/v6.10.0/share/man:
```

Stack Trace:
```shell
/Users/juliannadeau/src/github.com/bundler/bundler/lib/bundler/shared_helpers.rb:213:in `set_env': new key MANPATH (ArgumentError)
	from /Users/juliannadeau/src/github.com/bundler/bundler/lib/bundler/runtime.rb:272:in `setup_manpath'
	from /Users/juliannadeau/src/github.com/bundler/bundler/lib/bundler/runtime.rb:47:in `setup'
	from /Users/juliannadeau/src/github.com/bundler/bundler/lib/bundler.rb:101:in `setup'
	from /Users/juliannadeau/src/github.com/bundler/bundler/lib/bundler/setup.rb:10:in `<top (required)>'
	from /opt/rubies/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rubies/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/juliannadeau/src/github.com/Shopify/shopify/config/boot.rb:32:in `block in <top (required)>'
	from /Users/juliannadeau/src/github.com/Shopify/shopify/lib/boot_lib/timing_helpers.rb:12:in `_t'
	from /Users/juliannadeau/src/github.com/Shopify/shopify/config/boot.rb:31:in `<top (required)>'
	from bin/rake:2:in `require_relative'
	from bin/rake:2:in `<main>'
```

[Adding MANPATH to the environment_preserver.rb's BUNDLER_KEYS](https://github.com/bundler/bundler/blob/master/lib/bundler/environment_preserver.rb#L5) seems to solve it. I'm not familiar with this functionality to know if this is the right call - but looking at the code, it looks like MANPATH was forgotten in the list.

This does raise a question for me - will bundler crash if I clash with another env var now? If I set another environment variable with the same name as Bundler's will it throw the same exception?

cc @segiddins

**Comment by jules2689** [comment]
bundler env without the Gemfile (private)

## Environment

```
Bundler   1.15.1
RubyGems  2.6.12
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
GEM_HOME  /Users/juliannadeau/.gem/ruby/2.3.3
GEM_PATH  /Users/juliannadeau/.gem/ruby/2.3.3:/opt/rubies/2.3.3/lib/ruby/gems/2.3.0
Git       2.13.1
Platform  x86_64-darwin-16
```

## Bundler Build Metadata

```
Built At          2017-06-16
Git SHA           0c651a97a
Released Version  false
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/Users/juliannadeau/.bundle/config): "--use-system-libraries"
gem.test
  Set for the current user (/Users/juliannadeau/.bundle/config): "minitest"
gem.mit
  Set for the current user (/Users/juliannadeau/.bundle/config): "false"
gem.coc
  Set for the current user (/Users/juliannadeau/.bundle/config): "true"
jobs
  Set for your local app (/Users/juliannadeau/src/github.com/Shopify/shopify/.bundle/config): "8"
bundler_orig_bundle_bin_path
  You have not configured a value for `bundler_orig_bundle_bin_path`
bundler_orig_bundle_gemfile
  You have not configured a value for `bundler_orig_bundle_gemfile`
```
