### ISSUE TITLE
Bundle install fails sometimes with `Bundler::GemNotFound`

### ISSUE THREAD

**Issue by joneshf** [bundler/bundler#5821]
## What you're trying to accomplish

We've got a Jenkins build server that deploys to production. Occasionally, bundle fails with `Bundler::GemNotFound`. However, the gem if fails on changes each time. When we rerun the deploy job, it succeeds the second time. The failure occurs sporadically.

##  The command you ran

We use capistrano bundler for the deploy process on jenkins, so the command is part of that library. We're not certain that capistrano bundler is operating properly, but it doesn't seem to be the source of the failures.

## What you expected to happen

Bundler should install without failures, or retry on a gem not found, or give a better error message?

## What actually happened

Bundler fails to install a gem once. But on rerunning, will reinstall the gems fine.

## The exception backtrace(s), if any

Here are some examples:

```
16:20:21 Bundler::GemNotFound: Could not find aws-record-1.1.0 in any of the sources
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
16:20:21   /opt/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

```
21:34:58 Bundler::GemNotFound: Could not find i18n-0.8.4 in any of the sources
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
21:34:58   /opt/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

```
16:57:22 Bundler::GemNotFound: Could not find activerecord-import-0.18.3 in any of the sources
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
16:57:22   /opt/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Any help would be appreciated. Thanks!

**Comment by arbonap** [comment]
hi @joneshf. Could you please provide a Gemfile? Thanks!

**Comment by colby-swandale** [comment]
ping @joneshf

**Comment by joneshf** [comment]
Sorry, it turned out we had a tricky deploy setup. A recent change there started causing this failure. Looks like nothing's wrong now.

Thanks for the quick responses though!
