### ISSUE TITLE
Bundle install not working

### ISSUE THREAD

**Issue by kkhanstella** [bundler/bundler#5835]
Just installed ruby and devkit and installed gem bundler, now bundle install is giving following error:

```
RuntimeError: Unable to find a spec satisfying wdm (~> 0.1.0) in the set. Perhaps the lockfile is corrupted?
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:39:in `block in for'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:24:in `loop'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:24:in `for'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:79:in `materialize'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/definition.rb:199:in `missing_dependencies'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/installer.rb:219:in `block in resolve_if_need'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/ui/shell.rb:127:in `with_level'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/ui/shell.rb:86:in `silence'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/installer.rb:216:in `resolve_if_need'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/installer.rb:78:in `run'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/installer.rb:24:in `install'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/cli/install.rb:70:in `run'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/cli.rb:186:in `block in install'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/settings.rb:100:in `temporary'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/cli.rb:185:in `install'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
  C:/Ruby22-x64/bin/bundle:23:in `load'
  C:/Ruby22-x64/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler   1.15.1
Rubygems  2.4.5.2
Ruby      2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
GEM_HOME  C:/Ruby22-x64/lib/ruby/gems/2.2.0
GEM_PATH  C:/Ruby22-x64/lib/ruby/gems/2.2.0;C:/Users/Khashal/.gem/ruby/2.2.0
Git       2.13.1.windows.2
Platform  x64-mingw32
OpenSSL   OpenSSL 1.0.2j  26 Sep 2016
```

### Gemfile

```ruby
# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-compass', '>= 4.0.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    backports (3.6.8)
    chunky_png (1.3.8)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.4)
    contracts (0.13.0)
    dotenv (2.2.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.2)
    eventmachine (1.2.2-x64-mingw32)
    execjs (2.7.0)
    fast_blank (1.0.0)
    fastimage (2.0.1)
      addressable (~> 2)
    ffi (1.9.17)
    ffi (1.9.17-x64-mingw32)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.5.1)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    kramdown (1.13.2)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    memoist (0.15.0)
    middleman (4.2.1)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.2.1)
      middleman-core (= 4.2.1)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.2.1)
      thor (>= 0.17.0, < 2.0)
    middleman-compass (4.0.1)
      compass (>= 1.0.0, < 2.0.0)
      middleman-core (>= 4.0.0)
    middleman-core (4.2.1)
      activesupport (>= 4.2, < 5.1)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      contracts (~> 0.13.0)
      dotenv
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0.0)
      memoist (~> 0.14)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 3)
      sass (>= 3.4)
      servolux
      tilt (~> 2.0)
      uglifier (~> 3.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    minitest (5.10.1)
    multi_json (1.12.1)
    padrino-helpers (0.13.3.3)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.3.3)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.13.3.3)
      activesupport (>= 3.1)
    parallel (1.10.0)
    public_suffix (2.0.5)
    rack (2.0.1)
    rack-livereload (0.3.16)
      rack
    rb-fsevent (0.9.8)
    rb-inotify (0.9.8)
      ffi (>= 0.5.0)
    sass (3.4.23)
    servolux (0.12.0)
    thor (0.19.4)
    thread_safe (0.3.5)
    tilt (2.0.6)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.4)
      execjs (>= 0.3.0, < 3)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  middleman (>= 4.0.0)
  middleman-compass (>= 4.0.0)
  middleman-livereload
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.14.6
```

**Comment by segiddins** [comment]
Your lockfile does indeed seem to be missing a spec for `wdm`, so the Lockfile is corrupted as the error message suggests.

**Comment by colby-swandale** [comment]
ping @kkhanstella, were you able to resolve your problem?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by dantistus** [comment]
I have found several threads like this and not one of them has any hint at the possible solution. Thanks guys, you are the best :)

**Comment by renodor** [comment]
Hello,

I have exactely the same issue as @kkhanstella 
Did anyone found a solution to this pb?

Thanks.

**Comment by mikegee** [comment]
I failed to reproduce the original issue using @kkhanstella's `Gemfile`, `Gemfile.lock` and the `Dockerfile` pasted below.

```
FROM ruby:2.2.6
RUN gem uninstall -i /usr/local/lib/ruby/gems/2.2.0 bundler && gem install --version 1.15.1 bundler
WORKDIR /app
ADD . /app
RUN bundle install
```

Please refer to [this guide](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) if you think there is a bug in Bundler or need assistance.

**Comment by vikas-a2** [comment]
Remove your Gemfile.lock file and bundle install again. This should help you.
