### ISSUE TITLE
With Bundler.with_original_env MRI ruby installed gem failed to load intermittently from jruby

### ISSUE THREAD

**Issue by abhichvn** [bundler/bundler#5959]
I am trying to run ruby code with MRI ruby from jruby via subprocess

Environment details:
- jruby:  1.7.19 (1.9.3p551)
- bundler: 1.13.2
- MRI ruby: 1.9.3

**defect_test.rb**
```
require 'rubygems'
require 'bundler'

def run_general_script
	command = "C:/dev/Ruby193/bin/ruby.exe C:/Users/abchavan/dev/test.txt"
	script_result, results_err, results_out = '', '', ''
	status = IO::popen4(command) do |pid, stdin, stdout, stderr|
		stdin.close
		[
            Thread.new(stdout) do |stdout_io|
              stdout_io.each_line { |l| results_out += l }
              stdout_io.close
            end,

            Thread.new(stderr) do |stderr_io|
              stderr_io.each_line { |l| results_err += l }
            end
          ].each(&:join)
	end

	puts results_out
	puts results_err
end

threads = []
1000.times do |i|
	puts i
	threads << Thread.new { Bundler.with_original_env { run_general_script } }
end
threads.each(&:join)
```

**test.txt**
```
require 'rubygems'
require 'rack'

puts "executing ruby file"
```

to run the program using jruby:
**`jruby C:\Users\abchavan\defect_test.rb`**

After running this program 2-3 times, you will get following error
```
C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:526:in `join': can't convert nil into String (TypeError)
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:526:in `rescue in find_home'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:512:in `find_home'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:1070:in `user_home'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb:64:in `default_path'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb:63:in `path='
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb:29:in `initialize'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:395:in `new'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:395:in `paths'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:416:in `path'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:383:in `dirs'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:268:in `_all'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:411:in `each'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:443:in `find'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:443:in `find_by_path'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:206:in `try_activate'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
        from C:/dev/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from C:/Users/abchavan/dev/test.txt:2:in `<main>'
```

**Comment by abhichvn** [comment]
I also check this issue with latest version of Bundler gem above v1.13.2 eg v1.15.4 issue is still there

**Comment by segiddins** [comment]
This seems to be happening deep in RubyGems and I'm not seeing Bundler in the stack trace, what's the output of `gem env`?

**Comment by abhichvn** [comment]
This is happening with all the installed gem only.
If I have added following content in test.text file
```
require 'rubygems'
require 'rexml/document'
require 'net/http'
require 'uri'
require 'rack'
require 'json'
```
Then you will get error for "require 'rack'" line only.
I also check this without **Bundler.with_original_env** with following line
`threads << Thread.new {  run_general_script  }`

I ran this 4-5 times it doesn't throw any error

**jruby: gem env output**
```
- RUBYGEMS VERSION: 2.4.5
- RUBY VERSION: 1.9.3 (2015-01-29 patchlevel 551) [java]
- INSTALLATION DIRECTORY: C:/dev/jruby/lib/ruby/gems/shared
- RUBY EXECUTABLE: C:/dev/jruby/bin/jruby.exe
- EXECUTABLE DIRECTORY: C:/dev/jruby/bin
- SPEC CACHE DIRECTORY: C:/Users/abchavan/.gem/specs
- SYSTEM CONFIGURATION DIRECTORY: C:/dev/jruby/etc
- RUBYGEMS PLATFORMS:
  - ruby
  - universal-java-1.8
- GEM PATHS:
   - C:/dev/jruby/lib/ruby/gems/shared
- GEM CONFIGURATION:
   - :update_sources => true
   - :verbose => true
   - :backtrace => false
   - :bulk_threshold => 1000
   - "install" => "--no-rdoc --no-ri --env-shebang"
   - "update" => "--no-rdoc --no-ri --env-shebang"
- REMOTE SOURCES:
   - https://rubygems.org/
- SHELL PATH:
   - C:\dev\jruby\bin
   - c:\dev\torquebox\jboss\bin
   - C:\Windows\system32
   - C:\Windows
   - C:\Windows\System32\Wbem
   - C:\Windows\System32\WindowsPowerShell\v1.0\
   - C:\dev\java\bin
```

**MRI ruby: gem env output**
```
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.29
  - RUBY VERSION: 1.9.3 (2014-11-13 patchlevel 551) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/dev/Ruby193/lib/ruby/gems/1.9.1
  - RUBY EXECUTABLE: C:/dev/Ruby193/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/dev/Ruby193/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/dev/Ruby193/lib/ruby/gems/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
```

**Comment by abhichvn** [comment]
any update on this?

**Comment by segiddins** [comment]
I'd recommend updated to the latest released RubyGems version, 2.6.11, since the error you're running into is happening inside RUbyGems

**Comment by abhichvn** [comment]
Ok, I will check and confirm

**Comment by abhichvn** [comment]
@segiddins Thank you for help, it looks like a issue of rubygems with windows environment, I will open this issue there.
