### ISSUE TITLE
Bundler fails on Ruby 2.4.1

### ISSUE THREAD

**Issue by SuperSajuuk** [bundler/bundler#5967]
I'm trying to run `bundle install` in a folder containing the gemfile for Redmine's latest build (at the time of this post, it's 3.4.2). While the command worked first time (by installing every gem under root because it kept complaining of "corrupt gems"), now it doesn't seem to work, constantly returning `ThreadError can't create Thread: Resource temporarily unavailable.`.

This generally hangs the system and doesn't fix itself without `exit` out of the user running the command. Waiting and retrying doesn't fix. I've tried various listed solutions (like `gem uninstall bundler` and then reinstalling, or upgrading ruby), but neither fixes the issue.

In the errors, bundler seems to want to use Ruby 2.4.0, but I have Ruby 2.4.1 installed (it was compiled from source, because CentOS 7's repositories are chronically out of date). Does this cause problems?

Command Run: `bundle install` in the folder containing the GemFile
Expected Result: Install listed gems in gemfile and prepare for Redmine installation
Actual Result: `ThreadError can't create Thread: Resource temporarily unavailable.` was returned

Tried: Reinstalling ruby (via source compilation and EasyApache 4's manager), uninstalling and reinstalling bundler, etc.

## Backtrace

```
ThreadError: can't create Thread: Resource temporarily unavailable
  /usr/local/lib/ruby/2.4.0/timeout.rb:83:in `start'
  /usr/local/lib/ruby/2.4.0/timeout.rb:83:in `block in timeout'
  /usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
  /usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
  /usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  /usr/local/lib/ruby/2.4.0/net/http.rb:882:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:702:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:967:in `reset'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:630:in `connection_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:996:in `request'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/fetcher/downloader.rb:50:in `request'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/fetcher/downloader.rb:16:in `fetch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/fetcher/compact_index.rb:116:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/compact_index_client/updater.rb:50:in `block in update'
  /usr/local/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/compact_index_client/updater.rb:30:in `update'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/compact_index_client.rb:81:in `update'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/compact_index_client.rb:97:in `update_info'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/compact_index_client.rb:54:in `block in dependencies'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/fetcher/compact_index.rb:87:in `block (3 levels) in compact_index_client'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/worker.rb:63:in `apply_func'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/worker.rb:58:in `block in process_queue'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/worker.rb:55:in `loop'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/worker.rb:55:in `process_queue'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/worker.rb:89:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler   1.15.4
Rubygems  2.6.12
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
GEM_HOME  /usr/local/lib/ruby/gems/2.4.0
GEM_PATH  /usr/local/lib/ruby/gems/2.4.0:/home/********/.gem/ruby/2.4.0
Git       2.14.0
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1e 11 Feb 2013
```

### Gemfile

```ruby
source 'https://rubygems.org'

if Gem::Version.new(Bundler::VERSION) < Gem::Version.new('1.5.0')
  abort "Redmine requires Bundler 1.5.0 or higher (you're using #{Bundler::VERSION}).\nPlease update with 'gem update bundler'."
end

gem "rails", "4.2.8"
gem "addressable", "2.4.0" if RUBY_VERSION < "2.0"
gem "jquery-rails", "~> 3.1.4"
gem "coderay", "~> 1.1.1"
gem "request_store", "1.0.5"
gem "mime-types", (RUBY_VERSION >= "2.0" ? "~> 3.0" : "~> 2.99")
gem "protected_attributes"
gem "actionpack-xml_parser"
gem "roadie-rails", "~> 1.1.1"
gem "roadie", "~> 3.2.1"
gem "mimemagic"

gem "nokogiri", (RUBY_VERSION >= "2.1" ? "~> 1.7.2" : "~> 1.6.8")
gem "i18n", "~> 0.7.0"
gem "ffi", "1.9.14", :platforms => :mingw if RUBY_VERSION < "2.0"

# Request at least rails-html-sanitizer 1.0.3 because of security advisories
gem "rails-html-sanitizer", ">= 1.0.3"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :x64_mingw, :mswin]
gem "rbpdf", "~> 1.19.2"

# Optional gem for LDAP authentication
group :ldap do
  gem "net-ldap", "~> 0.12.0"
end

# Optional gem for OpenID authentication
group :openid do
  gem "ruby-openid", "~> 2.3.0", :require => "openid"
  gem "rack-openid"
end

platforms :mri, :mingw, :x64_mingw do
  # Optional gem for exporting the gantt to a PNG file, not supported with jruby
  group :rmagick do
    gem "rmagick", ">= 2.14.0"
  end

  # Optional Markdown support, not for JRuby
  group :markdown do
    gem "redcarpet", "~> 3.4.0"
  end
end

# Include database gems for the adapters found in the database
# configuration file
require 'erb'
require 'yaml'
database_file = File.join(File.dirname(__FILE__), "config/database.yml")
if File.exist?(database_file)
  database_config = YAML::load(ERB.new(IO.read(database_file)).result)
  adapters = database_config.values.map {|c| c['adapter']}.compact.uniq
  if adapters.any?
    adapters.each do |adapter|
      case adapter
      when 'mysql2'
gem "mysql2", "~> 0.4.6", :platforms => [:mri, :mingw, :x64_mingw]
      when /postgresql/
gem "pg", "~> 0.18.1", :platforms => [:mri, :mingw, :x64_mingw]
      when /sqlite3/
gem "sqlite3", (RUBY_VERSION < "2.0" && RUBY_PLATFORM =~ /mingw/ ? "1.3.12" : "~>1.3.12"),
               :platforms => [:mri, :mingw, :x64_mingw]
      when /sqlserver/
gem "tiny_tds", (RUBY_VERSION >= "2.0" ? "~> 1.0.5" : "~> 0.7.0"), :platforms => [:mri, :mingw, :x64_mingw]
gem "activerecord-sqlserver-adapter", :platforms => [:mri, :mingw, :x64_mingw]
      else
warn("Unknown database adapter `#{adapter}` found in config/database.yml, use Gemfile.local to load your own database gems")
      end
    end
  else
    warn("No adapter found in config/database.yml, please configure it first")
  end
else
  warn("Please configure your config/database.yml first")
end

group :development do
  gem "rdoc", "~> 4.3"
  gem "yard"
end

group :test do
  gem "minitest"
  gem "rails-dom-testing"
  gem "mocha"
  gem "simplecov", "~> 0.9.1", :require => false
  # TODO: remove this after upgrading to Rails 5
  gem "test_after_commit", "~> 0.4.2"
  # For running UI tests
  gem "capybara"
  gem "selenium-webdriver", "~> 2.53.4"
end

local_gemfile = File.join(File.dirname(__FILE__), "Gemfile.local")
if File.exists?(local_gemfile)
  eval_gemfile local_gemfile
end

# Load plugins' Gemfiles
Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
  eval_gemfile file
end
```

### Gemfile.lock

```
<No /home/********/redmine/Gemfile.lock found>
```

**Comment by segiddins** [comment]
Does your system have an abnormally low per-process thread limit?

**Comment by SuperSajuuk** [comment]
@segiddins I'm not sure, where would I find out that particular bit of information?

**Comment by segiddins** [comment]
That's seems like plenty, so I'm not entirely sure why you're unable to create a new one

**Comment by SuperSajuuk** [comment]
I initially thought that it was some sort of "ratelimiting" from RubyGems.org, so I tried it just now and it's still returning this error. Should I try restarting the whole VPS to clear out things, and see if it works again?

**Comment by segiddins** [comment]
I honestly have no idea, sorry

**Comment by colby-swandale** [comment]
@SuperSajuuk were you able to resolve your issue?

**Comment by SuperSajuuk** [comment]
@colby-swandale I've not had any chance to check for the past week, since the server runs a Discord Bot for the Discord chat platform, thus shutting down the whole VPS to see if that fixes the bundler problem isn't always practical. I'll try next weekend to see if that works, if not I will feedback on this thread :)

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
