### ISSUE TITLE
env: ruby_executable_hooks: No such file or directory

### ISSUE THREAD

**Issue by yakimant** [bundler/bundler#5971]
```
$ BUNDLE_GEMFILE=.fastlane/Gemfile.fastlane bundle exec fastlane -h
env: ruby_executable_hooks: No such file or directory
```

```
$ sudo gem install executable-hooks --bindir /usr/local/bin
Ignoring sqlite3-1.3.11 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.11
Building native extensions.  This could take a while...
ERROR:  Error installing executable-hooks:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.0.0/gems/executable-hooks-1.3.2/ext/wrapper_installer
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20170825-49278-rus3tb.rb extconf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1381:in `initialize': Operation not permitted - /usr/bin/ruby_executable_hooks (Errno::EPERM)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1381:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1381:in `block in copy_file'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:477:in `copy_file'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:394:in `block in cp'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:393:in `cp'
        from /Library/Ruby/Gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/wrapper.rb:52:in `install_from'
        from extconf.rb:18:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/executable-hooks-1.3.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/executable-hooks-1.3.2/gem_make.out
```

**Comment by segiddins** [comment]
This looks like an issue with your ruby installation, rather than anything to do with Bundler specifically?

**Comment by yakimant** [comment]
@segiddins, don't know. Maybe someone from here knows.
Is bundle using ruby_executable_hooks from PATH?

**Comment by segiddins** [comment]
That's a gem that I think inserts itself into the executable shims that RubyGems creates, you can try running `gem pristine --all --only-executables` to regenerate those shims from scratch

**Comment by yakimant** [comment]
@segiddins, anyway it's not a bundler issue. Made an issue here:
https://github.com/rvm/executable-hooks/issues/24

Also, prestine doesn't support `--bindir`:
https://github.com/rubygems/rubygems/issues/1997

Thank you!
