### ISSUE TITLE
Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by paulettee** [bundler/bundler#5974]
I'm trying to deploy my rails application on passenger and nginx and I keep getting this error. I've ran 'bundle install' over and over but it keeps coming back with this error. Please help!
```
/root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
  /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by segiddins** [comment]
Please share the output of `bundle env`, thanks!

**Comment by paulettee** [comment]
This is the output below. Thanks for helping out.

## Environment

```
Bundler   1.15.4
Rubygems  2.6.12
Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
GEM_HOME  /root/.rvm/gems/ruby-2.4.0
GEM_PATH  /root/.rvm/gems/ruby-2.4.0:/root/.rvm/gems/ruby-2.4.0@global
RVM       1.29.2 (latest)
Git       1.8.3.1
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1e 11 Feb 2013
```

## Bundler settings

```
without
  Set for your local app (/var/www/atl_rockville/atl_code/.bundle/config): "development:test"
bin
  Set for your local app (/var/www/atl_rockville/atl_code/.bundle/config): "bin"
path
  Set for your local app (/var/www/atl_rockville/atl_code/.bundle/config): "vendor/cache"
disable_shared_gems
  Set for your local app (/var/www/atl_rockville/atl_code/.bundle/config): true
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'rake', '~> 12.0.0'
gem 'bootstrap-sass', '3.3.6'
# Bootstrap datepicker 
gem 'bootstrap-datepicker-rails'

# Pagination
gem 'will_paginate', '~> 3.1', '>= 3.1.6'
gem 'will_paginate-bootstrap', '~> 1.0', '>= 1.0.1'

# Devise user setup and authentication
gem 'devise'

# Flash notice for devise login
gem 'toastr-rails'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'jquery-ui-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# rails_admin
gem 'remotipart', github: 'mshibuya/remotipart'
gem 'rails_admin', '>= 1.0.0.rc'

# Cancancan
gem 'cancancan'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'rails-controller-testing', '0.1.1'
  gem 'minitest-reporters',	'1.1.9'
  gem 'guard',	'2.13.0'
  gem 'guard-minitest',	'2.4.4'
end

group :production do
 # gem 'pg', '0.18.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GIT
  remote: https://github.com/mshibuya/remotipart.git
  revision: cd653ddc43bb09767b8f2802d6e27b3e00ef992f
  specs:
    remotipart (1.3.1)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.5)
      actionpack (= 5.0.5)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.5)
      actionpack (= 5.0.5)
      actionview (= 5.0.5)
      activejob (= 5.0.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.5)
      actionview (= 5.0.5)
      activesupport (= 5.0.5)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.5)
      activesupport (= 5.0.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.5)
      activesupport (= 5.0.5)
      globalid (>= 0.3.6)
    activemodel (5.0.5)
      activesupport (= 5.0.5)
    activerecord (5.0.5)
      activemodel (= 5.0.5)
      activesupport (= 5.0.5)
      arel (~> 7.0)
    activesupport (5.0.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    ansi (1.5.0)
    arel (7.1.4)
    autoprefixer-rails (7.1.2.6)
      execjs
    bcrypt (3.1.11)
    bindex (0.5.0)
    bootstrap-datepicker-rails (1.7.1.1)
      railties (>= 3.0)
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    builder (3.2.3)
    byebug (9.1.0)
    cancancan (2.0.0)
    coderay (1.1.1)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    devise (4.3.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
    erubis (2.7.0)
    execjs (2.7.0)
    ffi (1.9.18)
    font-awesome-rails (4.7.0.2)
      railties (>= 3.2, < 5.2)
    formatador (0.2.5)
    globalid (0.4.0)
      activesupport (>= 4.2.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-minitest (2.4.4)
      guard-compat (~> 1.2)
      minitest (>= 3.0)
    haml (5.0.2)
      temple (>= 0.8.0)
      tilt
    i18n (0.8.6)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    kaminari (1.0.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.0.1)
      kaminari-activerecord (= 1.0.1)
      kaminari-core (= 1.0.1)
    kaminari-actionview (1.0.1)
      actionview
      kaminari-core (= 1.0.1)
    kaminari-activerecord (1.0.1)
      activerecord
      kaminari-core (= 1.0.1)
    kaminari-core (1.0.1)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.12)
    mail (2.6.6)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.2.0)
    minitest (5.10.3)
    minitest-reporters (1.1.9)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    multi_json (1.12.1)
    mysql2 (0.4.9)
    nenv (0.3.0)
    nested_form (0.3.2)
    nio4r (2.1.0)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    orm_adapter (0.5.0)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    puma (3.10.0)
    rack (2.0.3)
    rack-pjax (1.0.0)
      nokogiri (~> 1.5)
      rack (>= 1.1)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.5)
      actioncable (= 5.0.5)
      actionmailer (= 5.0.5)
      actionpack (= 5.0.5)
      actionview (= 5.0.5)
      activejob (= 5.0.5)
      activemodel (= 5.0.5)
      activerecord (= 5.0.5)
      activesupport (= 5.0.5)
      bundler (>= 1.3.0)
      railties (= 5.0.5)
      sprockets-rails (>= 2.0.0)
    rails-controller-testing (0.1.1)
      actionpack (~> 5.x)
      actionview (~> 5.x)
      activesupport (~> 5.x)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails_admin (1.2.0)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (>= 4.0, < 6)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (>= 0.14, < 2.0)
      nested_form (~> 0.3)
      rack-pjax (>= 0.7)
      rails (>= 4.0, < 6)
      remotipart (~> 1.3)
      sass-rails (>= 4.0, < 6)
    railties (5.0.5)
      actionpack (= 5.0.5)
      activesupport (= 5.0.5)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    ruby-progressbar (1.8.1)
    sass (3.5.1)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    shellany (0.0.1)
    slop (3.6.0)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    temple (0.8.0)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    toastr-rails (1.0.3)
      railties (>= 3.1.0)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.3)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (3.5.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    will_paginate (3.1.6)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-datepicker-rails
  bootstrap-sass (= 3.3.6)
  byebug
  cancancan
  coffee-rails (~> 4.2)
  devise
  guard (= 2.13.0)
  guard-minitest (= 2.4.4)
  jbuilder (~> 2.5)
  jquery-rails
  jquery-ui-rails
  listen (~> 3.0.5)
  minitest-reporters (= 1.1.9)
  mysql2 (>= 0.3.18, < 0.5)
  puma (~> 3.0)
  rails (~> 5.0.1)
  rails-controller-testing (= 0.1.1)
  rails_admin (>= 1.0.0.rc)
  rake (~> 12.0.0)
  remotipart!
  sass-rails (~> 5.0)
  spring
  spring-watcher-listen (~> 2.0.0)
  toastr-rails
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)
  will_paginate (~> 3.1, >= 3.1.6)
  will_paginate-bootstrap (~> 1.0, >= 1.0.1)

BUNDLED WITH
   1.15.4

**Comment by paulettee** [comment]
The application works ok in development and when I run rails s -e production it works,  but not in production with passenger and nginx. That's when I get the error.

**Comment by segiddins** [comment]
How are you running the application when it doesn't work?

**Comment by paulettee** [comment]
I run 'sudo service nginx restart' then try to access the app from my browser http://myapp.com. Is there something I'm missing?

**Comment by paulettee** [comment]
My application running ok now. Had to delete the entire application from the production server and reinstall from scratch. Thanks for your help.
