### ISSUE TITLE
`bundle install` from `bundle exec`

### ISSUE THREAD

**Issue by AlexWayfer** [bundler/bundler#5984]
## Real-life case

[Gist](https://gist.github.com/AlexWayfer/3a00e87941d1b786a46e777527a5e779), [project](https://github.com/AlexWayfer/flame) (`rake` or `bundle exec rake`).

Tests run with `bundle exec`, inside tests new directory created (by template with `Gemfile`) and `bundle install` executed (and failed).

## Simplified example (with output)

[Gist](https://gist.github.com/AlexWayfer/d53263a24f0c79d1e1fe6630e7f89e62).

`bundle exec ruby file.rb`, or `ruby another_file.rb`.

## System information

```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ rbenv -v
rbenv 1.1.0-7-g755c820
$ bundler -v
Bundler version 1.15.4
$ uname -a
Linux archlinux 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux
```

**Comment by AlexWayfer** [comment]
```
$ bacon -a -s
Coverage report generated for RSpec to /home/alex/Projects/ruby/flame/coverage. 284 / 686 LOC (41.4%) covered.
0 specifications (0 requirements), 0 failures, 0 errors
/home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'byebug' (~> 9.1) - did find: [byebug-9.0.6] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/alex/.gem/ruby/2.4.0:/home/alex/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0', execute `gem env` for more information
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:1431:in `each'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:1431:in `activate_dependencies'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:1413:in `activate'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from spec/spec_helper.rb:18:in `<top (required)>'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bacon-1.2.0/bin/bacon:116:in `load'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bacon-1.2.0/bin/bacon:116:in `block in <top (required)>'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bacon-1.2.0/bin/bacon:115:in `each'
	from /home/alex/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bacon-1.2.0/bin/bacon:115:in `<top (required)>'
	from /home/alex/.rbenv/versions/2.4.1/bin/bacon:22:in `load'
	from /home/alex/.rbenv/versions/2.4.1/bin/bacon:22:in `<main>
```

Fixed by:

```diff
- s.add_development_dependency 'pry-byebug', '~> 3'
+ s.add_development_dependency 'pry-byebug', '~> 3.5'
```

And `bundle install`:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using public_suffix 2.0.5
Using ast 2.3.0
Using bacon 1.2.0
Using bundler 1.15.4
Fetching byebug 9.1.0 (was 9.0.6)
Installing byebug 9.1.0 (was 9.0.6) with native extensions
Using json 2.0.2
Using docile 1.1.5
Using simplecov-html 0.10.0
Using url 0.3.2
Using coderay 1.1.1
Using gorilla-patch 2.4.0
Using rack 2.0.3
Using thor 0.20.0
Using tilt 2.0.8
Using method_source 0.8.2
Using parallel 1.12.0
Using powerpack 0.1.1
Using slop 3.6.0
Using puma 3.10.0
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.3.0
Using rainbow 2.2.2
Using addressable 2.5.1
Using parser 2.4.0.0
Using bacon-colored_output 1.1.1
Using simplecov 0.14.1
Using rack-test 0.7.0
Using rack-utf8_sanitizer 1.3.2
Using pry 0.10.4
Using flame 4.18.1 from source at `.`
Using rubocop 0.49.1
Using codecov 0.1.10
Using pry-byebug 3.5.0 (was 3.4.3)
Bundle complete! 12 Gemfile dependencies, 34 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

…

I'm really confused :confused: 

I'm sorry.
