### ISSUE TITLE
Failed to allocate memory on aws eb

### ISSUE THREAD

**Issue by christophebeling** [bundler/bundler#6027]
When running bundler on aws eb deploy it fails with error failed to allocate memory. Here are the logs. Already tried to lock gem, chache and increase instance (t2.medium)

`## Backtrace
  
  ```
  NoMemoryError: failed to allocate memory
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package/tar_reader/entry.rb:134:in `read'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package/tar_reader/entry.rb:134:in `read'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:382:in `block (3 levels) in extract_tar_gz'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:381:in `open'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:381:in `block (2 levels) in extract_tar_gz'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:363:in `block in extract_tar_gz'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:457:in `block in open_tar_gz'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:454:in `wrap'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:454:in `open_tar_gz'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:362:in `extract_tar_gz'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:343:in `block (2 levels) in extract_files'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:340:in `block in extract_files'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package/file_source.rb:30:in `open'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package/file_source.rb:30:in `with_read_io'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/package.rb:337:in `extract_files'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/installer.rb:768:in `extract_files'
    /opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/installer.rb:295:in `install'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/source/rubygems.rb:145:in `block in install'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/rubygems_integration.rb:195:in `preserve_paths'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/source/rubygems.rb:135:in `install'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/installer/gem_installer.rb:55:in `install'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/installer/parallel_installer.rb:115:in `block in worker_pool'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/worker.rb:63:in `apply_func'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/worker.rb:58:in `block in process_queue'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/worker.rb:55:in `loop'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/worker.rb:55:in `process_queue'
    /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/worker.rb:89:in `block (2 levels) in create_threads'
  ```
  
  ## Environment
  
  ```
  Bundler   1.15.0
  Rubygems  2.5.2
  Ruby      2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
  GEM_HOME  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0
  GEM_PATH  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0:/.gem/ruby/2.3.0
  Git       not installed
  Platform  x86_64-linux
  OpenSSL   OpenSSL 1.0.1k 8 Jan 2015
  ```
  
  ## Bundler settings
  
  ```
  without
    Set for your local app (/var/app/ondeck/.bundle/config): "test:development"
    Set via BUNDLE_WITHOUT: "test:development"
  ```
  
  ## Gemfile
  
  ### Gemfile
  
  ```ruby
  source 'https://rubygems.org'
  
  git_source(:github) do |repo_name|
    repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
    "https://github.com/#{repo_name}.git"
  end
  
  
  # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
  gem 'rails', '~> 5.0.4'
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Use Puma as the app server
  gem 'puma', '~> 3.0'
  # Use SCSS for stylesheets
  gem 'sass-rails', '~> 5.0'
  # Use Uglifier as compressor for JavaScript assets
  gem 'uglifier', '>= 1.3.0'
  # Use CoffeeScript for .coffee assets and views
  gem 'coffee-rails', '~> 4.2'
  
  gem 'fae-rails'
  
  gem 'typescript-rails'
  
  gem 'bootstrap-sass', '~> 3.2.0'
  
  gem 'autoprefixer-rails'
  
  # See https://github.com/rails/execjs#readme for more supported runtimes
  # gem 'therubyracer', platforms: :ruby
  
  # Use jquery as the JavaScript library
  gem 'jquery-rails'
  # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
  gem 'turbolinks', '~> 5'
  # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
  gem 'jbuilder', '~> 2.5'
  # Use Redis adapter to run Action Cable in production
  # gem 'redis', '~> 3.0'
  # Use ActiveModel has_secure_password
  # gem 'bcrypt', '~> 3.1.7'
  
  # Use Capistrano for deployment
  # gem 'capistrano-rails', group: :development
  
  group :development, :test do
    # Call 'byebug' anywhere in the code to stop execution and get a debugger console
    gem 'byebug', platform: :mri
  end
  
  group :development do
    # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
    gem 'web-console', '>= 3.3.0'
    gem 'listen', '~> 3.0.5'
    # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
    gem 'spring'
    gem 'spring-watcher-listen', '~> 2.0.0'
  end
  
  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
  ```
  
  ### Gemfile.lock
  
  ```
  GEM
    remote: https://rubygems.org/
    specs:
      actioncable (5.0.6)
        actionpack (= 5.0.6)
        nio4r (>= 1.2, < 3.0)
        websocket-driver (~> 0.6.1)
      actionmailer (5.0.6)
        actionpack (= 5.0.6)
        actionview (= 5.0.6)
        activejob (= 5.0.6)
        mail (~> 2.5, >= 2.5.4)
        rails-dom-testing (~> 2.0)
      actionpack (5.0.6)
        actionview (= 5.0.6)
        activesupport (= 5.0.6)
        rack (~> 2.0)
        rack-test (~> 0.6.3)
        rails-dom-testing (~> 2.0)
        rails-html-sanitizer (~> 1.0, >= 1.0.2)
      actionview (5.0.6)
        activesupport (= 5.0.6)
        builder (~> 3.1)
        erubis (~> 2.7.0)
        rails-dom-testing (~> 2.0)
        rails-html-sanitizer (~> 1.0, >= 1.0.3)
      activejob (5.0.6)
        activesupport (= 5.0.6)
        globalid (>= 0.3.6)
      activemodel (5.0.6)
        activesupport (= 5.0.6)
      activerecord (5.0.6)
        activemodel (= 5.0.6)
        activesupport (= 5.0.6)
        arel (~> 7.0)
      activesupport (5.0.6)
        concurrent-ruby (~> 1.0, >= 1.0.2)
        i18n (~> 0.7)
        minitest (~> 5.1)
        tzinfo (~> 1.1)
      acts_as_list (0.9.7)
        activerecord (>= 3.0)
      arel (7.1.4)
      autoprefixer-rails (7.1.4)
        execjs
      bcrypt (3.1.11)
      bindex (0.5.0)
      bootstrap-sass (3.2.0.2)
        sass (~> 3.2)
      browser (0.8.0)
      builder (3.2.3)
      byebug (9.1.0)
      carrierwave (0.10.0)
        activemodel (>= 3.2.0)
        activesupport (>= 3.2.0)
        json (>= 1.7)
        mime-types (>= 1.16)
      coffee-rails (4.2.2)
        coffee-script (>= 2.2.0)
        railties (>= 4.0.0)
      coffee-script (2.4.1)
        coffee-script-source
        execjs
      coffee-script-source (1.12.2)
      concurrent-ruby (1.0.5)
      devise (4.3.0)
        bcrypt (~> 3.0)
        orm_adapter (~> 0.1)
        railties (>= 4.1.0, < 5.2)
        responders
        warden (~> 1.2.3)
      erubis (2.7.0)
      execjs (2.7.0)
      fae-rails (1.6.0)
        acts_as_list (~> 0.9.0)
        browser (~> 0.8.0)
        carrierwave (~> 0.10.0)
        devise (>= 3.4.1)
        jquery-rails (>= 3.1.1)
        jquery-ui-rails (~> 4.2.1)
        judge (~> 2.1.1)
        judge-simple_form (~> 1.0.0)
        kaminari (~> 0.17.0)
        rails (>= 4.1)
        remotipart (~> 1.3.1)
        rmagick (~> 2.13.3)
        sass (>= 3.4.0)
        sass-rails (>= 5.0.3)
        simple_form (>= 3.1.0)
        slim
        uglifier
      ffi (1.9.18)
      globalid (0.4.0)
        activesupport (>= 4.2.0)
      i18n (0.8.6)
      jbuilder (2.7.0)
        activesupport (>= 4.2.0)
        multi_json (>= 1.2)
      jquery-rails (4.3.1)
        rails-dom-testing (>= 1, < 3)
        railties (>= 4.2.0)
        thor (>= 0.14, < 2.0)
      jquery-ui-rails (4.2.1)
        railties (>= 3.2.16)
      json (2.1.0)
      judge (2.1.1)
        rails (>= 3.1)
      judge-simple_form (1.0.0)
        judge (~> 2.0)
        simple_form (>= 2.0)
      kaminari (0.17.0)
        actionpack (>= 3.0.0)
        activesupport (>= 3.0.0)
      listen (3.0.8)
        rb-fsevent (~> 0.9, >= 0.9.4)
        rb-inotify (~> 0.9, >= 0.9.7)
      loofah (2.0.3)
        nokogiri (>= 1.5.9)
      mail (2.6.6)
        mime-types (>= 1.16, < 4)
      method_source (0.8.2)
      mime-types (3.1)
        mime-types-data (~> 3.2015)
      mime-types-data (3.2016.0521)
      mini_portile2 (2.2.0)
      minitest (5.10.3)
      multi_json (1.12.2)
      nio4r (2.1.0)
      nokogiri (1.8.0)
        mini_portile2 (~> 2.2.0)
      orm_adapter (0.5.0)
      puma (3.10.0)
      rack (2.0.3)
      rack-test (0.6.3)
        rack (>= 1.0)
      rails (5.0.6)
        actioncable (= 5.0.6)
        actionmailer (= 5.0.6)
        actionpack (= 5.0.6)
        actionview (= 5.0.6)
        activejob (= 5.0.6)
        activemodel (= 5.0.6)
        activerecord (= 5.0.6)
        activesupport (= 5.0.6)
        bundler (>= 1.3.0)
        railties (= 5.0.6)
        sprockets-rails (>= 2.0.0)
      rails-dom-testing (2.0.3)
        activesupport (>= 4.2.0)
        nokogiri (>= 1.6)
      rails-html-sanitizer (1.0.3)
        loofah (~> 2.0)
      railties (5.0.6)
        actionpack (= 5.0.6)
        activesupport (= 5.0.6)
        method_source
        rake (>= 0.8.7)
        thor (>= 0.18.1, < 2.0)
      rake (12.1.0)
      rb-fsevent (0.10.2)
      rb-inotify (0.9.10)
        ffi (>= 0.5.0, < 2)
      remotipart (1.3.1)
      responders (2.4.0)
        actionpack (>= 4.2.0, < 5.3)
        railties (>= 4.2.0, < 5.3)
      rmagick (2.13.4)
      sass (3.5.1)
        sass-listen (~> 4.0.0)
      sass-listen (4.0.0)
        rb-fsevent (~> 0.9, >= 0.9.4)
        rb-inotify (~> 0.9, >= 0.9.7)
      sass-rails (5.0.6)
        railties (>= 4.0.0, < 6)
        sass (~> 3.1)
        sprockets (>= 2.8, < 4.0)
        sprockets-rails (>= 2.0, < 4.0)
        tilt (>= 1.1, < 3)
      simple_form (3.5.0)
        actionpack (> 4, < 5.2)
        activemodel (> 4, < 5.2)
      slim (3.0.8)
        temple (>= 0.7.6, < 0.9)
        tilt (>= 1.3.3, < 2.1)
      spring (2.0.2)
        activesupport (>= 4.2)
      spring-watcher-listen (2.0.1)
        listen (>= 2.7, < 4.0)
        spring (>= 1.2, < 3.0)
      sprockets (3.7.1)
        concurrent-ruby (~> 1.0)
        rack (> 1, < 3)
      sprockets-rails (3.2.1)
        actionpack (>= 4.0)
        activesupport (>= 4.0)
        sprockets (>= 3.0.0)
      sqlite3 (1.3.13)
      temple (0.8.0)
      thor (0.20.0)
      thread_safe (0.3.6)
      tilt (2.0.8)
      turbolinks (5.0.1)
        turbolinks-source (~> 5)
      turbolinks-source (5.0.3)
      typescript-node (1.6.2)
        typescript-src (~> 1.6.2)
      typescript-rails (0.6.2.4)
        railties
        tilt
        typescript-node (>= 1.6.2)
      typescript-src (1.6.2.0)
      tzinfo (1.2.3)
        thread_safe (~> 0.1)
      uglifier (3.2.0)
        execjs (>= 0.3.0, < 3)
      warden (1.2.7)
        rack (>= 1.0)
      web-console (3.5.1)
        actionview (>= 5.0)
        activemodel (>= 5.0)
        bindex (>= 0.4.0)
        railties (>= 5.0)
      websocket-driver (0.6.5)
        websocket-extensions (>= 0.1.0)
      websocket-extensions (0.1.2)
  
  PLATFORMS
    ruby
  
  DEPENDENCIES
    autoprefixer-rails
    bootstrap-sass (~> 3.2.0)
    byebug
    coffee-rails (~> 4.2)
    fae-rails
    jbuilder (~> 2.5)
    jquery-rails
    listen (~> 3.0.5)
    puma (~> 3.0)
    rails (~> 5.0.4)
    sass-rails (~> 5.0)
    spring
    spring-watcher-listen (~> 2.0.0)
    sqlite3
    turbolinks (~> 5)
    typescript-rails
    tzinfo-data
    uglifier (>= 1.3.0)
    web-console (>= 3.3.0)
  
  BUNDLED WITH
     1.15.3
  ```
  
  --- TEMPLATE END ----------------------------------------------------------------
  
  Unfortunately, an unexpected error occurred, and Bundler cannot continue.
  
  First, try this link to see if there are any existing issue reports for this error:
  https://github.com/bundler/bundler/search?q=failed+to+allocate+memory&type=Issues
  
  If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
  https://github.com/bundler/bundler/issues/new (Executor::NonZeroExitStatus)

`

Any ideas?

**Comment by colby-swandale** [comment]
This error is raised when the Ruby engine is unable to allocate memory. I suggest increasing the amount of memory available in your system.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
