### ISSUE TITLE
no implicit conversion of Bundler::Settings::Path into String (TypeError)

### ISSUE THREAD

**Issue by nishantkumar1292** [bundler/bundler#6045]
I added a gem in my `Gemfile` and thus I ran `bundle install` from my rails application root folder.
I was suggested to update my bundle, so I ran update with `gem install bundler --pre`.

I then started getting this error whenever I am trying to run `rails c`.
Error trace:
```
/home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:78:in `initialize': no implicit conversion of Bundler::Settings::Path into String (TypeError)
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:78:in `new'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:78:in `bundle_path'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:505:in `configure_gem_path'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:493:in `configure_gem_home_and_path'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:64:in `configure'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:128:in `definition'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/bundler.rb:112:in `load'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:46:in `candidate?'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:92:in `setup'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:124:in `check'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /home/ubuntu/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:10:in `<main>'
```

How can I resolve this?

**Comment by colby-swandale** [comment]
Hi, can you please attach the output of `bundle env`

**Comment by nishantkumar1292** [comment]
Hi @colby-swandale . Please find below the output for 
```
## Environment

``
Bundler           1.16.0.pre.2
RubyGems          2.6.13
Ruby              2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
GEM_HOME          /home/ubuntu/.rvm/gems/ruby-2.4.0
GEM_PATH          /home/ubuntu/.rvm/gems/ruby-2.4.0:/home/ubuntu/.rvm/gems/ruby-2.4.0@global
RVM               1.29.1 (latest)
Git               2.7.4
Platform          x86_64-linux
OpenSSL           OpenSSL 1.0.2g  1 Mar 2016
rubygems-bundler  (1.4.4)
``

## Bundler Build Metadata

``
Built At          2017-09-07
Git SHA           c1db119a5
Released Version  true
``

## Bundler settings

``
git.allow_insecure
  Set for your local app (/home/ubuntu/.bundle/config): "true"
  Set for the current user (/home/ubuntu/.bundle/config): "true"
``
```

**Comment by colby-swandale** [comment]
Hi, unfortunately we need the full output of `bundle env` which includes the `Gemfile` and `Gemfile.lock

**Comment by colby-swandale** [comment]
Are you or is RVM overwriting the `BUNDLE_PATH? This issue seems specific to your environment as I can install your Gemfile without any issues.

**Comment by nishantkumar1292** [comment]
On a different machine even I was able to install the gems. However in my system I am getting this error.
How can I know if RVM is overwriting BUNDLE PATH?

**Comment by colby-swandale** [comment]
I would recommend uninstalling rvm and then reinstalling ram, ruby and your gems as it's much easier then trying to debug an environment problem like this.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
