### ISSUE TITLE
unable to run tests using bitname ruby stack on rubymine editor

### ISSUE THREAD

**Issue by pavan93** [bundler/bundler#6050]
need some urgent support working on devise where I can execute on my local machine

```
C:\Bitnami\rubystack-2.3.4-6\ruby\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) -Ilib:test C:/Users/pavankumar/RubymineProjects/devisenew/test/test/integration_helpers_test.rb
Testing started at 6:01 PM ...
C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/source/git.rb:204:in `rescue in load_spec_files': git://github.com/rails/activemodel-serializers-xml.git (at master@dd9c0ac) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/source/git.rb:201:in `load_spec_files'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/source/path.rb:97:in `local_specs'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/source/git.rb:166:in `specs'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:246:in `block (2 levels) in index'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:244:in `each'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:244:in `block in index'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/index.rb:10:in `build'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:241:in `index'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:235:in `resolve'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from C:/Users/pavankumar/.gems/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from C:/Bitnami/rubystack-2.3.4-6/ruby/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Bitnami/rubystack-2.3.4-6/ruby/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

thanks in advance for helping me out
pavan

**Comment by colby-swandale** [comment]
Did you run `bundle install`?

**Comment by pavan93** [comment]
Yep did run bundle install but there are errors after DB migrate
Thanks

**Comment by colby-swandale** [comment]
@pavan93 were you able to resolve your problem?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
