### ISSUE TITLE
Error during bundle install "Unable to find a spec ffi"

### ISSUE THREAD

**Issue by goley** [bundler/bundler#6079]
The bundler command does not work in one of our teamcity agents (although its configuration is similar to other agents). It says that it can't find an ffi spec, but it's present in Gemfile.lock.

# Error Report

- **What did you do?**
I ran the command `C:/Ruby21-x64/bin/bundle install`

- **What did you expect to happen?**
I expected Bundler to install the gems

- **What happened instead?**
Instead, what happened was that the bundler through an error saying can't find the spec for ffi, which is actually mentioned in the Gemfile. I can see the folder for the gem ffi (1.9.10-x86-mingw32) in the gems folder too. (C:\Ruby21-x64\lib\ruby\gems\2.1.0\gems\ffi-1.9.10-x64-mingw32)

## Backtrace

```
RuntimeError: Unable to find a spec satisfying ffi (>= 0.5.0) in the set. Perhaps the lockfile is corrupted?
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:39:in `block in for'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:24:in `loop'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:24:in `for'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:79:in `materialize'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/definition.rb:199:in `missing_dependencies'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/installer.rb:219:in `block in resolve_if_need'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/ui/shell.rb:127:in `with_level'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/ui/shell.rb:86:in `silence'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/installer.rb:216:in `resolve_if_need'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/installer.rb:78:in `run'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/installer.rb:24:in `install'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/cli/install.rb:68:in `run'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/cli.rb:188:in `block in install'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/settings.rb:92:in `temporary'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/cli.rb:187:in `install'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
  C:/Ruby21-x64/bin/bundle:23:in `load'
  C:/Ruby21-x64/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler   1.15.4
Rubygems  2.2.5
Ruby      2.1.9p490 (2016-03-30 revision 54437) [x64-mingw32]
GEM_HOME  C:/Ruby21-x64/lib/ruby/gems/2.1.0
GEM_PATH  C:/Ruby21-x64/lib/ruby/gems/2.1.0;c:/Go/.gem/ruby/2.1.0
Git       1.9.5.msysgit.0
Platform  x64-mingw32
OpenSSL   OpenSSL 1.0.1l 15 Jan 2015
```

### Gemfile

```ruby
source 'http://rubygems.org'

gem 'albacore' , '2.2.0'
gem 'version_bumper'
gem 'nokogiri'
gem 'compass', '1.0.3'
gem 'sass-css-importer', '1.0.0.beta.0'
gem 'scss-lint', '0.37.0'
```

### Gemfile.lock

```
GEM
  remote: http://rubygems.org/
  specs:
    albacore (2.2.0)
      map (~> 6.5)
      nokogiri (~> 1.5)
      rake (~> 10)
      semver2 (~> 3.4)
    chunky_png (1.3.5)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    ffi (1.9.10-x86-mingw32)
    map (6.6.0)
    mini_portile2 (2.0.0)
    multi_json (1.11.2)
    nokogiri (1.6.7.1-x64-mingw32)
      mini_portile2 (~> 2.0.0.rc2)
    nokogiri (1.6.7.1-x86-mingw32)
      mini_portile2 (~> 2.0.0.rc2)
    rainbow (2.1.0)
    rake (10.5.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    sass (3.4.21)
    sass-css-importer (1.0.0.beta.0)
      sass (>= 3.1)
    scss-lint (0.37.0)
      rainbow (~> 2.0)
      sass (~> 3.4.1)
    semver2 (3.4.2)
    version_bumper (0.3.0)

PLATFORMS
  x64-mingw32
  x86-mingw32

DEPENDENCIES
  albacore (= 2.2.0)
  compass (= 1.0.3)
  nokogiri
  sass-css-importer (= 1.0.0.beta.0)
  scss-lint (= 0.37.0)
  version_bumper
```

**Comment by segiddins** [comment]
Yup, this looks like a bug (lockfile only has one of the platforms for ffi). Out of curiosity, can you check if 1.16.0.pre.3 fixes the issue?

**Comment by goley** [comment]
Yes 1.16.0.pre.3 fixes this problem. But the folder of 1.16.0.pre.3 does not have a bin folder which is causing my build steps to fail. Looks like teamcity agent is attempting to look for that.

**Comment by goley** [comment]
To temporarily resolve this, I tried copying the bin folder from 1.15.4 to 1.16.0.pre.3 and it worked. 

Also, looks like the ffi dependency issue is not completely resolved. It started appearing again. So maybe it is intermittent.

**Comment by soundasleep** [comment]
I am getting this error a lot on a Travis-ci build, intermittently but [failing more often than not](https://travis-ci.org/cryptfolionz/api/builds/331076341). Seems to be occurring with both Bundler 1.16.0 and 1.16.1 and 1.15.3.

ffi was listed in my Gemfile.lock with only a single x86 platform (I'm developing on Windows):

```
GEM
  remote: https://rubygems.org/
  specs:
    ffi (1.9.18-x64-mingw32)    
```

I tried `bundle lock --add-platform ruby` and `bundle lock --add-platform x86_64-linux` but that didn't do anything; they're already listed as platforms in the Gemfile.lock.

My solution was to manually edit the `Gemfile.lock` and add a non-w32 'ffi' gem manually. Yuck. But [now it works](https://travis-ci.org/cryptfolionz/api/builds/331078258).

```
GEM
  remote: https://rubygems.org/
  specs:
    ffi (1.9.18)
    ffi (1.9.18-x64-mingw32)
```

**Comment by segiddins** [comment]
I wonder if this will fix itself if you remove the `x64-mingw32` platform from your lockfile, and run `bundle install` again. Or alternatively if you run `bundle update ffi`? The issue seems to be that bundler does not think it needs to run the resolver again to pick up the `ffi` spec for the local platform

**Comment by segiddins** [comment]
Reproduced this, just wondering how `x64-mingw32` got into the lockfile without the entry for `ffi`...

**Comment by segiddins** [comment]
Took a while to wrap my head around things, but I hope https://github.com/bundler/bundler/pull/6288 will fix this bug! Thanks for bearing with us 🤞
