### ISSUE TITLE
 ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by MatheusRV** [bundler/bundler#6110]
```
$ bundle install
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using minitest 5.10.3
Using thread_safe 0.3.6
Using public_suffix 2.0.5
Using bundler 1.15.4
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using colorator 1.1.0
Fetching ffi 1.9.18


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password:
Installing ffi 1.9.18 with native extensions
Using multipart-post 2.0.0
Using forwardable-extended 2.6.0
Using gemoji 3.0.0
Using net-dns 0.8.0
Using rb-fsevent 0.10.2
Using kramdown 1.14.0
Using liquid 4.0.0
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using mini_portile2 2.3.0
Using jekyll-paginate 1.1.0
Using jekyll-swiss 0.4.0
Using unicode-display_width 1.3.0
Using i18n 0.9.0
Using tzinfo 1.2.3
Using addressable 2.5.2
Using coffee-script 2.4.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20171019-5673-f428t9ffi-1.9.18/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20171019-5673-yxk6q7.rb extconf.rb
/usr/lib/ruby/2.3.0/mkmf.rb:1547: warning: Insecure world writable dir /home/turing/.nvm/versions/node/v8.7.0 in PATH,
mode 040777
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
        from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
        from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20171019-5673-f428t9ffi-1.9.18/extensions/x86_64-linux/2.3.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20171019-5673-f428t9ffi-1.9.18/gems/ffi-1.9.18 for inspection.
Results logged to /tmp/bundler20171019-5673-f428t9ffi-1.9.18/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 164, which depends on
    github-pages-health-check was resolved to 1.3.5, which depends on
      typhoeus was resolved to 0.8.0, which depends on
        ethon was resolved to 0.10.1, which depends on
          ffi
```

```
## Environment

```
Bundler   1.15.4
Rubygems  2.5.1
Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
Git       2.7.4
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.2g  1 Mar 2016
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "github-pages", group: :jekyll_plugins
```

### Gemfile.lock

```
<No /mnt/c/Cloud/OneDrive/Dev/Descobridor/Gemfile.lock found>
```
```


Runing on WSL Build 16257.rs_prerelease.170728-1630

**Comment by colby-swandale** [comment]
Does `gem install ffi -v '1.9.18'` work?

**Comment by MatheusRV** [comment]
Fetching: ffi-1.9.18.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.

**Comment by colby-swandale** [comment]
You don't appear to have the right permissions to install your gems into that directory and not an issue with Bundler itself.

**Comment by MatheusRV** [comment]
https://github.com/ffi/ffi/issues/286#issuecomment-267675030

`$ apt-get install build-essential dh-autoreconf`

Works well ty

**Comment by Kshitij29** [comment]
Got the same error when tried to install cool.io on Solaris 10 (extconf.rb failed).
Can somebody help with the solaris equivalent of the solution?

**Comment by colby-swandale** [comment]
@Kshitij29 please open a new issue with the details of your problem
