### ISSUE TITLE
bundler with --path fails to properly map the gem path and causes error like rails or cucumber not found

### ISSUE THREAD

**Issue by alenteria** [bundler/bundler#6147]
I recently encountered error on travis build, see error details
```
DETAIL:  This name may be disallowed altogether in future versions of PostgreSQL.
/home/travis/.rvm/rubies/ruby-2.2.6/bin/ruby -S bundle exec cucumber  --profile default
bundler: failed to load command: cucumber (/home/travis/.bundle/ruby/2.2.0/bin/cucumber)
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: user requested 'bundler (= 1.14.6)'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:231:in `search_for'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:283:in `block in sort_dependencies'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `each'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `sort_by'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `with_index'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `sort_dependencies'
  /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_de`
```
I ran the travis build in debug mode and tried bundle install with --system and the error didn't occur anymore.

**Comment by tf** [comment]
Might be related to #6144.

**Comment by segiddins** [comment]
Could you please share the output of `bundle env`? Thanks!

**Comment by colby-swandale** [comment]
ping @alenteria
