### ISSUE TITLE
ArgumentError: wrong number of arguments (0 for 1..2)

### ISSUE THREAD

**Issue by janephilipps** [bundler/bundler#6171]
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details
```
ArgumentError: wrong number of arguments (0 for 1..2)
/usr/local/lib/ruby/2.2.0/uri/generic.rb:373:in `check_userinfo'
/usr/local/lib/ruby/2.2.0/uri/generic.rb:443:in `userinfo='
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems/remote.rb:38:in `apply_auth'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems/remote.rb:14:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:233:in `new'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:233:in `block in fetchers'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:232:in `map'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:232:in `fetchers'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/lazy_specification.rb:61:in `__materialize__'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:91:in `block in materialize'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `map!'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `materialize'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
```
Environment
```
  Bundler   1.13.6
  Rubygems  2.6.8
  Ruby      2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
  GEM_HOME  /usr/local/bundle
  GEM_PATH
  Git       2.1.4
```
      Bundler settings
```
    Set for the current user (/root/.bundle/config): {}
  disable_shared_gems
    Set for your local app (/usr/local/bundle/config): true
  app_config
    Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
  bin
    Set via BUNDLE_BIN: "/usr/local/bundle/bin"
  path
    Set via BUNDLE_PATH: "/usr/local/bundle"
  silence_root_warning
    Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
```

**Comment by colby-swandale** [comment]
This is a pretty old version of bundler, can you try updating to the latest version to see if your problem has already been resolved.

**Comment by janephilipps** [comment]
thanks @colby-swandale - I will try that and keep you posted.
