### ISSUE TITLE
Test suite does not work in path with dash

### ISSUE THREAD

**Issue by voxik** [bundler/bundler#6185]
Test suite does not work in patch such as ```rubygem-bundler```, e.g. the path with dash in it. This is apparently due to d967ea961a1c269751344f00c75956892eb71a35. I believe that there is nothing magical about "-" character and I'd be surprised if any commonly used system has issues handling dash in path. So I wonder what are the "special characters" you are trying to protect against?

@hmistry was talking about "white spaces" (and asking you to mention this somewhere, but this does not happened :/ ), but you are matching for "\w", which stands for "word character" (typically matches matches the ASCII characters [A-Za-z0-9_] and probably more unicode characters).

Why don't you match the white space characters, i.e. \s (which matches [ \t\r\n\f]), as was the original request?

**Comment by segiddins** [comment]
Because at the moment the tests don't all pass when those characters are present

**Comment by voxik** [comment]
Could you please be more specific about "those characters"? Does the set include dash? Let me try that ...

**Comment by segiddins** [comment]
I believe so. And since none of the maintainers keep bundler in a path with non-ascii characters, it's hard for us to guarantee things will work, which would make for a bad experience for someone trying to contribute for the first time

**Comment by voxik** [comment]
You are right, there is one test failure when dash is included in path:

~~~

  1) bundle update --bundler updates the bundler version in the lockfile without re-resolving
     Failure/Error: bundle! :update, :bundler => true, :verbose => true
     
     RuntimeError:
       Invoking bundle!(:update, {:bundler=>true, :verbose=>true, "no-color"=>true}) failed:
       Running `bundle update --bundler "> 0.a" --no-color --verbose` with bundler 1.16.0
       Found changes from the lockfile, re-resolving dependencies because the list of sources changed
       Fetching source index from file:/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/tmp/gems/remote4/
       Gem::RemoteFetcher::FetchError: Errno::ENOENT: No such file or directory @ rb_sysopen - /builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/tmp/gems/remote4/specs.4.8.gz (file:/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/tmp/gems/remote4/specs.4.8.gz)
       /usr/share/rubygems/rubygems/remote_fetcher.rb:311:in `rescue in fetch_path'
         /usr/share/rubygems/rubygems/remote_fetcher.rb:284:in `fetch_path'

... snip ...

       Commands:
       $ /usr/bin/ruby -rubygems -S gem --backtrace generate_index
       Generating Marshal quick index gemspecs for 2 gems

... snip ...

       # $? => 0
     
       $ /usr/bin/ruby \
         -I/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/lib:/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/spec \
         -rsupport/hax \
         -r/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/spec/support/artifice/fail \
         /builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/exe/bundle \
         install --retry 0 --no-color

... snip ...

       # $? => 0
     
       $ /usr/bin/ruby \
         -I/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/lib:/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/spec \
         -rsupport/hax \
         -r/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/spec/support/artifice/fail \
         /builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/exe/bundle update \
         --bundler --verbose --no-color
       Running `bundle update --bundler "> 0.a" --no-color --verbose` with bundler 1.16.0
       Found changes from the lockfile, re-resolving dependencies because the list of sources changed
       Fetching source index from file:/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/tmp/gems/remote4/
       Gem::RemoteFetcher::FetchError: Errno::ENOENT: No such file or directory @ rb_sysopen - /builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/tmp/gems/remote4/specs.4.8.gz (file:/builddir/build/BUILD/rubygem-bundler-1.16.0/usr/share/gems/gems/bundler-1.16.0/tmp/gems/remote4/specs.4.8.gz)
       /usr/share/rubygems/rubygems/remote_fetcher.rb:311:in `rescue in fetch_path'
         /usr/share/rubygems/rubygems/remote_fetcher.rb:284:in `fetch_path'

... snip ...
~~~

To me it seems that this is not problem in test suite but in Bundler which cannot, for some reason, correctly handle the "source" directive with "file:" url containing spaces when the location itself actually does not exists (since it was removed previously in the test case).

**Comment by voxik** [comment]
The PR #6194 fixing the failing test for me and it fails for completely different reasons the dash in path. I see no other failing tests when I have dash in the path. Please consider relaxing the restriction and allow dashes at least. This sed does the job for me:

~~~
sed -i 's|\[^\\w/\\.]|\[^\\w/\\.-\]|' spec/spec_helper.rb
~~~

I can send PR if it won't be wasted effort.

**Comment by colby-swandale** [comment]
Feel free to open a pr @voxik
