### ISSUE TITLE
problem launching bootstrap

### ISSUE THREAD

**Issue by rez20004** [bundler/bundler#6214]
```
URI::InvalidURIError: can not set user with opaque
  /root/.rbenv/versions/2.4.3/lib/ruby/2.4.0/uri/generic.rb:395:in `check_user'
  /root/.rbenv/versions/2.4.3/lib/ruby/2.4.0/uri/generic.rb:474:in `user='
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:922:in `proxy_from_env'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:860:in `proxy='
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:528:in `initialize'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/fetcher.rb:241:in `new'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/fetcher.rb:241:in `connection'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/fetcher.rb:85:in `initialize'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:251:in `new'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:251:in `block in fetchers'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:249:in `map'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:249:in `fetchers'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:383:in `block in remote_specs'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/index.rb:11:in `build'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:382:in `remote_specs'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/source/rubygems.rb:89:in `specs'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:268:in `block (2 levels) in index'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:266:in `each'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:266:in `block in index'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/index.rb:11:in `build'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:263:in `index'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:257:in `resolve'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:170:in `specs'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/definition.rb:158:in `resolve_remotely!'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/installer.rb:279:in `resolve_if_needed'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/installer.rb:83:in `block in run'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/process_lock.rb:12:in `block in lock'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/process_lock.rb:9:in `open'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/process_lock.rb:9:in `lock'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/installer.rb:72:in `run'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/installer.rb:25:in `install'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/install.rb:65:in `run'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:224:in `block in install'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/settings.rb:136:in `temporary'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:223:in `install'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
  /root/.rbenv/versions/2.4.3/bin/bundle:23:in `load'
  /root/.rbenv/versions/2.4.3/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       1.16.0
  Platforms   ruby, x86_64-linux
Ruby          2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  Full Path   /root/.rbenv/versions/2.4.3/bin/ruby
  Config Dir  /root/.rbenv/versions/2.4.3/etc
RubyGems      2.6.14
  Gem Home    /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0
  Gem Path    /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0:/root/.gem/ruby/2.4.0
  User Path   /root/.gem/ruby/2.4.0
  Bin Dir     /root/.rbenv/versions/2.4.3/bin
OpenSSL       
  Compiled    OpenSSL 1.0.2k  26 Jan 2017
  Loaded      OpenSSL 1.0.2k-fips  26 Jan 2017
  Cert File   /etc/pki/tls/cert.pem
  Cert Dir    /etc/pki/tls/certs
Tools         
  Git         1.8.3.1
  RVM         not installed
  rbenv       rbenv 1.1.1-28-gb943955

  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-10-31
Git SHA           10f20fa33
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'github-pages'
gem 'jekyll-octicons'

group :development, :test do
  gem 'html-proofer'
  gem 'parallel'
  gem 'rake'
  gem 'rubocop'
  gem 'typhoeus'
end
```

### Gemfile.lock

```
<No /root/government.github.com/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by segiddins** [comment]
Can you please share what's in your ENV, particularly the http proxy variables? Thanks!

**Comment by rez20004** [comment]
%5b%5d%3d-c.ri   empty%3f-c.ri      keys-c.ri       size-c.ri
%5b%5d-c.ri      fetch-c.ri         length-c.ri     store-c.ri
assoc-c.ri       has_key%3f-c.ri    member%3f-c.ri  to_a-c.ri
cdesc-ENV.ri     has_value%3f-c.ri  rassoc-c.ri     to_hash-c.ri
clear-c.ri       include%3f-c.ri    rehash-c.ri     to_h-c.ri
delete-c.ri      index-c.ri         reject%21-c.ri  to_s-c.ri
delete_if-c.ri   inspect-c.ri       reject-c.ri     update-c.ri
each-c.ri        invert-c.ri        replace-c.ri    value%3f-c.ri
each_key-c.ri    keep_if-c.ri       select%21-c.ri  values_at-c.ri
each_pair-c.ri   key%3f-c.ri        select-c.ri     values-c.ri
each_value-c.ri  key-c.ri           shift-c.ri

**Comment by rez20004** [comment]
I am though proxy servers
