### ISSUE TITLE
TypeError: superclass mismatch for class Cipher

### ISSUE THREAD

**Issue by Dorian** [bundler/bundler#6234]
# Error Report

I was trying to create a Gemfile for bundler and encountered this error:

## Questions

- **What did you do?**

  I ran the command `/Users/d/.rvm/gems/ruby-2.4.1/bin/bundle`

- **What did you expect to happen?**

  I expected Bundler to install the dependencies from `bundler.gemspec`

- **What happened instead?**

  Instead, what happened was this error :).

## Backtrace

```
TypeError: superclass mismatch for class Cipher
  /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/cipher.rb:64:in `<class:Cipher>'
  /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/cipher.rb:16:in `<module:OpenSSL>'
  /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/cipher.rb:15:in `<top (required)>'
  /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl.rb:17:in `require'
  /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl.rb:17:in `<top (required)>'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:211:in `require'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:211:in `md5_available?'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/fetcher/compact_index.rb:65:in `available?'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/fetcher/compact_index.rb:16:in `call'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/fetcher.rb:158:in `use_api'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:376:in `block in api_fetchers'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:376:in `select'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:376:in `api_fetchers'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:381:in `block in remote_specs'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/index.rb:11:in `build'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:380:in `remote_specs'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:89:in `specs'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:268:in `block (2 levels) in index'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:266:in `each'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:266:in `block in index'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/index.rb:11:in `build'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:263:in `index'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:257:in `resolve'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/definition.rb:158:in `resolve_remotely!'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/installer.rb:279:in `resolve_if_needed'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/installer.rb:83:in `block in run'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/process_lock.rb:9:in `open'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/process_lock.rb:9:in `lock'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/installer.rb:72:in `run'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/installer.rb:25:in `install'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli/install.rb:65:in `run'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:224:in `block in install'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/settings.rb:136:in `temporary'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:223:in `install'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  /Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
  /Users/d/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
  /Users/d/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler       1.16.1
  Platforms   ruby, x86_64-darwin-14
Ruby          2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/2.4.1_1/etc
RubyGems      2.6.11
  Gem Home    /Users/d/.rvm/gems/ruby-2.4.1
  Gem Path    /Users/d/.rvm/gems/ruby-2.4.1:/Users/d/.rvm/gems/ruby-2.4.1@global
  User Path   /Users/d/.gem/ruby/2.4.0
  Bin Dir     /Users/d/.rvm/gems/ruby-2.4.1/bin
OpenSSL
  Compiled    OpenSSL 1.0.2k  26 Jan 2017
  Loaded      OpenSSL 1.0.2n  7 Dec 2017
  Cert File   /usr/local/etc/openssl/cert.pem
  Cert Dir    /usr/local/etc/openssl/certs
Tools
  Git         2.13.2
  RVM         1.29.3master
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

## Bundler settings

```
bin_path
  Set via BUNDLE_BIN_PATH: "/Users/d/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/Users/d/src/clones/bundler/Gemfile"
```

### Gemfile

```ruby
source "https://www.rubygems.org"

gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:

GEM
  remote: https://www.rubygems.org/
  specs:
    automatiek (0.1.2)
    diff-lcs (1.3)
    hpricot (0.8.6)
    mustache (1.0.5)
    rake (10.5.0)
    rdiscount (2.2.0.1)
    ronn (0.7.3)
      hpricot (>= 0.8.2)
      mustache (>= 0.7.0)
      rdiscount (>= 1.5.8)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.0)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.0)

PLATFORMS
  ruby

DEPENDENCIES
  automatiek (~> 0.1.0)
  bundler!
  mustache (~> 1.0.5)
  rake (~> 10.0)
  rdiscount (~> 2.2)
  ronn (~> 0.7.3)
  rspec (~> 3.6)

BUNDLED WITH
   1.16.1
```

### bundler.gemspec

```ruby
# coding: utf-8
# frozen_string_literal: true

require File.expand_path("../lib/bundler/version", __FILE__)
require "shellwords"

Gem::Specification.new do |s|
  s.name        = "bundler"
  s.version     = Bundler::VERSION
  s.license     = "MIT"
  s.authors     = [
    "André Arko", "Samuel Giddins", "Chris Morris", "James Wen", "Tim Moore",
    "André Medeiros", "Jessica Lynn Suttles", "Terence Lee", "Carl Lerche",
    "Yehuda Katz"
  ]
  s.email       = ["team@bundler.io"]
  s.homepage    = "http://bundler.io"
  s.summary     = "The best way to manage your application's dependencies"
  s.description = "Bundler manages an application's dependencies through its entire life, across many machines, systematically and repeatably"

  if s.respond_to?(:metadata=)
    s.metadata = {
      "bug_tracker_uri" => "http://github.com/bundler/bundler/issues",
      "changelog_uri" => "https://github.com/bundler/bundler/blob/master/CHANGELOG.md",
      "homepage_uri" => "https://bundler.io/",
      "source_code_uri" => "http://github.com/bundler/bundler/",
    }
  end

  if s.version >= Gem::Version.new("2.a".dup)
    s.required_ruby_version     = ">= 2.3.0"
    s.required_rubygems_version = ">= 2.5.0"
  else
    s.required_ruby_version     = ">= 1.8.7"
    s.required_rubygems_version = ">= 1.3.6"
  end

  s.add_development_dependency "automatiek", "~> 0.1.0"
  s.add_development_dependency "mustache",   "~> 1.0.5"
  s.add_development_dependency "rake",       "~> 10.0"
  s.add_development_dependency "rdiscount",  "~> 2.2"
  s.add_development_dependency "ronn",       "~> 0.7.3"
  s.add_development_dependency "rspec",      "~> 3.6"

  s.files = `git -C #{Shellwords.escape File.dirname(__FILE__)} ls-files -z`.split("\x0").select {|f| f.match(%r{^(lib|exe)/}) }

  # we don't check in man pages, but we need to ship them because
  # we use them to generate the long-form help for each command.
  s.files += Dir.glob("man/**/*")
  # Include the CHANGELOG.md, LICENSE.md, README.md manually
  s.files += %w[CHANGELOG.md LICENSE.md README.md]
  # include the gemspec itself because warbler breaks w/o it
  s.files += %w[bundler.gemspec]

  s.bindir        = "exe"
  s.executables   = %w[bundle bundler]
  s.require_paths = ["lib"]
end
```

**Comment by segiddins** [comment]
Can you run `gem which openssl/cipher` for me? My guess is that somehow two different versions of openssl are being loaded on your machine, which is weird

**Comment by colby-swandale** [comment]
ping @Dorian

**Comment by Dorian** [comment]
@segiddins @colby-swandale I get:

```
/Users/d/.rvm/gems/ruby-2.4.1/gems/openssl-2.0.4/lib/openssl/cipher.rb
```

**Comment by segiddins** [comment]
Yeah, that's different from `/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/openssl/cipher.rb`

**Comment by xero88** [comment]
I get the same error, how to resolve that ?

**Comment by segiddins** [comment]
I don't know, sorry

**Comment by colby-swandale** [comment]
Is this problem still occurring on newer versions of Bundler?

**Comment by colby-swandale** [comment]
Closing due to no response.
