### ISSUE TITLE
Could not find multi_json-1.12.1 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by MNIKGANDE** [bundler/bundler#6236]
$ bundle env
## Environment

```
Bundler       1.16.1
  Platforms   ruby, x64-mingw32
Ruby          2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
  Full Path   C:/Ruby22-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      2.4.5.2
  Gem Home    C:/Ruby22-x64/lib/ruby/gems/2.2.0
  Gem Path    C:/Users/kgande/.gem/ruby/2.2.0;C:/Ruby22-x64/lib/ruby/gems/2.2.0
  User Path   C:/Users/kgande/.gem/ruby/2.2.0
  Bin Dir     C:/Ruby22-x64/bin
Tools
  Git         2.14.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

```
 [exec] C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find multi_json-1.12.1 in any of the sources (Bundler::GemNotFound)
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
     [exec]     from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
     [exec]     from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
     [exec] Result: 6
```

**Comment by segiddins** [comment]
Can you please share the whole output from `bundle env`, including your Gemfile? Thanks!

**Comment by MNIKGANDE** [comment]
[bundler-1.16.1.zip](https://github.com/bundler/bundler/files/1594358/bundler-1.16.1.zip)


prepareUI:
     [echo] Preparing UIResource.resource...
     [exec] parameters: + -optimizeUI
     [exec] Creating UIPath...
     [exec] mnadmin mnapp mncatalog mnconfig mnconfigadmin mnquote uifw
     [exec] Generating CSS using production (optimized) mode...
     [exec] (node:4208) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.Running "compass:clean" (compass) task
     [exec]
     [exec] Warning: ↑ Use --force to continue.
     [exec]
     [exec] Aborted due to warnings.
     [exec] C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find multi_json-1.12.1 in any of the sources (Bundler::GemNotFound)
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
     [exec]     from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
     [exec]     from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
     [exec]     from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
     [exec] Result: 6
     [echo] Preparing UIResource.resource...Done.

**Comment by colby-swandale** [comment]
@MNIKGANDE what you have linked is Bundler's source code and the error log which does not really help us. Please attach the the output by running the command `bundler env` in your project directory.

**Comment by MNIKGANDE** [comment]
kgande@mnikgande MINGW64 ~
$ bundler env
## Environment

```
Bundler       1.16.1
  Platforms   ruby, x64-mingw32
Ruby          2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
  Full Path   C:/Ruby22-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      2.4.5.2
  Gem Home    C:/Ruby22-x64/lib/ruby/gems/2.2.0
  Gem Path    C:/Users/kgande/.gem/ruby/2.2.0;C:/Ruby22-x64/lib/ruby/gems/2.2.0
  User Path   C:/Users/kgande/.gem/ruby/2.2.0
  Bin Dir     C:/Ruby22-x64/bin
Tools
  Git         2.14.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

**Comment by colby-swandale** [comment]
@MNIKGANDE please attach the full output of `bundler evn` which includes the `Gemfile` and `Gemfile.lock`

**Comment by MNIKGANDE** [comment]
@colby-swandale  Please can you help me where can i find those files.

**Comment by MNIKGANDE** [comment]
$ bundler env
## Environment

```
Bundler       1.16.1
  Platforms   ruby, x64-mingw32
Ruby          2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
  Full Path   C:/Ruby22-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      2.4.5.2
  Gem Home    C:/Ruby22-x64/lib/ruby/gems/2.2.0
  Gem Path    C:/Users/kgande/.gem/ruby/2.2.0;C:/Ruby22-x64/lib/ruby/gems/2.2.0
  User Path   C:/Users/kgande/.gem/ruby/2.2.0
  Bin Dir     C:/Ruby22-x64/bin
Tools
  Git         2.14.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

## Gemfile

### Gemfile

```ruby
# enforce specific versions of ruby dependencies

source 'http://rubygems.org'

gem 'sass'
gem 'compass'
gem 'scss-lint'
```

### Gemfile.lock

```
GEM
  remote: http://rubygems.org/
  specs:
    chunky_png (1.3.8)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    ffi (1.9.18-x64-mingw32)
    multi_json (1.12.1)
    rainbow (2.2.1)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.8)
      ffi (>= 0.5.0)
    sass (3.4.23)
    scss-lint (0.38.0)
      rainbow (~> 2.0)
      sass (~> 3.4.1)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  compass
  sass
  scss-lint

BUNDLED WITH
   1.14.6
```

**Comment by colby-swandale** [comment]
I can install this Gemfile  without any errors.

```
root@18a71e8b028b:/tmp# bundle install
Fetching gem metadata from http://rubygems.org/...........
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies...
Using bundler 1.16.1
Using chunky_png 1.3.8
Using multi_json 1.12.1
Using sass 3.4.23
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.8
Using ffi 1.9.18
Using rb-inotify 0.9.8
Using compass 1.0.3
Using rainbow 2.2.1
Fetching scss-lint 0.38.0
Installing scss-lint 0.38.0
Bundle complete! 3 Gemfile dependencies, 12 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Post-install message from scss-lint:
WARNING: `scss-lint` has been renamed to `scss_lint` to follow proper RubyGems naming conventions. Update your Gemfile or relevant install scripts to install `scss_lint`.
````

**Comment by MNIKGANDE** [comment]
@colby-swandale  Thanks i have run bundle install my problem resolved.
