### ISSUE TITLE
ThreadError can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by stalker37** [bundler/bundler#6322]
Debian wheezy or  jessie. ruby 2.4 and bunder 1.16.1
error in bundle install 

user@labsrv:~/test$  rvm use 2.4 do bundle install --path ./gems
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/.Failed to create threads for the Compact Index (rubygems.org) worker: can't create Thread: Resource temporarily unavailable

Retrying fetcher due to error (2/4): ThreadError can't create Thread: Resource temporarily unavailable.
Retrying fetcher due to error (3/4): ThreadError can't create Thread: Resource temporarily unavailable.
Retrying fetcher due to error (4/4): ThreadError can't create Thread: Resource temporarily unavailable.
...

in normal work user running ~25 processes
ps -mu user | wc -l
25

after run 'rvm use 2.4 do bunlde install':
root@labsrv:~# ps -mu user | wc -l
50

root@labsrv:~# ps -mu user
  PID TTY          TIME CMD
 4699 ?        00:00:05 bundle
    - -        00:00:05 -
    - -        00:00:00 -
 4731 ?        00:00:01 bundle
    - -        00:00:01 -
    - -        00:00:00 -
14124 ?        00:00:00 sshd
    - -        00:00:00 -
14125 pts/0    00:00:00 bash
    - -        00:00:00 -
22235 ?        00:00:11 ruby
    - -        00:00:11 -
    - -        00:00:00 -
22387 ?        00:18:33 ruby
    - -        00:18:33 -
    - -        00:00:00 -
26422 pts/0    00:00:02 bundle
    - -        00:00:01 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
29294 ?        00:00:24 ruby
    - -        00:00:24 -
    - -        00:00:00 -
29409 ?        01:50:08 ruby
    - -        01:50:08 -
    - -        00:00:00 -

and as a result, limits are triggered, according to the limits.conf

test     hard    rss            512000
test     hard    nproc           40
test     hard    priority        10
test     hard    cpu             20

downgrade to 1.11.2  the  fixes the problem

**Comment by colby-swandale** [comment]
Does setting Bundler to run only a single thread like:`bundle install -j 1` fix this problem?

**Comment by stalker37** [comment]
Hi!
No
user@labsrv:~/test$ rvm use 2.4 do bundle install -j 1 --path ./gems/
root@labsrv:~# ps -mu user | wc -l
50

**Comment by segiddins** [comment]
That's probably because the compact index updater is set to automatically use a whole bunch of threads

**Comment by vs-adm** [comment]
I guess the key point is the `25` hardcode in https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher/compact_index.rb#L100

```ruby
def bundle_worker(func = nil)
        @bundle_worker ||= begin
          worker_name = "Compact Index (#{display_uri.host})"
          Bundler::Worker.new(Bundler.current_ruby.rbx? ? 1 : 25, worker_name, func)
        end
        @bundle_worker.tap do |worker|
          worker.instance_variable_set(:@func, func) if func
        end
      end
```

I'm going to limit thread pool for compact index updater. What is the best way to impement this fix?

1. Introduce new ENV variable which set pool size
2. Align compact indexer thread pool size with `-j` option
3. Introduce new option to set this

**Comment by segiddins** [comment]
The worker should transparently handle hitting the thread limit...

**Comment by segiddins** [comment]
@mislav please try with bundler 1.16.2

**Comment by dwn** [comment]
@segiddins not working for me using 1.16.2

**Comment by segiddins** [comment]
With the same backtrace ?

**Comment by dwn** [comment]
On a BlueHost server...

Retrying fetcher due to error (2/4): ThreadError can't create Thread: Resource temporarily unavailable.
Retrying fetcher due to error (3/4): ThreadError can't create Thread: Resource temporarily unavailable.
Retrying fetcher due to error (4/4): ThreadError can't create Thread: Resource temporarily unavailable.
^C/home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/timeout.rb:81:in `start': can't create Thread: Resource temporarily unavailable (ThreadError)
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/timeout.rb:81:in `block in timeout'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/net/http.rb:858:in `start'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:702:in `start'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:967:in `reset'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:630:in `connection_for'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendored_persistent.rb:23:in `connection_for'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:996:in `request'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/fetcher/downloader.rb:51:in `request'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/fetcher/downloader.rb:17:in `fetch'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/fetcher/compact_index.rb:117:in `call'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/compact_index_client/updater.rb:53:in `block in update'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/compact_index_client/updater.rb:31:in `update'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/compact_index_client.rb:82:in `update'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/compact_index_client.rb:98:in `update_info'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/compact_index_client.rb:55:in `block in dependencies'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/worker.rb:64:in `apply_func'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/worker.rb:59:in `block in process_queue'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/worker.rb:56:in `loop'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/worker.rb:56:in `process_queue'
	from /home2/miamini2/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

miamini2@miaminice.us [~/museum]# bundle env
fatal: not a git repository (or any parent up to mount point /home2)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
## Environment

```
Bundler       1.16.2
  Platforms   ruby, x86_64-linux
Ruby          2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
  Full Path   /home2/miamini2/.rvm/rubies/ruby-2.3.7/bin/ruby
  Config Dir  /home2/miamini2/.rvm/rubies/ruby-2.3.7/etc
RubyGems      2.7.7
  Gem Home    /home2/miamini2/.rvm/gems/ruby-2.3.7
  Gem Path    /home2/miamini2/.rvm/gems/ruby-2.3.7:/home2/miamini2/.rvm/gems/ruby-2.3.7@global
  User Path   /home2/miamini2/.gem/ruby/2.3.0
  Bin Dir     /home2/miamini2/.rvm/gems/ruby-2.3.7/bin
Tools         
  Git         2.17.1
  RVM         1.29.4 (latest)
  rbenv       not installed
  chruby      not installed
```

**Comment by vs-adm** [comment]
I've proposed PR which demonstrates the problem and possible solution.

**Comment by dwn** [comment]
Could someone please provide a workaround? The client's breathing down my neck.

**Comment by vs-adm** [comment]
@dwn I can't figure how to workaround, you may build version from my PR and use it providing `COMPACT_INDEX_POOL=1` env variable.
