### ISSUE TITLE
A rake build failed because of missing bundler/dep_proxy

### ISSUE THREAD

**Issue by breakfast1** [bundler/bundler#6340]
Here is the said build: <https://travis-ci.org/tech-angels/vandamme/builds/353287717>. The error is happening at <https://travis-ci.org/tech-angels/vandamme/jobs/353287720#L852>.

As you can see the error is only happening with `ruby-head`.

The only change in the code base is that I updated dependencies. Previous builds were successful.

```
$ bundle exec rake
bundler: failed to load command: rake (/home/travis/build/tech-angels/vandamme/vendor/bundle/ruby/2.6.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/setup.rb:10:in `<top (required)>'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

**Comment by hsbt** [comment]
This is an environment of travis issue. Please submit a https://github.com/travis-ci/travis-ci/issues as first.

**Comment by bf4** [comment]
Fwiw, I have this happening on my mac book pro, running rvm (1.29.3), just upgraded to ruby 2.4.4 from 2.3.3. When I switched from 2.4.4 to 2.3.3 and back to 2.4.4 I get this error and cannot get rid of it. I get it with bundler 1.15.x and 1.16.x and with standalone and not standalone and rm'ng the install, and clearing the Gemfile.lock. I previously got this same error on 2.5.x in development which prevented me from updating my Ruby. For the life of me, I don't know what's causing it except for some kind of disconnect between the bundler autoload and the loaded bundler. Even calling `ruby -S bundle` doesn't help, nor does something dumb like ```bundle exec ruby -e 'puts Bundler.with_clean_env { `bin/rspec spec/models/user_spec.rb` }'```. I also uninstalled rubygems-bundler gem-wrappers and executable-hooks and run ` gem regenerate_binstubs`, .  

Omg, while writing this I just tried `gem update --system`, which I swear I've tried before and it seems to have worked.


system update juicy parts

```
📝 $ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.6.gem (100%)
Successfully installed rubygems-update-2.7.6
Parsing documentation for rubygems-update-2.7.6
Installing ri documentation for rubygems-update-2.7.6
Done installing documentation for rubygems-update after 29 seconds
Parsing documentation for rubygems-update-2.7.6
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.6
Bundler 1.16.1 installed
RubyGems 2.7.6 installed
Regenerating binstubs
Parsing documentation for rubygems-2.7.6
Installing ri documentation for rubygems-2.7.6

RubyGems installed the following executables:
        /Users/benjamin/.rvm/rubies/ruby-2.4.4/bin/gem
        /Users/benjamin/.rvm/rubies/ruby-2.4.4/bin/bundle

```

stacktrace below:

```
bundler: failed to load command: rails (/Users/benjamin/.rvm/gems/ruby-2.4.4/bin/rails)
LoadError: cannot load such file -- bundler/dep_proxy
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:856:in `block (2 levels) in expand_dependencies'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:855:in `each'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:855:in `block in expand_dependencies'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:842:in `each'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:842:in `expand_dependencies'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:779:in `converge_locked_specs'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:228:in `resolve'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:9:in `<top (required)>'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- bundler (LoadError)
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/shared_helpers.rb:275:in `prints_major_deprecations?'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/shared_helpers.rb:133:in `major_deprecation'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/shared_helpers.rb:285:in `deprecate_gemfile'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/shared_helpers.rb:140:in `print_major_deprecations!'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:18:in `ensure in start'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:18:in `start'
        from /Users/benjamin/.rvm/gems/ruby-2.4.4/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
        from /Users/benjamin/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from /Users/benjamin/.rvm/gems/ruby-2.4.4/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
        from /Users/benjamin/.rvm/gems/ruby-2.4.4/bin/bundle:23:in `load'
        from /Users/benjamin/.rvm/gems/ruby-2.4.4/bin/bundle:23:in `<main>'
```

**Comment by indirect** [comment]
@bf4 it sounds like you might have a different problem. I was able to resolve the issue on travis by running `gem install bundler`. If that doesn’t work for you, I think a new ticket with full information about your issue is the way to go.

**Comment by bf4** [comment]
@indirect I could make a new issue. If I'm able to reproduce the issue, anything in particular I should share?
