### ISSUE TITLE
bundler blows up when running on readonly device

### ISSUE THREAD

**Issue by grosser** [bundler/bundler#6461]
(I'm using the Bundler::CLI module here to make it easier to reproduce, otherwise would need a Gemfile)

```
docker run --read-only ruby ruby -r bundler/cli -e "puts Bundler::VERSION; Bundler::CLI.start(['exec', 'ruby', '-v'], :debug => true)"
/usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:193:in `rescue in tmp_home_path': `/root` is not writable. (Bundler::GenericSystemCallError)
Bundler also failed to create a temporary home directory at `/tmp/bundler/home':
There was an error accessing `/tmp/bundler/home`.
The underlying system error is Errno::EROFS: Read-only file system @ dir_s_mkdir - /tmp/bundler
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:181:in `tmp_home_path'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:172:in `user_home'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:197:in `user_bundle_path'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/plugin.rb:99:in `global_root'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/plugin/index.rb:73:in `global_index_file'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/plugin/index.rb:32:in `initialize'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/plugin.rb:78:in `new'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/plugin.rb:78:in `index'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/plugin.rb:114:in `command?'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:130:in `handle_no_command_error'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:31:in `run'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:128:in `run'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
	from -e:1:in `<main>'
1.16.1
```

Adding `-e BUNDLE_PLUGINS=false` solves the crash, but it's annoying since now I have to always type that or add it to our `Dockerfile`

FYI adding BUNDLE_CONFIG=/dev/null silences the leftover warning (`Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily`) that still comes up after it got past the plugins.

**Comment by segiddins** [comment]
Something like the following should do the trick:

```diff
diff --git a/lib/bundler/plugin/index.rb b/lib/bundler/plugin/index.rb
index cd7a5093b..f7787048e 100644
--- a/lib/bundler/plugin/index.rb
+++ b/lib/bundler/plugin/index.rb
@@ -29,7 +29,11 @@ module Bundler
         @hooks = {}
         @load_paths = {}
 
-        load_index(global_index_file, true)
+        begin
+          load_index(global_index_file, true)
+        rescue SystemCallError
+          # no need to fail when on a read-only FS, for example
+        end
         load_index(local_index_file) if SharedHelpers.in_bundle?
       end
 
```

**Comment by grosser** [comment]
Yes this was with the nobody user ... But I'd think it fails with a real
user too if home is read-only

**Comment by segiddins** [comment]
I’m pretty sure it’s only happening since Bundler is hitting fallback code that only happens when home does not exist

**Comment by segiddins** [comment]
Feel free, just needs a test!
