### ISSUE TITLE
Bundler.with_clean_env crashes by accessing private method clone on hash

### ISSUE THREAD

**Issue by jugutier** [bundler/bundler#6545]
```
NoMethodError: private method `clone' called for #<Hash:0x007f9c978763e8>
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/environment_preserver.rb:45:in `restore'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:22:in `<module:Bundler>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:20:in `<top (required)>'
```

This issue happens using ruby 2.4.0 through `rvm` as well

To reproduce follow setup instructions in this project.

https://github.com/CocoaPods/Strata

Issue happens over here:
https://github.com/CocoaPods/Strata/blob/master/Rakefile#L373

Other things tried:
1. To rule out that `rake-12.3.1` wasn't somehow locking the ENV hash I set up a simple Rakefile with the following:
```
task default: %w[test]

task :test do
    original = ENV.to_hash
    copy = original.clone
    puts copy
end

```

Which seems to work well.

2. On irb also tried the same code

```
original = ENV.to_hash
    copy = original.clone
    puts copy
```
which also seems to work well.

Full stack trace

```
rake aborted!
NoMethodError: private method `clone' called for #<Hash:0x007fcf00a59480>
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/environment_preserver.rb:45:in `restore'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:22:in `<module:Bundler>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:20:in `<top (required)>'
~/Strata/Rakefile:375:in `block (2 levels) in clone_repos'
~/Strata/Rakefile:373:in `chdir'
~/Strata/Rakefile:373:in `block in clone_repos'
~/Strata/Rakefile:363:in `each'
```

Also tried with bundler 1.1.6.1 with same results. 

[environment_preserver.rb#L45](https://github.com/bundler/bundler/blob/master/lib/bundler/environment_preserver.rb#L45) hasn't been touched for a long time so I'm out of clues.

**Comment by segiddins** [comment]
Looks like it's fixed with the following:

```diff
diff --git a/Rakefile b/Rakefile
index 369cf37..41113ee 100644
--- a/Rakefile
+++ b/Rakefile
@@ -29,7 +29,7 @@ DEFAULT_REPOS = WEB_REPOS
 #-----------------------------------------------------------------------------#
 
 def setup name
-  clone name
+  clone_repo name
   bootstrap name
 end
 
@@ -59,7 +59,7 @@ def bootstrap name = nil
   puts "\nDisk usage: #{disk_usage}"
 end
 
-def clone name
+def clone_repo name
   repos = fetch_default_repos
   if name
     repos = [repos.find { |repo| repo['name'] == name }]
@@ -110,7 +110,7 @@ begin
 
   desc "Clones the web repositories"
   task :clone, :name do |task, args|
-    clone(args.name)
+    clone_repo(args.name)
   end
 
   # Task install_system_deps
@@ -140,7 +140,7 @@ begin
       bootstrap(name)
     else
       Bundler.with_clean_env do
-        puts `bundle install`
+        sh 'bundle install'
       end
     end
   end

```

**Comment by jugutier** [comment]
Just tested on Strata, now I don't get the error anymore. Good catch I didn't think the rakefile would define a `clone` method.

Thanks @segiddins !
