### ISSUE TITLE
Error install rails on NFS

### ISSUE THREAD

**Issue by brabo-hi** [bundler/bundler#6566]
I tried to install rails on mac on NFS, and got that error

**rails new blog**

`## Backtrace

```
Errno::ENOTSUP: Operation not supported @ rb_file_flock - /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/bundler.lock
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/process_lock.rb:10:in `flock'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/process_lock.rb:10:in `block in lock'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/process_lock.rb:9:in `open'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/process_lock.rb:9:in `lock'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/installer.rb:72:in `run'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/installer.rb:25:in `install'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/cli/install.rb:65:in `run'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/cli.rb:224:in `block in install'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/settings.rb:136:in `temporary'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/cli.rb:223:in `install'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/exe/bundle:30:in `block in <main>'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.2/exe/bundle:22:in `<main>'
```

## Environment

```
Bundler             1.16.2
  Platforms         ruby, x86_64-darwin-17
Ruby                2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
  Full Path         /nfs/2017/b/brabo-hi/.rvm/rubies/ruby-2.3.1/bin/ruby
  Config Dir        /nfs/2017/b/brabo-hi/.rvm/rubies/ruby-2.3.1/etc
RubyGems            2.6.14
  Gem Home          /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1
  Gem Path          /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1:/nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1@global
  User Path         /nfs/2017/b/brabo-hi/.gem/ruby/2.3.0
  Bin Dir           /nfs/2017/b/brabo-hi/.rvm/gems/ruby-2.3.1/bin
OpenSSL
  Compiled          OpenSSL 1.0.2o  27 Mar 2018
  Loaded            OpenSSL 1.0.2o  27 Mar 2018
  Cert File         /nfs/2017/b/brabo-hi/.brew/etc/openssl/cert.pem
  Cert Dir          /nfs/2017/b/brabo-hi/.brew/etc/openssl/certs
Tools
  Git               2.15.1 (Apple Git-101)
  RVM               1.29.3 (master)
  rbenv             rbenv 1.1.1

  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2018-05-16
Git SHA           9f7bf0ac3
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
<No /private/tmp/bloge/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Operation+not+supported+%40+rb_file_flock+-+%2Fnfs%2F2017%2Fb%2Fbrabo-hi%2F.rvm%2Fgems%2Fruby-2.3.1%2Fbundler.lock&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
         run  bundle exec spring binstub --all
bundler: command not found: spring
Install missing gem executables with `bundle install``

**Comment by colby-swandale** [comment]
Thanks for the error report! It seems that Bundler is trying to perform an operation that is not supported by the NFS mount. This is a bug in Bundler.
