### ISSUE TITLE
Failure?

### ISSUE THREAD

**Issue by SolarAquarion** [bundler/bundler#6567]
bundle install
/usr/lib/ruby/site_ruby/2.5.0/rubygems/ext/builder.rb:164: warning: conflicting chdir during another chdir block
/usr/lib/ruby/site_ruby/2.5.0/rubygems/ext/builder.rb:172: warning: conflicting chdir during another chdir block

## Backtrace

```
NoMethodError: undefined method `remotes' for #<Bundler::Source::Git:0x000055940a9e1f30>
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/gem_installer.rb:47:in `gem_install_message'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/gem_installer.rb:39:in `failure_message'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/gem_installer.rb:34:in `specific_failure_message'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/gem_installer.rb:25:in `rescue in install_from_spec'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/parallel_installer.rb:163:in `do_install'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/parallel_installer.rb:148:in `install_serially'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/parallel_installer.rb:103:in `call'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer/parallel_installer.rb:78:in `call'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer.rb:288:in `install_in_parallel'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer.rb:196:in `install'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer.rb:91:in `block in run'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/process_lock.rb:9:in `open'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/process_lock.rb:9:in `lock'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer.rb:72:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/installer.rb:25:in `install'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/cli/install.rb:65:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/cli.rb:224:in `block in install'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/settings.rb:142:in `temporary'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/cli.rb:223:in `install'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/cli.rb:27:in `dispatch'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/cli.rb:18:in `start'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/exe/bundle:30:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.0.dev/exe/bundle:22:in `<top (required)>'
  /bin/bundle:23:in `load'
  /bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.0.0.dev
  Platforms   ruby, x86_64-linux
Ruby          2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
  Full Path   /usr/bin/ruby
  Config Dir  /etc
RubyGems      3.0.0.beta1
  Gem Home    /home/solaraquarion/topinambour/.bundle/ruby/2.5.0
  Gem Path    
  User Path   /home/solaraquarion/.gem/ruby/2.5.0
  Bin Dir     /home/solaraquarion/topinambour/.bundle/ruby/2.5.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.0g  2 Nov 2017
  Loaded      OpenSSL 1.1.0h  27 Mar 2018
  Cert File   /etc/ssl/cert.pem
  Cert Dir    /etc/ssl/certs
Tools         
  Git         2.17.1
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-06-06
Git SHA           43b4fa975
Released Version  false
```

**Comment by zersiax** [comment]
Still seeing this problem after running gem update bundler as of today. Is the proposed fix already included in that version?
