### ISSUE TITLE
Bundler 1 crashes on gemfiles generated using bundler 2

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6595]
I think it could be reasonable to warn or even fail with an upgrade message, but the crash one currently gets seems like a no-go.

#### To reproduce

```
$ git clone bundler/bundler

$ cd bundler

$ bin/rake install
Could not find 'automatiek' (~> 0.1.0) among 562 total gem(s)
Checked in 'GEM_PATH=/home/deivid/.gem/ruby/2.5.0:/home/deivid/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'mustache' (= 0.99.6) - did find: [mustache-1.0.5]
Checked in 'GEM_PATH=/home/deivid/.gem/ruby/2.5.0:/home/deivid/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0', execute `gem env` for more information (Gem::MissingSpecVersionError)
Could not find 'rdiscount' (~> 2.2) among 562 total gem(s)
Checked in 'GEM_PATH=/home/deivid/.gem/ruby/2.5.0:/home/deivid/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'ronn' (~> 0.7.3) among 562 total gem(s)
Checked in 'GEM_PATH=/home/deivid/.gem/ruby/2.5.0:/home/deivid/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0', execute `gem env` for more information (Gem::MissingSpecError)
Install the ronn gem to build the help pages
bundler 2.0.0.dev built to pkg/bundler-2.0.0.dev.gem.
bundler (2.0.0.dev) installed.
install ran for   0.000000   0.004000   1.628000 (  2.361539)

$ bundle --version
2.0.0.dev

$ mkdir test_app

$ cd test_app

$ echo -e "source 'https://rubygems.org'\n\ngem 'byebug'" > Gemfile

$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Installing byebug 10.0.2 with native extensions
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./.bundle`

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    byebug (10.0.2)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  byebug

BUNDLED WITH
   2.0.0.dev

$ gem list bundler

*** LOCAL GEMS ***

bundler (2.0.0.dev, default: 1.16.2)
guard-bundler (2.1.0)

$ gem uninstall bundler -v 2.0.0.dev
Remove executables:
	bundler

in addition to the gem? [Yn]  Y
Removing bundler
Successfully uninstalled bundler-2.0.0.dev

$ bundle --version
Traceback (most recent call last):
	2: from /home/deivid/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
	1: from /home/deivid/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/deivid/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

**Comment by hdf1986** [comment]
I think im missing something here, but you did just uninstalled bundler, and after that you try to do a `bundle --version`, it's weird that it tries to call the executable.

I tried to reproduce locally (using rbenv also) but it shows this message: 

```bash
☁  test_app [master] ⚡  bundle --version
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.3.3
  2.4.0
  2.4.1

☁  test_app [master] ⚡  rbenv --version
rbenv 1.1.1-30-gc8ba27f
☁  test_app [master] ⚡  ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

Maybe it's something related with your rbenv, rubygems or ruby version

**Comment by deivid-rodriguez** [comment]
To reproduce you need bundler 1 installed for the ruby version you're using. It doesn't seem to be your case, no?

**Comment by deivid-rodriguez** [comment]
In the case of `rubygems 2.7.7` that should be the default, so maybe upgrading rubygems reproduces this for you. Otherwise try `gem install bundler` before running `bundle --version` and after generating the lockfile with `bundler 2`.

**Comment by hdf1986** [comment]
Oh, i didn't saw you also have 1.16.2 installed, i thougth the dev version where the only one, my bad.

I've just installed 1.16.2 and i could reproduce it:
```bash
☁  test_app [master] ⚡  bundle
Traceback (most recent call last):
        2: from /home/wolox/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
        1: from /home/wolox/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/wolox/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

```

**Comment by hdf1986** [comment]
I've check the content of the bin/bundle file, it includes this:

```ruby
#!/home/wolox/.rbenv/versions/2.5.1/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'
version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('bundler', 'bundle', version)
else
gem "bundler", version
load Gem.bin_path("bundler", "bundle", version)
end

```

It seems to be related to the version

I tried to change the version to `version = ">= 0.0.a"`, and the error is now:

```
☁  test_app [master] ⚡  bundle
Traceback (most recent call last):
        2: from /home/wolox/.rbenv/versions/2.5.1/bin/bundle:22:in `<main>'
        1: from /home/wolox/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/wolox/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': Could not find 'bundler' (2.0.0.dev) required by your /home/wolox/workspace/bundler/test_app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the lastest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.0.dev`
```

Which makes a lot more sense. Does this solve your issue?

**Comment by deivid-rodriguez** [comment]
Nice @hdf1986! That's definitely a better error, and definitely a good starting point for a PR. I suspect the bundler team is going to prefer a warning here, but this is definitely an improvement! :+1:

**Comment by deivid-rodriguez** [comment]
If the fix lies in the version constraint I agree, since the binstub is generated by rubygems.
