### ISSUE TITLE
bundler 1.16.3 Bundler::HTTPError: Net::HTTPTooManyRequests 

### ISSUE THREAD

**Issue by mfmcdonagh** [bundler/bundler#6639]
Hello,
I'm running bundler in a ci enviorment, 

I've stared to see the following errors:

```
2018-07-24 23:21:21.857 GMT |  HTTP GET https://index.rubygems.org/info/hirb
2018-07-24 23:21:21.857 GMT |  Bundler::HTTPError: Net::HTTPTooManyRequests: 
2018-07-24 23:21:21.857 GMT |  
2018-07-24 23:21:21.857 GMT |  
2018-07-24 23:21:21.857 GMT |  
429 Too Many Requests

2018-07-24 23:21:21.857 GMT |  
nginx

2018-07-24 23:21:21.857 GMT |  
2018-07-24 23:21:21.857 GMT |  
2018-07-24 23:21:21.857 GMT |  
2018-07-24 23:21:21.857 GMT |  /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/fetcher/downloader.rb:37:in `fetch'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/fetcher/compact_index.rb:117:in `call'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/compact_index_client/updater.rb:53:in `block in update'
2018-07-24 23:21:21.857 GMT |    /usr/local/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/compact_index_client/updater.rb:31:in `update'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/compact_index_client.rb:82:in `update'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/compact_index_client.rb:98:in `update_info'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/compact_index_client.rb:55:in `block in dependencies'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/fetcher/compact_index.rb:88:in `call'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/worker.rb:64:in `call'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/worker.rb:64:in `apply_func'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/worker.rb:59:in `block in process_queue'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/worker.rb:56:in `loop'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/worker.rb:56:in `process_queue'
2018-07-24 23:21:21.857 GMT |    /usr/local/bundle/gems/bundler-1.16.3/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
```

Is there a way to prevent bundler from hitting these rate limits ?

**Comment by segiddins** [comment]
I'll bring this up with the rubygems.org team

**Comment by mfmcdonagh** [comment]
@colby-swandale Is there a fix for this issue ? just wondering why it has been closed ?

**Comment by colby-swandale** [comment]
Sorry. I should have left a message. There is no fix that can be applied to Bundler to resolve this issue. The rate limiting is a setting that is controlled by RubyGems.org and Fastly. The core will talk to them about this but beyond that - there is not much else we can do.

**Comment by mfmcdonagh** [comment]
Thanks for the update @colby-swandale
