### ISSUE TITLE
bundler not finding recently updated gem

### ISSUE THREAD

**Issue by krainboltgreene** [bundler/bundler#6644]
Here's where I pushed it to rubygems:

<img width="1424" alt="screen shot 2018-07-30 at 3 53 09 pm" src="https://user-images.githubusercontent.com/334809/43427947-b02b153a-9410-11e8-9ea2-5a27050b164e.png">

Here's where I try to install.

<img width="1422" alt="screen shot 2018-07-30 at 3 53 43 pm" src="https://user-images.githubusercontent.com/334809/43427968-c40d9118-9410-11e8-9e27-2bd621f24fa7.png">

Notice the 6 minutes between each step.

What can I do to debug this?

**Comment by indirect** [comment]
Try again? Looks like it's there now:

```
$ curl index.rubygems.org/versions | tail
aws-sdk-directconnect 1.3.0 2c93c97bb8cb14c806b58dfabf0d2a87
aws-sdk-iot 1.10.0 183f07c100b02f1bb70a25b7efd89e77
knife-lpar 0.0.3 972fb1a571ecf0d5828261ca2ef295cc
solidus-returnly 0.11.0 9c8403f1cd90d47e8b882694f17ede37
jekyll-timeago 0.11.0 29b0d093169e93fa6054ed88f2134fe4
chef-apply 0.1.17 22ae0842edfaccba6bf61a1fc4563295
smart_params 2.1.0 03c40f7af094e86441f4c60f2914d493
jsonapi-realizer 4.3.0 97bd27ce2533af1766f24e300458c602
csv-safe 1.2.0 874cc33462a1f243698fd6cec5bb3099
smart_params 2.2.0 3092a59822a5ac31215fe3d5207f6d05
```

**Comment by krainboltgreene** [comment]
Still happening:

```
𝑓 7 DEBUG=1 VERBOSE=1 bundle update
Running `bundle update` with bundler 1.16.2
Found changes from the lockfile, re-resolving dependencies because bundler is unlocking HTTP GET https://index.rubygems.org/versions
HTTP 206 Partial Content https://index.rubygems.org/versions
Fetching gem metadata from https://rubygems.org/
Looking up gems ["rails", "oj", "pg", "puma", "hiredis", "redis", "redis-rails", "connection_pool", "rack-cors", "rack-attack", "redis-rack-cache", "rack-authentication_bearer", "secure_headers", "draper", "sidekiq", "devise", "devise-async", "groupdate", "active_record-pool", "state_machines-activerecord", "activerecord-like", "ar_after_transaction", "friendly_id", "strong_migrations", "ar_transaction_changes", "goldiloader", "rein", "gutentag", "country_select", "kaminari", "money-rails", "activerecord-safer_migrations", "migration_data", "puma_worker_killer", "pundit", "redis-objects", "pry-rails", "pry-doc", "jsonapi-serializers", "jsonapi-realizer", "jsonapi-home", "smart_params", "bugsnag", "paper_trail", "action_operation", "redlock", "flag_shih_tzu", "rack-timeout", "newrelic_rpm", "dotenv-rails", "rspec-rails", "listen", "factory_bot_rails", "faker", "timecop", "active_record_query_trace", "brakeman", "bundler-audit", "flamegraph", "memory_profiler", "rack-mini-profiler", "rails-callback_log", "rubocop", "ruby-prof", "stackprof"]
HTTP GET https://index.rubygems.org/info/draper
HTTP 206 Partial Content https://index.rubygems.org/info/draper
Looking up gems ["rack", "rspec", "actionmailer", "actionpack", "activerecord", "activeresource", "activesupport", "rake", "actionwebservice", "bundler", "railties", "sprockets-rails", "actionview", "activemodel", "activejob", "actioncable", "activestorage", "kaminari-actionview", "kaminari-activerecord", "kaminari-core", "rake-compiler", "redis-actionpack", "redis-activesupport", "redis-store", "appraisal", "rack-cache", "warden", "bcrypt-ruby", "orm_adapter", "thread_safe", "bcrypt", "responders", "state_machines-activemodel", "arel", "hoe", "newgem", "sqlite3-ruby", "unicode", "babosa", "celluloid", "multi_json", "redis-namespace", "compass", "sass", "sprockets-sass", "i18n", "sinatra", "slim", "json", "concurrent-ruby", "rack-protection", "money", "monetize", "brwsr", "user_agent_parser", "useragent", "pry", "yard", "array-where", "bacon", "jeweler", "request_store", "paper_trail-association_tracking", "httparty", "countries", "sort_alphabetical", "dry-monads", "dry-types", "recursive-open-struct", "get_process_mem", "echoe", "rb-fchange", "rb-fsevent", "rb-inotify", "rb-kqueue", "celluloid-io", "ruby_dep", "thor", "cucumber", "webrat", "rspec-core", "rspec-expectations", "rspec-mocks", "rspec-collection_matchers", "rspec-support", "term-ansicolor", "rainbow", "parser", "backports", "powerpack", "ruby-progressbar", "astrolabe", "tins", "unicode-display_width", "parallel", "jaro_winkler", "dotenv", "factory_bot", "erubis", "haml", "ruby2ruby", "ruport", "ruby_parser", "fastercsv", "highline", "terminal-table", "json_pure", "safe_yaml", "fast_stack", "activemodel-serializers-xml"]
HTTP GET https://index.rubygems.org/info/countries
HTTP 206 Partial Content https://index.rubygems.org/info/countries
Looking up gems ["rack-mount", "rack-test", "builder", "tzinfo", "sprockets", "journey", "rails-deprecated_sanitizer", "rails-dom-testing", "rails-html-sanitizer", "memcache-client", "minitest", "method_source", "camping", "fcgi", "mongrel", "ruby-openid", "test-spec", "thin", "activerecord-deprecated_finders", "erubi", "diff-lcs", "spicycode-rcov", "syntax", "coffee-rails", "em-hiredis", "faye-websocket", "websocket-driver", "nio4r", "rack-ssl", "rdoc", "marcel", "redis-rack", "mail", "text-format", "rails-observers", "aruba", "atomic", "activemodel-globalid", "globalid", "chunky_png", "fssm", "compass-core", "compass-import-once", "state_machines", "rubyforge", "RubyInline", "gemcutter", "RedCloth", "rubigen", "timers", "facter", "celluloid-essentials", "celluloid-extras", "celluloid-fsm", "celluloid-pool", "celluloid-supervision", "nenv", "rspec-logsplit", "sprockets-helpers", "tilt", "escape_utils", "temple", "functional-ruby", "ref", "shotgun", "mustermann", "sqlite3", "sass-listen", "sixarm_ruby_unaccent", "coderay", "win32console", "slop", "spoon", "peterwald-git", "schacon-git", "git", "mhennemeyer-output_catcher", "mocha", "redgreen", "rr", "thoughtbot-shoulda", "github_api", "nokogiri", "semver", "psych", "semver2", "unicode_utils", "jnunemaker-crack", "crack", "multi_xml", "dry-equalizer", "dry-core", "ffi", "hpricot", "rcov", "allison", "sexp_processor", "ast", "dry-configurable", "dry-container", "dry-logic", "inflecto", "kleisli", "ice_nine", "dry-inflector", "abstract", "polyglot", "treetop", "gherkin", "multi_test", "cucumber-core", "gherkin3", "cucumber-wire", "event-bus", "cucumber-expressions", "win32-api", "maruku", "termios", "dotenv-deployment", "ParseTree", "pdf-writer", "transaction-simple", "mailfactory", "scruffy", "gem_plugin", "parseinput", "prawn", "spruz", "algorithms", "currencies", "i18n_data"]
Looking up gems ["multimap", "hike", "ruby-yadis", "daemons", "eventmachine", "eventmachine-le", "http_parser.rb", "preforker", "coffee-script", "mime-types", "tlsmail", "mini_mime", "ZenTest", "net-scp", "cgi_multipart_eof_fix", "fastthread", "flexmock", "hitimes", "loofah", "markaby", "metaid", "mab", "coveralls", "mimemagic", "websocket-extensions", "CFPropertyList", "sys-admin", "win32-dir", "windows-api", "windows-pr", "win32-security", "text-hyphen", "celluloid-gems", "background_process", "childprocess", "bcat", "rdiscount", "contracts", "launchy", "faraday", "hashie", "oauth2", "addressable", "descendants_tracker", "metaclass", "tool", "racc", "rexical", "tenderlove-frex", "weakling", "mini_portile", "mini_portile2", "pkg-config", "facets", "trollop", "bones", "jar-dependencies", "cucumber-tag_expressions", "test-unit", "SexpProcessor", "color", "color-tools", "prawn-layout", "prawn-core", "prawn-format", "prawn-security", "pdf-reader", "ttfunk", "afm", "ruby-rc4", "pdf-core"]
Looking up gems ["archive-tar-minitar", "mime-types-data", "net-ssh", "configuration", "mkrf", "crass", "colorize", "rest-client", "simplecov", "coffee-script-source", "execjs", "libxml-ruby", "ffi-win32-extensions", "multipart-post", "public_suffix", "curses", "faraday-middleware", "httpauth", "jwt", "ruby-maven", "little-plugger", "loquacious", "bones-extras", "bones-git", "Ascii85", "hashery", "power_assert"]
Looking up gems ["minitar", "minitar-cli", "needle", "jruby-pageant", "bcrypt_pbkdf", "rbnacl", "rbnacl-libsodium", "simplecov-html", "docile", "lockfile", "maven-tools", "ruby-maven-libs", "netrc", "http-cookie", "http-accept", "bones-rcov", "bones-rspec", "bones-rubyforge", "bones-zentest", "pattern-match", "blankslate"]
Looking up gems ["virtus", "powerbar", "domain_name"]
Looking up gems ["unf", "axiom-types", "coercible", "equalizer", "ansi"]
Looking up gems ["unf_ext", "adamantium"]
Looking up gems ["memoizable"]
Double checking for ["bundler"] in rubygems repository https://rubygems.org/ or installed locally
Fetching gem metadata from https://rubygems.org/
Looking up gems ["bundler"]
Could not find gem 'smart_params (= 2.2.0)' in any of the gem sources listed in your Gemfile.
Bundler::GemNotFound: Could not find gem 'smart_params (= 2.2.0)' in any of the gem sources listed in your Gemfile.
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:289:in `block in verify_gemfile_dependencies_are_found!'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:257:in `each'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:257:in `verify_gemfile_dependencies_are_found!'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:48:in `start'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/resolver.rb:22:in `resolve'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:258:in `resolve'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:171:in `specs'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/definition.rb:159:in `resolve_remotely!'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/installer.rb:287:in `resolve_if_needed'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/installer.rb:83:in `block in run'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/process_lock.rb:9:in `open'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/process_lock.rb:9:in `lock'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/installer.rb:72:in `run'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/installer.rb:25:in `install'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/cli/update.rb:61:in `run'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/cli.rb:266:in `update'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/bin/bundle:23:in `load'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/bin/bundle:23:in `<main>'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
  /Users/krainboltgreene/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by indirect** [comment]
(IIRC we have told Fastly to cache the versions list for up to 10 minutes? maybe we should reduce that to 5 minutes or something.)

**Comment by krainboltgreene** [comment]
Tailing myself:

```
𝑓 7 curl index.rubygems.org/versions | tail
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M  100 18.6M    0     0  12.5M      0  0:00:01  0:00:01 --:--:-- 12.5M
aws-sdk-cloudhsmv2 1.3.0 d73c756914d24dae94648a00e14abfc6
aws-sdk-directconnect 1.3.0 2c93c97bb8cb14c806b58dfabf0d2a87
aws-sdk-iot 1.10.0 183f07c100b02f1bb70a25b7efd89e77
knife-lpar 0.0.3 972fb1a571ecf0d5828261ca2ef295cc
solidus-returnly 0.11.0 9c8403f1cd90d47e8b882694f17ede37
jekyll-timeago 0.11.0 29b0d093169e93fa6054ed88f2134fe4
chef-apply 0.1.17 22ae0842edfaccba6bf61a1fc4563295
smart_params 2.1.0 03c40f7af094e86441f4c60f2914d493
jsonapi-realizer 4.3.0 97bd27ce2533af1766f24e300458c602
csv-safe 1.2.0 874cc33462a1f243698fd6cec5bb3099
```

**Comment by indirect** [comment]
It's working for me :/

```
$ bundle add smart_params
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Fetching dry-inflector 0.1.2
Fetching dry-equalizer 0.2.1
Fetching recursive-open-struct 1.1.0
Installing minitest 5.11.3
Installing thread_safe 0.3.6
Installing concurrent-ruby 1.0.5
Installing dry-equalizer 0.2.1
Installing dry-inflector 0.1.2
Installing recursive-open-struct 1.1.0
Installing tzinfo 1.2.5
Fetching dry-core 0.4.7
Installing dry-configurable 0.7.0
Installing i18n 1.0.1
Installing dry-core 0.4.7
Installing dry-container 0.6.0
Fetching dry-logic 0.4.2
Installing dry-logic 0.4.2
Installing activesupport 5.2.0
Fetching dry-types 0.13.2
Installing dry-types 0.13.2
Fetching smart_params 2.2.0
Installing smart_params 2.2.0
```

**Comment by krainboltgreene** [comment]
Okay, so this must be some sort of edge network issue. I don't mind waiting longer.

**Comment by indirect** [comment]
Hmm, I guess it is actually a Fastly cache thing somehow, sorry about that. 😬 Might even be worth visiting http://www.fastly-debug.com and then opening a support ticket using the widget in the bottom right corner.

**Comment by krainboltgreene** [comment]
```
𝑓 curl index.rubygems.org/versions | tail
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M  100 18.6M    0     0  12.2M      0  0:00:01  0:00:01 --:--:-- 12.2M
aws-sdk-directconnect 1.3.0 2c93c97bb8cb14c806b58dfabf0d2a87
aws-sdk-iot 1.10.0 183f07c100b02f1bb70a25b7efd89e77
knife-lpar 0.0.3 972fb1a571ecf0d5828261ca2ef295cc
solidus-returnly 0.11.0 9c8403f1cd90d47e8b882694f17ede37
jekyll-timeago 0.11.0 29b0d093169e93fa6054ed88f2134fe4
chef-apply 0.1.17 22ae0842edfaccba6bf61a1fc4563295
smart_params 2.1.0 03c40f7af094e86441f4c60f2914d493
jsonapi-realizer 4.3.0 97bd27ce2533af1766f24e300458c602
csv-safe 1.2.0 874cc33462a1f243698fd6cec5bb3099
smart_params 2.2.0 3092a59822a5ac31215fe3d5207f6d05

𝑓 bundle update
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'smart_params (= 2.2.0)' in any of the gem sources listed in your Gemfile.
```

Now I'm confused.

**Comment by krainboltgreene** [comment]
```
𝑓 7 curl index.rubygems.org/versions | tail
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M  100 18.6M    0     0  12.2M      0  0:00:01  0:00:01 --:--:-- 12.2M
aws-sdk-cloudhsmv2 1.3.0 d73c756914d24dae94648a00e14abfc6
aws-sdk-directconnect 1.3.0 2c93c97bb8cb14c806b58dfabf0d2a87
aws-sdk-iot 1.10.0 183f07c100b02f1bb70a25b7efd89e77
knife-lpar 0.0.3 972fb1a571ecf0d5828261ca2ef295cc
solidus-returnly 0.11.0 9c8403f1cd90d47e8b882694f17ede37
jekyll-timeago 0.11.0 29b0d093169e93fa6054ed88f2134fe4
chef-apply 0.1.17 22ae0842edfaccba6bf61a1fc4563295
smart_params 2.1.0 03c40f7af094e86441f4c60f2914d493
jsonapi-realizer 4.3.0 97bd27ce2533af1766f24e300458c602
csv-safe 1.2.0 874cc33462a1f243698fd6cec5bb3099
```

lol, okay, yeah, time to talk to fastly. Thanks @indirect for your help <3.

**Comment by indirect** [comment]
Meeeee too. When I ran `bundle add smart_params`, I got 2.2.0. 😕
