### ISSUE TITLE
Bundle Install in MacOS 10.14 Mojave causing "unexpected error"

### ISSUE THREAD

**Issue by syedrakib** [bundler/bundler#6753]
Recently upgraded my MacOS to Mojave. Tried to run `bundle install` as usual. Faced `unexpected error`.

    bundle install
    Fetching gem metadata from https://rubygems.org/.
    Retrying fetcher due to error (2/4): IOError uninitialized stream.
    Retrying fetcher due to error (3/4): IOError stream closed.
    Retrying fetcher due to error (4/4): IOError stream closed.

--- ERROR REPORT TEMPLATE -------------------------------------------------------

## Backtrace

```
IOError: uninitialized stream
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/compact_index_client/updater.rb:111:in `read'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/compact_index_client/updater.rb:111:in `block in checksum_for_file'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:118:in `filesystem_access'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/compact_index_client/updater.rb:110:in `checksum_for_file'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/compact_index_client.rb:88:in `update_info'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/compact_index_client.rb:55:in `block in dependencies'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/worker.rb:64:in `apply_func'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/worker.rb:59:in `block in process_queue'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/worker.rb:56:in `loop'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/worker.rb:56:in `process_queue'
  /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.16.3/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       1.16.3
  Platforms   ruby, x86_64-darwin-17
Ruby          2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
  Full Path   /Users/rakib/.rvm/rubies/ruby-2.3.1/bin/ruby
  Config Dir  /Users/rakib/.rvm/rubies/ruby-2.3.1/etc
RubyGems      2.7.7
  Gem Home    /Users/rakib/.rvm/gems/ruby-2.3.1@my-app
  Gem Path    /Users/rakib/.rvm/gems/ruby-2.3.1@my-app:/Users/rakib/.rvm/gems/ruby-2.3.1@global
  User Path   /Users/rakib/.gem/ruby/2.3.0
  Bin Dir     /Users/rakib/.rvm/gems/ruby-2.3.1@my-app/bin
OpenSSL
  Compiled    OpenSSL 1.0.2o  27 Mar 2018
  Loaded      OpenSSL 1.0.2o  27 Mar 2018
  Cert File   /usr/local/etc/openssl/cert.pem
  Cert Dir    /usr/local/etc/openssl/certs
Tools
  Git         2.6.2
  RVM         1.29.4 (latest)
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-07-17
Git SHA           12e73cab7
Released Version  true
```

--- TEMPLATE END ----------------------------------------------------------------

```
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
```

**Comment by jfrank3220** [comment]
I got the same error when using 


## Backtrace

```
IOError: closed stream
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:102:in `read'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:102:in `block in checksum_for_file'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:118:in `filesystem_access'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/compact_index_client/updater.rb:101:in `checksum_for_file'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/compact_index_client.rb:88:in `update_info'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/compact_index_client.rb:55:in `block in dependencies'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/worker.rb:64:in `apply_func'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/worker.rb:59:in `block in process_queue'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/worker.rb:56:in `loop'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/worker.rb:56:in `process_queue'
  /Users/jordanfrank/.rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler             1.16.1
  Platforms         ruby, x86_64-darwin-17
Ruby                2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin17]
  Full Path         /Users/jordanfrank/.rvm/rubies/ruby-2.3.0/bin/ruby
  Config Dir        /Users/jordanfrank/.rvm/rubies/ruby-2.3.0/etc
RubyGems            2.6.14
  Gem Home          /Users/jordanfrank/.rvm/gems/ruby-2.3.0
  Gem Path          /Users/jordanfrank/.rvm/gems/ruby-2.3.0:/Users/jordanfrank/.rvm/gems/ruby-2.3.0@global
  User Path         /Users/jordanfrank/.gem/ruby/2.3.0
  Bin Dir           /Users/jordanfrank/.rvm/gems/ruby-2.3.0/bin
OpenSSL
  Compiled          OpenSSL 1.0.2n  7 Dec 2017
  Loaded            OpenSSL 1.0.2p  14 Aug 2018
  Cert File         /usr/local/etc/openssl/cert.pem
  Cert Dir          /usr/local/etc/openssl/certs
Tools
  Git               2.19.1
  RVM               1.29.4 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

Bundler works fine with Ruby >2.5.0 on mojave though, as I've been using it for other projects without issue.

**Comment by coenwulf** [comment]
Also same error with version 1.17.1:
## Backtrace

```
IOError: uninitialized stream
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/shared_helpers.rb:118:in `read'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/shared_helpers.rb:118:in `read'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/shared_helpers.rb:118:in `filesystem_access'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/compact_index_client/cache.rb:90:in `lines'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/compact_index_client/cache.rb:62:in `dependencies'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/compact_index_client.rb:56:in `block in dependencies'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/worker.rb:64:in `apply_func'

  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/worker.rb:59:in `block in process_queue'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/worker.rb:56:in `loop'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/worker.rb:56:in `process_queue'
  /Users/jeremy/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.17.1/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler             1.17.1
  Platforms         ruby, x86_64-darwin-17
Ruby                2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
  Full Path         /Users/jeremy/.rvm/rubies/ruby-2.3.1/bin/ruby
  Config Dir        /Users/jeremy/.rvm/rubies/ruby-2.3.1/etc
RubyGems            2.7.5
  Gem Home          /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal
  Gem Path          /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal:/Users/jeremy/.rvm/gems/ruby-2.3.1@global
  User Path         /Users/jeremy/.gem/ruby/2.3.0
  Bin Dir           /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/bin
OpenSSL
  Compiled          OpenSSL 1.0.2n  7 Dec 2017
  Loaded            OpenSSL 1.0.2p  14 Aug 2018
  Cert File         /usr/local/etc/openssl/cert.pem
  Cert Dir          /usr/local/etc/openssl/certs
Tools
  Git               2.19.1
  RVM               1.29.4 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2018-10-25
Git SHA           2760d72d3
Released Version  true
```

**Comment by Saibotx** [comment]
Hi - i was having this issue too with OSX Mojave as well

try repairing your environment 

# General environment repairs
`sudo rvm repair all`

This solved the issue for me

**Comment by jvigne** [comment]
I did have the same problem but using rbenv. The solution may apply to both rvm and rbenv. I just upgraded bundler (for me it was from 1.16.1 to 1.17.1). 

PS :  If this fix does not work, you can also try to upgrade rbenv, uninstall the broken ruby version and then reinstall the ruby version and bundler.

**Comment by s-hocking** [comment]
I had this same issue, but with rbenv. I did an `rbenv uninstall 2.3.3` and `rbenv install 2.3.3`, and also reinstalled Bundler for good measure. That fixed it!

**Comment by murilomendes** [comment]
> Hi - i was having this issue too with OSX Mojave as well
> 
> try repairing your environment
> 
> #### General environment repairs
> `sudo rvm repair all`
> 
> This solved the issue for me

Here works ! Thank you! :)

**Comment by colby-swandale** [comment]
i'm going to close this ticket, It seems like this issue can be resolved outside of Bundler.
