### ISSUE TITLE
[Windows test failure] rspec ./spec/bundler/cli_spec.rb:16 # bundle executable looks for a binary and executes it if it's named bundler-<task>

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6876]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next failing test is this one:

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec spec/bundler/cli_spec.rb:16
Run options:
  include {:locations=>{"./spec/bundler/cli_spec.rb"=>[16]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

bundle executable
$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle testtasks
Could not find command "testtasks".
# $? => 15
  looks for a binary and executes it if it's named bundler-<task> (FAILED - 1)


Retried examples: 0

Failures:

  1) bundle executable looks for a binary and executes it if it's named bundler-<task>
     Failure/Error: expect(exitstatus).to be_zero if exitstatus

       expected `15.zero?` to return true, got false

       Commands:
       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle testtasks
       Could not find command "testtasks".
       # $? => 15
     # ./spec/bundler/cli_spec.rb:27:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 7.62 seconds (files took 2.17 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/bundler/cli_spec.rb:16 # bundle executable looks for a binary and executes it if it's named bundler-<task>
```

Test definition is here:
https://github.com/janpio/bundler/blob/b97a280c33607a0db12ee33dbb9104f735a3a527/spec/bundler/cli_spec.rb#L16-L28

Here the problem is `with_path_added`:
https://github.com/janpio/bundler/blob/b97a280c33607a0db12ee33dbb9104f735a3a527/spec/support/helpers.rb#L357-L361

On Windows, paths are not seperated by `:` but `;`:
```
C:\Projects\bundler (windows -> origin)
λ set PATH
Path=C:\Users\Jan\Desktop\cmder_mini\bin;C:\Users\Jan\Desktop\cmder_mini\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\Jan\Desktop\cmder_mini\bin;C:\Users\Jan\Desktop\cmder_mini\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\Jan\Desktop\cmder_mini\vendor\conemu-maximus5;C:\Users\Jan\Desktop\cmder_mini\vendor\conemu-maximus5\ConEmu;C:\Program Files\ImageMagick-7.0.8-Q16;C:\Program Files (x86)\Business Objects\Common\3.5\bin\NOTES\;C:\Program Files (x86)\Business Objects\Common\3.5\bin\NOTES\DATA\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Bluetooth Software\;C:\Program Files\Lenovo\Bluetooth Software\syswow64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\PuTTY\;C:\nvm;C:\Program Files\nodejs;C:\Program Files\Git LFS;C:\ProgramData\chocolatey\bin;C:\Gradle\gradle-3.3\bin;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH\;C:\HashiCorp\Vagrant\bin;C:\xampp\php;C:\Program Files (x86)\GTK2-Runtime\bin;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Users\Jan\.windows-build-tools\python27\;C:\nvm\v10.12.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files\nodejs\node_modules\windows-build-tools\node_modules\.bin;C:\Program Files\nodejs\node_modules\.bin;C:\Program Files\ImageMagick-7.0.8-Q16;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Lenovo\Bluetooth Software\;C:\Program Files\Lenovo\Bluetooth Software\syswow64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\PuTTY\;C:\nvm;C:\Program Files\nodejs;C:\Program Files\Git LFS;C:\ProgramData\chocolatey\bin;C:\Gradle\gradle-3.3\bin;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH\;C:\HashiCorp\Vagrant\bin;C:\xampp\php;C:\Program Files (x86)\GTK2-Runtime\bin;C:\ProgramData\ComposerSetup\bin;C:\Users\Jan\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Users\Jan\scoop\shims;C:\Users\Jan\AppData\Local\Programs\Python\Launcher\;C:\Ruby24-x64\bin;C:\Android;C:\Users\Jan\AppData\Local\Microsoft\WindowsApps;C:\Android\tools;C:\Android\platform-tools;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Users\Jan\AppData\Local\Microsoft\WindowsApps;C:\Users\Jan\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Jan\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Git\mingw64\libexec\git-core;C:\Users\Jan\PATH;;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\Users\Jan\Desktop\cmder_mini\;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\Users\Jan\Desktop\cmder_mini\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
```

So we could either add some if-else-conditionals checking for the operating system, or find a cross platform way to modify the PATH env variable (maybe ruby has this by itself? maybe a third party gem?). Thoughts?

**Comment by janpio** [comment]
Ha, TIL: https://ruby-doc.org/core-2.2.3/File.html#PATH_SEPARATOR
