### ISSUE TITLE
[Windows test failure] rspec ./spec/bundler/definition_spec.rb:75 # Bundler::Definition detects changes for a path gem with changes

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6886]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next failing test is this one:

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec ./spec/bundler/definition_spec.rb:75
Run options:
  include {:locations=>{"./spec/bundler/definition_spec.rb"=>[75]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

Bundler::Definition
  detects changes
$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install --retry 0
Fetching source index from file://localhostC/Projects/bundler/tmp/gems/remote1/
Resolving dependencies...
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./.bundle`
# $? => 0
    for a path gem with changes (FAILED - 1)


Retried examples: 0

Failures:

  1) Bundler::Definition detects changes for a path gem with changes
     Failure/Error:
             Open3.popen3(cmd.to_s) do |stdin, stdout, stderr, wait_thr|
               yield stdin, stdout, wait_thr if block_given?
               stdin.close

               command_execution.stdout = Thread.new { stdout.read }.value.strip
               command_execution.stderr = Thread.new { stderr.read }.value.strip
               command_execution.exitstatus = wait_thr && wait_thr.value.exitstatus
             end

     Errno::ENOENT:
       No such file or directory - DEBUG='1'  C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib;C:/Projects/bundler/spec -rsupport/hax -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install

       Commands:
       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install --retry 0
       Fetching source index from file://localhostC/Projects/bundler/tmp/gems/remote1/
       Resolving dependencies...
       Bundle complete! 1 Gemfile dependency, 2 gems now installed.
       Bundled gems are installed into `./.bundle`
       # $? => 0
     # ./spec/support/helpers.rb:227:in `sys_exec'
     # ./spec/support/helpers.rb:150:in `bundle'
     # ./spec/bundler/definition_spec.rb:87:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 7.97 seconds (files took 1.02 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/bundler/definition_spec.rb:75 # Bundler::Definition detects changes for a path gem with changes
```

Problem here seems to be how env vars are set before the command:
```
Errno::ENOENT:
       No such file or directory - DEBUG='1'  C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib;C:/Projects/bundler/spec -rsupport/hax -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install
```
Unfortunately it doesn't work this way on Windows :/ I suspect this will affect a whole lot of tests, so fixing this should get the number of failing tests down by quite a bit I hope.

**Comment by deivid-rodriguez** [comment]
popen3 receives an optional first hash argument with the environment. Instead of passing it in front of the command, maybe we can use that?

**Comment by janpio** [comment]
Yeah, there are multiple ways to work around that. I like this one from fastlane: https://github.com/fastlane/fastlane/blob/c6513d100e21a6751f647874aea217541305387f/fastlane_core/spec/spec_helper.rb#L36-L43 

Unfortunately then we hit the next problem on Windows ;)

**Comment by janpio** [comment]
Ok, you suggestion is actually much nicer as it "just works" here without adding additional code: https://github.com/janpio/bundler/pull/2/commits/3783a564bbbb111de9dcb773d27d2b29a75cffa0 ✋ 👍

**Comment by janpio** [comment]
That was pretty effective as well.

Before: `2509 examples, 671 failures, 1 pending`
After: `2509 examples, 620 failures, 1 pending`

💯

**Comment by janpio** [comment]
Still, that test is not passing yet but now failing with this:

```
C:\Projects\bundler (windows_6886_DEBUG=1 -> origin)                                                                                                                         
λ ruby bin/rspec ./spec/bundler/definition_spec.rb:75                                                                                                                        
Run options:                                                                                                                                                                 
  include {:locations=>{"./spec/bundler/definition_spec.rb"=>[75]}}                                                                                                          
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}     
                                                                                                                                                                             
Bundler::Definition                                                                                                                                                          
  detects changes                                                                                                                                                            
$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \                                                                             
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install --retry 0                                                                          
Fetching source index from file://localhostC/Projects/bundler/tmp/gems/remote1/                                                                                              
Resolving dependencies...                                                                                                                                                    
Bundle complete! 1 Gemfile dependency, 2 gems now installed.                                                                                                                 
Bundled gems are installed into `./.bundle`                                                                                                                                  
# $? => 0                                                                                                                                                                    
                                                                                                                                                                             
$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \                                                                             
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install                                                                                    
Running `bundle install` with bundler 2.0.0.dev                                                                                                                              
Found changes from the lockfile, re-resolving dependencies because the gemspecs for path gems changed, the lockfile does not have all gems needed for the current platform   
Fetching source index from file://localhostC/Projects/bundler/tmp/gems/remote1/                                                                                              
Resolving dependencies...                                                                                                                                                    
Using bundler 2.0.0.dev                                                                                                                                                      
0:  bundler (2.0.0.dev) from C:/Projects/bundler/lib/bundler/source                                                                                                          
Fetching rack 1.0.0                                                                                                                                                          
Installing rack 1.0.0                                                                                                                                                        
Rack's post install message                                                                                                                                                  
1:  rack (1.0.0) from C:/Projects/bundler/tmp/bundled_app/.bundle/ruby/2.4.0/specifications/rack-1.0.0.gemspec                                                               
Using foo 1.0 from source at `C:/Projects/bundler/tmp/libs/foo`                                                                                                              
2:  foo (1.0) from C:/Projects/bundler/tmp/libs/foo/foo.gemspec                                                                                                              
Bundle complete! 1 Gemfile dependency, 3 gems now installed.                                                                                                                 
Bundled gems are installed into `./.bundle`                                                                                                                                  
Post-install message from rack:                                                                                                                                              
Rack's post install message                                                                                                                                                  
# $? => 0                                                                                                                                                                    
    for a path gem with changes (FAILED - 1)                                                                                                                                 
                                                                                                                                                                             
                                                                                                                                                                             
Retried examples: 0                                                                                                                                                          
                                                                                                                                                                             
Failures:                                                                                                                                                                    
                                                                                                                                                                             
  1) Bundler::Definition detects changes for a path gem with changes                                                                                                         
     Failure/Error: expect(bundled_app("Gemfile.lock")).to read_as(normalize_uri_file(strip_whitespace(expected)))                                                           
                                                                                                                                                                             
       expected "GEM\n  remote: file://localhostC/Projects/bundler/tmp/gems/remote1/\n  specs:\n    rack (1.0.0)\n\nP...   rack (= 1.0)\n\nPLATFORMS\n  x64-mingw32\n\nDEPEND
ENCIES\n  foo!\n\nBUNDLED WITH\n   2.0.0.dev\n" to read as "GEM\n  remote: file://localhostC:/Projects/bundler/tmp/gems/remote1/\n  specs:\n    rack (1.0.0)\n\n...\n\nPLATFO
RMS\n  x64-mingw32\n  x64-mingw32\n\nDEPENDENCIES\n  foo!\n\nBUNDLED WITH\n   2.0.0.dev\n"                                                                                   
       Diff:                                                                                                                                                                 
       @@ -1,5 +1,5 @@                                                                                                                                                       
        GEM                                                                                                                                                                  
       -  remote: file://localhostC:/Projects/bundler/tmp/gems/remote1/                                                                                                      
       +  remote: file://localhostC/Projects/bundler/tmp/gems/remote1/                                                                                                       
          specs:                                                                                                                                                             
            rack (1.0.0)                                                                                                                                                     
                                                                                                                                                                             
       @@ -10,7 +10,6 @@                                                                                                                                                     
              rack (= 1.0)                                                                                                                                                   
                                                                                                                                                                             
        PLATFORMS                                                                                                                                                            
       -  x64-mingw32                                                                                                                                                        
          x64-mingw32                                                                                                                                                        
                                                                                                                                                                             
        DEPENDENCIES                                                                                                                                                         
                                                                                                                                                                             
                                                                                                                                                                             
       Commands:                                                                                                                                                             
       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \                                                                      
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install --retry 0                                                                   
       Fetching source index from file://localhostC/Projects/bundler/tmp/gems/remote1/                                                                                       
       Resolving dependencies...                                                                                                                                             
       Bundle complete! 1 Gemfile dependency, 2 gems now installed.                                                                                                          
       Bundled gems are installed into `./.bundle`                                                                                                                           
       # $? => 0                                                                                                                                                             
                                                                                                                                                                             
       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \                                                                      
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install                                                                             
       Running `bundle install` with bundler 2.0.0.dev                                                                                                                       
       Found changes from the lockfile, re-resolving dependencies because the gemspecs for path gems changed, the lockfile does not have all gems needed for the current plat
form                                                                                                                                                                         
       Fetching source index from file://localhostC/Projects/bundler/tmp/gems/remote1/                                                                                       
       Resolving dependencies...                                                                                                                                             
       Using bundler 2.0.0.dev                                                                                                                                               
       0:  bundler (2.0.0.dev) from C:/Projects/bundler/lib/bundler/source                                                                                                   
       Fetching rack 1.0.0                                                                                                                                                   
       Installing rack 1.0.0                                                                                                                                                 
       Rack's post install message                                                                                                                                           
       1:  rack (1.0.0) from C:/Projects/bundler/tmp/bundled_app/.bundle/ruby/2.4.0/specifications/rack-1.0.0.gemspec                                                        
       Using foo 1.0 from source at `C:/Projects/bundler/tmp/libs/foo`                                                                                                       
       2:  foo (1.0) from C:/Projects/bundler/tmp/libs/foo/foo.gemspec                                                                                                       
       Bundle complete! 1 Gemfile dependency, 3 gems now installed.                                                                                                          
       Bundled gems are installed into `./.bundle`                                                                                                                           
       Post-install message from rack:                                                                                                                                       
       Rack's post install message                                                                                                                                           
       # $? => 0                                                                                                                                                             
     # ./spec/support/matchers.rb:239:in `lockfile_should_be'                                                                                                                
     # ./spec/bundler/definition_spec.rb:90:in `block (3 levels) in <top (required)>'                                                                                        
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'                                                                                                   
                                                                                                                                                                             
Finished in 10.4 seconds (files took 0.94985 seconds to load)                                                                                                                
1 example, 1 failure                                                                                                                                                         
                                                                                                                                                                             
Failed examples:                                                                                                                                                             
                                                                                                                                                                             
rspec ./spec/bundler/definition_spec.rb:75 # Bundler::Definition detects changes for a path gem with changes                                                                 
```

Problems seems to be the remote URL being generated there:

```
       -  remote: file://localhostC:/Projects/bundler/tmp/gems/remote1/
       +  remote: file://localhostC/Projects/bundler/tmp/gems/remote1/
```

`file://localhost` looks strange to me anyway, but if I understood correctly this is normal and/or stripped away to `file://C/Projects/bundler/tmp/gems/remote1/`. The `:` is missing though: `file:///C:/Projects/bundler/tmp/gems/remote1/` - at least that one works in my browser while the other doesn't.

So now to find where this remote URL is built...

**Comment by janpio** [comment]
Currently working on the PR for this.
