### ISSUE TITLE
[Windows test failure] rspec ./spec/bundler/plugin/installer_spec.rb:64 # Bundler::Plugin::Installer cli install with actual installers git plugins returns the installed spec after installing

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6888]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next one:

```

C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec ./spec/bundler/plugin/installer_spec.rb:64
Run options:
  include {:locations=>{"./spec/bundler/plugin/installer_spec.rb"=>[64]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

Bundler::Plugin::Installer
  cli install
    with actual installers
      git plugins
error: pathspec 'INITIAL' did not match any file(s) known to git
error: pathspec 'COMMIT'' did not match any file(s) known to git
warning: You appear to have cloned an empty repository.
fatal: Needed a single revision
$ C:/Ruby24-x64/bin/ruby.exe -rrubygems -S gem --backtrace generate_index
Generating Marshal quick index gemspecs for 65 gems
.................................................................
Complete
Generated Marshal quick index gemspecs: 0.256s
Generating specs index
Generated specs index: 0.010s
Generating latest specs index
Generated latest specs index: 0.000s
Generating prerelease specs index
Generated prerelease specs index: 0.010s
Compressing indices
Compressed indices: 0.023s
C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:22: warning: constant ::Fixnum is deprecated
C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:89: warning: constant ::Fixnum is deprecated
# $? => 0
        returns the installed spec after installing (FAILED - 1)


Retried examples: 0

Failures:

  1) Bundler::Plugin::Installer cli install with actual installers git plugins returns the installed spec after installing
     Failure/Error: raise MissingGitRevisionError.new(ref, URICredentialsFilter.credential_filtered_uri(uri))

     Bundler::Source::Git::MissingGitRevisionError:
       Revision master does not exist in the repository file://C/Projects/bundler/tmp/libs/ga-plugin. Maybe you misspelled it?

       Commands:
       $ C:/Ruby24-x64/bin/ruby.exe -rrubygems -S gem --backtrace generate_index
       Generating Marshal quick index gemspecs for 65 gems
       .................................................................
       Complete
       Generated Marshal quick index gemspecs: 0.256s
       Generating specs index
       Generated specs index: 0.010s
       Generating latest specs index
       Generated latest specs index: 0.000s
       Generating prerelease specs index
       Generated prerelease specs index: 0.010s
       Compressing indices
       Compressed indices: 0.023s
       C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:22: warning: constant ::Fixnum is deprecated
       C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:89: warning: constant ::Fixnum is deprecated
       # $? => 0
     # ./spec/bundler/plugin/installer_spec.rb:61:in `block (5 levels) in <top (required)>'
     # ./spec/bundler/plugin/installer_spec.rb:65:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Bundler::Source::Git::GitCommandError:
     #   Git error: command `git rev-parse --verify master` in directory C:/Projects/bundler/tmp/home/.bundle/plugin/cache/bundler/git/ga-plugin-19ad2683c72a755707c3fd4bc59294bd48b3ad11 has failed.
     #   If this error persists you could try removing the cache directory 'C:/Projects/bundler/tmp/home/.bundle/plugin/cache/bundler/git/ga-plugin-19ad2683c72a755707c3fd4bc59294bd48b3ad11'
     #   ./spec/bundler/plugin/installer_spec.rb:61:in `block (5 levels) in <top (required)>'

Finished in 8.84 seconds (files took 0.92972 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/bundler/plugin/installer_spec.rb:64 # Bundler::Plugin::Installer cli install with actual installers git plugins returns the installed spec after installing
```

--- 

There are actually 3 more failures in that file:
```
2019-01-07T19:17:49.6657698Z rspec ./spec/bundler/plugin/installer_spec.rb:69 # Bundler::Plugin::Installer cli install with actual installers git plugins has expected full gem path
2019-01-07T19:17:49.6657798Z rspec ./spec/bundler/plugin/installer_spec.rb:87 # Bundler::Plugin::Installer cli install with actual installers local git plugins returns the installed spec after installing
2019-01-07T19:17:49.6657938Z rspec ./spec/bundler/plugin/installer_spec.rb:92 # Bundler::Plugin::Installer cli install with actual installers local git plugins has expected full gem path
```

All tests have to do with "git plugins", error message is similar as well.

---

"git plugins" here seem to be bundle plugins via git: https://bundler.io/v1.17/guides/bundler_plugins.html#using-a-plugin

So somewhere between creating this `ga-plugin` repository and then checking is current revision stuff goes wrong. Possibly related to a path again.

**Comment by janpio** [comment]
Turns out, the real reason was a lot simpler: The code couldn't create the git repository, indicated by this output that I missed before:
```
error: pathspec 'INITIAL' did not match any file(s) known to git
error: pathspec 'COMMIT'' did not match any file(s) known to git
warning: You appear to have cloned an empty repository.
fatal: Needed a single revision
```

The `git` command was using single quotes, which doesn't work on Windows.

Will create PR to fix that.

**Comment by deivid-rodriguez** [comment]
This one was closed by https://github.com/bundler/bundler/pull/7010.
