### ISSUE TITLE
[Windows test failure] rspec ./spec/bundler/shared_helpers_spec.rb:19 # Bundler::SharedHelpers#default_gemfile Gemfile is present returns the Gemfile path

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6890]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next one:

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec ./spec/bundler/shared_helpers_spec.rb:19
Run options:
  include {:locations=>{"./spec/bundler/shared_helpers_spec.rb"=>[19]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

Bundler::SharedHelpers
  #default_gemfile
    Gemfile is present
      returns the Gemfile path (FAILED - 1)


Retried examples: 0

Failures:

  1) Bundler::SharedHelpers#default_gemfile Gemfile is present returns the Gemfile path
     Failure/Error: expect(subject.default_gemfile).to eq(expected_gemfile_path)

       expected: #<Pathname:/path/Gemfile>
            got: #<Pathname:C:/path/Gemfile>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Pathname:/path/Gemfile>
       +#<Pathname:C:/path/Gemfile>

     # ./spec/bundler/shared_helpers_spec.rb:20:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 7.41 seconds (files took 1.49 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/bundler/shared_helpers_spec.rb:19 # Bundler::SharedHelpers#default_gemfile Gemfile is present returns the Gemfile path
```

Obviously the path here is missing the `C:`, which is probably related to #6875. 

---

After looking into the code of `SharedHelpers.default_gemfile` the problem was caused by an additional `.expand_path` in the implementation that the test was not applying to the expected result string - this adds the `C:` on Windows for a fully expanded path.

Will create a PR to fix this.

**Comment by janpio** [comment]
Working on a PR for this.
