### ISSUE TITLE
[Windows test failure] rspec ./spec/commands/binstubs_spec.rb

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6894]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next one(s):

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec spec/commands/binstubs_spec.rb:77
Run options:
  include {:locations=>{"./spec/commands/binstubs_spec.rb"=>[77]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

bundle binstubs <gem>
  when the gem exists in the lockfile
    when generating bundle binstub outside bundler
$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install --retry 0
Fetching source index from file://C/Projects/bundler/tmp/gems/remote1/
Resolving dependencies...
Fetching rack 1.0.0
Installing rack 1.0.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./.bundle`
Post-install message from rack:
Rack's post install message
# $? => 0

$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle binstubs rack
# $? => 0
      should abort (FAILED - 1)


Retried examples: 0

Failures:

  1) bundle binstubs <gem> when the gem exists in the lockfile when generating bundle binstub outside bundler should abort
     Failure/Error:
             Open3.popen3(env, cmd.to_s) do |stdin, stdout, stderr, wait_thr|
               yield stdin, stdout, wait_thr if block_given?
               stdin.close

               command_execution.stdout = Thread.new { stdout.read }.value.strip
               command_execution.stderr = Thread.new { stderr.read }.value.strip
               command_execution.exitstatus = wait_thr && wait_thr.value.exitstatus
             end

     Errno::ENOEXEC:
       Exec format error - bin/rackup

       Commands:
       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle install --retry 0
       Fetching source index from file://C/Projects/bundler/tmp/gems/remote1/
       Resolving dependencies...
       Fetching rack 1.0.0
       Installing rack 1.0.0
       Bundle complete! 1 Gemfile dependency, 2 gems now installed.
       Bundled gems are installed into `./.bundle`
       Post-install message from rack:
       Rack's post install message
       # $? => 0

       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle binstubs rack
       # $? => 0
     # ./spec/support/helpers.rb:227:in `sys_exec'
     # ./spec/commands/binstubs_spec.rb:89:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 12.77 seconds (files took 3.89 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/commands/binstubs_spec.rb:77 # bundle binstubs <gem> when the gem exists in the lockfile when generating bundle binstub outside bundler should abort
```

Actually one of several in that file with the same underlying reason:

```
rspec ./spec/commands/binstubs_spec.rb:129 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub runs bundler
rspec ./spec/commands/binstubs_spec.rb:135 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub when BUNDLER_VERSION is set runs the correct version of bundler
rspec ./spec/commands/binstubs_spec.rb:144 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub when a lockfile exists with a locked bundler version runs the correct version of bundler when the version is newer
rspec ./spec/commands/binstubs_spec.rb:152 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub when a lockfile exists with a locked bundler version runs the correct version of bundler when the version is older
rspec ./spec/commands/binstubs_spec.rb:161 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub when a lockfile exists with a locked bundler version runs the correct version of bundler when the version is a pre-release
rspec ./spec/commands/binstubs_spec.rb:174 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub when update --bundler is called calls through to the latest bundler version
rspec ./spec/commands/binstubs_spec.rb:179 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub when update --bundler is called calls through to the explicit bundler version
rspec ./spec/commands/binstubs_spec.rb:188 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub without a lockfile falls back to the latest installed bundler
rspec ./spec/commands/binstubs_spec.rb:197 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub using another binstub loads all gems
rspec ./spec/commands/binstubs_spec.rb:205 # bundle binstubs <gem> when the gem exists in the lockfile the bundle binstub using another binstub when requesting a different bundler version attempts to load that version
```

Underlying reason is that bundler does not generate binstubs that work on Windows: https://github.com/bundler/bundler/issues/4512

The solution will be to add creating of Windows compatible binstubs I guess. (Working on this now.)

**Comment by janpio** [comment]
Although #4512 suggested using the Rubygems implementation as a template, it was much easier to use how e.g. Cordova CLI does it: Just create a `command.cmd` file with content `@ruby "%~dpn0" %*` (for us with ruby here). Fixed the tests and has minimal code.

I will create a PR for this.
