### ISSUE TITLE
How to use Bundler 2.0 on MRI 2.6.0?

### ISSUE THREAD

**Issue by eregon** [bundler/bundler#6913]
I can install the gem with `gem install bundler`, but it's not used:
```
$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (2.0.1, default: 1.17.3)
...

$ bundle --version
Bundler version 1.17.3

$ bundle _2.0.1_ --version
Traceback (most recent call last):
	2: from /home/eregon/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
	1: from /home/eregon/.rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/home/eregon/.rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /home/eregon/code/mspec/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
```

And running that (or `bundle _2.0.1_ update --bundler`) doesn't change the Gemfile.lock.

I also tried to update RubyGems with `gem update --system`, but that doesn't help either.

**Comment by deivid-rodriguez** [comment]
We definitely need to better communicate this, but it sounds like your lock file is locked to bundler 1.16.1 (`BUNDLED WITH 1.16.1`). You have 2 options: either upgrade your lock file to the bundler version you are using (`bundle update --bundler`), or use the bundler version you're locked to (`gem install bundler:1.16.1`).

**Comment by eregon** [comment]
It's quite confusing imho, I would expect `bundler` to be "a gem" and so when I install version 2.0.1, the latest version is used like for other gems.
Compatibility would then be achieved by having code in Bundler 2.0 that cares about that, rather than relying on a `bundler 1.x` gem being installed, and having RubyGems or Bundler magically choose a different version based on the `Gemfile.lock` in the current directory.
This also means releases of 1.x would be less needed, but right now 1.x has to be maintained because 2.x cannot run 1.x Gemfile.lock, right?

**Comment by eregon** [comment]
[This blog post](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html) explains the behavior, but I still find it surprising. Running `bundle --version` in a directory without a Gemfile.lock, I can indeed see `Bundler version 2.0.1`.

@colby-swandale What's the plan to drop 1.8.7 support, but still support existing `Gemfile.lock` files which will keep existing for a while?
Should Bundler 2 support these existing `Gemfile.lock` files, and not support Ruby 1.8.7? That would make sense to me, and then Bundler 1.x could be truly deprecated.

**Comment by SashkaSh** [comment]
I have the same issue and I changed my ruby version from 2.6.1 to 2.5.3. Only this helped. before that, I tried everything.

**Comment by eregon** [comment]
@colby-swandale @deivid-rodriguez @hsbt I'd like to have your opinion on this issue, regarding my latest comment. What's the plan to drop 1.8.7 in Bundler 2.x but still support 1.x Gemfiles? Is it hard to support 1.x Gemfiles with Bundler 2? I would expect it's not, and that would allow to really deprecate Bundler 1.x.

**Comment by hsbt** [comment]
@SashkaSh Try to use Ruby 2.6.2. I fixed some of the issues related to this.

I'm not sure what your concerns. But Bundler 2 still support 1.x Gemiles and drop to support Ruby 1.8 and 1.9 now.

**Comment by deivid-rodriguez** [comment]
@eregon I think this is precisely what we are addressing in #6996 and rubygems/rubygems#2696. I'm working on both right now.

**Comment by eregon** [comment]
@hsbt 
> @eregon I'm not sure what your concerns. But Bundler 2 still support 1.x Gemiles and drop to support Ruby 1.8 and 1.9 now.

AFAIK, RubyGems magically switches to use Bundler 1 in that case. I find that behavior very confusing.

Bundler 2 does not work at all if there is a `Gemfile.lock` with `BUNDLED WITH 1.16.4`:
```
$ chruby 2.6.2
$ gem install bundler
$ bundle version
Bundler version 1.17.2 (2018-12-19 commit 3fc4de72b)
$ bundle _2.0.1_ version
Traceback (most recent call last):
	2: from /home/eregon/.rubies/ruby-2.6.2/bin/bundle:23:in `<main>'
	1: from /home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (1.16.4) required by your /home/eregon/tmp/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.4`
```

**Comment by hsbt** [comment]
@eregon It's intentional behavior. You need to run `bundle update --bundler` for using Bundler 2 includes 2.0 and 2.1.
