### ISSUE TITLE
Cannot update bundler version to be older using `bundler update --bundler

### ISSUE THREAD

**Issue by schneems** [bundler/bundler#6917]
If you are trying to use a Gemfile.lock with a `BUNDLED WITH` that indicates bundler 2.x and try to use it on a system that does not have bundler 2.x then you'll get this error:

```
$ bundle
Traceback (most recent call last):
	2: from /Users/rschneeman/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
	1: from /Users/rschneeman/.rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/Users/rschneeman/.rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.0) required by your /private/tmp/default_ruby/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.0`
```

If you try to follow the first instruction to update the Gemfile.lock you get this error:

```
$ bundle update --bundler
You must use Bundler 2 or greater with this lockfile.
```

## Repro

```
docker run -it --rm ruby:2.6 bash
```

```
gem install bundler -v 2.0.1
touch Gemfile
bundle install
gem uninstall bundler -v 2.0.1 -x
bundle install
bundle update --bundler
```

output:

```
root@f1fbb993272b:/# bundle install
Traceback (most recent call last):
  2: from /usr/local/bundle/bin/bundle:23:in `<main>'
  1: from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
root@f1fbb993272b:/# bundle update --bundler
You must use Bundler 2 or greater with this lockfile.
```

**Comment by segiddins** [comment]
What are you trying to downgrade it to — it should work to go from 2.0.1 to 2.0.0, but not down to 1.x because of the lockfile incompatibility

**Comment by schneems** [comment]
The error message tells me to do a thing that is not possible.

Right now people cannot use a lockfile with bundler 2.x on cloud providers that do not yet provide a 2.x version of bundler due to https://github.com/rubygems/rubygems/issues/2592.

When they try, they get that message. If they try to follow directions, using an older version of bundler, then the directions do not work.
