### ISSUE TITLE
can't run bundle exec irb with Ruby 2.6

### ISSUE THREAD

**Issue by Fryguy** [bundler/bundler#6929]
To reproduce...

```sh
> mkdir vanilla; cd vanilla
> touch Gemfile
> bundle update
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle updated!
> gem list bundler

*** LOCAL GEMS ***

bundler (2.0.1, default: 1.17.2)
> cat Gemfile.lock
GEM
  specs:

PLATFORMS
  ruby
  x86_64-darwin-17

DEPENDENCIES

BUNDLED WITH
   2.0.1
> bundle exec irb
bundler: failed to load command: irb (/Users/jfrey/.rubies/ruby-2.6.0/bin/irb)
Gem::Exception: can't find executable irb for gem irb. irb is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Users/jfrey/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /Users/jfrey/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
  /Users/jfrey/.rubies/ruby-2.6.0/bin/irb:23:in `<top (required)>'
```

Similarly, I can't do the manual approach either, but I get a different error because it seems to want to load 1.17.2 regardless.

```sh
> irb
irb(main):001:0> require 'bundler/setup'
You must use Bundler 2 or greater with this lockfile.
# Note that this immediately exits irb

> irb
irb(main):001:0> require 'bundler'
=> true
irb(main):002:0> Bundler::VERSION
=> "1.17.2"
```

Probably related to #6913

**Comment by Fryguy** [comment]
Same steps on Ruby 2.5.3:

```sh
> bundle exec irb
irb(main):001:0> Bundler::VERSION
=> "2.0.1"
> irb
irb(main):001:0> require 'bundler/setup'
=> true
```

**Comment by Fryguy** [comment]
wow TIL.  Thanks!  Should this be documented in bundler docs or FAQ?

**Comment by deivid-rodriguez** [comment]
I see where the error comes from but I think we should fix it. The purpose of default gems is that they are _always_ available. Bundler should respect that.
