### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass installing gem from GitHub Ruby 2.6.1 Bundler version 1.15.2

### ISSUE THREAD

**Issue by PhilCoggins** [bundler/bundler#7021]
I am encountering issues trying to bundle install gems (seems to be isolated to installing a gem lib from GitHub). I am using Ruby 2.6.1, bundler version 1.15.2 (to match Heroku's version).

Here are some details:

```
~/Workbench/bundler_test $ rbenv local
2.6.1
~/Workbench/bundler_test $ gem -v
3.0.3
~/Workbench/bundler_test $ gem list bundler

*** LOCAL GEMS ***

bundler (default: 1.17.3, 1.15.2)
~/Workbench/bundler_test $ bundler --version
Bundler version 1.15.2
~/Workbench/bundler_test $ bundle --version
Bundler version 1.17.3
~/Workbench/bundler_test $ ls
Gemfile
~/Workbench/bundler_test $ cat Gemfile
source "http://rubygems.org"
ruby "2.6.1"

gem "rails", git: "https://github.com/rails/rails.git"
~/Workbench/bundler_test $ bundle _1.15.2_ install --verbose
...
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:484:in `generate_bin'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/source/path/installer.rb:46:in `generate_bin'
/Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/source/path/installer.rb:35:in `block in
post_install'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/shared_helpers.rb:55:in `chdir'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/shared_helpers.rb:55:in `block in chdir'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/shared_helpers.rb:54:in `chdir'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/source/path/installer.rb:27:in `post_install'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/source/path.rb:233:in `generate_bin'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/source/git.rb:184:in `install'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/installer/gem_installer.rb:55:in `install'
/Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/installer/gem_installer.rb:15:in
`install_from_spec'
/Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/installer/parallel_installer.rb:115:in `block in
worker_pool'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/worker.rb:63:in `apply_func'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/worker.rb:58:in `block in process_queue'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/worker.rb:55:in `loop'
  /Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/worker.rb:55:in `process_queue'
/Users/philcoggins/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.15.2/lib/bundler/worker.rb:89:in `block (2 levels) in
create_threads'
```

If I remove the `_1.15.2_` from the `bundle install` command (to use 1.17.3) then it succeeds without errors and generates a `Gemfile.lock` as expected. The error also appears to be intermittent when using 1.15.2, but even if it does not error, it does not generate a `Gemfile.lock`. I've also tested with various different gems in my `Gemfile` and get the same errors so it does not seem to be related the Rails lib itself.

Happy to provide more information as requested, hopefully I'm not missing something small.

**Comment by schneems** [comment]
I'm not able to reproduce this with 2.6.1 on chruby here's my output: https://gist.github.com/schneems/18e4a3ab0f4e7b5e4bf3257b0fc52fb5

**Comment by colby-swandale** [comment]
This is a pretty old version of Bundler, and if this problem is not occurring in 1.17.3 - then I'm not sure what you're expecting us to do?

**Comment by PhilCoggins** [comment]
We ended up upgrading to 2.0.1 since Heroku also supports that with Ruby 2.6.1. We could not find resolution for 1.15.2.

**Comment by phuongnd08** [comment]
We are getting this with bundler 1.17.3 and ruby 2.4.5. It happen with a github based gem with bundled fine with ruby 2.4.3

**Comment by phuongnd08** [comment]
Our bad, it's using 1.15.2
