### ISSUE TITLE
Git clone is taking too long

### ISSUE THREAD

**Issue by localhostdotdev** [bundler/bundler#7050]
Tried using latest version of Rails for a couple of weeks and can't because of this.

```
bundle update --verbose
Running `bundle update --verbose` with bundler 2.0.1
Fetching https://github.com/rails/rails.git
```

Interesting part of my `Gemfile`.

```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", github: "rails/rails"
```

I have other `github:` sources for other gems and they work just fine. I'm guessing this has to do with the size of the Rails repo. Maybe it's doing a full `git clone` instead of `git clone --depth=1`-style commands. (Happened to me a few years ago, maybe CocoaPods though)

Might also be that I already have an older version of repo and it's trying to catch up by fetching intermediate commits but doesn't have the previous commits so it becomes quite an expensive operation.

Stacktrace (when interrupting):

```
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:171:in ``'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:171:in `block (2 levels) in git'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:249:in `block in capture_and_filter_stderr'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/tempfile.rb:295:in `open'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:247:in `capture_and_filter_stderr'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:171:in `block in git'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/shared_helpers.rb:83:in `with_clean_git_env'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:170:in `git'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:162:in `block in git_retry'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/retry.rb:40:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/retry.rb:30:in `attempt'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:161:in `git_retry'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:103:in `checkout'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git.rb:303:in `fetch'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/source/git.rb:161:in `specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:758:in `block in converge_locked_specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:744:in `each'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:744:in `converge_locked_specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:247:in `resolve'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/definition.rb:158:in `resolve_remotely!'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:310:in `resolve_if_needed'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:84:in `block in run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `open'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:73:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/installer.rb:25:in `install'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli/update.rb:61:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli.rb:280:in `update'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli.rb:27:in `dispatch'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/cli.rb:18:in `start'
.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
.rvm/rubies/ruby-head/lib/ruby/2.7.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
.rvm/rubies/ruby-head/bin/bundle:23:in `load'
.rvm/rubies/ruby-head/bin/bundle:23:in `<main>'
.rvm/gems/ruby-head/bin/ruby_executable_hooks:24:in `eval'
.rvm/gems/ruby-head/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by localhostdotdev** [comment]
Value of `command` is:

```
clone 'https://github.com/rails/rails.git' "/Users/localhostdotdev/.rvm/gems/ruby-head/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32" --bare --no-hardlinks --quiet
```

**Comment by colby-swandale** [comment]
This seems to be more that your connection to github is slow rather then something is broken in Bundler.

**Comment by localhostdotdev** [comment]
40 Mbps on fast.com, 100ms ping to github.com

**Comment by localhostdotdev** [comment]
```
$ time git clone --depth=1 https://github.com/rails/rails
       67.54 real         2.44 user         2.72 sys
```

I'm actually at ~300kb/s when git cloning, not sure why (I don't have any proxy or anything).

```
$ time bundle
90.18 real         1.95 user         0.85 sys -> for ~14% of the rails repo (updated the code to see the logging and then interrupted at some point).
```

I'm at 1.50MiB/s -2 MiB/s when dropping the `--no-hardlinks` flag so it might be an issue on Github's end (didn't time it but was quite fast).

So the source of the issue seems to be the `--no-hardlinks` option:

> Force the cloning process from a repository on a local filesystem to copy the files under the .git/objects directory instead of using hardlinks. This may be desirable if you are trying to make a back-up of your repository.

I'm not a git expert so I don't understand why is this option needed but I'm pretty sure it's here for a reason, if that reason is performance, it might be time to re-evaluate the flags passed to git clone.

**Comment by deivid-rodriguez** [comment]
@localhostdotdev I was just having a look at this today (did the #7051 cleanup since I was there). I wondered the exact same thing and looked at the `--no-hardlinks` help too.

I'm going to remove this option, make our CI work a bit and see which feedback it gives us.

Thanks for investigating this :+1:

**Comment by localhostdotdev** [comment]
I'm going to close this for now as somehow this works fine now, feel free to reopen if you can reproduce.

**Comment by localhostdotdev** [comment]
I'm still reproducing this issue every time I tried in the past week or so (different networks, tried ssh too, git clone works fine)

**Comment by deivid-rodriguez** [comment]
Can you try #7054?

**Comment by localhostdotdev** [comment]
thanks replied there https://github.com/bundler/bundler/pull/7054#issuecomment-483891895, looks like the overall changes to the next version of bundler might be making me avoid that `--no-hardlinks`/`--depth=1` path anyway and it worked fine (even if it takes ~5 minutes without any output/progress bar).

I could try again once the pre-release is more stable
