### ISSUE TITLE
bundle fails on mojave 10.14.5 with "can't find gem bundler (>= 0.a) with executable bundle"

### ISSUE THREAD

**Issue by pgtaboada** [bundler/bundler#7130]
Hi,

I am getting this error message on every project on my recently updated macosx:

```
bundle install
Traceback (most recent call last):
 
    2: from /usr/local/bin/bundle:22:in `<main>'    
    1: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path' /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

```

I updated Mojave a few days ago.

**Comment by deivid-rodriguez** [comment]
I guess mojave 10.14.5 ships with an outdated rubygems version. Can you run `gem update --system` and try again?

**Comment by colby-swandale** [comment]
ping @pgtaboada
