### ISSUE TITLE
bundle/inline leaves gem executable unusable

### ISSUE THREAD

**Issue by svenfuchs** [bundler/bundler#7181]
Not sure if I'm not using this right, but it looks like `bundler/inline` leaves the `gem` executable unusable. 

Also, I would have expected `Bundle.clean_env` to fix that, but it doesn't, while manually resetting `ENV` to `Bundler.original_env`, does.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'json'
end

# doesn't fix it
# Bundler.clean_env

# fixes it
# ENV.replace(Bundler.original_env)

require 'fileutils'
include FileUtils

mkdir_p 'tmp'
chdir 'tmp'

File.write 'test.gemspec', <<~str
  Gem::Specification.new do |s|
    s.name        = 'test'
    s.version     = '0.0.1'
    s.licenses    = ['MIT']
    s.summary     = "This is test"
    s.description = "This is test."
    s.authors     = ["Travis CI"]
    s.email       = 'contact@travis-ci.com'
    s.homepage    = 'https://github.org/travis-ci/test'
  end
str

puts `gem build test.gemspec`
```

```
Traceback (most recent call last):
        5: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        4: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/setup.rb:20:in `<top (required)>'
        2: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:101:in `setup'
        1: from /Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:135:in `definition'
/Users/sven/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:32:in `build': /Users/sven/Development/projects/travis/dpl/tmp/Gemfile not found (Bundler::GemfileNotFound)
```

**Comment by indirect** [comment]
I think maybe what you want is `Bundler.with_original_env { \`gem build test.gemspec\` }`?

**Comment by svenfuchs** [comment]
Whoops, sorry, missed your response @indirect 

Hmmm, i'm not quite sure. would be possible, but i think i'd rather want to restore the env in such a way that `gem build ...` is functional at a later point.

I see `with_original_env` also uses `ENV.replace` https://github.com/bundler/bundler/blob/97c8e428318c6dab46ccef5c00d4c096d31d41fe/lib/bundler.rb#L616 like I currently do, so maybe that's acceptable.

Do you think `bundle/inline` leaving executables installed by ruby gems broken is an expected condition? (If I understand correctly what is going on, at all, that is.)

**Comment by deivid-rodriguez** [comment]
Hi @svenfuchs!

> Hmmm, i'm not quite sure. would be possible, but i think i'd rather want to restore the env in such a way that gem build ... is functional at a later point.

I think @indirect's suggestion does just that?

The problem is that when you load `bundler`, one of the environment modifications `bundler` does is adding `-rbundler/setup` to `RUBYOPT`, so when you load any subprocesses, ruby will try to load `bundler` first thing. In your case, there's no Gemfile, so that fails. It can be argued that modifying `RUBYOPT` in this way does not make much sense for `bundler/inline`, but I'm not sure how easy is to change that.

In any case, @indirect's suggestion should just work and I think that's what you want anyways. You could also remove `-rbundler/setup` from `RUBYOPT` before launching the subprocess and that should work too.

**Comment by svenfuchs** [comment]
@deivid-rodriguez aah, ok, i didn't realize Bundler modified `RUBYOPT`. 

I was looking for a way to clean things up without having to wrap subprocesses into a bundler specific block and method call later, mostly because of the way this library i am working on is structured. it would create a weird dependency in a place where that's not quite that obvious ... and i think i my usecase i certainly don't want Ruby subprocesses to look for and load a Gemfile. At the same time I realize my usecase is certainly not a typical one. I think keeping `ENV.replace(env)` in place might be the cleanest approach for now.

I'd personally still consider this a small bug in `bundler/inline`, or at least a very rough edge ... but if you all think it's expected behaviour and a non-issue then let's close this here.
