### ISSUE TITLE
uninitialized constant ActionView::Helpers::InstanceTag

### ISSUE THREAD

**Issue by devpolish** [bundler/bundler#7219]
I'm trying to run ```bash $ bundle console``` in my Rails project and I get the next output:

## Backtrace

```
NameError: uninitialized constant ActionView::Helpers::InstanceTag
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/country_select-4.0.0/lib/country_select/rails3/country_select_helper.rb:22:in `<module:Helpers>'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/country_select-4.0.0/lib/country_select/rails3/country_select_helper.rb:2:in `<module:ActionView>'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/country_select-4.0.0/lib/country_select/rails3/country_select_helper.rb:1:in `<top (required)>'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/country_select-4.0.0/lib/country_select.rb:13:in `require'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/country_select-4.0.0/lib/country_select.rb:13:in `<top (required)>'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/console.rb:15:in `run'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:494:in `console'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
  /home/devpolish/.rbenv/versions/2.5.2/bin/bundle:23:in `load'
  /home/devpolish/.rbenv/versions/2.5.2/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.0.1
  Platforms   ruby, x86_64-linux
Ruby          2.5.2p104 (2018-10-18 revision 65133) [x86_64-linux]
  Full Path   /home/devpolish/.rbenv/versions/2.5.2/bin/ruby
  Config Dir  /home/devpolish/.rbenv/versions/2.5.2/etc
RubyGems      3.0.4
  Gem Home    /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0
  Gem Path    /home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0:/home/devpolish/.gem/ruby/2.5.0
  User Path   /home/devpolish/.gem/ruby/2.5.0
  Bin Dir     /home/devpolish/.rbenv/versions/2.5.2/bin
OpenSSL       
  Compiled    OpenSSL 1.1.0g  2 Nov 2017
  Loaded      OpenSSL 1.1.0g  2 Nov 2017
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.17.1
  RVM         not installed
  rbenv       rbenv 1.1.2-2-g4e92322
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2019-01-04
Git SHA           d7ad2192f
Released Version  true
```

## Bundler settings

```
bin_path
  Set via BUNDLE_BIN_PATH: "/home/devpolish/.rbenv/versions/2.5.2/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/home/devpolish/Code/foodApp-backend/Gemfile"
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.5.2"

gem 'fog-aws'
gem 'active_model_serializers'
gem 'bootsnap'
gem 'bootstrap', '~> 4.1.1' # For bootstrap 4
gem 'cancancan'
gem 'carrierwave'
gem 'carrierwave-base64'
gem 'country_select'
gem 'devise'
gem 'devise-i18n'
gem 'draper'
gem 'omniauth'
gem 'omniauth-instagram'
gem 'pg'
gem 'pg_search'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.0'
gem 'rails-i18n', '~> 5.1'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'sweetalert-rails'
gem 'sweetify'

gem 'cocoon'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'aasm'
gem 'apipie-rails'
gem 'dotenv-rails'
gem 'faker'
gem 'faraday'
gem 'faraday_middleware'
gem 'haml'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'knock'
gem 'mini_magick'
gem 'request_id'
gem 'select2-rails'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem "simple_calendar", "~> 2.0"
gem 'simple_form'
gem 'social-share-button'
gem 'will_paginate'
gem 'will_paginate-bootstrap4'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Fake data
  gem 'rails-erd', require: false
  # Pretty logger
  gem 'beautiful-log'
  # Deploy
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano3-puma'
  gem 'capistrano'
  gem 'capistrano-rbenv'
  gem 'capistrano-sidekiq'
  gem 'pry-rails', group: :development
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'chromedriver-helper'
  gem 'factory_bot'
  gem 'rspec-rails', '~> 3.7'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 3.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    aasm (5.0.5)
      concurrent-ruby (~> 1.0)
    actioncable (5.2.3)
      actionpack (= 5.2.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.3)
      actionview (= 5.2.3)
      activesupport (= 5.2.3)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.3)
      activesupport (= 5.2.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_model_serializers (0.10.9)
      actionpack (>= 4.1, < 6)
      activemodel (>= 4.1, < 6)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    activejob (5.2.3)
      activesupport (= 5.2.3)
      globalid (>= 0.3.6)
    activemodel (5.2.3)
      activesupport (= 5.2.3)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (5.2.3)
      activemodel (= 5.2.3)
      activesupport (= 5.2.3)
      arel (>= 9.0)
    activestorage (5.2.3)
      actionpack (= 5.2.3)
      activerecord (= 5.2.3)
      marcel (~> 0.3.1)
    activesupport (5.2.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.6.0)
      public_suffix (>= 2.0.2, < 4.0)
    airbrussh (1.3.2)
      sshkit (>= 1.6.1, != 1.7.0)
    apipie-rails (0.5.16)
      rails (>= 4.1)
    archive-zip (0.12.0)
      io-like (~> 0.3.0)
    arel (9.0.0)
    autoprefixer-rails (9.6.0)
      execjs
    awesome_print (1.8.0)
    bcrypt (3.1.13)
    beautiful-log (0.2.2)
      awesome_print (~> 1.8.0)
      colorize (~> 0.8.1)
    bindex (0.7.0)
    bootsnap (1.4.4)
      msgpack (~> 1.0)
    bootstrap (4.1.3)
      autoprefixer-rails (>= 6.0.3)
      popper_js (>= 1.12.9, < 2)
      sass (>= 3.5.2)
    builder (3.2.3)
    byebug (11.0.1)
    cancancan (3.0.1)
    capistrano (3.11.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.5.0)
      capistrano (~> 3.1)
    capistrano-rails (1.4.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rbenv (2.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capistrano-sidekiq (1.0.2)
      capistrano (>= 3.9.0)
      sidekiq (>= 3.4)
    capistrano3-puma (3.1.1)
      capistrano (~> 3.7)
      capistrano-bundler
      puma (~> 3.4)
    capybara (3.24.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.5)
      xpath (~> 3.2)
    carrierwave (1.3.1)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      mime-types (>= 1.16)
    carrierwave-base64 (2.8.0)
      carrierwave (>= 0.8.0)
      mime-types (~> 3.0)
      mimemagic (~> 0.3.2)
    case_transform (0.2)
      activesupport
    childprocess (1.0.1)
      rake (< 13.0)
    choice (0.2.0)
    chromedriver-helper (2.1.1)
      archive-zip (~> 0.10)
      nokogiri (~> 1.8)
    cocoon (1.2.13)
    coderay (1.1.2)
    coffee-rails (5.0.0)
      coffee-script (>= 2.2.0)
      railties (>= 5.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    colorize (0.8.1)
    concurrent-ruby (1.1.5)
    connection_pool (2.2.2)
    countries (3.0.0)
      i18n_data (~> 0.8.0)
      sixarm_ruby_unaccent (~> 1.1)
      unicode_utils (~> 1.4)
    country_select (4.0.0)
      countries (~> 3.0)
      sort_alphabetical (~> 1.0)
    crass (1.0.4)
    devise (4.6.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    devise-i18n (1.8.0)
      devise (>= 4.6)
    diff-lcs (1.3)
    dotenv (2.7.2)
    dotenv-rails (2.7.2)
      dotenv (= 2.7.2)
      railties (>= 3.2, < 6.1)
    draper (3.1.0)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
      activemodel-serializers-xml (>= 1.0)
      activesupport (>= 5.0)
      request_store (>= 1.0)
    equatable (0.6.0)
    erubi (1.8.0)
    erubis (2.7.0)
    et-orbi (1.2.1)
      tzinfo
    excon (0.64.0)
    execjs (2.7.0)
    factory_bot (5.0.2)
      activesupport (>= 4.2.0)
    faker (1.9.4)
      i18n (>= 0.7)
      pastel (~> 0.7.2)
      thor (~> 0.20.0)
      tty-pager (~> 0.12.0)
      tty-screen (~> 0.6.5)
      tty-tree (~> 0.3.0)
    faraday (0.15.4)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.13.1)
      faraday (>= 0.7.4, < 1.0)
    ffi (1.11.1)
    fog-aws (3.5.1)
      fog-core (~> 2.1)
      fog-json (~> 1.1)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (2.1.2)
      builder
      excon (~> 0.58)
      formatador (~> 0.2)
      mime-types
    fog-json (1.2.0)
      fog-core
      multi_json (~> 1.10)
    fog-xml (0.1.3)
      fog-core
      nokogiri (>= 1.5.11, < 2.0.0)
    font-awesome-rails (4.7.0.5)
      railties (>= 3.2, < 6.1)
    formatador (0.2.5)
    fugit (1.2.2)
      et-orbi (~> 1.1, >= 1.1.8)
      raabro (~> 1.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    haml (5.1.1)
      temple (>= 0.8.0)
      tilt
    haml-rails (2.0.1)
      actionpack (>= 5.1)
      activesupport (>= 5.1)
      haml (>= 4.0.6, < 6.0)
      html2haml (>= 1.0.1)
      railties (>= 5.1)
    hashie (3.6.0)
    html2haml (2.2.0)
      erubis (~> 2.7.0)
      haml (>= 4.0, < 6)
      nokogiri (>= 1.6.0)
      ruby_parser (~> 3.5)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    i18n_data (0.8.0)
    io-like (0.3.0)
    ipaddress (0.8.3)
    jquery-rails (4.3.5)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jsonapi-renderer (0.2.2)
    jwt (1.5.6)
    knock (2.1.1)
      bcrypt (~> 3.1)
      jwt (~> 1.5)
      rails (>= 4.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mime-types (3.2.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2019.0331)
    mimemagic (0.3.3)
    mini_magick (4.9.3)
    mini_mime (1.0.1)
    mini_portile2 (2.4.0)
    minitest (5.11.3)
    msgpack (1.3.0)
    multi_json (1.13.1)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    net-scp (2.0.0)
      net-ssh (>= 2.6.5, < 6.0.0)
    net-ssh (5.2.0)
    nio4r (2.3.1)
    nokogiri (1.10.3)
      mini_portile2 (~> 2.4.0)
    oauth2 (1.4.1)
      faraday (>= 0.8, < 0.16.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.9.0)
      hashie (>= 3.4.6, < 3.7.0)
      rack (>= 1.6.2, < 3)
    omniauth-instagram (1.3.0)
      omniauth (~> 1)
      omniauth-oauth2 (~> 1)
    omniauth-oauth2 (1.6.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.9)
    orm_adapter (0.5.0)
    pastel (0.7.3)
      equatable (~> 0.6)
      tty-color (~> 0.5)
    pg (1.1.4)
    pg_search (2.2.0)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
    popper_js (1.14.5)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    public_suffix (3.1.0)
    puma (3.12.1)
    raabro (1.1.6)
    rack (2.0.7)
    rack-protection (2.0.5)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.3)
      actioncable (= 5.2.3)
      actionmailer (= 5.2.3)
      actionpack (= 5.2.3)
      actionview (= 5.2.3)
      activejob (= 5.2.3)
      activemodel (= 5.2.3)
      activerecord (= 5.2.3)
      activestorage (= 5.2.3)
      activesupport (= 5.2.3)
      bundler (>= 1.3.0)
      railties (= 5.2.3)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-erd (1.6.0)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
      choice (~> 0.2.0)
      ruby-graphviz (~> 1.2)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    rails-i18n (5.1.3)
      i18n (>= 0.7, < 2)
      railties (>= 5.0, < 6)
    railties (5.2.3)
      actionpack (= 5.2.3)
      activesupport (= 5.2.3)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (12.3.2)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    redis (4.1.2)
    regexp_parser (1.5.1)
    request_id (0.4.3)
    request_store (1.4.1)
      rack (>= 1.4)
    responders (3.0.0)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rspec-core (3.8.1)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.2)
    ruby-graphviz (1.2.4)
    ruby_dep (1.5.0)
    ruby_parser (3.13.1)
      sexp_processor (~> 4.9)
    rubyzip (1.2.3)
    rufus-scheduler (3.6.0)
      fugit (~> 1.1, >= 1.1.6)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    select2-rails (4.0.3)
      thor (~> 0.14)
    selenium-webdriver (3.142.3)
      childprocess (>= 0.5, < 2.0)
      rubyzip (~> 1.2, >= 1.2.2)
    sexp_processor (4.12.1)
    shoulda-matchers (3.1.3)
      activesupport (>= 4.0.0)
    sidekiq (5.2.7)
      connection_pool (~> 2.2, >= 2.2.2)
      rack (>= 1.5.0)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sidekiq-scheduler (3.0.0)
      redis (>= 3, < 5)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
    simple_calendar (2.3.0)
      rails (>= 3.0)
    simple_form (4.1.0)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
    sixarm_ruby_unaccent (1.2.0)
    social-share-button (1.2.0)
      coffee-rails
    sort_alphabetical (1.1.0)
      unicode_utils (>= 1.2.2)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.18.2)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    strings (0.1.5)
      strings-ansi (~> 0.1)
      unicode-display_width (~> 1.5)
      unicode_utils (~> 1.4)
    strings-ansi (0.1.0)
    sweetalert-rails (1.1.3)
      railties (>= 3.1.0)
    sweetify (2.0.0)
      actionpack
    temple (0.8.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.9)
    tty-color (0.5.0)
    tty-pager (0.12.1)
      strings (~> 0.1.4)
      tty-screen (~> 0.6)
      tty-which (~> 0.4)
    tty-screen (0.6.5)
    tty-tree (0.3.0)
    tty-which (0.4.1)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.20)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.6.0)
    unicode_utils (1.4.0)
    warden (1.2.8)
      rack (>= 2.0.6)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    will_paginate (3.1.7)
    will_paginate-bootstrap4 (0.2.2)
      will_paginate (~> 3.0, >= 3.0.0)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  aasm
  active_model_serializers
  apipie-rails
  beautiful-log
  bootsnap
  bootstrap (~> 4.1.1)
  byebug
  cancancan
  capistrano
  capistrano-bundler
  capistrano-rails
  capistrano-rbenv
  capistrano-sidekiq
  capistrano3-puma
  capybara (>= 2.15, < 4.0)
  carrierwave
  carrierwave-base64
  chromedriver-helper
  cocoon
  country_select
  devise
  devise-i18n
  dotenv-rails
  draper
  factory_bot
  faker
  faraday
  faraday_middleware
  fog-aws
  font-awesome-rails
  haml
  haml-rails
  jquery-rails
  jquery-turbolinks
  knock
  listen (>= 3.0.5, < 3.2)
  mini_magick
  omniauth
  omniauth-instagram
  pg
  pg_search
  pry-rails
  puma (~> 3.11)
  rails (~> 5.2.0)
  rails-erd
  rails-i18n (~> 5.1)
  request_id
  rspec-rails (~> 3.7)
  sass-rails (~> 5.0)
  select2-rails
  selenium-webdriver
  shoulda-matchers (~> 3.1)
  sidekiq
  sidekiq-scheduler
  simple_calendar (~> 2.0)
  simple_form
  social-share-button
  spring
  spring-watcher-listen (~> 2.0.0)
  sweetalert-rails
  sweetify
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)
  will_paginate
  will_paginate-bootstrap4

RUBY VERSION
   ruby 2.5.2p104

BUNDLED WITH
   2.0.2
```
****

**Comment by devpolish** [comment]
country_select was incompatible with my current Gemset, so, I take off it and it worked.
