### ISSUE TITLE
Bundler installer issue using opsworks

### ISSUE THREAD

**Issue by prajithktr007** [bundler/bundler#7227]
I am running opswork agent (AWS) and it is failing bundle install. From the logs it is showing as its taking a long time for resolving dependencies. Can someone please help.

```
2019-06-29T15:14:37+00:00] ERROR: Running exception handlers
[2019-06-29T15:14:37+00:00] ERROR: Exception handlers complete
[2019-06-29T15:14:37+00:00] FATAL: Stacktrace dumped to /var/chef/runs/36a3eb5d-dff4-41c4-bc7c-e31a36cc34c3/local-mode-cache/cache/chef-stacktrace.out
[2019-06-29T15:14:37+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-06-29T15:14:37+00:00] ERROR: Command timed out after 600s:
Command exceeded allowed execution time, process terminated
---- Begin output of bundle install ----
STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies..........................................................................................................................................................................................
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
 
I ran the command `/opt/chef/embedded/bin/bundle install`
 
- What did you expect to happen?
 
I expected Bundler to...
 
- What happened instead?
 
Instead, what actually happened was...
 
 
Error details
 
SignalException: SIGTERM
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/dep_proxy.rb:16:in `=='
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:223:in `include?'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:223:in `block in parent_of'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `reverse_each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `parent_of'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:282:in `requirement_tree_for'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:273:in `block in requirement_trees'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:273:in `map'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:273:in `requirement_trees'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:264:in `create_conflict'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:334:in `attempt_to_activate_existing_spec'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:318:in `attempt_to_activate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:72:in `resolve'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:201:in `start'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/chef/embedded/bin/bundle:22:in `load'
/opt/chef/embedded/bin/bundle:22:in `<main>'
 
Environment
 
Bundler   1.12.5
Rubygems  2.6.8
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
GEM_HOME  /opt/chef/embedded/lib/ruby/gems/2.3.0
GEM_PATH  /opt/chef/embedded/lib/ruby/gems/2.3.0:/root/.gem/ruby/2.3.0
Git       1.9.1
 
Bundler settings
 
orig_path
Set via BUNDLE_ORIG_PATH: "/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin"
--- TEMPLATE END ----------------------------------------------------------------
 
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
 
First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=SIGTERM&type=Issues
 
If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
STDERR: 
---- End output of bundle install ----
Ran bundle install returned 1
[2019-06-29T15:14:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by colby-swandale** [comment]
It seems you don't have an `Gemfile.lock` in your projects and as a result AWS is spending time most of its time resolving dependencies.  I suggest running `bundle install` outside of AWS and committing the `Gemfile.lock` into your project so that AWS doesn't have to resolve your Gemfile.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
