### ISSUE TITLE
bundler doesn't install from rubygems.org - tlsv1 alert protocol version

### ISSUE THREAD

**Issue by mjgs** [bundler/bundler#7273]
I am seeing some sort of tls connection error when installing:

```
/tmp $ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)
```

Debug output:

```
/tmp $ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14.1
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [universal.x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-15
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/marksmith/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
/tmp $ bundle env
Traceback (most recent call last):
	2: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
/tmp $ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
OpenSSL 1.0.2s  28 May 2019
```

I am able to download the file mentioned in the error message using curl:

```
/tmp $ curl -O https://rubygems.org/latest_specs.4.8.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1261k  100 1261k    0     0   128k      0  0:00:09  0:00:09 --:--:--  233k
/tmp $ ls -l latest_specs.4.8.gz
-rw-r--r--  1 marksmith  wheel  1292008  3 Aug 18:51 latest_specs.4.8.gz
```

Why is the gem install bundler command erroring?

**Comment by mjgs** [comment]
I got this working by installing ruby from source.

**Comment by duckinator** [comment]
RubyGems 2.0.14 and Ruby 2.0.0 were both released in 2013, and Ruby 2.0.0 reached EOL 3 years ago.

I'm not sure there's any real suggestion to make aside from updating things.

**Comment by mjgs** [comment]
Like I said in my previous post I got it working by installing ruby from source

**Comment by deivid-rodriguez** [comment]
We can close this then, right?

**Comment by mjgs** [comment]
Yup I don't need any more info, with the ruby compiled from source it all
works fine.
