### ISSUE TITLE
Bundle install from jenkins

### ISSUE THREAD

**Issue by olivier95-ruby** [bundler/bundler#7444]
Hi, 
When i launch this command from jenkins jobs :
    - /var/lib/jenkins/.rbenv/versions/jruby-1.7.20.1/bin/bundle install

I receive this backtrace and i don't find the solution : 

## Backtrace

```
NameError: uninitialized constant Bundler::Fetcher
  org/jruby/RubyModule.java:2733:in `const_missing'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/cli/install.rb:56:in `run'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/cli.rb:188:in `install'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/settings.rb:92:in `temporary'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/cli.rb:187:in `install'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/exe/bundle:30:in `(root)'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /srv/jenkins/.rbenv/versions/jruby-1.7.20.1/lib/ruby/gems/shared/gems/bundler-1.15.4/exe/bundle:22:in `(root)'
  org/jruby/RubyKernel.java:1091:in `load'
  /var/lib/jenkins/.rbenv/versions/jruby-1.7.20.1/bin/bundle:23:in `(root)'
```

## Environment

```
Bundler   1.15.4
Rubygems  2.4.8
Ruby      1.9.3p551 (2015-06-10 revision 48406) [java]
Git       1.7.1
Platform  universal-java-1.6


Thanks for your help

**Comment by colby-swandale** [comment]
This is a very old version of Bundler. Does the error still occur if you install the latest version of 1.X?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
