### ISSUE TITLE
Bundler 2.10 breaks rake

### ISSUE THREAD

**Issue by jessebs** [bundler/bundler#7492]
When I try to run `rake` after upgrading to 2.10, I get an error.

I'm on ruby 2.5.1, bundler 2.10, rake 13.0.1.  It worked fine on 2.0.2.

Similar backtrace exists on ruby 2.5.7, 2.6.5, and 2.7.0-preview3. 

This is reproducible in an empty directory with only the rake and bundle gems installed.

```
$ rake
Traceback (most recent call last):
	10: from /Users/user/.rvm/gems/ruby-2.5.1@armagh/bin/ruby_executable_hooks:10:in `<main>'
	 9: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	 8: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	 7: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	 6: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	 5: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:35:in `require'
	 4: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	 3: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	 2: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	 1: from /Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/Users/user/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fab73945fb8> (NoMethodError)
```

`bundle exec rake` gets me past the error

**Comment by deivid-rodriguez** [comment]
This is again `rubygems-bundler`, I really need to get to this but for the time being, uninstall rubygems-bundler and you should be fine (`gem uninstall rubygems-bundler`).

**Comment by jessebs** [comment]
Thanks. I just came across #7488 and I agree this is a duplicate
