### ISSUE TITLE
fluentd (>= 0.a) with executable fluentd Gem::GemNotFoundException

### ISSUE THREAD

**Issue by ram2valar** [bundler/bundler#7496]
Hi Team,

We need to upgrade fluentd to v1.7.4. For this we tried upgrading ruby, bundler and gem with following version:

root@test-instance{~}# bundler -v
Bundler version 2.0.2
root@test-instance{~}# bundle -v
Bundler version 2.0.2
root@test-instance{~}# /usr/local/rvm/rubies/ruby-2.3.1/bin/bundle -v
Bundler version 2.0.2
root@test-instance{~}# gem env version
2.7.9
root@test-instance{~}# ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

When i tried to bring fluentd under supervisord process, its failing with following error:

/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluentd (Gem::GemNotFoundException)
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:303:in `activate_bin_path'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/fluentd:23:in `<main>'

I have tried updating and downgrading system-wise gem as 2.7.9/3.0.6/3.1.1. still no luck. Because of this other process under supervisord is also failing to startup.

i followed the solution specified in this blog:
https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html

no luck. please assist.

**Comment by deivid-rodriguez** [comment]
Could ypu post some steps to reproduce the error? Thanks!
