### ISSUE TITLE
Bundler 2.1.0 raising error when it doesn't need to

### ISSUE THREAD

**Issue by schneems** [bundler/bundler#7538]
I thought this behavior was removed from bundler:

```
$ bundle
Traceback (most recent call last):
	2: from /Users/rschneeman/.rubies/ruby-2.7.0/bin/bundle:23:in `<main>'
	1: from /Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/Users/rschneeman/.rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.16.2) required by your /Users/rschneeman/Documents/projects/barnes/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.2`
⛄ 2.7.0 🚀  ~/Documents/projects/barnes (master)
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin17]
⛄ 2.7.0 🚀  ~/Documents/projects/barnes (master)
$ gem -v
3.1.2
```

Here's the Gemfile.lock https://gist.github.com/schneems/751ea79c9886d397e076cf5389575796

I've been asking for some kind of a killswitch or "escape valve" and the message I got was that it wasn't needed because the behavior was being removed. Is that still happening or is that work only going to be targeting 3.0? If it's not going to happen for a while can we add an env var that skips this check ah-la "escape valve"?

**Comment by deivid-rodriguez** [comment]
Yeah, not yet removed but this is a priority right now.

The plan is to completely remove the `BundlerVersionFinder` from `rubygems`, and then add a better version switcher inside bundler following the principle that it should never raise unnecessarily like you point out.

I'll work on this in the next few days.

**Comment by schneems** [comment]
Great, thanks! I spoke to Coby and Andre at RubyConf and think I understand the path forwards, it sounds like the lockfile parser will be versioned and that the latest release of bundler will always contain code to parse all versions of lockfiles (might be a gross over-simplification, but that's how I interpreted it). 

On the Heroku side of things not sure if you've seen. I've made my own escape valve of sorts by deleting the `BUNDLED WITH` information after we've parsed it and used it to determine the major version of bundler.
